// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: ABA Elite · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const abaEliteCatalog: CatalogItem[] = [
  {
    id: 'abaElite-el-tsm2604s03',
    model: 'Cat 6A 10GS Shielded (FTP), (CM), Stranded Cond. Cable - 200 Ft',
    manufacturer: 'ABA Elite',
    category: 'cable',
    description: 'Cat 6A 10GS Shielded (FTP), (CM), Stranded Cond. Cable - 200 Ft',
    partNumber: 'EL-TSM2604S03',
    estimatedCost: '$91.70',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['abaElite'],
  },
];

export default abaEliteCatalog;
