// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: AOI · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const aoiCatalog: CatalogItem[] = [
  {
    id: 'aoi-a7el-lnd3-adma',
    model: 'Applied Optoelectronics A7EL-LND3-ADMA Transceiver',
    manufacturer: 'AOI',
    category: 'transceiver',
    description: 'Applied Optoelectronics A7EL-LND3-ADMA Transceiver',
    partNumber: 'A7EL-LND3-ADMA',
    estimatedCost: '$20.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['aoi'],
  },
];

export default aoiCatalog;
