// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Arrow Electronics, Inc · 6 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const arrowElectronicsIncCatalog: CatalogItem[] = [
  {
    id: 'arrowElectronicsInc-1u-1n-gen5-1nic',
    model: 'Single Server 1U Chassis inc (Single NIC, Dual Port 200Gb\'s QSFP112 or Dual Port HDR200 QSFP112)',
    manufacturer: 'Arrow Electronics, Inc',
    category: 'hardware',
    description: 'Single Server 1U Chassis inc (Single NIC, Dual Port 200Gb\'s QSFP112 or Dual Port HDR200 QSFP112)',
    partNumber: '1U-1N-GEN5-1NIC',
    estimatedCost: '$10,000.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['arrowElectronicsInc'],
  },
  {
    id: 'arrowElectronicsInc-df-3015',
    model: 'Ceres Enclosure: 1U HA Enclosure (up to 50GB/s): incl. 338TB NVMe Flash, 6.4TB SCM, 8 x 100Gb Bluefield 1 (ETH or IB)',
    manufacturer: 'Arrow Electronics, Inc',
    category: 'hardware',
    description: 'Ceres Enclosure: 1U HA Enclosure (up to 50GB/s): incl. 338TB NVMe Flash, 6.4TB SCM, 8 x 100Gb Bluefield 1 (ETH or IB)',
    partNumber: 'DF-3015',
    estimatedCost: '$52,058.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['arrowElectronicsInc'],
  },
  {
    id: 'arrowElectronicsInc-df-3060',
    model: 'Ceres Enclosure: 1U HA VAST Enclosure (up to 50GB/s): incl. 1350TB NVMe Flash, 12.8TB SCM(TBC), Bluefield DPUs (ETH or IB)',
    manufacturer: 'Arrow Electronics, Inc',
    category: 'hardware',
    description: 'Ceres Enclosure: 1U HA VAST Enclosure (up to 50GB/s): incl. 1350TB NVMe Flash, 12.8TB SCM(TBC), Bluefield DPUs (ETH or IB)',
    partNumber: 'DF-3060',
    estimatedCost: '$169,000.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['arrowElectronicsInc'],
  },
  {
    id: 'arrowElectronicsInc-df-5630',
    model: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 1350TB NVMe Flash, 18TB SCM, 4 x 100Gb (ETH or CX5 IB)',
    manufacturer: 'Arrow Electronics, Inc',
    category: 'hardware',
    description: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 1350TB NVMe Flash, 18TB SCM, 4 x 100Gb (ETH or CX5 IB)',
    partNumber: 'DF-5630',
    estimatedCost: '$240,444.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['arrowElectronicsInc'],
  },
  {
    id: 'arrowElectronicsInc-quad-4n-il-2nic',
    model: 'Quad Server Chassis inc 4 x Ice Lake Servers (Dual NIC)(Quad Port 100Gb\'s QSFP28 or Quad Port HDR100 QSFP56)',
    manufacturer: 'Arrow Electronics, Inc',
    category: 'hardware',
    description: 'Quad Server Chassis inc 4 x Ice Lake Servers (Dual NIC)(Quad Port 100Gb\'s QSFP28 or Quad Port HDR100 QSFP56)',
    partNumber: 'QUAD-4N-IL-2NIC',
    estimatedCost: '$29,411.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['arrowElectronicsInc'],
  },
  {
    id: 'arrowElectronicsInc-spare-kit-df-3015',
    model: 'Vast Data Spare Kit for DF-3015. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM Drives, NVMe Flash QLC (15.36TB)',
    manufacturer: 'Arrow Electronics, Inc',
    category: 'hardware',
    description: 'Vast Data Spare Kit for DF-3015. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM Drives, NVMe Flash QLC (15.36TB)',
    partNumber: 'SPARE-KIT-DF-3015',
    estimatedCost: '$10,149.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['arrowElectronicsInc'],
  },
];

export default arrowElectronicsIncCatalog;
