// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: ASA Computers · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const asaComputersCatalog: CatalogItem[] = [
  {
    id: 'asaComputers-im7200',
    model: 'Opengear IM7200 - 48 - RJ45 Software Selectable Pinout Ports, 2 -10/100/1000 # IM7248-2-DAC-US',
    manufacturer: 'ASA Computers',
    category: 'hardware',
    description: 'Opengear IM7200 - 48 - RJ45 Software Selectable Pinout Ports, 2 -10/100/1000 # IM7248-2-DAC-US',
    partNumber: 'IM7200',
    estimatedCost: '$64.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['asaComputers'],
  },
  {
    id: 'asaComputers-qdd-2x400g-fr4',
    model: '800G QSFP-DD TRANSCEIVER,2X400G-FR4, DUAL DUPLEX LC,2KM SMF',
    manufacturer: 'ASA Computers',
    category: 'transceiver',
    description: '800G QSFP-DD TRANSCEIVER,2X400G-FR4, DUAL DUPLEX LC,2KM SMF',
    partNumber: 'QDD-2X400G-FR4=',
    estimatedCost: '$899.71',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['asaComputers'],
  },
];

export default asaComputersCatalog;
