// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Asus · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const asusCatalog: CatalogItem[] = [
  {
    id: 'asus-esc8000a-e11',
    model: '4U - Dual AMD EPYC 7003 - 8xGPUs - 8x 3.5" SATA/SAS-4xNVMe - 32x DDR4 - 2200W 2+2 Redundant',
    manufacturer: 'Asus',
    category: 'hardware',
    description: '4U - Dual AMD EPYC 7003 - 8xGPUs - 8x 3.5" SATA/SAS-4xNVMe - 32x DDR4 - 2200W 2+2 Redundant',
    partNumber: 'ESC8000A-E11',
    estimatedCost: '$9,518.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['asus'],
  },
];

export default asusCatalog;
