// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: BluDog Technologies, Inc., dba Rackfinity · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const bludogTechnologiesIncDbaRackfinityCatalog: CatalogItem[] = [
  {
    id: 'bludogTechnologiesIncDbaRackfinity-apc-netshelter',
    model: 'APC NetShelter Aisle Containment, Depth Adapter, 600 to 750mm, for 1070 to 1200 mm 42U SX to 48U SX',
    manufacturer: 'BluDog Technologies, Inc., dba Rackfinity',
    category: 'hardware',
    description: 'APC NetShelter Aisle Containment, Depth Adapter, 600 to 750mm, for 1070 to 1200 mm 42U SX to 48U SX',
    partNumber: 'APC NetShelter',
    estimatedCost: '$485.65',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['bludogTechnologiesIncDbaRackfinity'],
  },
];

export default bludogTechnologiesIncDbaRackfinityCatalog;
