// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: CABLES Y COMPONENTES ELÉCTRICOS, S.A. · 4 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const cablesYComponentesElCtricosSACatalog: CatalogItem[] = [
  {
    id: 'cablesYComponentesElCtricosSA-027250117',
    model: '027250117 LATIG. RJ45-RJ45 UTP 7 MT CAT.6A',
    manufacturer: 'CABLES Y COMPONENTES ELÉCTRICOS, S.A.',
    category: 'cable',
    description: '027250117 LATIG. RJ45-RJ45 UTP 7 MT CAT.6A',
    partNumber: '027250117',
    estimatedCost: '$4.36',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cablesYComponentesElCtricosSA'],
  },
  {
    id: 'cablesYComponentesElCtricosSA-027250126',
    model: '027250126 LATIG. RJ45-RJ45 UTP 2 MT CAT.6A',
    manufacturer: 'CABLES Y COMPONENTES ELÉCTRICOS, S.A.',
    category: 'cable',
    description: '027250126 LATIG. RJ45-RJ45 UTP 2 MT CAT.6A',
    partNumber: '027250126',
    estimatedCost: '$1.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cablesYComponentesElCtricosSA'],
  },
  {
    id: 'cablesYComponentesElCtricosSA-027250136',
    model: '027250136 LATIG. RJ45-RJ45 UTP 3 MT CAT.6A',
    manufacturer: 'CABLES Y COMPONENTES ELÉCTRICOS, S.A.',
    category: 'cable',
    description: '027250136 LATIG. RJ45-RJ45 UTP 3 MT CAT.6A',
    partNumber: '027250136',
    estimatedCost: '$2.33',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cablesYComponentesElCtricosSA'],
  },
  {
    id: 'cablesYComponentesElCtricosSA-027250146',
    model: '027250146 LATIG. RJ45-RJ45 UTP 5 MT CAT.6A',
    manufacturer: 'CABLES Y COMPONENTES ELÉCTRICOS, S.A.',
    category: 'cable',
    description: '027250146 LATIG. RJ45-RJ45 UTP 5 MT CAT.6A',
    partNumber: '027250146',
    estimatedCost: '$3.37',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cablesYComponentesElCtricosSA'],
  },
];

export default cablesYComponentesElCtricosSACatalog;
