// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Cable Matters · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const cableMattersCatalog: CatalogItem[] = [
  {
    id: 'cableMatters-16001-blk-7',
    model: '7\' Cat6 UTP Ethernet Patch Cables RJ45',
    manufacturer: 'Cable Matters',
    category: 'cable',
    description: '7\' Cat6 UTP Ethernet Patch Cables RJ45',
    partNumber: '16001-BLK-7',
    estimatedCost: '$24.49',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cableMatters'],
  },
];

export default cableMattersCatalog;
