// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Cablofil · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const cablofilCatalog: CatalogItem[] = [
  {
    id: 'cablofil-sdo150pg',
    model: 'Cablofil 6 INCH STANDARD DROPOUT KIT PRE-GALV',
    manufacturer: 'Cablofil',
    category: 'consumable',
    description: 'Cablofil 6 INCH STANDARD DROPOUT KIT PRE-GALV',
    partNumber: 'SDO150PG',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['cablofil'],
  },
];

export default cablofilCatalog;
