// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Central Computer · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const centralComputerCatalog: CatalogItem[] = [
  {
    id: 'centralComputer-cab-tpt6-sb4',
    model: 'CAT6 Straight Patch 550MHz UTP 24AWG Cable 2ft Green',
    manufacturer: 'Central Computer',
    category: 'cable',
    description: 'CAT6 Straight Patch 550MHz UTP 24AWG Cable 2ft Green',
    partNumber: 'CAB-TPT6-SB4',
    estimatedCost: '$2.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['centralComputer'],
  },
  {
    id: 'centralComputer-cab-tpt6-sc4',
    model: 'CAT6 Straight Patch 550MHz UTP 24AWG Cable 3ft Green',
    manufacturer: 'Central Computer',
    category: 'cable',
    description: 'CAT6 Straight Patch 550MHz UTP 24AWG Cable 3ft Green',
    partNumber: 'CAB-TPT6-SC4',
    estimatedCost: '$3.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['centralComputer'],
  },
];

export default centralComputerCatalog;
