// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Cerio Corp · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const cerioCorpCatalog: CatalogItem[] = [
  {
    id: 'cerioCorp-rpp-pd-xxx-x',
    model: '400A, 415/240V, 3PH, 4W, 42kAIC RPP',
    manufacturer: 'Cerio Corp',
    category: 'hardware',
    description: '400A, 415/240V, 3PH, 4W, 42kAIC RPP',
    partNumber: 'RPP-PD-XXX-X',
    estimatedCost: '$21,540.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['cerioCorp'],
  },
];

export default cerioCorpCatalog;
