// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Chatsworth · 6 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const chatsworthCatalog: CatalogItem[] = [
  {
    id: 'chatsworth-12100-712',
    model: 'Chatsworth RUNWY RAD DROP 12IN BLAC',
    manufacturer: 'Chatsworth',
    category: 'consumable',
    description: 'Chatsworth RUNWY RAD DROP 12IN BLAC',
    partNumber: '12100-712',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['chatsworth'],
  },
  {
    id: 'chatsworth-12100-718',
    model: 'Chatsworth RUNWY RAD DROP 18 BLACK',
    manufacturer: 'Chatsworth',
    category: 'consumable',
    description: 'Chatsworth RUNWY RAD DROP 18 BLACK',
    partNumber: '12100-718',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['chatsworth'],
  },
  {
    id: 'chatsworth-14304-712',
    model: 'Chatsworth 12 INCH RADIUS DROP',
    manufacturer: 'Chatsworth',
    category: 'consumable',
    description: 'Chatsworth 12 INCH RADIUS DROP',
    partNumber: '14304-712',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['chatsworth'],
  },
  {
    id: 'chatsworth-14304-718',
    model: 'Chatsworth 18 INCH RADIUS DROP',
    manufacturer: 'Chatsworth',
    category: 'consumable',
    description: 'Chatsworth 18 INCH RADIUS DROP',
    partNumber: '14304-718',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['chatsworth'],
  },
  {
    id: 'chatsworth-14305-700',
    model: 'Chatsworth RADIUS DROP STRINGER LG BK',
    manufacturer: 'Chatsworth',
    category: 'consumable',
    description: 'Chatsworth RADIUS DROP STRINGER LG BK',
    partNumber: '14305-700',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['chatsworth'],
  },
  {
    id: 'chatsworth-14305-701',
    model: 'Chatsworth RADIUS DROP STRINGER SM BK',
    manufacturer: 'Chatsworth',
    category: 'consumable',
    description: 'Chatsworth RADIUS DROP STRINGER SM BK',
    partNumber: '14305-701',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['chatsworth'],
  },
];

export default chatsworthCatalog;
