// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Chenbro Micom (USA) Inc. · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const chenbroMicomUsaIncCatalog: CatalogItem[] = [
  {
    id: 'chenbroMicomUsaInc-384-mix01686b000',
    model: 'Rack Blanking Panel',
    manufacturer: 'Chenbro Micom (USA) Inc.',
    category: 'hardware',
    description: 'Rack Blanking Panel',
    partNumber: '384-MIX01686B000',
    estimatedCost: '$380.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['chenbroMicomUsaInc'],
  },
];

export default chenbroMicomUsaIncCatalog;
