// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: CIsco · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const ciscoCatalog: CatalogItem[] = [
  {
    id: 'cisco-glc-te-i',
    model: 'Cisco GLC-TE Compatible 1000Base-T SFP 100m RJ45 CATx EXT TAA Transceiver Module',
    manufacturer: 'CIsco',
    category: 'transceiver',
    description: 'Cisco GLC-TE Compatible 1000Base-T SFP 100m RJ45 CATx EXT TAA Transceiver Module',
    partNumber: 'GLC-TE-I',
    estimatedCost: '$16.90',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['cisco'],
  },
];

export default ciscoCatalog;
