// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Codecom · 4 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const codecomCatalog: CatalogItem[] = [
  {
    id: 'codecom-cc-hdpp-96-lcsm-cw-wht',
    model: 'CC-96F-CW-WHITE 1 x 1U 96F White Panel, 12 x 1.5m Polarity B MPO Cables 8F',
    manufacturer: 'Codecom',
    category: 'cable',
    description: 'CC-96F-CW-WHITE 1 x 1U 96F White Panel, 12 x 1.5m Polarity B MPO Cables 8F',
    partNumber: 'CC-HDPP-96-LCSM-CW-WHT',
    estimatedCost: '$1,942.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['codecom'],
  },
  {
    id: 'codecom-cc-sm96fl-eb-cw-mblu',
    model: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to SM G657A1 96FO LC Premium to 12xMPO(Elite) Male 8FO (Flat with FrontManager) Shuttered LC - Coreweave Co-Branded - Midnight Blue',
    manufacturer: 'Codecom LLC',
    category: 'cable',
    description: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to SM G657A1 96FO LC Premium to 12xMPO(Elite) Male 8FO (Flat with FrontManager) Shuttered LC - Coreweave Co-Branded - Midnight Blue',
    partNumber: 'CC-SM96FL-EB-CW-MBLU',
    estimatedCost: '$1,558.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['codecom'],
  },
  {
    id: 'codecom-cc-sm96fl-eb-cw-wht',
    model: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to 12xMPO(Elite) Male 8FO (Flat with Front Manager) Shuttered LC - Coreweave Co- Branded - White',
    manufacturer: 'Codecom LLC',
    category: 'cable',
    description: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to 12xMPO(Elite) Male 8FO (Flat with Front Manager) Shuttered LC - Coreweave Co- Branded - White',
    partNumber: 'CC-SM96FL-EB-CW-WHT',
    estimatedCost: '$1,558.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['codecom'],
  },
  {
    id: 'codecom-cc1-5smmc8mtpfemtpfe-b',
    model: 'LSZH Pre-Terminated Cable MTP(f) Elite - LSZH Pre-Terminated Cable MTP(f) Elite - MTP(f) Elite - POLARITY B',
    manufacturer: 'Codecom LLC',
    category: 'cable',
    description: 'LSZH Pre-Terminated Cable MTP(f) Elite - LSZH Pre-Terminated Cable MTP(f) Elite - MTP(f) Elite - POLARITY B',
    partNumber: 'CC1.5SMMC8MTPFEMTPFE-B',
    estimatedCost: '$32.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['codecom'],
  },
];

export default codecomCatalog;
