// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Comnet Telecom Supply · 3 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const comnetTelecomSupplyCatalog: CatalogItem[] = [
  {
    id: 'comnetTelecomSupply-fsod2a4ccs-185m',
    model: 'CORNING SM DUPLEX LC/LC 2.0mm PVC 185M',
    manufacturer: 'Comnet Telecom Supply',
    category: 'cable',
    description: 'CORNING SM DUPLEX LC/LC 2.0mm PVC 185M',
    partNumber: 'FSOD2A4CCS-185M',
    estimatedCost: '$122.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['comnetTelecomSupply'],
  },
  {
    id: 'comnetTelecomSupply-fsod2a4ccs-225m',
    model: 'CORNING SM DUPLEX LC/LC 2.0mm PVC 225M',
    manufacturer: 'Comnet Telecom Supply',
    category: 'cable',
    description: 'CORNING SM DUPLEX LC/LC 2.0mm PVC 225M',
    partNumber: 'FSOD2A4CCS-225M',
    estimatedCost: '$140.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['comnetTelecomSupply'],
  },
  {
    id: 'comnetTelecomSupply-fsod2a4ccs-240m',
    model: 'CORNING SM DUPLEX LC/LC 2.0mm PVC 240M',
    manufacturer: 'Comnet Telecom Supply',
    category: 'cable',
    description: 'CORNING SM DUPLEX LC/LC 2.0mm PVC 240M',
    partNumber: 'FSOD2A4CCS-240M',
    estimatedCost: '$150.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['comnetTelecomSupply'],
  },
];

export default comnetTelecomSupplyCatalog;
