// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Compware Technology · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const compwareTechnologyCatalog: CatalogItem[] = [
  {
    id: 'compwareTechnology-cdr-2222-3m1',
    model: '2200W Dual Input (AC/DC-DC) Redundant Power Supply',
    manufacturer: 'Compware Technology',
    category: 'consumable',
    description: '2200W Dual Input (AC/DC-DC) Redundant Power Supply',
    partNumber: 'CDR-2222-3M1',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['compwareTechnology'],
  },
];

export default compwareTechnologyCatalog;
