// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Cooper B-Line Systems · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const cooperBLineSystemsCatalog: CatalogItem[] = [
  {
    id: 'cooperBLineSystems-drop-out',
    model: 'Cooper B-Line 8IN DROPOUT GALVANIZED',
    manufacturer: 'Cooper B-Line Systems',
    category: 'consumable',
    description: 'Cooper B-Line 8IN DROPOUT GALVANIZED',
    partNumber: 'DROP OUT',
    estimatedCost: '$14.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['cooperBLineSystems'],
  },
  {
    id: 'cooperBLineSystems-fta2do',
    model: 'Cooper B-Line FLEXTRAY CABLE DROPOUT PLASTIC',
    manufacturer: 'Cooper B-Line Systems',
    category: 'consumable',
    description: 'Cooper B-Line FLEXTRAY CABLE DROPOUT PLASTIC',
    partNumber: 'FTA2DO',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['cooperBLineSystems'],
  },
];

export default cooperBLineSystemsCatalog;
