// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: CP Technologies · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const cpTechnologiesCatalog: CatalogItem[] = [
  {
    id: 'cpTechnologies-gs-lc2-smd-15',
    model: 'Single-mode Fiber Optic Duplex Network Patch Cable, 15ft, LC Male to LC Male, Yellow, Strain Relief, UPC Polished, Booted',
    manufacturer: 'CP Technologies',
    category: 'cable',
    description: 'Single-mode Fiber Optic Duplex Network Patch Cable, 15ft, LC Male to LC Male, Yellow, Strain Relief, UPC Polished, Booted',
    partNumber: 'GS-LC2-SMD-15',
    estimatedCost: '$32.98',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cpTechnologies'],
  },
  {
    id: 'cpTechnologies-gs-lc2-smd-25',
    model: 'Single-mode Fiber Optic Duplex Network Patch Cable, 25ft, LC Male to LC Male, Yellow, Strain Relief, UPC Polished, Booted',
    manufacturer: 'CP Technologies',
    category: 'cable',
    description: 'Single-mode Fiber Optic Duplex Network Patch Cable, 25ft, LC Male to LC Male, Yellow, Strain Relief, UPC Polished, Booted',
    partNumber: 'GS-LC2-SMD-25',
    estimatedCost: '$65.96',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['cpTechnologies'],
  },
];

export default cpTechnologiesCatalog;
