// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Croit · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const croitCatalog: CatalogItem[] = [
  {
    id: 'croit-ccs-tb',
    model: 'Croit Ceph software cluster license subscription per raw TB for cluster ID 2671768b-6c42-424a-9b42- 8af1733182f1 Requires 24x7 support SLA',
    manufacturer: 'Croit',
    category: 'service',
    description: 'Croit Ceph software cluster license subscription per raw TB for cluster ID 2671768b-6c42-424a-9b42- 8af1733182f1 Requires 24x7 support SLA',
    partNumber: 'CCS-TB',
    estimatedCost: '$6.28',
    specs: 'Service | UOM: Eaches',
    vendorIds: ['croit'],
  },
  {
    id: 'croit-ccss',
    model: 'Standard SLA cluster support with subscription Requires software license subscription by raw TB',
    manufacturer: 'Croit',
    category: 'service',
    description: 'Standard SLA cluster support with subscription Requires software license subscription by raw TB',
    partNumber: 'CCSS',
    estimatedCost: '$4,708.20',
    specs: 'Service | UOM: Eaches',
    vendorIds: ['croit'],
  },
];

export default croitCatalog;
