// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Crucial · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const crucialCatalog: CatalogItem[] = [
  {
    id: 'crucial-ct4k8g4dfd824a',
    model: 'Crucial 32GB Kit (8GBx4) DDR4 2400 MT/s (PC4-19200) DR x8 DIMM 288-Pin Memory',
    manufacturer: 'Crucial',
    category: 'hardware',
    description: 'Crucial 32GB Kit (8GBx4) DDR4 2400 MT/s (PC4-19200) DR x8 DIMM 288-Pin Memory',
    partNumber: 'CT4K8G4DFD824A',
    estimatedCost: '$128.99',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['crucial'],
  },
  {
    id: 'crucial-ct500p1ssd8',
    model: 'Crucial P1 500GB M.2 NVMe PCIe SSD/Solid State Drive',
    manufacturer: 'Crucial',
    category: 'hardware',
    description: 'Crucial P1 500GB M.2 NVMe PCIe SSD/Solid State Drive',
    partNumber: 'CT500P1SSD8',
    estimatedCost: '$80.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['crucial'],
  },
];

export default crucialCatalog;
