// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Datalec Power Installations Limited · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const datalecPowerInstallationsLimitedCatalog: CatalogItem[] = [
  {
    id: 'datalecPowerInstallationsLimited-datalec-2a-48u',
    model: '48U W WITH BOTH SIDE PANELS 1.2a 48U with both side panels (without the door)',
    manufacturer: 'Datalec Power Installations Limited',
    category: 'hardware',
    description: '48U W WITH BOTH SIDE PANELS 1.2a 48U with both side panels (without the door)',
    partNumber: 'Datalec-2A 48U',
    estimatedCost: '$1,066.36',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['datalecPowerInstallationsLimited'],
  },
  {
    id: 'datalecPowerInstallationsLimited-datalec-2b-48u',
    model: '1.2B 48U ONE SIDE PANEL (WITHOUT PI Cabinets 1.2b 48U one side panel (without the door)',
    manufacturer: 'Datalec Power Installations Limited',
    category: 'hardware',
    description: '1.2B 48U ONE SIDE PANEL (WITHOUT PI Cabinets 1.2b 48U one side panel (without the door)',
    partNumber: 'Datalec-2B 48U',
    estimatedCost: '$990.25',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['datalecPowerInstallationsLimited'],
  },
];

export default datalecPowerInstallationsLimitedCatalog;
