// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Dedicated Networks Inc. · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const dedicatedNetworksIncCatalog: CatalogItem[] = [
  {
    id: 'dedicatedNetworksInc-arista-dcs-7280qr-c36',
    model: 'Arista DCS-7280QR-C36-F 24x40GbE QSFP+ & 12x100GbE QSFP switch',
    manufacturer: 'Dedicated Networks Inc.',
    category: 'hardware',
    description: 'Arista DCS-7280QR-C36-F 24x40GbE QSFP+ & 12x100GbE QSFP switch',
    partNumber: 'Arista DCS-7280QR-C36',
    estimatedCost: '$11,626.26',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['dedicatedNetworksInc'],
  },
  {
    id: 'dedicatedNetworksInc-arista-dcs-7368-16c',
    model: 'Arista DCS-7368-16C 16 PORT 100G BLADE FOR 7368 7304 CHASSIS',
    manufacturer: 'Dedicated Networks Inc.',
    category: 'hardware',
    description: 'Arista DCS-7368-16C 16 PORT 100G BLADE FOR 7368 7304 CHASSIS',
    partNumber: 'Arista DCS-7368-16C',
    estimatedCost: '$2,500.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['dedicatedNetworksInc'],
  },
];

export default dedicatedNetworksIncCatalog;
