// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: DEI Logistics · 5 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const deiLogisticsCatalog: CatalogItem[] = [
  {
    id: 'deiLogistics-ecd17020047',
    model: 'GB300 MGX PSU, 68mm 5.5kW',
    manufacturer: 'DET Logistics (USA) Corporation',
    category: 'consumable',
    description: 'GB300 MGX PSU, 68mm 5.5kW',
    partNumber: 'ECD17020047',
    estimatedCost: '$0.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deiLogistics'],
  },
  {
    id: 'deiLogistics-ecd68000085',
    model: 'GB300 MGX shelf. 1RU Shelf 19" (Left input; L bracket, 744mm, match Rack v1.1)',
    manufacturer: 'DET Logistics (USA) Corporation',
    category: 'consumable',
    description: 'GB300 MGX shelf. 1RU Shelf 19" (Left input; L bracket, 744mm, match Rack v1.1)',
    partNumber: 'ECD68000085',
    estimatedCost: '$0.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deiLogistics'],
  },
  {
    id: 'deiLogistics-ecd70000031',
    model: 'GB300 MGX PMC, common',
    manufacturer: 'DET Logistics (USA) Corporation',
    category: 'consumable',
    description: 'GB300 MGX PMC, common',
    partNumber: 'ECD70000031',
    estimatedCost: '$0.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deiLogistics'],
  },
  {
    id: 'deiLogistics-lchd124a4qa',
    model: 'CDU L-L GEN3',
    manufacturer: 'DEI Logistics (USA) Corporation',
    category: 'hardware',
    description: 'CDU L-L GEN3',
    partNumber: 'LCHD124A4QA',
    estimatedCost: '$12,000.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['deiLogistics'],
  },
  {
    id: 'deiLogistics-pse048t-ac',
    model: '48x POE Injecter AC Power Model',
    manufacturer: 'DEI Logistics (USA) Corporation',
    category: 'hardware',
    description: '48x POE Injecter AC Power Model',
    partNumber: 'PSE048T-AC',
    estimatedCost: '$4,846.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['deiLogistics'],
  },
];

export default deiLogisticsCatalog;
