// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Dell Marketing LP · 6 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const dellMarketingLpCatalog: CatalogItem[] = [
  {
    id: 'dellMarketingLp-210-bsdq',
    model: '33kW power shelves 1 x 60a input',
    manufacturer: 'Dell Marketing LP',
    category: 'consumable',
    description: '33kW power shelves 1 x 60a input',
    partNumber: '210-BSDQ',
    estimatedCost: '$212,059.50',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['dellMarketingLp'],
  },
  {
    id: 'dellMarketingLp-210-bsry',
    model: 'NvLink Non-Scalable switches 210-BSRY',
    manufacturer: 'Dell Marketing LP',
    category: 'hardware',
    description: 'NvLink Non-Scalable switches 210-BSRY',
    partNumber: '210-BSRY',
    estimatedCost: '$106,029.74',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['dellMarketingLp'],
  },
  {
    id: 'dellMarketingLp-210-btcm',
    model: 'Dell Server 9712a Server Nodes',
    manufacturer: 'Dell Marketing LP',
    category: 'hardware',
    description: 'Dell Server 9712a Server Nodes',
    partNumber: '210-BTCM',
    estimatedCost: '$53,014.88',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['dellMarketingLp'],
  },
  {
    id: 'dellMarketingLp-629-bbgs',
    model: 'MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU,Busbar powered 629-BBGS',
    manufacturer: 'Dell Marketing LP',
    category: 'hardware',
    description: 'MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU,Busbar powered 629-BBGS',
    partNumber: '629-BBGS',
    estimatedCost: '$212,059.50',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['dellMarketingLp'],
  },
  {
    id: 'dellMarketingLp-ovtvd',
    model: 'Delta Power Supply',
    manufacturer: 'Dell Marketing LP',
    category: 'consumable',
    description: 'Delta Power Supply',
    partNumber: 'OVTVD',
    estimatedCost: '$21,205.95',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['dellMarketingLp'],
  },
  {
    id: 'dellMarketingLp-oykc3',
    model: 'Delta PMC Power Supply',
    manufacturer: 'Dell Marketing LP',
    category: 'consumable',
    description: 'Delta PMC Power Supply',
    partNumber: 'OYKC3',
    estimatedCost: '$212,059.50',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['dellMarketingLp'],
  },
];

export default dellMarketingLpCatalog;
