// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Delta Electronics (Americas) Ltd. · 3 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const deltaElectronicsAmericasLtdCatalog: CatalogItem[] = [
  {
    id: 'deltaElectronicsAmericasLtd-clscd305aeb01-0',
    model: 'SuperCDU-3000',
    manufacturer: 'Delta Electronics (Americas) Ltd.',
    category: 'hardware',
    description: 'SuperCDU-3000',
    partNumber: 'CLSCD305AEB01-0',
    estimatedCost: '$250,000.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['deltaElectronicsAmericasLtd'],
  },
  {
    id: 'deltaElectronicsAmericasLtd-clshk-aeb01-s',
    model: 'Valvey Train Assembly - Supply',
    manufacturer: 'Delta Electronics (Americas) Ltd.',
    category: 'hardware',
    description: 'Valvey Train Assembly - Supply',
    partNumber: 'CLSHK-AEB01-S',
    estimatedCost: '$10,500.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['deltaElectronicsAmericasLtd'],
  },
  {
    id: 'deltaElectronicsAmericasLtd-clshk-aeb02-s',
    model: 'Valvey Train Assembly - Return',
    manufacturer: 'Delta Electronics (Americas) Ltd.',
    category: 'hardware',
    description: 'Valvey Train Assembly - Return',
    partNumber: 'CLSHK-AEB02-S',
    estimatedCost: '$11,000.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['deltaElectronicsAmericasLtd'],
  },
];

export default deltaElectronicsAmericasLtdCatalog;
