// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Delta Electronics · 4 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const deltaElectronicsCatalog: CatalogItem[] = [
  {
    id: 'deltaElectronics-dps-1900ab',
    model: 'Arista 1900W AC Power Supply PWR-00237-01',
    manufacturer: 'Delta Electronics',
    category: 'consumable',
    description: 'Arista 1900W AC Power Supply PWR-00237-01',
    partNumber: 'DPS-1900AB',
    estimatedCost: '$268.11',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deltaElectronics'],
  },
  {
    id: 'deltaElectronics-dps-3000ab-1a',
    model: 'Delta Electronics 3000W Switching Power Supply',
    manufacturer: 'Delta Electronics',
    category: 'consumable',
    description: 'Delta Electronics 3000W Switching Power Supply',
    partNumber: 'DPS-3000AB-1A',
    estimatedCost: '$360.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deltaElectronics'],
  },
  {
    id: 'deltaElectronics-dps-3000ab-10c',
    model: 'Delta Electronics 3000W Switching Power Supply',
    manufacturer: 'Delta Electronics',
    category: 'consumable',
    description: 'Delta Electronics 3000W Switching Power Supply',
    partNumber: 'DPS-3000AB-10C',
    estimatedCost: '$360.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deltaElectronics'],
  },
  {
    id: 'deltaElectronics-ecd68000060',
    model: '3kW power shelves 1 x 60a input',
    manufacturer: 'Delta Electronics Americas LTD',
    category: 'consumable',
    description: '3kW power shelves 1 x 60a input',
    partNumber: 'ECD68000060',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['deltaElectronics'],
  },
];

export default deltaElectronicsCatalog;
