// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Dynacom · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const dynacomCatalog: CatalogItem[] = [
  {
    id: 'dynacom-dyn2016-fd1',
    model: '1U SIngle Sided Finger Duct Wiring Manager',
    manufacturer: 'Dynacom',
    category: 'consumable',
    description: '1U SIngle Sided Finger Duct Wiring Manager',
    partNumber: 'DYN2016-FD1',
    estimatedCost: '$24.29',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['dynacom'],
  },
];

export default dynacomCatalog;
