// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: FiberMall · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const fibermallCatalog: CatalogItem[] = [
  {
    id: 'fibermall-qsfpp-40g-ir4',
    model: '40G QSFP+ IR4 1310nm (CWDM4) 2km LC SMF DDM Transceiver Module',
    manufacturer: 'FiberMall',
    category: 'transceiver',
    description: '40G QSFP+ IR4 1310nm (CWDM4) 2km LC SMF DDM Transceiver Module',
    partNumber: 'QSFPP-40G-IR4',
    estimatedCost: '$129.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['fibermall'],
  },
];

export default fibermallCatalog;
