// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Finisar · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const finisarCatalog: CatalogItem[] = [
  {
    id: 'finisar-ftlc9555repm',
    model: 'Finisar 100G SR4 QSFP28 Transceiver',
    manufacturer: 'Finisar',
    category: 'transceiver',
    description: 'Finisar 100G SR4 QSFP28 Transceiver',
    partNumber: 'FTLC9555REPM',
    estimatedCost: '$452.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['finisar'],
  },
];

export default finisarCatalog;
