// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: FlexOptix · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const flexoptixCatalog: CatalogItem[] = [
  {
    id: 'flexoptix-p-1396-10',
    model: 'SMF 1310nm 0.6-11.3Gbit/s 10G LR Programmable SFP+ Transceiver',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: 'SMF 1310nm 0.6-11.3Gbit/s 10G LR Programmable SFP+ Transceiver',
    partNumber: 'P.1396.10',
    estimatedCost: '$45.04',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['flexoptix'],
  },
  {
    id: 'flexoptix-q-8540g-02',
    model: '40GB QSFP+ SR4 MPO Multimod 4x 850nm 100m QSFP+ Transceiver',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: '40GB QSFP+ SR4 MPO Multimod 4x 850nm 100m QSFP+ Transceiver',
    partNumber: 'Q.8540G.02',
    estimatedCost: '$78.89',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['flexoptix'],
  },
];

export default flexoptixCatalog;
