// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Fluke Electronics Corp · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const flukeElectronicsCorpCatalog: CatalogItem[] = [
  {
    id: 'flukeElectronicsCorp-mftk-mm850-sm1310',
    model: 'FLUKE MULTIFIBER PRO KIT WITH 850/1310 NM PMLS',
    manufacturer: 'Fluke Electronics Corp',
    category: 'hardware',
    description: 'FLUKE MULTIFIBER PRO KIT WITH 850/1310 NM PMLS',
    partNumber: 'MFTK-MM850-SM1310',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['flukeElectronicsCorp'],
  },
];

export default flukeElectronicsCorpCatalog;
