// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: General Cabel · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const generalCabelCatalog: CatalogItem[] = [
  {
    id: 'generalCabel-7141801',
    model: 'GenSPEED 10 UTP, Gen5, Cat 6A, Cable, 23 AWG U/UTP, CMP, White, 1000 ft., Spoolpac',
    manufacturer: 'General Cabel',
    category: 'cable',
    description: 'GenSPEED 10 UTP, Gen5, Cat 6A, Cable, 23 AWG U/UTP, CMP, White, 1000 ft., Spoolpac',
    partNumber: '7141801',
    estimatedCost: '$800.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['generalCabel'],
  },
];

export default generalCabelCatalog;
