// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: General Datatech, LP · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const generalDatatechLpCatalog: CatalogItem[] = [
  {
    id: 'generalDatatechLp-a900a',
    model: 'Switchless CDOT with 1xNS224 with 24x7.6TB NVMe SED Drives, ONTAP Base Package, 3 Years of SupportEdge Advisor Next Business Day Replacement and Software Subscription, Advanced NetApp Install AFF A900A, (8) 200GbE RoCE HBAs, 100Gb SFP\'s and cabling 12x Drive Pack 2X7.6TB,NVMe,SED,-C Base Package (NFS, CIFS, FCP, iSCSI, FlexClone, SnapRestore)',
    manufacturer: 'General Datatech, LP',
    category: 'hardware',
    description: 'Switchless CDOT with 1xNS224 with 24x7.6TB NVMe SED Drives, ONTAP Base Package, 3 Years of SupportEdge Advisor Next Business Day Replacement and Software Subscription, Advanced NetApp Install AFF A900A, (8) 200GbE RoCE HBAs, 100Gb SFP\'s and cabling 12x Drive Pack 2X7.6TB,NVMe,SED,-C Base Package (NFS, CIFS, FCP, iSCSI, FlexClone, SnapRestore)',
    partNumber: 'A900A',
    estimatedCost: '$183,866.18',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['generalDatatechLp'],
  },
];

export default generalDatatechLpCatalog;
