// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: GIGA Computing Technology Inc · 5 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const gigaComputingTechnologyIncCatalog: CatalogItem[] = [
  {
    id: 'gigaComputingTechnologyInc-gpu-h100-06',
    model: 'G593-SD0-AAX1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x MBF2M345A-HECOT 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    manufacturer: 'GIGA Computing Technology Inc',
    category: 'hardware',
    description: 'G593-SD0-AAX1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x MBF2M345A-HECOT 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    partNumber: 'GPU-H100-06',
    estimatedCost: '$262,084.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigaComputingTechnologyInc'],
  },
  {
    id: 'gigaComputingTechnologyInc-gpu-h100-07',
    model: 'G593-SD2-AAR1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x MBF2H536C-CECOT 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    manufacturer: 'GIGA Computing Technology Inc',
    category: 'hardware',
    description: 'G593-SD2-AAR1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x MBF2H536C-CECOT 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    partNumber: 'GPU-H100-07',
    estimatedCost: '$262,084.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigaComputingTechnologyInc'],
  },
  {
    id: 'gigaComputingTechnologyInc-gpu-h100-08',
    model: 'G593-SD2-AAR1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    manufacturer: 'GIGA Computing Technology Inc',
    category: 'hardware',
    description: 'G593-SD2-AAR1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    partNumber: 'GPU-H100-08',
    estimatedCost: '$262,084.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigaComputingTechnologyInc'],
  },
  {
    id: 'gigaComputingTechnologyInc-gpu-h100-09',
    model: 'G593-SD2-AAX1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    manufacturer: 'GIGA Computing Technology Inc',
    category: 'hardware',
    description: 'G593-SD2-AAX1-C20 2x Intel 8462Y+ 32x 64GB DDR5 1 x MZQL27T6HBLA-00A07 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB"',
    partNumber: 'GPU-H100-09',
    estimatedCost: '$262,084.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigaComputingTechnologyInc'],
  },
  {
    id: 'gigaComputingTechnologyInc-gpu-h100-13',
    model: 'G593-SD2-AAX1-C20 2x Intel 8462Y+ 32x 64GB DDR5 8 x MZQL27T6HBLA-00A07 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x GPU-NVHGX-H100-LC-88',
    manufacturer: 'GIGA Computing Technology Inc',
    category: 'hardware',
    description: 'G593-SD2-AAX1-C20 2x Intel 8462Y+ 32x 64GB DDR5 8 x MZQL27T6HBLA-00A07 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x GPU-NVHGX-H100-LC-88',
    partNumber: 'GPU-H100-13',
    estimatedCost: '$262,084.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigaComputingTechnologyInc'],
  },
];

export default gigaComputingTechnologyIncCatalog;
