// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Gigabyte Computing · 3 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const gigabyteComputingCatalog: CatalogItem[] = [
  {
    id: 'gigabyteComputing-cln4752',
    model: 'Intel® XL710-BM2 40Gb/s 2-port LAN Card NIC',
    manufacturer: 'Gigabyte Computing',
    category: 'hardware',
    description: 'Intel® XL710-BM2 40Gb/s 2-port LAN Card NIC',
    partNumber: 'CLN4752',
    estimatedCost: '$576.99',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigabyteComputing'],
  },
  {
    id: 'gigabyteComputing-ctm010',
    model: 'TPM2.0 Infineon SLB9670VQ2',
    manufacturer: 'Gigabyte Computing',
    category: 'hardware',
    description: 'TPM2.0 Infineon SLB9670VQ2',
    partNumber: 'CTM010',
    estimatedCost: '$25.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigabyteComputing'],
  },
  {
    id: 'gigabyteComputing-gbt-psu',
    model: 'PSU MODULE 12Vsb/54V 3000W',
    manufacturer: 'Gigabyte Computing',
    category: 'hardware',
    description: 'PSU MODULE 12Vsb/54V 3000W',
    partNumber: 'GBT PSU',
    estimatedCost: '$432.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['gigabyteComputing'],
  },
];

export default gigabyteComputingCatalog;
