// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Global 1 · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const global1Catalog: CatalogItem[] = [
  {
    id: 'global1-p-sm6836',
    model: 'Advanced Smart PDU 60A- 3PH - 10ft Cord - PDU - New in Box * 43.5kW @ 400V 63A * Metered by input with Outlet Switching * 36 Outlets - (18) C13 * C39 outlets (18x) - New OLED screen * IEC 60309 3P+N+PE * 10/100/1000 Base-T',
    manufacturer: 'Global 1',
    category: 'hardware',
    description: 'Advanced Smart PDU 60A- 3PH - 10ft Cord - PDU - New in Box * 43.5kW @ 400V 63A * Metered by input with Outlet Switching * 36 Outlets - (18) C13 * C39 outlets (18x) - New OLED screen * IEC 60309 3P+N+PE * 10/100/1000 Base-T',
    partNumber: 'P-SM6836',
    estimatedCost: '$2,180.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['global1'],
  },
];

export default global1Catalog;
