// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Global 1 Resources · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const global1ResourcesCatalog: CatalogItem[] = [
  {
    id: 'global1Resources-p-ap87651',
    model: 'PDU Bracket Kits (2pcs per) Mount on rear of cabinets',
    manufacturer: 'Global 1 Resources',
    category: 'hardware',
    description: 'PDU Bracket Kits (2pcs per) Mount on rear of cabinets',
    partNumber: 'P-AP87651',
    estimatedCost: '$20.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['global1Resources'],
  },
];

export default global1ResourcesCatalog;
