// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Grainger · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const graingerCatalog: CatalogItem[] = [
  {
    id: 'grainger-ccp1-00bk250',
    model: 'Braided Sleeving: 1 in Inside Dia, Expandable, For 1.188 in Max Bundle Dia, 250 ft Lg, PET, Black',
    manufacturer: 'Grainger',
    category: 'consumable',
    description: 'Braided Sleeving: 1 in Inside Dia, Expandable, For 1.188 in Max Bundle Dia, 250 ft Lg, PET, Black',
    partNumber: 'CCP1.00BK250',
    estimatedCost: '$217.92',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['grainger'],
  },
];

export default graingerCatalog;
