// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Graybar · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const graybarCatalog: CatalogItem[] = [
  {
    id: 'graybar-osfp-port-dustplug-c',
    model: 'OSFP Port Dust Plug / Cover / Cap for Optics',
    manufacturer: 'Graybar',
    category: 'transceiver',
    description: 'OSFP Port Dust Plug / Cover / Cap for Optics',
    partNumber: 'OSFP-PORT-DUSTPLUG-C',
    estimatedCost: '$0.49',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['graybar'],
  },
  {
    id: 'graybar-plc13bk',
    model: 'C14 PLUG LOCK INSERTS',
    manufacturer: 'Graybar',
    category: 'consumable',
    description: 'C14 PLUG LOCK INSERTS',
    partNumber: 'PLC13BK',
    estimatedCost: '$0.65',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['graybar'],
  },
];

export default graybarCatalog;
