// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: HP · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const hpCatalog: CatalogItem[] = [
  {
    id: 'hp-dps-2000ab-29d',
    model: 'HP 2000-Watts 48V Power Supply for AlphaServer GS1280',
    manufacturer: 'HP',
    category: 'consumable',
    description: 'HP 2000-Watts 48V Power Supply for AlphaServer GS1280',
    partNumber: 'DPS-2000AB-29D',
    estimatedCost: '$154.85',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['hp'],
  },
  {
    id: 'hp-p21841-005',
    model: 'HP 12.8TB NVMe U.3',
    manufacturer: 'HP',
    category: 'hardware',
    description: 'HP 12.8TB NVMe U.3',
    partNumber: 'P21841-005',
    estimatedCost: '$1,456.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['hp'],
  },
];

export default hpCatalog;
