// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: IBM Corporation · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const ibmCorporationCatalog: CatalogItem[] = [
  {
    id: 'ibmCorporation-5149-f48',
    model: 'IBM SSS 6000 Model F48 (All NVME) 7 PB Usable Capacity Configuration Includes: 2 x IBM Management Servers 2 x IBM Protocol Servers 2 x IBM AFM Servers 2 x IBM Token Servers',
    manufacturer: 'IBM Corporation',
    category: 'hardware',
    description: 'IBM SSS 6000 Model F48 (All NVME) 7 PB Usable Capacity Configuration Includes: 2 x IBM Management Servers 2 x IBM Protocol Servers 2 x IBM AFM Servers 2 x IBM Token Servers',
    partNumber: '5149-F48',
    estimatedCost: '$555,357.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['ibmCorporation'],
  },
  {
    id: 'ibmCorporation-ibm-storage-scale-software-licenses',
    model: 'IBM Storage Scale Software Licenses',
    manufacturer: 'IBM Corporation',
    category: 'service',
    description: 'IBM Storage Scale Software Licenses',
    partNumber: 'IBM Storage Scale Software Licenses',
    estimatedCost: '$0.00',
    specs: 'Service | UOM: Eaches',
    vendorIds: ['ibmCorporation'],
  },
];

export default ibmCorporationCatalog;
