// AUTO-GENERATED by scripts/generateCatalog.mjs — re-run to refresh.
import type { CatalogItem } from './types';
import lumaOpticsCatalog from './lumaOptics';
import proficiumCatalog from './proficium';
import anixterCatalog from './anixter';
import cienaCatalog from './ciena';
import molexCatalog from './molex';
import supermicroCatalog from './supermicro';
import fsCatalog from './fs';
import nvidiaCatalog from './nvidia';
import nokiaCatalog from './nokia';
import ciscoCatalog from './cisco';
import networksCentreCatalog from './networksCentre';
import cConnexCatalog from './cConnex';
import dellCatalog from './dell';
import myriad360Catalog from './myriad360';
import aristaCatalog from './arista';
import hpeCatalog from './hpe';
import hpeJuniperCatalog from './hpeJuniper';
import sycompCatalog from './sycomp';
import micfoCatalog from './micfo';
import pulseCatalog from './pulse';
import samsungCatalog from './samsung';
import avnetIncCatalog from './avnetInc';
import micronCatalog from './micron';
import eatonCatalog from './eaton';
import shiCatalog from './shi';
import intelCatalog from './intel';
import juniperCatalog from './juniper';
import hynixCatalog from './hynix';
import comtopCatalog from './comtop';
import ubiquitiCatalog from './ubiquiti';
import siemonCatalog from './siemon';
import starlineHoldingsLlcCatalog from './starlineHoldingsLlc';
import datadirectNetworksCatalog from './datadirectNetworks';
import opengearCatalog from './opengear';
import cableleaderCatalog from './cableleader';
import cablesComCatalog from './cablesCom';
import amdCatalog from './amd';
import chatsworthCatalog from './chatsworth';
import eziblankCatalog from './eziblank';
import arrowElectronicsIncCatalog from './arrowElectronicsInc';
import dellMarketingLpCatalog from './dellMarketingLp';
import gigaComputingTechnologyIncCatalog from './gigaComputingTechnologyInc';
import seagateCatalog from './seagate';
import itmCommunicationsLimitedCatalog from './itmCommunicationsLimited';
import deiLogisticsCatalog from './deiLogistics';
import openGearCatalog from './openGear';
import codecomCatalog from './codecom';
import vertivCatalog from './vertiv';
import mellanoxCatalog from './mellanox';
import asrockRackCatalog from './asrockRack';
import flexoptixCatalog from './flexoptix';
import deltaElectronicsCatalog from './deltaElectronics';
import cablesYComponentesElCtricosSACatalog from './cablesYComponentesElCtricosSA';
import cablecelCatalog from './cablecel';
import rwlCatalog from './rwl';
import wescoIndustrialProductsCatalog from './wescoIndustrialProducts';
import aflCatalog from './afl';
import smcCatalog from './smc';
import nexusCatalog from './nexus';
import comnetTelecomSupplyCatalog from './comnetTelecomSupply';
import sourcePhotonicsCatalog from './sourcePhotonics';
import gigabyteComputingCatalog from './gigabyteComputing';
import deltaElectronicsAmericasLtdCatalog from './deltaElectronicsAmericasLtd';
import usConecLtdCatalog from './usConecLtd';
import vestilManufacturingCoCatalog from './vestilManufacturingCo';
import startechCatalog from './startech';
import cooperBLineSystemsCatalog from './cooperBLineSystems';
import asaComputersCatalog from './asaComputers';
import paloAltoCatalog from './paloAlto';
import dedicatedNetworksIncCatalog from './dedicatedNetworksInc';
import kingstonCatalog from './kingston';
import crucialCatalog from './crucial';
import hpCatalog from './hp';
import amazonCatalog from './amazon';
import ibmCorporationCatalog from './ibmCorporation';
import centralComputerCatalog from './centralComputer';
import soligmCatalog from './soligm';
import flexoptixCatalog from './flexoptix';
import sanyoCatalog from './sanyo';
import lenovoCatalog from './lenovo';
import flexoptixCatalog from './flexoptix';
import cpTechnologiesCatalog from './cpTechnologies';
import murataCatalog from './murata';
import kioxiaCatalog from './kioxia';
import datalecPowerInstallationsLimitedCatalog from './datalecPowerInstallationsLimited';
import croitCatalog from './croit';
import graybarCatalog from './graybar';
import magDaddyCatalog from './magDaddy';
import pelicanProductsIncCatalog from './pelicanProductsInc';
import nventCatalog from './nvent';
import flukeElectronicsCorpCatalog from './flukeElectronicsCorp';
import cablofilCatalog from './cablofil';
import waltherCatalog from './walther';
import vaneCatalog from './vane';
import netappCatalog from './netapp';
import vastCatalog from './vast';
import rocketQCatalog from './rocketQ';
import sabrentCatalog from './sabrent';
import nexiusCatalog from './nexius';
import finisarCatalog from './finisar';
import nidecCatalog from './nidec';
import nemixCatalog from './nemix';
import robofiberCatalog from './robofiber';
import voltiveCatalog from './voltive';
import rxlCatalog from './rxl';
import ciscoCatalog from './cisco';
import cableMattersCatalog from './cableMatters';
import renesasElectronicsCatalog from './renesasElectronics';
import dynacomCatalog from './dynacom';
import liteonCatalog from './liteon';
import generalCabelCatalog from './generalCabel';
import legrandCatalog from './legrand';
import unbrandedCatalog from './unbranded';
import graingerCatalog from './grainger';
import abaEliteCatalog from './abaElite';
import pactechCatalog from './pactech';
import wavesplitterCatalog from './wavesplitter';
import aoiCatalog from './aoi';
import intellinetCatalog from './intellinet';
import spirentCommunicationsIncCatalog from './spirentCommunicationsInc';
import compwareTechnologyCatalog from './compwareTechnology';
import v10gtekCatalog from './v10gtek';
import fibermallCatalog from './fibermall';
import asusCatalog from './asus';
import westernDigitalCatalog from './westernDigital';
import wellShinCatalog from './wellShin';
import nznydnlCatalog from './nznydnl';
import wirepathCatalog from './wirepath';
import quantaCatalog from './quanta';
import phsWestCatalog from './phsWest';
import v3yPowerTechnologyIncCatalog from './v3yPowerTechnologyInc';
import bludogTechnologiesIncDbaRackfinityCatalog from './bludogTechnologiesIncDbaRackfinity';
import serverliftCorporationCatalog from './serverliftCorporation';
import global1ResourcesCatalog from './global1Resources';
import generalDatatechLpCatalog from './generalDatatechLp';
import pureStorageCatalog from './pureStorage';
import cerioCorpCatalog from './cerioCorp';
import liteOnCatalog from './liteOn';
import vastCatalog from './vast';
import schneiderElecItCatalog from './schneiderElecIt';
import global1Catalog from './global1';
import monopriceCatalog from './monoprice';
import quantumTechCatalog from './quantumTech';
import chenbroMicomUsaIncCatalog from './chenbroMicomUsaInc';
import tsoTorManagementCompanyUlcCatalog from './tsoTorManagementCompanyUlc';
import wahtsIncCatalog from './wahtsInc';

/** Map of vendor slug -> catalog. Add hand-written vendors above the loop. */
export const VENDOR_CATALOGS: Record<string, CatalogItem[]> = Object.fromEntries([
  ['lumaOptics', lumaOpticsCatalog],
  ['proficium', proficiumCatalog],
  ['anixter', anixterCatalog],
  ['ciena', cienaCatalog],
  ['molex', molexCatalog],
  ['supermicro', supermicroCatalog],
  ['fs', fsCatalog],
  ['nvidia', nvidiaCatalog],
  ['nokia', nokiaCatalog],
  ['cisco', ciscoCatalog],
  ['networksCentre', networksCentreCatalog],
  ['cConnex', cConnexCatalog],
  ['dell', dellCatalog],
  ['myriad360', myriad360Catalog],
  ['arista', aristaCatalog],
  ['hpe', hpeCatalog],
  ['hpeJuniper', hpeJuniperCatalog],
  ['sycomp', sycompCatalog],
  ['micfo', micfoCatalog],
  ['pulse', pulseCatalog],
  ['samsung', samsungCatalog],
  ['avnetInc', avnetIncCatalog],
  ['micron', micronCatalog],
  ['eaton', eatonCatalog],
  ['shi', shiCatalog],
  ['intel', intelCatalog],
  ['juniper', juniperCatalog],
  ['hynix', hynixCatalog],
  ['comtop', comtopCatalog],
  ['ubiquiti', ubiquitiCatalog],
  ['siemon', siemonCatalog],
  ['starlineHoldingsLlc', starlineHoldingsLlcCatalog],
  ['datadirectNetworks', datadirectNetworksCatalog],
  ['opengear', opengearCatalog],
  ['cableleader', cableleaderCatalog],
  ['cablesCom', cablesComCatalog],
  ['amd', amdCatalog],
  ['chatsworth', chatsworthCatalog],
  ['eziblank', eziblankCatalog],
  ['arrowElectronicsInc', arrowElectronicsIncCatalog],
  ['dellMarketingLp', dellMarketingLpCatalog],
  ['gigaComputingTechnologyInc', gigaComputingTechnologyIncCatalog],
  ['seagate', seagateCatalog],
  ['itmCommunicationsLimited', itmCommunicationsLimitedCatalog],
  ['deiLogistics', deiLogisticsCatalog],
  ['openGear', openGearCatalog],
  ['codecom', codecomCatalog],
  ['vertiv', vertivCatalog],
  ['mellanox', mellanoxCatalog],
  ['asrockRack', asrockRackCatalog],
  ['flexoptix', flexoptixCatalog],
  ['deltaElectronics', deltaElectronicsCatalog],
  ['cablesYComponentesElCtricosSA', cablesYComponentesElCtricosSACatalog],
  ['cablecel', cablecelCatalog],
  ['rwl', rwlCatalog],
  ['wescoIndustrialProducts', wescoIndustrialProductsCatalog],
  ['afl', aflCatalog],
  ['smc', smcCatalog],
  ['nexus', nexusCatalog],
  ['comnetTelecomSupply', comnetTelecomSupplyCatalog],
  ['sourcePhotonics', sourcePhotonicsCatalog],
  ['gigabyteComputing', gigabyteComputingCatalog],
  ['deltaElectronicsAmericasLtd', deltaElectronicsAmericasLtdCatalog],
  ['usConecLtd', usConecLtdCatalog],
  ['vestilManufacturingCo', vestilManufacturingCoCatalog],
  ['startech', startechCatalog],
  ['cooperBLineSystems', cooperBLineSystemsCatalog],
  ['asaComputers', asaComputersCatalog],
  ['paloAlto', paloAltoCatalog],
  ['dedicatedNetworksInc', dedicatedNetworksIncCatalog],
  ['kingston', kingstonCatalog],
  ['crucial', crucialCatalog],
  ['hp', hpCatalog],
  ['amazon', amazonCatalog],
  ['ibmCorporation', ibmCorporationCatalog],
  ['centralComputer', centralComputerCatalog],
  ['soligm', soligmCatalog],
  ['flexoptix', flexoptixCatalog],
  ['sanyo', sanyoCatalog],
  ['lenovo', lenovoCatalog],
  ['flexoptix', flexoptixCatalog],
  ['cpTechnologies', cpTechnologiesCatalog],
  ['murata', murataCatalog],
  ['kioxia', kioxiaCatalog],
  ['datalecPowerInstallationsLimited', datalecPowerInstallationsLimitedCatalog],
  ['croit', croitCatalog],
  ['graybar', graybarCatalog],
  ['magDaddy', magDaddyCatalog],
  ['pelicanProductsInc', pelicanProductsIncCatalog],
  ['nvent', nventCatalog],
  ['flukeElectronicsCorp', flukeElectronicsCorpCatalog],
  ['cablofil', cablofilCatalog],
  ['walther', waltherCatalog],
  ['vane', vaneCatalog],
  ['netapp', netappCatalog],
  ['vast', vastCatalog],
  ['rocketQ', rocketQCatalog],
  ['sabrent', sabrentCatalog],
  ['nexius', nexiusCatalog],
  ['finisar', finisarCatalog],
  ['nidec', nidecCatalog],
  ['nemix', nemixCatalog],
  ['robofiber', robofiberCatalog],
  ['voltive', voltiveCatalog],
  ['rxl', rxlCatalog],
  ['cisco', ciscoCatalog],
  ['cableMatters', cableMattersCatalog],
  ['renesasElectronics', renesasElectronicsCatalog],
  ['dynacom', dynacomCatalog],
  ['liteon', liteonCatalog],
  ['generalCabel', generalCabelCatalog],
  ['legrand', legrandCatalog],
  ['unbranded', unbrandedCatalog],
  ['grainger', graingerCatalog],
  ['abaElite', abaEliteCatalog],
  ['pactech', pactechCatalog],
  ['wavesplitter', wavesplitterCatalog],
  ['aoi', aoiCatalog],
  ['intellinet', intellinetCatalog],
  ['spirentCommunicationsInc', spirentCommunicationsIncCatalog],
  ['compwareTechnology', compwareTechnologyCatalog],
  ['v10gtek', v10gtekCatalog],
  ['fibermall', fibermallCatalog],
  ['asus', asusCatalog],
  ['westernDigital', westernDigitalCatalog],
  ['wellShin', wellShinCatalog],
  ['nznydnl', nznydnlCatalog],
  ['wirepath', wirepathCatalog],
  ['quanta', quantaCatalog],
  ['phsWest', phsWestCatalog],
  ['v3yPowerTechnologyInc', v3yPowerTechnologyIncCatalog],
  ['bludogTechnologiesIncDbaRackfinity', bludogTechnologiesIncDbaRackfinityCatalog],
  ['serverliftCorporation', serverliftCorporationCatalog],
  ['global1Resources', global1ResourcesCatalog],
  ['generalDatatechLp', generalDatatechLpCatalog],
  ['pureStorage', pureStorageCatalog],
  ['cerioCorp', cerioCorpCatalog],
  ['liteOn', liteOnCatalog],
  ['vast', vastCatalog],
  ['schneiderElecIt', schneiderElecItCatalog],
  ['global1', global1Catalog],
  ['monoprice', monopriceCatalog],
  ['quantumTech', quantumTechCatalog],
  ['chenbroMicomUsaInc', chenbroMicomUsaIncCatalog],
  ['tsoTorManagementCompanyUlc', tsoTorManagementCompanyUlcCatalog],
  ['wahtsInc', wahtsIncCatalog],
]);

/** Flat list across every vendor catalog. */
export const ALL_CATALOG_ITEMS: CatalogItem[] = Object.values(VENDOR_CATALOGS).flat();

export type { CatalogItem };
