// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Kingston · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const kingstonCatalog: CatalogItem[] = [
  {
    id: 'kingston-ktd-pe432-32g',
    model: 'Kingston KTD-PE432/32G 32GB DDR4 3200MT/s PC4-25600 ECC Memory',
    manufacturer: 'Kingston',
    category: 'hardware',
    description: 'Kingston KTD-PE432/32G 32GB DDR4 3200MT/s PC4-25600 ECC Memory',
    partNumber: 'KTD-PE432-32G',
    estimatedCost: '$155.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['kingston'],
  },
  {
    id: 'kingston-kvr24e17s8-4',
    model: 'Kingston ValueRAM 4GB (1 x 4GB) DDR4 2400 RAM (Server Memory) ECC DIMM (288-Pin)',
    manufacturer: 'Kingston',
    category: 'hardware',
    description: 'Kingston ValueRAM 4GB (1 x 4GB) DDR4 2400 RAM (Server Memory) ECC DIMM (288-Pin)',
    partNumber: 'KVR24E17S8/4',
    estimatedCost: '$34.08',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['kingston'],
  },
];

export default kingstonCatalog;
