// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Kioxia · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const kioxiaCatalog: CatalogItem[] = [
  {
    id: 'kioxia-kcm6xvul12t8',
    model: '12.8TB NVME Kioxia SSD',
    manufacturer: 'Kioxia',
    category: 'hardware',
    description: '12.8TB NVME Kioxia SSD',
    partNumber: 'KCM6XVUL12T8',
    estimatedCost: '$1,100.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['kioxia'],
  },
  {
    id: 'kioxia-sdfsu81geb02t',
    model: 'Kioxia CD6-R 15.36TB 2.5inch PCIe 4.0 (NVMe) SSD',
    manufacturer: 'Kioxia',
    category: 'hardware',
    description: 'Kioxia CD6-R 15.36TB 2.5inch PCIe 4.0 (NVMe) SSD',
    partNumber: 'SDFSU81GEB02T',
    estimatedCost: '$1,550.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['kioxia'],
  },
];

export default kioxiaCatalog;
