// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Legrand · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const legrandCatalog: CatalogItem[] = [
  {
    id: 'legrand-31905-02',
    model: '1ft (0.3m) Cat6 Snagless Unshielded (UTP) Ethernet Network Patch Cable - Blue',
    manufacturer: 'Legrand',
    category: 'cable',
    description: '1ft (0.3m) Cat6 Snagless Unshielded (UTP) Ethernet Network Patch Cable - Blue',
    partNumber: '31905-02',
    estimatedCost: '$3.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['legrand'],
  },
];

export default legrandCatalog;
