// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Lite On · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const liteOnCatalog: CatalogItem[] = [
  {
    id: 'liteOn-ps-2521-2-lf',
    model: 'Lite On Cisco 500-Watts AC B-F Airflow Power Supply',
    manufacturer: 'Lite On',
    category: 'hardware',
    description: 'Lite On Cisco 500-Watts AC B-F Airflow Power Supply',
    partNumber: 'PS-2521-2-LF',
    estimatedCost: '$367.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['liteOn'],
  },
];

export default liteOnCatalog;
