// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Mag Daddy · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const magDaddyCatalog: CatalogItem[] = [
  {
    id: 'magDaddy-62452',
    model: 'Magnetic Hook and Loop Holder 26lbs pull strengh 3/4" slot width',
    manufacturer: 'Mag Daddy',
    category: 'consumable',
    description: 'Magnetic Hook and Loop Holder 26lbs pull strengh 3/4" slot width',
    partNumber: '62452',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['magDaddy'],
  },
];

export default magDaddyCatalog;
