// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Mellanox · 4 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const mellanoxCatalog: CatalogItem[] = [
  {
    id: 'mellanox-mcx311a-xcat',
    model: 'Mellanox ConnectX-3 EN 10G Ethernet 10GbE SFP+ PCIe NIC LC Cable',
    manufacturer: 'Mellanox',
    category: 'cable',
    description: 'Mellanox ConnectX-3 EN 10G Ethernet 10GbE SFP+ PCIe NIC LC Cable',
    partNumber: 'MCX311A-XCAT',
    estimatedCost: '$15.29',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['mellanox'],
  },
  {
    id: 'mellanox-mfp7e40-n007',
    model: '7M MPO FIBER',
    manufacturer: 'Mellanox',
    category: 'cable',
    description: '7M MPO FIBER',
    partNumber: 'MFP7E40-N007',
    estimatedCost: '$148.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['mellanox'],
  },
  {
    id: 'mellanox-mfs1s00-h050e',
    model: 'Mellanox MFS1S00 QSFP56 Fiber Optic Network Cable IB HDR 50m',
    manufacturer: 'Mellanox',
    category: 'cable',
    description: 'Mellanox MFS1S00 QSFP56 Fiber Optic Network Cable IB HDR 50m',
    partNumber: 'MFS1S00-H050E',
    estimatedCost: '$1,729.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['mellanox'],
  },
  {
    id: 'mellanox-mma1b00-c100d',
    model: 'NVIDIA/Mellanox MMA1B00-C100D Compatible 100GBASE-SR4 QSFP28 850nm 100m DOM MPO-12/UPC MMF Ethernet Optical Transceiver Module, Breakout to 4 x 25G-SR',
    manufacturer: 'Mellanox',
    category: 'transceiver',
    description: 'NVIDIA/Mellanox MMA1B00-C100D Compatible 100GBASE-SR4 QSFP28 850nm 100m DOM MPO-12/UPC MMF Ethernet Optical Transceiver Module, Breakout to 4 x 25G-SR',
    partNumber: 'MMA1B00-C100D',
    estimatedCost: '$99.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['mellanox'],
  },
];

export default mellanoxCatalog;
