// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Monoprice · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const monopriceCatalog: CatalogItem[] = [
  {
    id: 'monoprice-844660064534',
    model: 'Monoprice Extension Cord - IEC 60320 C14 to IEC 60320 C13, 16AWG, 13A/1625W, 3-Prong, SJT, Black, 6ft',
    manufacturer: 'Monoprice',
    category: 'consumable',
    description: 'Monoprice Extension Cord - IEC 60320 C14 to IEC 60320 C13, 16AWG, 13A/1625W, 3-Prong, SJT, Black, 6ft',
    partNumber: '844660064534',
    estimatedCost: '$5.19',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['monoprice'],
  },
];

export default monopriceCatalog;
