// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Murata · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const murataCatalog: CatalogItem[] = [
  {
    id: 'murata-d1u54p-w-1500-12-ha3tc-a0',
    model: 'Front End AC DC Converters 1 Output 12V 90 ~ 264 VAC Input',
    manufacturer: 'Murata',
    category: 'consumable',
    description: 'Front End AC DC Converters 1 Output 12V 90 ~ 264 VAC Input',
    partNumber: 'D1U54P-W-1500-12-HA3TC-A0',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['murata'],
  },
  {
    id: 'murata-d1u54p-w-2000-12-hb3c',
    model: '54mm 1U Front End AC-DC Power Supply Converter',
    manufacturer: 'Murata',
    category: 'consumable',
    description: '54mm 1U Front End AC-DC Power Supply Converter',
    partNumber: 'D1U54P-W-2000-12-HB3C',
    estimatedCost: '$624.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['murata'],
  },
];

export default murataCatalog;
