// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Netapp · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const netappCatalog: CatalogItem[] = [
  {
    id: 'netapp-150-00056-a0',
    model: 'Netapp 150-00056 C-24VDX421C8/NB | Metered PDU Cabinet Distribution Unit vt',
    manufacturer: 'Netapp',
    category: 'hardware',
    description: 'Netapp 150-00056 C-24VDX421C8/NB | Metered PDU Cabinet Distribution Unit vt',
    partNumber: '150-00056+A0',
    estimatedCost: '$350.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['netapp'],
  },
];

export default netappCatalog;
