// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Nexius · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const nexiusCatalog: CatalogItem[] = [
  {
    id: 'nexius-n9k-pac-650w',
    model: 'Nexus 9300 650W AC PS Port-side Intake',
    manufacturer: 'Nexius',
    category: 'hardware',
    description: 'Nexus 9300 650W AC PS Port-side Intake',
    partNumber: 'N9K-PAC-650W',
    estimatedCost: '$150.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['nexius'],
  },
];

export default nexiusCatalog;
