// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Nidec · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const nidecCatalog: CatalogItem[] = [
  {
    id: 'nidec-r40w12bs11ac-07',
    model: 'Nidec R40W12BS11AC-07 Server-Square Fan',
    manufacturer: 'Nidec',
    category: 'hardware',
    description: 'Nidec R40W12BS11AC-07 Server-Square Fan',
    partNumber: 'R40W12BS11AC-07',
    estimatedCost: '$27.38',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['nidec'],
  },
];

export default nidecCatalog;
