// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: nVent · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const nventCatalog: CatalogItem[] = [
  {
    id: 'nvent-en6950',
    model: 'Enlogic iPDU [EN6 SERIES] OUTLET SWITCHED AND METERED,380-415VAC, 3-phase (WW), 60A (48A DERATED)/63A - DUAL RATED [380-415VAC, 3-phase, (WW)], 1.8m, 560P6/563P6 (IP44) plug,21(C13/C15),21(4-in-1 Combo)',
    manufacturer: 'nVent',
    category: 'hardware',
    description: 'Enlogic iPDU [EN6 SERIES] OUTLET SWITCHED AND METERED,380-415VAC, 3-phase (WW), 60A (48A DERATED)/63A - DUAL RATED [380-415VAC, 3-phase, (WW)], 1.8m, 560P6/563P6 (IP44) plug,21(C13/C15),21(4-in-1 Combo)',
    partNumber: 'EN6950',
    estimatedCost: '$1,980.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['nvent'],
  },
];

export default nventCatalog;
