// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: NZNYDNL · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const nznydnlCatalog: CatalogItem[] = [
  {
    id: 'nznydnl-vf80804bx-1q040-s9h',
    model: '8080 54V 170.81W Chassis Violent Cooling Fan',
    manufacturer: 'NZNYDNL',
    category: 'hardware',
    description: '8080 54V 170.81W Chassis Violent Cooling Fan',
    partNumber: 'VF80804BX-1Q040-S9H',
    estimatedCost: '$66.18',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['nznydnl'],
  },
];

export default nznydnlCatalog;
