// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Open Gear · 5 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const openGearCatalog: CatalogItem[] = [
  {
    id: 'openGear-450051',
    model: 'CM8000 EXTERNAL DC-DC POWER CONVERTER KIT - INCLUDES 450045',
    manufacturer: 'Open Gear',
    category: 'hardware',
    description: 'CM8000 EXTERNAL DC-DC POWER CONVERTER KIT - INCLUDES 450045',
    partNumber: '450051',
    estimatedCost: '$0.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['openGear'],
  },
  {
    id: 'openGear-590074',
    model: 'DIGI SIM CARD KIT, FOR ACTIVATION, MUST BE SOLD WITH OPENGEAR CELLULAR DATA PLAN',
    manufacturer: 'Open Gear',
    category: 'consumable',
    description: 'DIGI SIM CARD KIT, FOR ACTIVATION, MUST BE SOLD WITH OPENGEAR CELLULAR DATA PLAN',
    partNumber: '590074',
    estimatedCost: '$0.00',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['openGear'],
  },
  {
    id: 'openGear-cm8008-c',
    model: 'OG 8XRS232 X2 PINOUT PT 2X1GBE/SFP COMBO 450048 PWR',
    manufacturer: 'Open Gear',
    category: 'hardware',
    description: 'OG 8XRS232 X2 PINOUT PT 2X1GBE/SFP COMBO 450048 PWR',
    partNumber: 'CM8008-C',
    estimatedCost: '$1,768.05',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['openGear'],
  },
  {
    id: 'openGear-og-fnts-cm8000-5yr',
    model: '5-YEAR FOUNDATION SUPPORT FOR CM8000 - 8X5 REGIONAL SUPPORT WITH ADVANCED REPLACEMENT',
    manufacturer: 'Open Gear',
    category: 'service',
    description: '5-YEAR FOUNDATION SUPPORT FOR CM8000 - 8X5 REGIONAL SUPPORT WITH ADVANCED REPLACEMENT',
    partNumber: 'OG-FNTS-CM8000-5YR',
    estimatedCost: '$0.00',
    specs: 'Service | UOM: Eaches',
    vendorIds: ['openGear'],
  },
  {
    id: 'openGear-opg-att-sm-1yr',
    model: 'OG CEL DATAPLAN-ATT-SMALL PLAN-1 YR LIC',
    manufacturer: 'Open Gear',
    category: 'service',
    description: 'OG CEL DATAPLAN-ATT-SMALL PLAN-1 YR LIC',
    partNumber: 'OPG-ATT-SM-1YR',
    estimatedCost: '$0.00',
    specs: 'Service | UOM: Eaches',
    vendorIds: ['openGear'],
  },
];

export default openGearCatalog;
