// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Pactech · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const pactechCatalog: CatalogItem[] = [
  {
    id: 'pactech-mm-s6ab-10-28lszh-f',
    model: 'Modular Cable Plug to Plug 8p8c (RJ45, Ethernet) 10.00\' (3.05m) Shielded',
    manufacturer: 'Pactech',
    category: 'cable',
    description: 'Modular Cable Plug to Plug 8p8c (RJ45, Ethernet) 10.00\' (3.05m) Shielded',
    partNumber: 'MM-S6AB-10-28LSZH-F',
    estimatedCost: '$16.74',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['pactech'],
  },
];

export default pactechCatalog;
