// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Palo Alto · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const paloAltoCatalog: CatalogItem[] = [
  {
    id: 'paloAlto-pa-850',
    model: 'Palo Alto PA-850 8x 1gb SFP or 4x 1Gb SFP 4x 10Gb SFP+ Refurbished',
    manufacturer: 'Palo Alto',
    category: 'hardware',
    description: 'Palo Alto PA-850 8x 1gb SFP or 4x 1Gb SFP 4x 10Gb SFP+ Refurbished',
    partNumber: 'PA-850',
    estimatedCost: '$450.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['paloAlto'],
  },
  {
    id: 'paloAlto-pwr-450w-ac',
    model: 'PA-3400,PA-1400 450W SPARE POWER SUPPLY',
    manufacturer: 'Palo Alto',
    category: 'consumable',
    description: 'PA-3400,PA-1400 450W SPARE POWER SUPPLY',
    partNumber: 'PWR-450W-AC',
    estimatedCost: '$551.57',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['paloAlto'],
  },
];

export default paloAltoCatalog;
