// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Pelican Products Inc · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const pelicanProductsIncCatalog: CatalogItem[] = [
  {
    id: 'pelicanProductsInc-016050-0001-110',
    model: 'PELICAN 1605 AIR CASE BLACK',
    manufacturer: 'Pelican Products Inc',
    category: 'hardware',
    description: 'PELICAN 1605 AIR CASE BLACK',
    partNumber: '016050-0001-110',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['pelicanProductsInc'],
  },
];

export default pelicanProductsIncCatalog;
