// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: PHS West · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const phsWestCatalog: CatalogItem[] = [
  {
    id: 'phsWest-phs-62122-001',
    model: 'DUAL MAST LIFTER, W/O HITCH, STOPPER, LADDER, LIGHTS',
    manufacturer: 'PHS West',
    category: 'hardware',
    description: 'DUAL MAST LIFTER, W/O HITCH, STOPPER, LADDER, LIGHTS',
    partNumber: 'PHS 62122-001',
    estimatedCost: '$15,579.30',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['phsWest'],
  },
];

export default phsWestCatalog;
