// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Pure Storage · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const pureStorageCatalog: CatalogItem[] = [
  {
    id: 'pureStorage-flashblades-install',
    model: 'PS FLASHBLADES-SINGLE CHASSIS INSTALL - Pure Storage FlashBlade Single Chassis install service for S200 and S500. Includes FlashBlade hardware, and configuration of networking components.Excludes XFM',
    manufacturer: 'Pure Storage',
    category: 'hardware',
    description: 'PS FLASHBLADES-SINGLE CHASSIS INSTALL - Pure Storage FlashBlade Single Chassis install service for S200 and S500. Includes FlashBlade hardware, and configuration of networking components.Excludes XFM',
    partNumber: 'FLASHBLADES-INSTALL',
    estimatedCost: '$12,750.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['pureStorage'],
  },
];

export default pureStorageCatalog;
