// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Quanta · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const quantaCatalog: CatalogItem[] = [
  {
    id: 'quanta-t22u-1u',
    model: 'QuantaPlex T22U-1U 2-Node 4 NVMe, 4x Gold 6230 2.1GHz 20-Core CPU, 1TB DDR4 RAM, 2x 1.6TB NVMe SSD, 2x 10GbE OCP 2.0',
    manufacturer: 'Quanta',
    category: 'hardware',
    description: 'QuantaPlex T22U-1U 2-Node 4 NVMe, 4x Gold 6230 2.1GHz 20-Core CPU, 1TB DDR4 RAM, 2x 1.6TB NVMe SSD, 2x 10GbE OCP 2.0',
    partNumber: 'T22U-1U',
    estimatedCost: '$2,394.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['quanta'],
  },
];

export default quantaCatalog;
