// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Quantum Tech · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const quantumTechCatalog: CatalogItem[] = [
  {
    id: 'quantumTech-r33456s912-fal10000',
    model: 'Intermittently Bonded Ribbon SM G.657 A2-200 um OFC Indoor/Outdoor-3456',
    manufacturer: 'Quantum Tech',
    category: 'cable',
    description: 'Intermittently Bonded Ribbon SM G.657 A2-200 um OFC Indoor/Outdoor-3456',
    partNumber: 'R33456S912 FAL10000',
    estimatedCost: '$200,032.81',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['quantumTech'],
  },
];

export default quantumTechCatalog;
