// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Renesas Electronics · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const renesasElectronicsCatalog: CatalogItem[] = [
  {
    id: 'renesasElectronics-ps-2501',
    model: 'DC Input Transistor Output Optocoupler PS2501-1-A',
    manufacturer: 'Renesas Electronics',
    category: 'hardware',
    description: 'DC Input Transistor Output Optocoupler PS2501-1-A',
    partNumber: 'PS-2501',
    estimatedCost: '$25.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['renesasElectronics'],
  },
];

export default renesasElectronicsCatalog;
