// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Robofiber · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const robofiberCatalog: CatalogItem[] = [
  {
    id: 'robofiber-qsfp-40010-lr4',
    model: 'QSFP-DD 400G LR4 optical transceiver, single-mode 4 CWDM channels',
    manufacturer: 'Robofiber',
    category: 'transceiver',
    description: 'QSFP-DD 400G LR4 optical transceiver, single-mode 4 CWDM channels',
    partNumber: 'QSFP-40010-LR4',
    estimatedCost: '$799.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['robofiber'],
  },
];

export default robofiberCatalog;
