// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Rocket Q · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const rocketQCatalog: CatalogItem[] = [
  {
    id: 'rocketQ-sb-rktq-1tb',
    model: 'ROCKET Q NVME PCIE M.2 2280 SSD',
    manufacturer: 'Rocket Q',
    category: 'hardware',
    description: 'ROCKET Q NVME PCIE M.2 2280 SSD',
    partNumber: 'SB-RKTQ-1TB',
    estimatedCost: '$49.99',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['rocketQ'],
  },
];

export default rocketQCatalog;
