// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: RXL · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const rxlCatalog: CatalogItem[] = [
  {
    id: 'rxl-rxl-1023-bk110',
    model: 'Stringer Radius Drop, 1.5″ Stringer, 10″ Wide, Black, 3 Spools',
    manufacturer: 'RXL',
    category: 'consumable',
    description: 'Stringer Radius Drop, 1.5″ Stringer, 10″ Wide, Black, 3 Spools',
    partNumber: 'RXL-1023-BK110',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['rxl'],
  },
];

export default rxlCatalog;
