// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Sabrent · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const sabrentCatalog: CatalogItem[] = [
  {
    id: 'sabrent-sb-rktq-2tb',
    model: 'Sabrent Rocket Q Sb-Rktq-2Tb 2 Tb Solid State Drive - M.2 2280 Internal - Pci Express Nvme (Pci Express Nvme 3.0 X4) - 3200 Mb/S Maximum Read Transfer Rate M.2 Pcie Gen3 X 4 Interface',
    manufacturer: 'Sabrent',
    category: 'hardware',
    description: 'Sabrent Rocket Q Sb-Rktq-2Tb 2 Tb Solid State Drive - M.2 2280 Internal - Pci Express Nvme (Pci Express Nvme 3.0 X4) - 3200 Mb/S Maximum Read Transfer Rate M.2 Pcie Gen3 X 4 Interface',
    partNumber: 'SB-RKTQ-2TB',
    estimatedCost: '$311.77',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['sabrent'],
  },
];

export default sabrentCatalog;
