// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Sanyo · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const sanyoCatalog: CatalogItem[] = [
  {
    id: 'sanyo-9gv0612p1h051',
    model: 'San Ace 2.0Amp 12Volt 120mm Fan 224',
    manufacturer: 'Sanyo',
    category: 'hardware',
    description: 'San Ace 2.0Amp 12Volt 120mm Fan 224',
    partNumber: '9GV0612P1H051',
    estimatedCost: '$42.32',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['sanyo'],
  },
  {
    id: 'sanyo-ps-2501-8q',
    model: 'San Ace 3.0Amp 12Volt 120mm Fan 224',
    manufacturer: 'Sanyo',
    category: 'hardware',
    description: 'San Ace 3.0Amp 12Volt 120mm Fan 224',
    partNumber: 'PS-2501-8Q',
    estimatedCost: '$32.83',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['sanyo'],
  },
];

export default sanyoCatalog;
