// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: SCHNEIDER ELEC IT · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const schneiderElecItCatalog: CatalogItem[] = [
  {
    id: 'schneiderElecIt-sxrackq-qmtu83668-00',
    model: 'Rack Enclosure AR3357 Rack with AR7716 Networking Roof',
    manufacturer: 'SCHNEIDER ELEC IT',
    category: 'hardware',
    description: 'Rack Enclosure AR3357 Rack with AR7716 Networking Roof',
    partNumber: 'SXRACKQ-QMTU83668-00',
    estimatedCost: '$1,702.20',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['schneiderElecIt'],
  },
];

export default schneiderElecItCatalog;
