// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: ServerLIFT Corporation · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const serverliftCorporationCatalog: CatalogItem[] = [
  {
    id: 'serverliftCorporation-sl-1000x',
    model: 'Heavy-duty, powered data center lift. 1000 lb capacity 48"x26"x85" (675 lb)',
    manufacturer: 'ServerLIFT Corporation',
    category: 'hardware',
    description: 'Heavy-duty, powered data center lift. 1000 lb capacity 48"x26"x85" (675 lb)',
    partNumber: 'SL-1000X',
    estimatedCost: '$15,200.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['serverliftCorporation'],
  },
];

export default serverliftCorporationCatalog;
