// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: SMC · 3 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const smcCatalog: CatalogItem[] = [
  {
    id: 'smc-gpu-h100-03',
    model: 'SYS-821GE-TNHR-03-CI061* 2x Intel 8462Y+ 32x 64GB DDR5 8 x MZQL27T6HBLA-00A07 1 x MCX623106AC-CDAT 8 x MCX75310AAS-NEAT 1 x GPU-NVHGX-H100-88',
    manufacturer: 'SMC',
    category: 'hardware',
    description: 'SYS-821GE-TNHR-03-CI061* 2x Intel 8462Y+ 32x 64GB DDR5 8 x MZQL27T6HBLA-00A07 1 x MCX623106AC-CDAT 8 x MCX75310AAS-NEAT 1 x GPU-NVHGX-H100-88',
    partNumber: 'GPU-H100-03',
    estimatedCost: '$262,084.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['smc'],
  },
  {
    id: 'smc-hds-iun0-ssdpf2kx076t1o',
    model: 'Solidigm 7.68TB SSD NVMe PCIe 4.0 x4 U.2',
    manufacturer: 'SMC',
    category: 'hardware',
    description: 'Solidigm 7.68TB SSD NVMe PCIe 4.0 x4 U.2',
    partNumber: 'HDS-IUN0-SSDPF2KX076T1O',
    estimatedCost: '$1,201.50',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['smc'],
  },
  {
    id: 'smc-pio-628u-tr4t-st031',
    model: 'Supermicro PIO-628U-TR4T+-ST031',
    manufacturer: 'SMC',
    category: 'hardware',
    description: 'Supermicro PIO-628U-TR4T+-ST031',
    partNumber: 'PIO-628U-TR4T+-ST031',
    estimatedCost: '$816.70',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['smc'],
  },
];

export default smcCatalog;
