// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Soligm · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const soligmCatalog: CatalogItem[] = [
  {
    id: 'soligm-ssdpf2kx076t1n1',
    model: '7.68TB PCIe 4.0 x4 U.2 2.5" SFF TLC SSD',
    manufacturer: 'Soligm',
    category: 'hardware',
    description: '7.68TB PCIe 4.0 x4 U.2 2.5" SFF TLC SSD',
    partNumber: 'SSDPF2KX076T1N1',
    estimatedCost: '$994.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['soligm'],
  },
  {
    id: 'soligm-ssdpf2kx076t1o',
    model: 'Solidigm Hard Drive 7.68TB SSD PCIe 4.0 x4 NVMe U.2 15mm SED+OPAL Encrypted TLC 2DWPD',
    manufacturer: 'Soligm',
    category: 'hardware',
    description: 'Solidigm Hard Drive 7.68TB SSD PCIe 4.0 x4 NVMe U.2 15mm SED+OPAL Encrypted TLC 2DWPD',
    partNumber: 'SSDPF2KX076T1O',
    estimatedCost: '$1,346.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['soligm'],
  },
];

export default soligmCatalog;
