// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Spirent Communications Inc. · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const spirentCommunicationsIncCatalog: CatalogItem[] = [
  {
    id: 'spirentCommunicationsInc-hwo-b3-800-osfp-8-400g',
    model: '1550A B3 8-Port Native OSFP800 800G/400G/200G/100G/50G 8-Port ENABLED BUNDLE',
    manufacturer: 'Spirent Communications Inc.',
    category: 'hardware',
    description: '1550A B3 8-Port Native OSFP800 800G/400G/200G/100G/50G 8-Port ENABLED BUNDLE',
    partNumber: 'HWO-B3-800-OSFP-8-400G',
    estimatedCost: '$892,500.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['spirentCommunicationsInc'],
  },
];

export default spirentCommunicationsIncCatalog;
