// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: StarTech · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const startechCatalog: CatalogItem[] = [
  {
    id: 'startech-cmlb102',
    model: 'Horizontal Cable Lacing Bars with 2 in. Offset for Racks - 10 Pack - TAA',
    manufacturer: 'StarTech',
    category: 'consumable',
    description: 'Horizontal Cable Lacing Bars with 2 in. Offset for Racks - 10 Pack - TAA',
    partNumber: 'CMLB102',
    estimatedCost: '$72.88',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['startech'],
  },
  {
    id: 'startech-cmlb104',
    model: 'StarTech 19” Lacing Bars 4” Offset 75 Degrees (10-Pack)',
    manufacturer: 'StarTech',
    category: 'consumable',
    description: 'StarTech 19” Lacing Bars 4” Offset 75 Degrees (10-Pack)',
    partNumber: 'CMLB104',
    estimatedCost: '$64.50',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['startech'],
  },
];

export default startechCatalog;
