// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: TSO TOR Management Company, ULC · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const tsoTorManagementCompanyUlcCatalog: CatalogItem[] = [
  {
    id: 'tsoTorManagementCompanyUlc-short-term-rent',
    model: 'Short Term Rent',
    manufacturer: 'TSO TOR Management Company, ULC',
    category: 'other',
    description: 'Short Term Rent',
    partNumber: 'Short Term Rent',
    estimatedCost: '',
    specs: 'Item | UOM: Eaches',
    vendorIds: ['tsoTorManagementCompanyUlc'],
  },
];

export default tsoTorManagementCompanyUlcCatalog;
