// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Unbranded · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const unbrandedCatalog: CatalogItem[] = [
  {
    id: 'unbranded-41-hdm150-pbxx01s',
    model: 'High Speed HDMI Cable',
    manufacturer: 'Unbranded',
    category: 'cable',
    description: 'High Speed HDMI Cable',
    partNumber: '41-HDM150-PBXX01S',
    estimatedCost: '$5.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ['unbranded'],
  },
];

export default unbrandedCatalog;
