// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: US Conec LTD · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const usConecLtdCatalog: CatalogItem[] = [
  {
    id: 'usConecLtd-7104',
    model: 'US Conec IBC MPO-MTP CLEANING TOOL',
    manufacturer: 'US Conec LTD',
    category: 'consumable',
    description: 'US Conec IBC MPO-MTP CLEANING TOOL',
    partNumber: '7104',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['usConecLtd'],
  },
  {
    id: 'usConecLtd-9393',
    model: 'UC Conec IBC LC ONE CLICK CLEANING TOOL',
    manufacturer: 'US Conec LTD',
    category: 'consumable',
    description: 'UC Conec IBC LC ONE CLICK CLEANING TOOL',
    partNumber: '9393',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['usConecLtd'],
  },
];

export default usConecLtdCatalog;
