// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: 10GTEK · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const v10gtekCatalog: CatalogItem[] = [
  {
    id: 'v10gtek-asf-ge-t',
    model: 'SFP,1.25Gb/s,GE,1000Base-T,CAT5,Copper,100M',
    manufacturer: '10GTEK',
    category: 'transceiver',
    description: 'SFP,1.25Gb/s,GE,1000Base-T,CAT5,Copper,100M',
    partNumber: 'ASF-GE-T',
    estimatedCost: '$35.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['v10gtek'],
  },
];

export default v10gtekCatalog;
