// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: 3Y Power Technology Inc · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const v3yPowerTechnologyIncCatalog: CatalogItem[] = [
  {
    id: 'v3yPowerTechnologyInc-ynec1600am-2a00p10',
    model: 'Power Supply 90-100VAC @800W',
    manufacturer: '3Y Power Technology Inc',
    category: 'consumable',
    description: 'Power Supply 90-100VAC @800W',
    partNumber: 'YNEC1600AM-2A00P10',
    estimatedCost: '',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['v3yPowerTechnologyInc'],
  },
];

export default v3yPowerTechnologyIncCatalog;
