// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Vane · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const vaneCatalog: CatalogItem[] = [
  {
    id: 'vane-3520vac',
    model: 'Vane Type Double Pump',
    manufacturer: 'Vane',
    category: 'hardware',
    description: 'Vane Type Double Pump',
    partNumber: '3520VAC',
    estimatedCost: '$1,000.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['vane'],
  },
];

export default vaneCatalog;
