// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: VAST · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const vastCatalog: CatalogItem[] = [
  {
    id: 'vast-fru-df-3000-60tb-p5336',
    model: 'Ceres, FRU Drive, 60TB E1.L P5336',
    manufacturer: 'VAST',
    category: 'hardware',
    description: 'Ceres, FRU Drive, 60TB E1.L P5336',
    partNumber: 'FRU-DF-3000-60TB-P5336',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['vast'],
  },
];

export default vastCatalog;
