// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Vestil Manufacturing Co · 2 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const vestilManufacturingCoCatalog: CatalogItem[] = [
  {
    id: 'vestilManufacturingCo-74-000-084',
    model: 'VESTIL HYD-10-DC ASSEMBLY GUIDE WHEEL',
    manufacturer: 'Vestil Manufacturing Co',
    category: 'hardware',
    description: 'VESTIL HYD-10-DC ASSEMBLY GUIDE WHEEL',
    partNumber: '74-000-084',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['vestilManufacturingCo'],
  },
  {
    id: 'vestilManufacturingCo-hyd-10-dc',
    model: 'VESTIL ELECTRICAL HEFTI LIFT',
    manufacturer: 'Vestil Manufacturing Co',
    category: 'hardware',
    description: 'VESTIL ELECTRICAL HEFTI LIFT',
    partNumber: 'HYD-10-DC',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['vestilManufacturingCo'],
  },
];

export default vestilManufacturingCoCatalog;
