// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: WAHTS Inc. · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const wahtsIncCatalog: CatalogItem[] = [
  {
    id: 'wahtsInc-6459-010-9003b',
    model: 'WAHTS AC System Includes: -Software access for 12 months -Shipping, handling, & insurance to lower 48',
    manufacturer: 'WAHTS Inc.',
    category: 'service',
    description: 'WAHTS AC System Includes: -Software access for 12 months -Shipping, handling, & insurance to lower 48',
    partNumber: '6459-010-9003B',
    estimatedCost: '$7,466.00',
    specs: 'Service | UOM: Eaches',
    vendorIds: ['wahtsInc'],
  },
];

export default wahtsIncCatalog;
