// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Walther · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const waltherCatalog: CatalogItem[] = [
  {
    id: 'walther-3o250vac',
    model: 'Walther SP 30a Plug With Cable Gland 4 Wire',
    manufacturer: 'Walther',
    category: 'hardware',
    description: 'Walther SP 30a Plug With Cable Gland 4 Wire',
    partNumber: '3O250VAC',
    estimatedCost: '$126.00',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['walther'],
  },
];

export default waltherCatalog;
