// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: WaveSplitter · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const wavesplitterCatalog: CatalogItem[] = [
  {
    id: 'wavesplitter-wst-sfp-lr-c',
    model: 'WaveSplitter SFP+ 10Gb LR Transceiver',
    manufacturer: 'WaveSplitter',
    category: 'transceiver',
    description: 'WaveSplitter SFP+ 10Gb LR Transceiver',
    partNumber: 'WST-SFP+LR-C',
    estimatedCost: '$25.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ['wavesplitter'],
  },
];

export default wavesplitterCatalog;
