// AUTO-GENERATED by scripts/generateCatalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Well Shin · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const wellShinCatalog: CatalogItem[] = [
  {
    id: 'wellShin-ws-309-4p-63a-p-a-ip44',
    model: 'Pin & Sleeve Splashproof 63A 277V/480V 288V/500V Connector',
    manufacturer: 'Well Shin',
    category: 'consumable',
    description: 'Pin & Sleeve Splashproof 63A 277V/480V 288V/500V Connector',
    partNumber: 'WS-309-4P-63A-P-A-IP44',
    estimatedCost: '$185.52',
    specs: 'Consumable | UOM: Eaches',
    vendorIds: ['wellShin'],
  },
];

export default wellShinCatalog;
