// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Wesco Industrial Products · 3 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const wescoIndustrialProductsCatalog: CatalogItem[] = [
  {
    id: 'wescoIndustrialProducts-261022',
    model: 'WESCO PLATFORM FIXED BASE POWERED STACKER',
    manufacturer: 'Wesco Industrial Products',
    category: 'hardware',
    description: 'WESCO PLATFORM FIXED BASE POWERED STACKER',
    partNumber: '261022',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['wescoIndustrialProducts'],
  },
  {
    id: 'wescoIndustrialProducts-272942',
    model: 'WESCO PLATFORM FOR 273204 LIFT STACKER',
    manufacturer: 'Wesco Industrial Products',
    category: 'hardware',
    description: 'WESCO PLATFORM FOR 273204 LIFT STACKER',
    partNumber: '272942',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['wescoIndustrialProducts'],
  },
  {
    id: 'wescoIndustrialProducts-273204',
    model: 'WESCO BATTERY OPERATED VALUE LIFT STACKER',
    manufacturer: 'Wesco Industrial Products',
    category: 'hardware',
    description: 'WESCO BATTERY OPERATED VALUE LIFT STACKER',
    partNumber: '273204',
    estimatedCost: '',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['wescoIndustrialProducts'],
  },
];

export default wescoIndustrialProductsCatalog;
