// AUTO-GENERATED by scripts/generate-catalog.mjs from References/NSIM Item Master 4-16-26 .csv
// Vendor: Western Digital · 1 items. Re-run the script to refresh.
import type { CatalogItem } from './types';

const westernDigitalCatalog: CatalogItem[] = [
  {
    id: 'westernDigital-wds100t1x0l',
    model: 'Western Digital WD BLACK AN1500 NVMe AIC 1TB PCI-Express 3.0 x8 Internal Solid State Drive',
    manufacturer: 'Western Digital',
    category: 'hardware',
    description: 'Western Digital WD BLACK AN1500 NVMe AIC 1TB PCI-Express 3.0 x8 Internal Solid State Drive',
    partNumber: 'WDS100T1X0L',
    estimatedCost: '$212.41',
    specs: 'Hardware | UOM: Eaches',
    vendorIds: ['westernDigital'],
  },
];

export default westernDigitalCatalog;
