import type { CatalogItem } from './types';

const anixterCatalog: CatalogItem[] = [
  {
    id: 'anixter-w1m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 1M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 1M',
    partNumber: 'W1M-2FSM-LCLC',
    estimatedCost: '$6.16',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w2m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 2M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 2M',
    partNumber: 'W2M-2FSM-LCLC',
    estimatedCost: '$6.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w3m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 3M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 3M',
    partNumber: 'W3M-2FSM-LCLC',
    estimatedCost: '$6.39',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w5m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 5M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 5M',
    partNumber: 'W5M-2FSM-LCLC',
    estimatedCost: '$6.62',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w7m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 7M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 7M',
    partNumber: 'W7M-2FSM-LCLC',
    estimatedCost: '$6.86',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w9m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 9M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 9M',
    partNumber: 'W9M-2FSM-LCLC',
    estimatedCost: '$7.10',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w10m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 10M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 10M',
    partNumber: 'W10M-2FSM-LCLC',
    estimatedCost: '$7.22',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w15m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 15M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 15M',
    partNumber: 'W15M-2FSM-LCLC',
    estimatedCost: '$7.81',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w20m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 20M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 20M',
    partNumber: 'W20M-2FSM-LCLC',
    estimatedCost: '$8.39',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w25m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 25M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 25M',
    partNumber: 'W25M-2FSM-LCLC',
    estimatedCost: '$8.97',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w30m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 30M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 30M',
    partNumber: 'W30M-2FSM-LCLC',
    estimatedCost: '$9.57',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w35m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 35M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 35M',
    partNumber: 'W35M-2FSM-LCLC',
    estimatedCost: '$10.16',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w40m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 40M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 40M',
    partNumber: 'W40M-2FSM-LCLC',
    estimatedCost: '$10.74',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w45m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 45M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 45M',
    partNumber: 'W45M-2FSM-LCLC',
    estimatedCost: '$11.32',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w50m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 50M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 50M',
    partNumber: 'W50M-2FSM-LCLC',
    estimatedCost: '$11.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w60m-2fsm-lclc',
    model: 'Corning OS2 Duplex LC-LC 60M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 Duplex LC-LC 60M',
    partNumber: 'W60M-2FSM-LCLC',
    estimatedCost: '$13.09',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w1m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 1M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 1M',
    partNumber: 'W1M-12F-FF-OS2',
    estimatedCost: '$49.34',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w2m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 2M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 2M',
    partNumber: 'W2M-12F-FF-OS2',
    estimatedCost: '$50.15',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w3m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 3M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 3M',
    partNumber: 'W3M-12F-FF-OS2',
    estimatedCost: '$50.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w5m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 5M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 5M',
    partNumber: 'W5M-12F-FF-OS2',
    estimatedCost: '$52.57',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w10m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 10M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 10M',
    partNumber: 'W10M-12F-FF-OS2',
    estimatedCost: '$56.61',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w15m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 15M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 15M',
    partNumber: 'W15M-12F-FF-OS2',
    estimatedCost: '$60.64',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w20m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 20M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 20M',
    partNumber: 'W20M-12F-FF-OS2',
    estimatedCost: '$64.68',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w25m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 25M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 25M',
    partNumber: 'W25M-12F-FF-OS2',
    estimatedCost: '$68.72',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w30m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 30M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 30M',
    partNumber: 'W30M-12F-FF-OS2',
    estimatedCost: '$72.76',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w35m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 35M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 35M',
    partNumber: 'W35M-12F-FF-OS2',
    estimatedCost: '$76.79',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w40m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 40M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 40M',
    partNumber: 'W40M-12F-FF-OS2',
    estimatedCost: '$80.84',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w45m-12f-ff-os2',
    model: 'Corning OS2 12F MTP F-F Type B 45M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 45M',
    partNumber: 'W45M-12F-FF-OS2',
    estimatedCost: '$84.88',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w10m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 10M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 10M Bun',
    partNumber: 'W10M-12F-OS2-B',
    estimatedCost: '$440.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w15m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 15M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 15M Bun',
    partNumber: 'W15M-12F-OS2-B',
    estimatedCost: '$468.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w20m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 20M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 20M Bun',
    partNumber: 'W20M-12F-OS2-B',
    estimatedCost: '$497.04',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w25m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 25M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 25M Bun',
    partNumber: 'W25M-12F-OS2-B',
    estimatedCost: '$525.64',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w30m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 30M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 30M Bun',
    partNumber: 'W30M-12F-OS2-B',
    estimatedCost: '$554.23',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w35m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 35M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 35M Bun',
    partNumber: 'W35M-12F-OS2-B',
    estimatedCost: '$582.81',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w40m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 40M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 40M Bun',
    partNumber: 'W40M-12F-OS2-B',
    estimatedCost: '$611.40',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w45m-12f-os2-b',
    model: 'Corning OS2 12F MTP F-F Type B 45M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OS2 12F MTP F-F Type B 45M Bun',
    partNumber: 'W45M-12F-OS2-B',
    estimatedCost: '$639.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w7m-12f-om3-b',
    model: 'Corning OM3 12F MTP F-F APC Type B 7M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM3 12F MTP F-F APC Type B 7M',
    partNumber: 'W7M-12F-OM3-B',
    estimatedCost: '$483.23',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w10m-12f-om3-b',
    model: 'Corning OM3 12F MTP F-F APC Type B 10M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM3 12F MTP F-F APC Type B 10M',
    partNumber: 'W10M-12F-OM3-B',
    estimatedCost: '$492.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w15m-12f-om3-b',
    model: 'Corning OM3 12F MTP F-F APC Type B 15M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM3 12F MTP F-F APC Type B 15M',
    partNumber: 'W15M-12F-OM3-B',
    estimatedCost: '$506.61',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w20m-12f-om3-b',
    model: 'Corning OM3 12F MTP F-F APC Type B 20M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM3 12F MTP F-F APC Type B 20M',
    partNumber: 'W20M-12F-OM3-B',
    estimatedCost: '$521.23',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w25m-12f-om3-b',
    model: 'Corning OM3 12F MTP F-F APC Type B 25M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM3 12F MTP F-F APC Type B 25M',
    partNumber: 'W25M-12F-OM3-B',
    estimatedCost: '$535.84',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w30m-12f-om3-b',
    model: 'Corning OM3 12F MTP F-F APC Type B 30M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM3 12F MTP F-F APC Type B 30M',
    partNumber: 'W30M-12F-OM3-B',
    estimatedCost: '$550.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w35m-12f-om4-b',
    model: 'Corning OM4 12F MTP F-F APC Type B 35M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM4 12F MTP F-F APC Type B 35M',
    partNumber: 'W35M-12F-OM4-B',
    estimatedCost: '$1,049.64',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w40m-12f-om4-b',
    model: 'Corning OM4 12F MTP F-F APC Type B 40M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM4 12F MTP F-F APC Type B 40M',
    partNumber: 'W40M-12F-OM4-B',
    estimatedCost: '$1,135.52',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w45m-12f-om4-b',
    model: 'Corning OM4 12F MTP F-F APC Type B 45M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM4 12F MTP F-F APC Type B 45M',
    partNumber: 'W45M-12F-OM4-B',
    estimatedCost: '$1,221.39',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w50m-12f-om4-b',
    model: 'Corning OM4 12F MTP F-F APC Type B 50M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Corning OM4 12F MTP F-F APC Type B 50M',
    partNumber: 'W50M-12F-OM4-B',
    estimatedCost: '$1,307.36',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-005f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 5FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 5FT',
    partNumber: 'WCAT6A-WHB-005F',
    estimatedCost: '$2.24',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-007f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 7FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 7FT',
    partNumber: 'WCAT6A-WHB-007F',
    estimatedCost: '$2.48',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-010f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 10FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 10FT',
    partNumber: 'WCAT6A-WHB-010F',
    estimatedCost: '$2.87',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-020f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 20FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 20FT',
    partNumber: 'WCAT6A-WHB-020F',
    estimatedCost: '$4.12',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-025f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 25FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 25FT',
    partNumber: 'WCAT6A-WHB-025F',
    estimatedCost: '$11.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-030f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 30FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 30FT',
    partNumber: 'WCAT6A-WHB-030F',
    estimatedCost: '$13.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-035f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 35FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 35FT',
    partNumber: 'WCAT6A-WHB-035F',
    estimatedCost: '$14.09',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-040f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 40FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 40FT',
    partNumber: 'WCAT6A-WHB-040F',
    estimatedCost: '$15.29',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-wcat6a-whb-050f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 50FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 50FT',
    partNumber: 'WCAT6A-WHB-050F',
    estimatedCost: '$17.42',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-he87808gph-kb005m',
    model: 'OS2 8-F MTP (UNPINNED) TO TWO4-F (UNPINNED) MTP APC TYPE-B 5M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 8-F MTP (UNPINNED) TO TWO4-F (UNPINNED) MTP APC TYPE-B 5M',
    partNumber: 'HE87808GPH-KB005M',
    estimatedCost: '$159.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-010f',
    model: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 10FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 10FT',
    partNumber: '6CAM-WHB-010F',
    estimatedCost: '$2.87',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-060f',
    model: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 60FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 60FT',
    partNumber: '6CAM-WHB-060F',
    estimatedCost: '$19.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w8m-2fsm-lclc',
    model: 'OS2 Duplex LC-LC 8M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 Duplex LC-LC 8M',
    partNumber: 'L040402G5120008M',
    estimatedCost: '$6.97',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w12m-2fsm-lclc',
    model: 'OS2 Duplex LC-LC 12M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 Duplex LC-LC 12M',
    partNumber: 'L040402G5120012M',
    estimatedCost: '$7.46',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w7m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 7M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 7M',
    partNumber: 'JZDZD12GE8-NB007M',
    estimatedCost: '$54.19',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w50m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 50M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 50M',
    partNumber: 'JZDZD12GE8-NB050M',
    estimatedCost: '$88.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w55m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 55M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 55M',
    partNumber: 'JZDZD12GE8-NB055M',
    estimatedCost: '$92.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w60m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 60M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 60M',
    partNumber: 'JZDZD12GE8-NB060M',
    estimatedCost: '$96.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w70m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 70M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 70M',
    partNumber: 'JZDZD12GE8-NB070M',
    estimatedCost: '$105.07',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w75m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 75M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 75M',
    partNumber: 'JZDZD12GE8-NB075M',
    estimatedCost: '$109.11',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w80m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 80M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 80M',
    partNumber: 'JZDZD12GE8-NB080M',
    estimatedCost: '$113.14',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w85m-12f-ff-os2',
    model: 'OS2 12F MTP F-F Type B 85M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 85M',
    partNumber: 'JZDZD12GE8-NB085M',
    estimatedCost: '$117.19',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w100m-12f-ffos2',
    model: 'OS2 12F MTP F-F Type B 100M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 100M',
    partNumber: 'JZDZD12GE8-NB100M',
    estimatedCost: '$129.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w50m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 50M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 50M Bun',
    partNumber: 'G-BND08-9090G-PN000- 050M',
    estimatedCost: '$668.59',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w55m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 55M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 55M Bun',
    partNumber: 'G-BND08-9090G-PN000- 055M',
    estimatedCost: '$697.18',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w60m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 60M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 60M Bun',
    partNumber: 'G-BND08-9090G-PN000- 060M',
    estimatedCost: '$725.76',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w65m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 65M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 65M Bun',
    partNumber: 'G-BND08-9090G-PN000- 065M',
    estimatedCost: '$754.35',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w70m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 70M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 70M Bun',
    partNumber: 'G-BND08-9090G-PN000- 070M',
    estimatedCost: '$782.94',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w75m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 75M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 75M Bun',
    partNumber: 'G-BND08-9090G-PN000- 075M',
    estimatedCost: '$811.54',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w80m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 80M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 80M Bun',
    partNumber: 'G-BND08-9090G-PN000- 080M',
    estimatedCost: '$840.12',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w85m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 85M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 85M Bun',
    partNumber: 'G-BND08-9090G-PN000- 085M',
    estimatedCost: '$868.71',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w90m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 90M Bun',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 90M Bun',
    partNumber: 'G-BND08-9090G-PN000- 090M',
    estimatedCost: '$897.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w125m-12f-os2-b',
    model: 'OS2 12F MTP F-F Type B 125M Bu',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OS2 12F MTP F-F Type B 125M Bu',
    partNumber: 'G-BND08-9090G-PN000- 125M',
    estimatedCost: '$1,097.43',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w55m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 55M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 55M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 055M',
    estimatedCost: '$1,393.14',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w60m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 60M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 60M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 060M',
    estimatedCost: '$1,479.02',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w65m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 65M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 65M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 065M',
    estimatedCost: '$1,564.90',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w75m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 75M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 75M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 075M',
    estimatedCost: '$1,736.65',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w80m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 80M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 80M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 080M',
    estimatedCost: '$1,822.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w900m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 90M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 90M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 090M',
    estimatedCost: '$1,994.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-005f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 5FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 5FT',
    partNumber: '6CAM-WHB-005F',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-007f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 7FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 7FT',
    partNumber: '6CAM-WHB-007F',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-020f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 20FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 20FT',
    partNumber: '6CAM-WHB-020F',
    estimatedCost: '$3.98',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-023f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 23FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 23FT',
    partNumber: '8C/6CAM-WHB-023F',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-025f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 25FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 25FT',
    partNumber: '6CAM-WHB-025F',
    estimatedCost: '$11.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-030f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 30FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 30FT',
    partNumber: '6CAM-WHB-030F',
    estimatedCost: '$12.58',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-033f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 33FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 33FT',
    partNumber: '8C/6CAM-WHB-033F',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-035f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 35FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 35FT',
    partNumber: '8C/6CAM-WHB-035F',
    estimatedCost: '$13.64',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-040f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 40FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 40FT',
    partNumber: '8C/6CAM-WHB-040F',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-050f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 50FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 50FT',
    partNumber: '8C/6CAM-WHB-050F',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-065f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 65FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 65FT',
    partNumber: '8C/6CAM-WHB-065F',
    estimatedCost: '$21.14',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-075f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 75FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 75FT',
    partNumber: '8C/6CAM-WHB-075F',
    estimatedCost: '$22.62',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-080f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 80FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 80FT',
    partNumber: '8C/6CAM-WHB-080F',
    estimatedCost: '$24.69',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-085f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 85FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 85FT',
    partNumber: '8C/6CAM-WHB-085F',
    estimatedCost: '$25.65',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-090f',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 90FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 90FT',
    partNumber: '8C/6CAM-WHB-090F',
    estimatedCost: '$26.61',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w4m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 4M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 4M',
    partNumber: 'L040402G5120004M',
    estimatedCost: '$6.51',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w11m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 11M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 11M',
    partNumber: 'L040402G5120011M',
    estimatedCost: '$7.33',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w13m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 13M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 13M',
    partNumber: 'L040402G5120013M',
    estimatedCost: '$7.57',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w14m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 14M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 14M',
    partNumber: 'L040402G5120014M',
    estimatedCost: '$7.69',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w16m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 16M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 16M',
    partNumber: 'L040402G5120016M',
    estimatedCost: '$7.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w17m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 17M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 17M',
    partNumber: 'L040402G5120017M',
    estimatedCost: '$8.04',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w19m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 19M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 19M',
    partNumber: 'L040402G5120019M',
    estimatedCost: '$8.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w22m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 22M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 22M',
    partNumber: 'L040402G5120022M',
    estimatedCost: '$8.62',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w23m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 23M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 23M',
    partNumber: 'L040402G5120023M',
    estimatedCost: '$8.74',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w26m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 26M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 26M',
    partNumber: 'L040402G5120026M',
    estimatedCost: '$9.09',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w28m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 28M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 28M',
    partNumber: 'L040402G5120028M',
    estimatedCost: '$9.33',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w31m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 31M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 31M',
    partNumber: 'L040402G5120031M',
    estimatedCost: '$9.68',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w33m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 33M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 33M',
    partNumber: 'L040402G5120033M',
    estimatedCost: '$9.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w34m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 34M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 34M',
    partNumber: 'L040402G5120034M',
    estimatedCost: '$10.04',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w36m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 36M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 36M',
    partNumber: 'L040402G5120036M',
    estimatedCost: '$10.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w37m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 37M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 37M',
    partNumber: 'L040402G5120037M',
    estimatedCost: '$10.39',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w39m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 39M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 39M',
    partNumber: 'L040402G5120039M',
    estimatedCost: '$10.62',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w48m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 48M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 48M',
    partNumber: 'L040402G5120048M',
    estimatedCost: '$11.68',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w58m-2fsm-lclc',
    model: 'LC Duplex to LC Duplex, SM - 58M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'LC Duplex to LC Duplex, SM - 58M',
    partNumber: 'L040402G5120058M',
    estimatedCost: '$12.85',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w10m-8f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 8F, SM Type B 10M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 8F, SM Type B 10M',
    partNumber: 'JEDED08GE8-NB010M',
    estimatedCost: '$55.09',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w11m-8f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 8F, SM Type B 11M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 8F, SM Type B 11M',
    partNumber: 'JEDED08GE8-NB011M',
    estimatedCost: '$56.11',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w4m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 4M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 4M',
    partNumber: 'JZDZD12GE8-NB004M',
    estimatedCost: '$51.77',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w11m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 11M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 11M',
    partNumber: 'JZDZD12GE8-NB011M',
    estimatedCost: '$57.41',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w13m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 13M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 13M',
    partNumber: 'JZDZD12GE8-NB013M',
    estimatedCost: '$59.03',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w14m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 14M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 14M',
    partNumber: 'JZDZD12GE8-NB014M',
    estimatedCost: '$59.84',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w16m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 16M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 16M',
    partNumber: 'JZDZD12GE8-NB016M',
    estimatedCost: '$61.46',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w17m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 17M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 17M',
    partNumber: 'JZDZD12GE8-NB017M',
    estimatedCost: '$62.26',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w19m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 19M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 19M',
    partNumber: 'JZDZD12GE8-NB019M',
    estimatedCost: '$63.88',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w22m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 22M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 22M',
    partNumber: 'JZDZD12GE8-NB022M',
    estimatedCost: '$66.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w23m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 23M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 23M',
    partNumber: 'JZDZD12GE8-NB023M',
    estimatedCost: '$67.10',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w26m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 26M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 26M',
    partNumber: 'JZDZD12GE8-NB026M',
    estimatedCost: '$69.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w28m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 28M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 28M',
    partNumber: 'JZDZD12GE8-NB028M',
    estimatedCost: '$71.15',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w29m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 29M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 29M',
    partNumber: 'JZDZD12GE8-NB029M',
    estimatedCost: '$71.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w31m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 31M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 31M',
    partNumber: 'JZDZD12GE8-NB031M',
    estimatedCost: '$73.57',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w33m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 33M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 33M',
    partNumber: 'JZDZD12GE8-NB033M',
    estimatedCost: '$75.19',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w34m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 34M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 34M',
    partNumber: 'JZDZD12GE8-NB034M',
    estimatedCost: '$75.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w36m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 36M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 36M',
    partNumber: 'JZDZD12GE8-NB036M',
    estimatedCost: '$77.61',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w37m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 37M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 37M',
    partNumber: 'JZDZD12GE8-NB037M',
    estimatedCost: '$78.41',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w42m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 42M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 42M',
    partNumber: 'JZDZD12GE8-NB042M',
    estimatedCost: '$82.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w43m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 43M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 43M',
    partNumber: 'JZDZD12GE8-NB043M',
    estimatedCost: '$83.26',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w48m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 48M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 48M',
    partNumber: 'JZDZD12GE8-NB048M',
    estimatedCost: '$87.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w58m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 58M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 58M',
    partNumber: 'JZDZD12GE8-NB058M',
    estimatedCost: '$95.38',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w70m-12f-om4-b',
    model: 'MPO APC Non-Pinned to MPO APC Non-Pinned, 12F, OM4 Type B 70M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO APC Non-Pinned to MPO APC Non-Pinned, 12F, OM4 Type B 70M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 070M',
    estimatedCost: '$1,650.77',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-006fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 6FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 6FT',
    partNumber: '8C/6CAM-WHB-006F',
    estimatedCost: '$8.05',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-009fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 9FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 9FT',
    partNumber: '8C/6CAM-WHB-009F',
    estimatedCost: '$8.66',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-012fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 12FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 12FT',
    partNumber: '8C/6CAM-WHB-012F',
    estimatedCost: '$9.28',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-015fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 15FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 15FT',
    partNumber: '8C/6CAM-WHB-015F',
    estimatedCost: '$9.91',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-035fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 35FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 35FT',
    partNumber: '8C/6CAM-WHB-035F',
    estimatedCost: '$14.01',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-040fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 40FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 40FT',
    partNumber: '8C/6CAM-WHB-040F',
    estimatedCost: '$15.05',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-045fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 45FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 45FT',
    partNumber: '8C/6CAM-WHB-045F',
    estimatedCost: '$16.08',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-050fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 50FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 50FT',
    partNumber: '8C/6CAM-WHB-050F',
    estimatedCost: '$17.11',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-055fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 55FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 55FT',
    partNumber: '8C/6CAM-WHB-055F',
    estimatedCost: '$18.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-060fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 60FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 60FT',
    partNumber: '8C/6CAM-WHB-060F',
    estimatedCost: '$19.56',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-065fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 65FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 65FT',
    partNumber: '8C/6CAM-WHB-065F',
    estimatedCost: '$20.58',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-070fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 70FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 70FT',
    partNumber: '8C/6CAM-WHB-070F',
    estimatedCost: '$21.62',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-075fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 75FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 75FT',
    partNumber: '8C/6CAM-WHB-075F',
    estimatedCost: '$23.05',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-080fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 80FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 80FT',
    partNumber: '8C/6CAM-WHB-080F',
    estimatedCost: '$24.07',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-085fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 85FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 85FT',
    partNumber: '8C/6CAM-WHB-085F',
    estimatedCost: '$25.10',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-100fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 100FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 100FT',
    partNumber: '8C/6CAM-WHB-100F',
    estimatedCost: '$28.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-105fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 105FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 105FT',
    partNumber: '8C/6CAM-WHB-105F',
    estimatedCost: '$29.23',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-110fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 110FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 110FT',
    partNumber: '8C/6CAM-WHB-110F',
    estimatedCost: '$30.25',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-115fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 115FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 115FT',
    partNumber: '8C/6CAM-WHB-115F',
    estimatedCost: '$31.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-125fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 125FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 125FT',
    partNumber: '8C/6CAM-WHB-125F',
    estimatedCost: '$33.34',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-130fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 130FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 130FT',
    partNumber: '8C/6CAM-WHB-130F',
    estimatedCost: '$35.15',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-150fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 150FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 150FT',
    partNumber: '8C/6CAM-WHB-150F',
    estimatedCost: '$40.07',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-185fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 185FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 185FT',
    partNumber: '8C/6CAM-WHB-185F',
    estimatedCost: '$48.07',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-190fn',
    model: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 190FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'Liberty CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 190FT',
    partNumber: '8C/6CAM-WHB-190F',
    estimatedCost: '$49.10',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w9m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 9M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 9M',
    partNumber: 'W9M-12F-FF-OS2',
    estimatedCost: '$55.79',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w12m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 12M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 12M',
    partNumber: 'W12M-12F-FF-OS2',
    estimatedCost: '$58.22',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w18m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 18M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 18M',
    partNumber: 'W18M-12F-FF-OS2',
    estimatedCost: '$63.07',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w21m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 21M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 21M',
    partNumber: 'W21M-12F-FF-OS2',
    estimatedCost: '$65.49',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w24m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 24M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 24M',
    partNumber: 'W24M-12F-FF-OS2',
    estimatedCost: '$67.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w27m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 27M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 27M',
    partNumber: 'W27M-12F-FF-OS2',
    estimatedCost: '$70.34',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w32m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 32M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 32M',
    partNumber: 'W32M-12F-FF-OS2',
    estimatedCost: '$74.37',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w47m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 47M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 47M',
    partNumber: 'W47M-12F-FF-OS2',
    estimatedCost: '$86.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w59m-12f-ff-os2',
    model: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 59M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO Non-Pinned to MPO Non-Pinned, 12F, SM Type B 59M',
    partNumber: 'W59M-12F-FF-OS2',
    estimatedCost: '$96.19',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-518457',
    model: 'CORNING-C EDGE-CS12-AE-P00RE 12-F SPLICE CASSETTE LC DUPLEXSM UPC, SINGLE-FIBER',
    manufacturer: 'Anixter',
    category: 'other',
    description: 'CORNING-C EDGE-CS12-AE-P00RE 12-F SPLICE CASSETTE LC DUPLEXSM UPC, SINGLE-FIBER 12 MODULEEDGE-CS12-AE-P00RE',
    partNumber: '518457',
    estimatedCost: '$532.66',
    specs: 'Consumables and Misc. | Serialized | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-512081',
    model: 'CORNING-C EDGE-CS12-AE 12-F EDGE FIELD-TERM CASSETTE SM OS2, 6X LC DUPLEX SHUTTE',
    manufacturer: 'Anixter',
    category: 'other',
    description: 'CORNING-C EDGE-CS12-AE 12-F EDGE FIELD-TERM CASSETTE SM OS2, 6X LC DUPLEX SHUTTEREDADAPTER',
    partNumber: '512081',
    estimatedCost: '$163.21',
    specs: 'Consumables and Misc. | Serialized | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-y56zq4-14161b53',
    model: '3456-FIBER ROCKETRIBBON® DIELECTRIC CABLE-200 FLOW, GEL-FREE BEND-IMPROVED SINGL',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '3456-FIBER ROCKETRIBBON® DIELECTRIC CABLE-200 FLOW, GEL-FREE BEND-IMPROVED SINGLE-MODE,(OS2),190 μM,G.652.D & G.657.A1 MAX: 0.4/0.4/0.3 DB/KM WITH 5% OF FIBERS UP TO 0.5/0.5/0.4 PRINT IN FT WITH SOCC',
    partNumber: 'Y56ZQ4-14161B53',
    estimatedCost: '$18.42',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w5m-8f-smapc-lc',
    model: '5m MPO-8 Female APC 8 Strand to 4 Duplex LC UPC Singlemode Yellow Breakout Cable',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '5m MPO-8 Female APC 8 Strand to 4 Duplex LC UPC Singlemode Yellow Breakout Cable, Type B, 0.5m Breakout Length',
    partNumber: 'W5M-8F-SMAPC-LC',
    estimatedCost: '$159.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-010fn',
    model: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 10FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 10FT',
    partNumber: 'W6CAM-WHB-010FN',
    estimatedCost: '$8.88',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w90m-12f-om4-b',
    model: 'OM4 12F MTP F-F APC Type B 90M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'OM4 12F MTP F-F APC Type B 90M',
    partNumber: 'G-BND08-Z1Z1Q-PN000- 090M',
    estimatedCost: '$1,994.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-ds-821b1xn7-03',
    model: 'WORLD CORD 8C/6CAM-WHB016F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 16FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'WORLD CORD 8C/6CAM-WHB016F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 16FT',
    partNumber: 'DS-821B1XN7-03',
    estimatedCost: '$9.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-025fn',
    model: '8C/6CAM-WHB-025F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 25FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '8C/6CAM-WHB-025F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 25FT',
    partNumber: 'W6CAM-WHB-025FN',
    estimatedCost: '$11.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-120fn',
    model: '8C/6CAM-WHB120F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 120FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '8C/6CAM-WHB120F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 120FT',
    partNumber: 'W6CAM-WHB-120FN',
    estimatedCost: '$32.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-140fn',
    model: '8C/6CAM-WHB140F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 140FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '8C/6CAM-WHB140F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 140FT',
    partNumber: 'W6CAM-WHB-140FN',
    estimatedCost: '$36.83',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-155fn',
    model: '8C/6CAM-WHB155F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 155FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '8C/6CAM-WHB155F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 155FT',
    partNumber: 'W6CAM-WHB-155FN',
    estimatedCost: '$41.29',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-180fn',
    model: '8C/6CAM-WHB180F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 180FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '8C/6CAM-WHB180F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 180FT',
    partNumber: 'W6CAM-WHB-180FN',
    estimatedCost: '$46.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-220fn',
    model: '8C/6CAM-WHB220F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 220FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '8C/6CAM-WHB220F CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 220FT',
    partNumber: 'W6CAM-WHB-220FN',
    estimatedCost: '$64.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w55m-2fsm-lclc',
    model: '2F ULT ZIP R LCUDUP/LCUDUP CORE 55M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '2F ULT ZIP R LCUDUP/LCUDUP CORE 55M',
    partNumber: 'W55M-2FSM-LCLC',
    estimatedCost: '$12.52',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w70m-2fsm-lclc',
    model: '2F ULT ZIP R LCUDUP/LCUDUP CORE70M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '2F ULT ZIP R LCUDUP/LCUDUP CORE70M',
    partNumber: 'W70M-2FSM-LCLC',
    estimatedCost: '$14.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w75m-2fsm-lclc',
    model: '2F ULT ZIP R LCUDUP/LCUDUP CORE75M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: '2F ULT ZIP R LCUDUP/LCUDUP CORE75M',
    partNumber: 'W75M-2FSM-LCLC',
    estimatedCost: '$14.87',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w5m-12f-om3-b',
    model: 'MESH BUNDLED JUMPER 8XMPO APC OM3, 78" NS LEGS 5M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MESH BUNDLED JUMPER 8XMPO APC OM3, 78" NS LEGS 5M',
    partNumber: 'W5M-12F-OM3-B',
    estimatedCost: '$477.84',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w85m-12f-om4-b',
    model: 'MPO APC Non-Pinned to MPO APC Non-Pinned, 12F, OM4 Type B 85M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'MPO APC Non-Pinned to MPO APC Non-Pinned, 12F, OM4 Type B 85M',
    partNumber: 'W85M-12F-OM4-B',
    estimatedCost: '$1,973.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w95m-12f-om4-b',
    model: 'FULL#G-BND08-Z1Z1Q-PN000-095M MESH BUNDLED JUMPER 8XMPO APC OM4 78" NS LEGS 095M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'FULL#G-BND08-Z1Z1Q-PN000-095M MESH BUNDLED JUMPER 8XMPO APC OM4 78" NS LEGS 095M',
    partNumber: 'W95M-12F-OM4-B',
    estimatedCost: '$2,174.67',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w100m-12f-om4-b',
    model: 'FULL#G-BND08-Z1Z1Q-PN000-100M MESH BUNDLED JUMPER 8XMPO APC OM4 78" NS LEGS 10',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'FULL#G-BND08-Z1Z1Q-PN000-100M MESH BUNDLED JUMPER 8XMPO APC OM4 78" NS LEGS 100M',
    partNumber: 'W100M-12F-OM4-B',
    estimatedCost: '$2,264.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w125m-2fsm-lclc',
    model: 'FULL# L040402G5120125M 2F ULT ZIP R LCUDUP/LCUDUP CORE 125M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'FULL# L040402G5120125M 2F ULT ZIP R LCUDUP/LCUDUP CORE 125M',
    partNumber: 'W125M-2FSM-LCLC',
    estimatedCost: '$21.66',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w125m-12f-ff-os2',
    model: 'FULL# JZDZD12GE8-NB125M 12F JMP OS2 MPO NON-PINNED TO MPO NP TYPE B 125M',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'FULL# JZDZD12GE8-NB125M 12F JMP OS2 MPO NON-PINNED TO MPO NP TYPE B 125M',
    partNumber: 'W125M-12F-FF-OS2',
    estimatedCost: '$156.28',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
  {
    id: 'anixter-w6cam-whb-165fn',
    model: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 165FT',
    manufacturer: 'Anixter',
    category: 'cable',
    description: 'CAT6A, 28AWG, UNSHLD, BOOTED, WHITE, 165FT',
    partNumber: 'W6CAM-WHB-165FN',
    estimatedCost: '$45.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["anixter"],
  },
];

export default anixterCatalog;
