import type { CatalogItem } from './types';

const aristaCatalog: CatalogItem[] = [
  {
    id: 'arista-dcs-7170b-64c',
    model: 'Arista 7170B, Programmable 64 x 100GbE QSFP switch, front to rear air, 2 x AC',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista 7170B, Programmable 64 x 100GbE QSFP switch, front to rear air, 2 x AC',
    partNumber: 'DCS-7170B-64C',
    estimatedCost: '$3,499.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-dcs-7170b-64c-f',
    model: 'Arista DCS-7160-48TC6-R 48x 10GbE RJ45 6x 100GbE QSFP Switch R-F Air',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista DCS-7160-48TC6-R 48x 10GbE RJ45 6x 100GbE QSFP Switch R-F Air',
    partNumber: 'DCS-7170B-64C',
    estimatedCost: '$4,837.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-arista-dcs-7260cx3-64',
    model: 'Arista DCS-7260CX3-64-F 7260X3 64x100GbE QSFP & 2xSFP+switch front-to-rear air 2',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista DCS-7260CX3-64-F 7260X3 64x100GbE QSFP & 2xSFP+switch front-to-rear air 2xAC',
    partNumber: 'Arista DCS-7260CX3-64',
    estimatedCost: '$6,930.63',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-arista-dcs-7050qx-32s',
    model: 'Arista 7050QX-32S 32x40GbE QSFP+ ports, 4 SFP+ ports',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista 7050QX-32S 32x40GbE QSFP+ ports, 4 SFP+ ports',
    partNumber: 'Arista DCS-7050QX-32S',
    estimatedCost: '$1,302.97',
    specs: 'Network Switches | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-arista-dcs-7050t-64',
    model: 'Arista 7050T-64 48 x 1/10GbE BaseT ports and 4 x 40GbE QSFP+ ports',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista 7050T-64 48 x 1/10GbE BaseT ports and 4 x 40GbE QSFP+ ports',
    partNumber: 'Arista DCS-7050T-64',
    estimatedCost: '$1,533.13',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-arista-dcs-7050tx-64',
    model: 'Arista DCS-7050TX-64-r 48x RJ45 1/10GBASE-T 4x QSFP+ 56 Refurbished',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista DCS-7050TX-64-r 48x RJ45 1/10GBASE-T 4x QSFP+ 56 Refurbished',
    partNumber: 'Arista DCS-7050TX-64',
    estimatedCost: '$5,779.50',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-arista-dcs-7060-cx-32s',
    model: 'Arista 7060CX-32S 32 x 100GbE QSFP100 ports, 2 SFP+ ports',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista 7060CX-32S 32 x 100GbE QSFP100 ports, 2 SFP+ ports',
    partNumber: 'Arista DCS-7060 CX-32S',
    estimatedCost: '$6,814.25',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-asy-00232-10',
    model: 'Arista F-TO-R FAN Module',
    manufacturer: 'Arista',
    category: 'server',
    description: 'Arista F-TO-R FAN Module',
    partNumber: 'ASY-00232-10',
    estimatedCost: '$114.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-asy-00246-10',
    model: 'Arista R-TO-F FAN Module For Arista 7150 24x1 / 10G Sfp+ Switch Rear TO Front Ai',
    manufacturer: 'Arista',
    category: 'other',
    description: 'Arista R-TO-F FAN Module For Arista 7150 24x1 / 10G Sfp+ Switch Rear TO Front Airflow',
    partNumber: 'ASY-00246-10',
    estimatedCost: '$58.79',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-cbl-00100',
    model: 'Arista cable 1X CBL-00100 REV.A1 1X CBL-00002 REV.A0 and 2X Power cords',
    manufacturer: 'Arista',
    category: 'cable',
    description: 'Arista cable 1X CBL-00100 REV.A1 1X CBL-00002 REV.A0 and 2X Power cords',
    partNumber: 'CBL-00100',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-arista-dcs-7060cx2-32s',
    model: 'Arista 7060X2, 32x100GbE QSFP & 2xSFP+ switch, configurable fans and psu, 2 x C1',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista 7060X2, 32x100GbE QSFP & 2xSFP+ switch, configurable fans and psu, 2 x C13-C14 cords',
    partNumber: 'Arista DCS-7060CX2-32S',
    estimatedCost: '$6,653.86',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-pwr-00159-04-b0',
    model: 'DPS-495CB-A For Desktop Power Supply',
    manufacturer: 'Arista',
    category: 'other',
    description: 'DPS-495CB-A For Desktop Power Supply',
    partNumber: 'PWR-00159-04-B0',
    estimatedCost: '$269.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-an1730',
    model: '7280 Series 1 RU (Gen 3) Data Center Switch',
    manufacturer: 'Arista',
    category: 'switch',
    description: '7280 Series 1 RU (Gen 3) Data Center Switch',
    partNumber: 'AN1730',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-pwr-00160-03',
    model: '495W Rear To Front Power Supply',
    manufacturer: 'Arista',
    category: 'other',
    description: '495W Rear To Front Power Supply',
    partNumber: 'PWR-00160-03',
    estimatedCost: '$145.00',
    specs: 'Machinery and Equipment | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-pwr-00160-04',
    model: '495W Rear To Front Power Supply',
    manufacturer: 'Arista',
    category: 'other',
    description: '495W Rear To Front Power Supply',
    partNumber: 'PWR-00160-04',
    estimatedCost: '$324.00',
    specs: 'Machinery and Equipment | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-dps-750ab-28',
    model: 'IBM 750-Watts AC high-efficiency 80-Plus Platinum Hot Swap Power Supply',
    manufacturer: 'Arista',
    category: 'other',
    description: 'IBM 750-Watts AC high-efficiency 80-Plus Platinum Hot Swap Power Supply',
    partNumber: 'DPS-750AB-28',
    estimatedCost: '$154.85',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-dcs-7368-sup-d',
    model: 'Arista 36-Port 100GbE Switch with Dual Supervisor',
    manufacturer: 'Arista',
    category: 'switch',
    description: 'Arista 36-Port 100GbE Switch with Dual Supervisor',
    partNumber: 'DCS-7368-SUP-D',
    estimatedCost: '$11,284.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-fan-7000-f',
    model: 'Arista Front-to-Back Airflow Switch Fan Module',
    manufacturer: 'Arista',
    category: 'server',
    description: 'Arista Front-to-Back Airflow Switch Fan Module',
    partNumber: 'FAN-7000-F',
    estimatedCost: '$34.99',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-fan-7000-r',
    model: 'Arista 7050 R-to-F B-to-F Blue Airflow ASY-00246-10 Switch Fan Module',
    manufacturer: 'Arista',
    category: 'server',
    description: 'Arista 7050 R-to-F B-to-F Blue Airflow ASY-00246-10 Switch Fan Module',
    partNumber: 'FAN-7000-R',
    estimatedCost: '$45.99',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-fan-7002-f',
    model: 'Arista Front-to-Back Airflow Switch Fan Module',
    manufacturer: 'Arista',
    category: 'server',
    description: 'Arista Front-to-Back Airflow Switch Fan Module',
    partNumber: 'FAN-7002-F',
    estimatedCost: '$69.99',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-dps-495cb-1a',
    model: 'Arista PWR-500AC-F DPS-495CB 7050SX 500W AC Front-to-Back Switch Power Supply',
    manufacturer: 'Arista',
    category: 'other',
    description: 'Arista PWR-500AC-F DPS-495CB 7050SX 500W AC Front-to-Back Switch Power Supply',
    partNumber: 'DPS-495CB-1A',
    estimatedCost: '$98.99',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-kit-4post-nt',
    model: 'Arista Post Rail Kit For 7280, 7250QX, 7050SX TX And QX',
    manufacturer: 'Arista',
    category: 'other',
    description: 'Arista Post Rail Kit For 7280, 7250QX, 7050SX TX And QX',
    partNumber: 'KIT-4POST-NT',
    estimatedCost: '$250.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["arista"],
  },
  {
    id: 'arista-pwr-500ac-r',
    model: 'ARISTA 500W PSU FOR 7050X/7280 R-F',
    manufacturer: 'Arista',
    category: 'other',
    description: 'ARISTA 500W PSU FOR 7050X/7280 R-F',
    partNumber: 'PWR-500AC-R',
    estimatedCost: '$150.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["arista"],
  },
];

export default aristaCatalog;
