import type { CatalogItem } from './types';

const arrowElectronicsCatalog: CatalogItem[] = [
  {
    id: 'arrowelectronics-1u-1n-gen5-1nic',
    model: 'Single Server 1U Chassis inc (Single NIC, Dual Port 200Gb\'s QSFP112 or Dual Port',
    manufacturer: 'Arrow Electronics',
    category: 'server',
    description: 'Single Server 1U Chassis inc (Single NIC, Dual Port 200Gb\'s QSFP112 or Dual Port HDR200 QSFP112)',
    partNumber: '1U-1N-GEN5-1NIC',
    estimatedCost: '$10,000.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["arrowElectronics"],
  },
  {
    id: 'arrowelectronics-df-3015',
    model: 'Ceres Enclosure: 1U HA Enclosure (up to 50GB/s): incl. 338TB NVMe Flash, 6.4TB S',
    manufacturer: 'Arrow Electronics',
    category: 'server',
    description: 'Ceres Enclosure: 1U HA Enclosure (up to 50GB/s): incl. 338TB NVMe Flash, 6.4TB SCM, 8 x 100Gb Bluefield 1 (ETH or IB)',
    partNumber: 'DF-3015',
    estimatedCost: '$52,058.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["arrowElectronics"],
  },
  {
    id: 'arrowelectronics-df-3060',
    model: 'Ceres Enclosure: 1U HA VAST Enclosure (up to 50GB/s): incl. 1350TB NVMe Flash, 1',
    manufacturer: 'Arrow Electronics',
    category: 'server',
    description: 'Ceres Enclosure: 1U HA VAST Enclosure (up to 50GB/s): incl. 1350TB NVMe Flash, 12.8TB SCM(TBC), Bluefield DPUs (ETH or IB)',
    partNumber: 'DF-3060',
    estimatedCost: '$169,000.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["arrowElectronics"],
  },
  {
    id: 'arrowelectronics-quad-4n-il-2nic',
    model: 'Quad Server Chassis inc 4 x Ice Lake Servers (Dual NIC)(Quad Port 100Gb\'s QSFP28',
    manufacturer: 'Arrow Electronics',
    category: 'server',
    description: 'Quad Server Chassis inc 4 x Ice Lake Servers (Dual NIC)(Quad Port 100Gb\'s QSFP28 or Quad Port HDR100 QSFP56)',
    partNumber: 'QUAD-4N-IL-2NIC',
    estimatedCost: '$29,411.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["arrowElectronics"],
  },
  {
    id: 'arrowelectronics-spare-kit-df-3015',
    model: 'Vast Data Spare Kit for DF-3015. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM Drives, N',
    manufacturer: 'Arrow Electronics',
    category: 'server',
    description: 'Vast Data Spare Kit for DF-3015. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM Drives, NVMe Flash QLC (15.36TB)',
    partNumber: 'SPARE-KIT-DF-3015',
    estimatedCost: '$10,149.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["arrowElectronics"],
  },
  {
    id: 'arrowelectronics-df-5630',
    model: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 1350TB NVMe Flash, 18TB SCM, 4',
    manufacturer: 'Arrow Electronics',
    category: 'server',
    description: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 1350TB NVMe Flash, 18TB SCM, 4 x 100Gb (ETH or CX5 IB)',
    partNumber: 'DF-5630',
    estimatedCost: '$240,444.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["arrowElectronics"],
  },
];

export default arrowElectronicsCatalog;
