import type { CatalogItem } from './types';

const avnetCatalog: CatalogItem[] = [
  {
    id: 'avnet-1u-1n-gen5-1nic',
    model: 'Single Server 1U Chassis inc (Single NIC, Dual Port 200Gb\'s QSFP112 or Dual Port',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Single Server 1U Chassis inc (Single NIC, Dual Port 200Gb\'s QSFP112 or Dual Port HDR200 QSFP112)',
    partNumber: '1U-1N-GEN5-1NIC',
    estimatedCost: '$10,000.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-df-3015',
    model: 'Ceres Enclosure: 1U HA Enclosure (up to 50GB/s): incl. 338TB NVMe Flash, 6.4TB S',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Ceres Enclosure: 1U HA Enclosure (up to 50GB/s): incl. 338TB NVMe Flash, 6.4TB SCM, 8 x 100Gb Bluefield 1 (ETH or IB)',
    partNumber: 'DF-3015',
    estimatedCost: '$52,058.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-df-3060',
    model: 'Ceres Enclosure: 1U HA VAST Enclosure (up to 50GB/s): incl. 1350TB NVMe Flash, 1',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Ceres Enclosure: 1U HA VAST Enclosure (up to 50GB/s): incl. 1350TB NVMe Flash, 12.8TB SCM(TBC), Bluefield DPUs (ETH or IB)',
    partNumber: 'DF-3060',
    estimatedCost: '$169,000.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-quad-4n-il-2nic',
    model: 'Quad Server Chassis inc 4 x Ice Lake Servers (Dual NIC)(Quad Port 100Gb\'s QSFP28',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Quad Server Chassis inc 4 x Ice Lake Servers (Dual NIC)(Quad Port 100Gb\'s QSFP28 or Quad Port HDR100 QSFP56)',
    partNumber: 'QUAD-4N-IL-2NIC',
    estimatedCost: '$29,411.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-spare-kit-df-3015',
    model: 'Vast Data Spare Kit for DF-3015. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM Drives, N',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Vast Data Spare Kit for DF-3015. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM Drives, NVMe Flash QLC (15.36TB)',
    partNumber: 'SPARE-KIT-DF-3015',
    estimatedCost: '$10,149.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-spare-kit-df-3060',
    model: 'SPARE-KIT-DF-3060 Spare Kit for DF-3060. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM (',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'SPARE-KIT-DF-3060 Spare Kit for DF-3060. DNODE, FAN, PSU, SCM Sled Inc 2 x SCM (1.6TB) Drives, NVMe Flash QLC (60TB)',
    partNumber: 'SPARE-KIT-DF-3060',
    estimatedCost: '$17,015.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-1u-1n-gen6-1nic',
    model: 'Single Server 1U Chassis (6th Gen) inc Single NIC, Dual Port 200Gb/HDR200 QSFP1',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Single Server 1U Chassis (6th Gen) inc Single NIC, Dual Port 200Gb/HDR200 QSFP112',
    partNumber: '1U-1N-GEN6-1NIC',
    estimatedCost: '$13,000.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-df-3060-v2',
    model: 'Ceres V2 Enclosure: 1U HA Enclosure (up to 60GB/s): incl. 1350TB NVMe Flash, 12.',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Ceres V2 Enclosure: 1U HA Enclosure (up to 60GB/s): incl. 1350TB NVMe Flash, 12.8TB SCM, 2x Bluefield 3 DPUs, 4x 200Gb/QSFP112 (ETH or IB)',
    partNumber: 'DF-3060-V2',
    estimatedCost: '$152,542.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-spare-kit-df-3060-v2',
    model: 'Spare Kit for DF-3060-V2. DNODEv2, FAN, PSU, SCM Sled Inc 2 x SCM (1.6TB) Drives',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Spare Kit for DF-3060-V2. DNODEv2, FAN, PSU, SCM Sled Inc 2 x SCM (1.6TB) Drives, NVMe Flash QLC (60TB)',
    partNumber: 'SPARE-KIT-DF-3060-V2',
    estimatedCost: '$17,015.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-1u-1n-gen6-2nic',
    model: 'Single Server 1U Chassis (6th Gen) inc Dual NIC, Dual Port 200Gb/HDR200 QSFP112',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Single Server 1U Chassis (6th Gen) inc Dual NIC, Dual Port 200Gb/HDR200 QSFP112',
    partNumber: '1U-1N-GEN6-2NIC',
    estimatedCost: '$14,500.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-df-56120',
    model: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 5400TB NVMe Flash, 38TB SCM, 4',
    manufacturer: 'Avnet',
    category: 'server',
    description: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 5400TB NVMe Flash, 38TB SCM, 4 x 100Gb (CX6 ETH or IB)',
    partNumber: 'DF-56120',
    estimatedCost: '$477,120.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-spare-kit-df-56120',
    model: 'Spare Kit for DF-56120 Enclosure incl. DNODE, FAN, PSU, 3.2TB SCM, NVMe Flash QL',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Spare Kit for DF-56120 Enclosure incl. DNODE, FAN, PSU, 3.2TB SCM, NVMe Flash QLC (120TB)',
    partNumber: 'SPARE-KIT-DF-56120',
    estimatedCost: '$21,313.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-df-5660',
    model: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 2700TB NVMe Flash, 18TB SCM, 4',
    manufacturer: 'Avnet',
    category: 'server',
    description: '2U HA Lightspeed Enclosure (up to 40GB/s): incl. 2700TB NVMe Flash, 18TB SCM, 4 x 100Gb (CX6 ETH or IB)',
    partNumber: 'DF-5660',
    estimatedCost: '$753,504.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
  {
    id: 'avnet-spare-kit-df-5660',
    model: 'Spare Kit for DF-5660 Enclosure incl. DNODE, FAN, PSU,1.6TB SCM, NVMe Flash QLC',
    manufacturer: 'Avnet',
    category: 'server',
    description: 'Spare Kit for DF-5660 Enclosure incl. DNODE, FAN, PSU,1.6TB SCM, NVMe Flash QLC (60TB)',
    partNumber: 'SPARE-KIT-DF-5660',
    estimatedCost: '$29,347.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["avnet"],
  },
];

export default avnetCatalog;
