import type { CatalogItem } from './types';

const cablesComCatalog: CatalogItem[] = [
  {
    id: 'cablescom-pc20c13-15a',
    model: '6ft (1.8m) IEC60320 C20 to IEC60320 C13 14AWG 250V/15A Power Cord, Black',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: '6ft (1.8m) IEC60320 C20 to IEC60320 C13 14AWG 250V/15A Power Cord, Black',
    partNumber: 'PC20C13-15A',
    estimatedCost: '$15.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
  {
    id: 'cablescom-c19c20-4-20a-y',
    model: '4 Feet C20 TO C19 PDU to Server 20 Amp Power Cord- Yellow',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: '4 Feet C20 TO C19 PDU to Server 20 Amp Power Cord- Yellow',
    partNumber: 'C19C20-4-20A-Y',
    estimatedCost: '$14.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
  {
    id: 'cablescom-pw134-7206',
    model: '6ft IEC-60320 C14 to C19 Extension Power Cord 14AWG 15A/250V SJT, Red',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: '6ft IEC-60320 C14 to C19 Extension Power Cord 14AWG 15A/250V SJT, Red',
    partNumber: 'PW134-7206',
    estimatedCost: '$5.86',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
  {
    id: 'cablescom-pw137-1206',
    model: '6ft IEC-320 C20 to C15 Heavy Duty Power Cord, 14 AWG, SJT, 15A/250V, Black',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: '6ft IEC-320 C20 to C15 Heavy Duty Power Cord, 14 AWG, SJT, 15A/250V, Black',
    partNumber: 'PW137-1206',
    estimatedCost: '$6.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
  {
    id: 'cablescom-c19c20-25-20a',
    model: 'C20 to C19 PDU Power Cord 12awg 20 amp - 25 Ft',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: 'C20 to C19 PDU Power Cord 12awg 20 amp - 25 Ft',
    partNumber: 'C19C20-25-20A',
    estimatedCost: '$98.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
  {
    id: 'cablescom-lcsc-3m50',
    model: '3MTR-OM2 LC/SC 50/125 1GB DX MM FIBER PATCH CABLE',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: '3MTR-OM2 LC/SC 50/125 1GB DX MM FIBER PATCH CABLE',
    partNumber: 'LCSC-3M50',
    estimatedCost: '$17.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
  {
    id: 'cablescom-lclc-2sm',
    model: 'Fiber Optic Cable Single Mode LC to LC OS2 9/125 Duplex Yellow 2 meter',
    manufacturer: 'Cables.com',
    category: 'cable',
    description: 'Fiber Optic Cable Single Mode LC to LC OS2 9/125 Duplex Yellow 2 meter',
    partNumber: 'LCLC-2SM',
    estimatedCost: '$8.75',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cablesCom"],
  },
];

export default cablesComCatalog;
