import type { CatalogItem } from './types';

const cableleaderCatalog: CatalogItem[] = [
  {
    id: 'cableleader-c13c14-5-r-15a',
    model: 'C13 to C14 Power Cord 15amp Red- 5 Feet',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: 'C13 to C14 Power Cord 15amp Red- 5 Feet',
    partNumber: 'C13C14-5-R-15A',
    estimatedCost: '$10.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
  {
    id: 'cableleader-c13c20-8-15a',
    model: 'C20 Plug Male to C13 Connector Female 8 Feet 15 Amp 14/3 SJT 250v Power Cord- Bl',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: 'C20 Plug Male to C13 Connector Female 8 Feet 15 Amp 14/3 SJT 250v Power Cord- Black',
    partNumber: 'C13C20-8-15A',
    estimatedCost: '$16.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
  {
    id: 'cableleader-c13c20-10-15a',
    model: 'C20 Plug Male to C13 Connector Female 10 Feet 15 Amp 14/3 SJT 250v Power Cord- B',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: 'C20 Plug Male to C13 Connector Female 10 Feet 15 Amp 14/3 SJT 250v Power Cord- Black',
    partNumber: 'C13C20-10-15A',
    estimatedCost: '$12.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
  {
    id: 'cableleader-p-c19c14-14a-03-blu',
    model: 'C19<>C20 - BLUE 3 FEET',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: 'C19<>C20 - BLUE 3 FEET',
    partNumber: 'P-C19C14-14A-03-BLU',
    estimatedCost: '$15.44',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
  {
    id: 'cableleader-p005-006-ard',
    model: 'C13<>C20 - RED 6 FEET',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: 'C13<>C20 - RED 6 FEET',
    partNumber: 'P005-006-ARD',
    estimatedCost: '$17.13',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
  {
    id: 'cableleader-p018-006-abl',
    model: 'C13<>C20 - BLUE 6 FEET',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: 'C13<>C20 - BLUE 6 FEET',
    partNumber: 'P018-006-ABL',
    estimatedCost: '$24.78',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
  {
    id: 'cableleader-pw127-1206',
    model: '6ft IEC-60320 C14 to C15 PDU Server Power Cord 14AWG 15A/250V SJT, Black',
    manufacturer: 'Cableleader',
    category: 'cable',
    description: '6ft IEC-60320 C14 to C15 PDU Server Power Cord 14AWG 15A/250V SJT, Black',
    partNumber: 'PW127-1206',
    estimatedCost: '$5.40',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cableleader"],
  },
];

export default cableleaderCatalog;
