import type { CatalogItem } from './types';

const cConnexCatalog: CatalogItem[] = [
  {
    id: 'cconnex-chds-3u-288f-sm-rb-lcu-b-sh-blue-cwea',
    model: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated, Corrugated Tubing, 3U, 288FO, LC/UPC, Grade A (max IL 0.1dB), Shuttered Dustproof Adapters, Navy Blue Coreweave Co-Branded',
    partNumber: 'CHDS-3U-288F-SM-RB-LCU-B-SH-BLUE-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-3u-288f-sm-rb-lcu-b-sh-wht-cwea',
    model: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated, Corrugated Tubing, 3U, 288FO, LC/UPC, Grade A (max IL 0.1dB), Shuttered Dustproof Adapters, White Coreweave Cobranded',
    partNumber: 'CHDS-3U-288F-SM-RB-LCU-B-SH-WHT-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-4u-12s-rbtr-blue-cwea',
    model: 'CHDS, 4U, Splice Enclosure, 12 Sliding out Trays (hold 144 Fiber each, 1728 Fibe',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CHDS, 4U, Splice Enclosure, 12 Sliding out Trays (hold 144 Fiber each, 1728 Fiber total), Ribbon Splice, Navy Blue Coreweave Co-Branded',
    partNumber: 'CHDS-4U-12S-RBTR-BLUE-CWEA',
    estimatedCost: '$599.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-4u-12s-rbtr-wht-cwea',
    model: 'CHDS, 4U, Splice Enclosure, 12 Sliding out Trays (hold 144 Fiber each, 1728 Fibe',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CHDS, 4U, Splice Enclosure, 12 Sliding out Trays (hold 144 Fiber each, 1728 Fiber total), Ribbon Splice, White Coreweave Co-Branded',
    partNumber: 'CHDS-4U-12S-RBTR-WHT-CWEA',
    estimatedCost: '$599.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-tbox-blk',
    model: 'CODECOM CHDS, Large Break-out/Transition Box Up to 3456FO RB, 1728FO LT, Exit up',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CODECOM CHDS, Large Break-out/Transition Box Up to 3456FO RB, 1728FO LT, Exit up to 12 Corrugated Tubing 7.5mm OD',
    partNumber: 'CHDS-TBOX-BLK',
    estimatedCost: '$50.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-tubg-400m-blk',
    model: 'CODECOM CHDS, Black Corrugated Tubing, 400 Meter of Tubing, Drum',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: 'CODECOM CHDS, Black Corrugated Tubing, 400 Meter of Tubing, Drum',
    partNumber: 'CHDS-TUBG-400M-BLK',
    estimatedCost: '$525.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-rspl-4u-288f-sm-rb-lca-a-sh-blue-cwea',
    model: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Sl',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Slide out Trays and Transition Kit, Single Mode G657.A1 - 250um Pigtails, 4RU, 288FO, LC/APC, Grade A (max IL 0.1dB), Shuttered adaptor, Blue Coreweave Co-Branded, + 19" & 23" bracket',
    partNumber: 'RSPL-4U-288F-SM-RB-LCA-A-SH-BLUE-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Rack | Serialized | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-rspl-4u-288f-sm-rb-lca-a-sh-wht-cwea',
    model: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Sli',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Slide out Trays and Transition Kit, Single Mode G657.A1 - 250um Pigtails, 4RU, 288FO, LC/APC, Grade A (max IL 0.1dB), Shuttered adaptor, White Coreweave Co-branded, + 19" & 23" bracket',
    partNumber: 'RSPL-4U-288F-SM-RB-LCA-A-SH-WHT-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Rack | Serialized | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-phoenix-320-lc-mpo',
    model: '3U Fixed panel, 320 Fiber, 320F LC/UPC- 40 x8F MPO(M) Elite Low Loss, Incl Front',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '3U Fixed panel, 320 Fiber, 320F LC/UPC- 40 x8F MPO(M) Elite Low Loss, Incl Front Manager, White, Coreweave Co-branded + FENIX',
    partNumber: 'PHOENIX-320-LC-MPO',
    estimatedCost: '$7,083.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-phoenix-160-lc-mpo',
    model: '2U Fixed panel, 160 Fiber, 160F LC/UPC- 20 x8F MPO(M) Elite Low Loss, Incl Front',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '2U Fixed panel, 160 Fiber, 160F LC/UPC- 20 x8F MPO(M) Elite Low Loss, Incl Front Manager, White, Coreweave Co-branded + FENIX',
    partNumber: 'PHOENIX-160-LC-MPO',
    estimatedCost: '$3,690.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-20-mt-80f-sm-a1-lszh-18-11-ylw-stag',
    model: '20 Meters, 80 fibers, Singlemode G657.A1, LSZH, 10 x 8f MPO each end, Elite Low',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '20 Meters, 80 fibers, Singlemode G657.A1, LSZH, 10 x 8f MPO each end, Elite Low Loss Female, Yellow, 500mm breakout',
    partNumber: '20-MT-80F-SM-A1-LSZH-18-11-YLW-STAG',
    estimatedCost: '$1,382.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-5-mt-2f-sm-a1-lszh-4-18-a-ylw',
    model: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- CS Dupl',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- CS Duplex, Grade A (Max Il .1dB) , Yellow',
    partNumber: '5-MT-2F-SM-A1-LSZH-4-18-A-YLW',
    estimatedCost: '$120.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-5-mt-2f-sm-a1-lszh-4-4-a-ylw',
    model: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC, Grade A (Max Il .1dB) , Yellow',
    partNumber: '5-MT-2F-SM-A1-LSZH-4-4-A-YLW',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-3-mt-2f-sm-a1-lszh-4-4-a-ylw',
    model: '3 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '3 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC, Grade A (Max Il .1dB) , Yellow',
    partNumber: '3-MT-2F-SM-A1-LSZH-4-4-A-YLW',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-1-5mt-8f-sm-a1-lszh-11-11-b-ylw',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 1M',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 1M',
    partNumber: '1.5MT-8F-SM-A1-LSZH-11-11-B-YLW',
    estimatedCost: '$32.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-cw-ph-288-w-1',
    model: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Sl',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Slide out Trays and Transition Kit, Single Mode G657.A1 - 250um Pigtails, 4RU, 288FO, LC/APC, Grade A (max IL 0.1dB), Shuttered adaptor, White Coreweave Co-Branded, + 19" & 23" bracket',
    partNumber: 'RSPL-4U-288F-SM-RB-LCA-A-SH-WHT-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Rack | Serialized | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-cw-ph-288-b-1',
    model: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Sli',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Slide out Trays and Transition Kit, Single Mode G657.A1 - 250um Pigtails, 4RU, 288FO, LC/APC, Grade A (max IL 0.1dB), Shuttered adaptor, Blue Coreweave Co-branded, + 19" & 23" bracket',
    partNumber: 'RSPL-4U-288F-SM-RB-LCA-A-SH-BLUE-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Rack | Serialized | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-qsfp-1u-96f-sm-lcu-sh-mpo-mbl-cwea',
    model: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to 12xMPO(Elit',
    manufacturer: 'C-Connex',
    category: 'transceiver',
    description: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to 12xMPO(Elite) Male 8FO (Flat with Front Manager) Shuttered LC, Midnight Blue - Coreweave Co-Branded',
    partNumber: 'QSFP-1U-96F-SM-LCU-SH-MPO-MBL-CWEA',
    estimatedCost: '$1,558.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-qsfp-1u-96f-sm-lcu-sh-mpo-wht-cwea',
    model: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to 12xMPO(Elit',
    manufacturer: 'C-Connex',
    category: 'transceiver',
    description: '1U Transition Panel QSFP 40G to SFP 10G SM G657A1 96FO LC Premium to 12xMPO(Elite) Male 8FO (Flat with Front Manager) Shuttered LC, White - Coreweave Co-Branded',
    partNumber: 'QSFP-1U-96F-SM-LCU-SH-MPO-MBL-CWEA',
    estimatedCost: '$1,558.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-20-mt-80f-sm-a1-lszh-18-11-ylw',
    model: '20 Meters, 80 fibers, Singlemode G657.A1, LSZH, 10 x 8f MPO each end, Elite Low',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '20 Meters, 80 fibers, Singlemode G657.A1, LSZH, 10 x 8f MPO each end, Elite Low Loss Female, Yellow, 500mm breakout',
    partNumber: '20-MT-80F-SM-A1-LSZH-18-11-YLW-STAG',
    estimatedCost: '$1,382.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-5-mt-2f-sm-a1-lszh-4-18-b-ylw',
    model: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- CS Dupl',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- CS Duplex, Grade A (Max Il .1dB) , Yellow',
    partNumber: '5-MT-2F-SM-A1-LSZH-4-18-A-YLW',
    estimatedCost: '$120.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-5-mt-2f-sm-a1-lszh-4-4-b-ylw',
    model: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '5 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC, Grade A (Max Il .1dB) , Yellow',
    partNumber: '5-MT-2F-SM-A1-LSZH-4-18-A-YLW',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-3-mt-2f-sm-a1-lszh-4-4-b-ylw',
    model: '3 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '3 Meters, 2 Fiber, Singlemode G657.A1, LSZH, LC/UPC Polarity Reversable- LC/UPC, Grade A (Max Il .1dB) , Yellow',
    partNumber: '3-MT-2F-SM-A1-LSZH-4-4-A-YLW',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-rspl-4u-288f-sm-rb-lcu-b-sh-blk',
    model: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Sli',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'Rear Splice Panel, 3.5Meters Pigtail Ribbon 2x144FO Corrugated Tubes, 3 Rear Slide out Trays and Transition Kit, Single Mode G657.A1 - 250um Pigtails, 4RU, 288FO, LC/UPC, Grade B (max IL 0.15dB), Shuttered adaptor, Black, + 19" &amp; 23" bracket',
    partNumber: 'RSPL-4U-288F-SM-RB-LCU-B-SH-BLK',
    estimatedCost: '$3,550.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-3u-288f-sm-rb-lcu-a-sh-blue-cwea',
    model: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated,',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated, Corrugated Tubing, 3U, 288FO, LC/UPC, Grade A (max IL 0.1dB), Shuttered Dustproof Adapters, Navy Blue Coreweave Co-Branded',
    partNumber: 'CHDS-3U-288F-SM-RB-LCU-A-SH-BLUE-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-3u-288f-sm-rb-lcu-a-sh-wht-cwea',
    model: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated,',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated, Corrugated Tubing, 3U, 288FO, LC/UPC, Grade A (max IL 0.1dB), Shuttered Dustproof Adapters, White Coreweave Cobranded',
    partNumber: 'CHDS-3U-288F-SM-RB-LCU-A-SH-WHT-CWEA',
    estimatedCost: '$3,450.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-3u-288f-sm-rb-lcu-a-sh-blue-cwea-200',
    model: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated,',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated, Corrugated Tubing, 3U, 288FO, LC/UPC, Shuttered Dustproof Adapters, Navy Blue Coreweave Co-Branded, 200 um pigtails',
    partNumber: 'CHDS-3U-288F-SM-RB-LCU-A-SH-BLUE-CWEA-200',
    estimatedCost: '$3,450.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-chds-3u-288f-sm-rb-lcu-a-sh-wht-cwea-200',
    model: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated,',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: 'CHDS, 5 Meters Pigtail Ribbon 2x144FO, Single Mode G657.A1, LSZH, Preterminated, Corrugated Tubing, 3U, 288FO, LC/UPC, Shuttered Dustproof Adapters, White Coreweave Cobranded, 200 um pigtails',
    partNumber: 'CHDS-3U-288F-SM-RB-LCU-A-SH-WHT-CWEA-200',
    estimatedCost: '$3,450.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-spp9-ldgldg-4xt',
    model: '288 Fiber LC Adapter Single-mode 4U Rack Mount Patch Panel',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: '288 Fiber LC Adapter Single-mode 4U Rack Mount Patch Panel',
    partNumber: 'SPP9-LDGLDG-4XT',
    estimatedCost: '$3,550.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-f-1u-96f-sm-mpo-mpo-sh-m-wht-cwea',
    model: 'F Series, 1 RU, 400G to 200G Panel, 96 Fibers, Singlemode G657.A1, 12x8F MPO APC',
    manufacturer: 'C-Connex',
    category: 'other',
    description: 'F Series, 1 RU, 400G to 200G Panel, 96 Fibers, Singlemode G657.A1, 12x8F MPO APC (Front), 24x4 MPO APC MPO APC (Rear), Shuttered Dust-Proof Adapter, Elite Low Loss Male, Incl Front Manager, White, Coreweave Co-branded',
    partNumber: 'F-1U-96F-SM-MPO-MPO-SH-M-WHT-CWEA',
    estimatedCost: '$2,678.26',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-f-1u-96f-sm-mpo-mpo-sh-m-blu-cwea',
    model: ': F Series, 1 RU, 400G to 200G Panel, 96 Fibers, Singlemode G657.A1, 12x8F MPO A',
    manufacturer: 'C-Connex',
    category: 'other',
    description: ': F Series, 1 RU, 400G to 200G Panel, 96 Fibers, Singlemode G657.A1, 12x8F MPO APC (Front), 24x4 MPO APC MPO APC (Rear), Shuttered Dust-Proof Adapter, Elite Low Loss Male, Incl Front Manager, Blue, Coreweave Co-branded',
    partNumber: 'F-1U-96F-SM-MPO-MPO-SH-M-BLU-CWEA',
    estimatedCost: '$2,678.26',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-1-14-km-3456f-sm-rb-out-1-1-blk',
    model: '1.14 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Untermi',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '1.14 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Unterminated, Black, Ribbon 250 micron',
    partNumber: '1.14-KM-3456F-SM-RB-OUT-1-1-BLK',
    estimatedCost: '$136,889.86',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-1-35-km-3456f-sm-rb-out-1-1-blk',
    model: '1.35 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Untermi',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '1.35 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Unterminated, Black, Ribbon 250 micron',
    partNumber: '1.35-KM-3456F-SM-RB-OUT-1-1-BLK',
    estimatedCost: '$162,106.16',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-1-48-km-3456f-sm-rb-out-1-1-blk',
    model: '1.48 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Untermi',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '1.48 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Unterminated, Black, Ribbon 250 micron',
    partNumber: '1.48-KM-3456F-SM-RB-OUT-1-1-BLK',
    estimatedCost: '$177,716.42',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-2-19-km-3456f-sm-rb-out-1-1-blk',
    model: '2.19 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Untermi',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '2.19 Kilometers, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Unterminated, Black, Ribbon 250 micron',
    partNumber: '2.19-KM-3456F-SM-RB-OUT-1-1-BLK',
    estimatedCost: '$262,972.46',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-1-5-mt-8f-sm-a1-lszh-11-11-ylw-b',
    model: '1.5 Meters, 8 Fibers, Single mode, OS2, G657.A1 Bend Insensitive, LSZH, 3mm OD,',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '1.5 Meters, 8 Fibers, Single mode, OS2, G657.A1 Bend Insensitive, LSZH, 3mm OD, MPO Elite Low Loss Female (APC) / MPO Elite Low Loss Female (APC), Yellow, Polarity B',
    partNumber: '1.5-MT-8F-SM-A1-LSZH-11-11-YLW-B',
    estimatedCost: '$32.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-10-000-ft-3456f-sm-rb-out-1-1-blk',
    model: '10,000 feet drum, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Unterm',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '10,000 feet drum, 3456 Fibers, Singlemode, Outdoor cables, Unterminated / Unterminated, Black, Ribbon 250 micron',
    partNumber: '10,000-FT-3456F-SM-RB-OUT-1-1-BLK',
    estimatedCost: '$366,000.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-f-4u-576f-sm-lc-mpo-sh-pbm-wht-cwea',
    model: '4U MPO-LC Panel SM G657A1 576FO LC Premium to 48xMPO(Elite) Male 12FO (Flat with',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: '4U MPO-LC Panel SM G657A1 576FO LC Premium to 48xMPO(Elite) Male 12FO (Flat with Front Manager) Shuttered LC - Coreweave Co-Branded',
    partNumber: 'F-4U-576F-SM-LC-MPO-SH-PBM-WHT-CWEA',
    estimatedCost: '$7,350.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-5-mt-72f-sm-a1-lszh-11-11-ylw-500-c',
    model: '5 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '5 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite Low loss Female (APC) / MPO Elite Low loss Female (APC), Yellow, Breakout of 500MM, Polarity C',
    partNumber: '5-MT-72F-SM-A1-LSZH-11-11-YLW-500-C',
    estimatedCost: '$519.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-10-mt-72f-sm-a1-lszh-11-11-ylw-500-c',
    model: '10 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '10 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite Low loss Female (APC) / MPO Elite Low loss Female (APC), Yellow, Breakout of 500MM, Polarity C',
    partNumber: '10-MT-72F-SM-A1-LSZH-11-11-YLW-500-C',
    estimatedCost: '$531.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-15-mt-72f-sm-a1-lszh-11-11-ylw-500-c',
    model: '15 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '15 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite Low loss Female (APC) / MPO Elite Low loss Female (APC), Yellow, Breakout of 500MM, Polarity C',
    partNumber: '15-MT-72F-SM-A1-LSZH-11-11-YLW-500-C',
    estimatedCost: '$542.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-20-mt-72f-sm-a1-lszh-11-11-ylw-500-c',
    model: '20 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '20 Meters, 72 Fibers, Singlemode, OS2, G657.A1 Bend Insensitive, LSZH, MPO Elite Low loss Female (APC) / MPO Elite Low loss Female (APC), Yellow, Breakout of 500MM, Polarity C',
    partNumber: '20-MT-72F-SM-A1-LSZH-11-11-YLW-500-C',
    estimatedCost: '$554.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-f-1u-72f-sm-lc-mpo-sh-pbm-wht-cwea',
    model: '1U MPO-LC Panel SM G657A1 72FO LC Premium to 6xMPO(Elite) Male 12FO (Flat with F',
    manufacturer: 'C-Connex',
    category: 'cabinet',
    description: '1U MPO-LC Panel SM G657A1 72FO LC Premium to 6xMPO(Elite) Male 12FO (Flat with Front Manager) Shuttered LC - Coreweave Co-Branded',
    partNumber: 'F-1U-72F-SM-LC-MPO-SH-PBM-WHT',
    estimatedCost: '$997.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
  {
    id: 'cconnex-1-ft-3456f-sm-a1-plen-1-1-blk-rb200',
    model: '1 Feet, 3456 Fibers, OS2, G657.A1 Bend Insensitive, PLENUM, Unterminated / Unter',
    manufacturer: 'C-Connex',
    category: 'cable',
    description: '1 Feet, 3456 Fibers, OS2, G657.A1 Bend Insensitive, PLENUM, Unterminated / Unterminated, Black, Ribbon 200 microns',
    partNumber: '1-FT-3456F-SM-A1-PLEN-1-1-BLK-RB200',
    estimatedCost: '$49.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cConnex"],
  },
];

export default cConnexCatalog;
