import type { CatalogItem } from './types';

const chatsworthProductsCatalog: CatalogItem[] = [
  {
    id: 'chatsworthproducts-12100-712',
    model: 'Chatsworth RUNWY RAD DROP 12IN BLAC',
    manufacturer: 'Chatsworth Products',
    category: 'other',
    description: 'Chatsworth RUNWY RAD DROP 12IN BLAC',
    partNumber: '12100-712',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["chatsworthProducts"],
  },
  {
    id: 'chatsworthproducts-12100-718',
    model: 'Chatsworth RUNWY RAD DROP 18 BLACK',
    manufacturer: 'Chatsworth Products',
    category: 'other',
    description: 'Chatsworth RUNWY RAD DROP 18 BLACK',
    partNumber: '12100-718',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["chatsworthProducts"],
  },
  {
    id: 'chatsworthproducts-14304-712',
    model: 'Chatsworth 12 INCH RADIUS DROP',
    manufacturer: 'Chatsworth Products',
    category: 'other',
    description: 'Chatsworth 12 INCH RADIUS DROP',
    partNumber: '14304-712',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["chatsworthProducts"],
  },
  {
    id: 'chatsworthproducts-14304-718',
    model: 'Chatsworth 18 INCH RADIUS DROP',
    manufacturer: 'Chatsworth Products',
    category: 'other',
    description: 'Chatsworth 18 INCH RADIUS DROP',
    partNumber: '14304-718',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["chatsworthProducts"],
  },
  {
    id: 'chatsworthproducts-14305-700',
    model: 'Chatsworth RADIUS DROP STRINGER LG BK',
    manufacturer: 'Chatsworth Products',
    category: 'other',
    description: 'Chatsworth RADIUS DROP STRINGER LG BK',
    partNumber: '14305-700',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["chatsworthProducts"],
  },
  {
    id: 'chatsworthproducts-14305-701',
    model: 'Chatsworth RADIUS DROP STRINGER SM BK',
    manufacturer: 'Chatsworth Products',
    category: 'other',
    description: 'Chatsworth RADIUS DROP STRINGER SM BK',
    partNumber: '14305-701',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["chatsworthProducts"],
  },
];

export default chatsworthProductsCatalog;
