import type { CatalogItem } from './types';

const cienaCatalog: CatalogItem[] = [
  {
    id: 'ciena-170-0062-900',
    model: 'EIA-RJ45M Standard To Cisco RJ45F Serial Port Adapter,6 In',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'EIA-RJ45M Standard To Cisco RJ45F Serial Port Adapter,6 In',
    partNumber: '170-0062-900',
    estimatedCost: '$10.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-174-0094-900',
    model: '1U Bulk Fiber Management Tray',
    manufacturer: 'Ciena',
    category: 'other',
    description: '1U Bulk Fiber Management Tray',
    partNumber: '174-0094-900',
    estimatedCost: '$280.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-1300-900',
    model: 'Waveserver 19 In. Bracket Kit',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Waveserver 19 In. Bracket Kit',
    partNumber: '186-1300-900',
    estimatedCost: '$120.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-1306-900',
    model: 'Waveserver Datacenter Rack Kit, 19 In Wide X 24-36 In Deep',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Waveserver Datacenter Rack Kit, 19 In Wide X 24-36 In Deep',
    partNumber: '186-1306-900',
    estimatedCost: '$170.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-1307-900',
    model: 'Waveserver Datacenter Rack Kit, 23 In Wide X 24-36 In Deep',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Waveserver Datacenter Rack Kit, 23 In Wide X 24-36 In Deep',
    partNumber: '186-1307-900',
    estimatedCost: '$170.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-1312-900',
    model: 'Waveserver Metric And Imperial Installation Kit',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Waveserver Metric And Imperial Installation Kit',
    partNumber: '186-1312-900',
    estimatedCost: '$39.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-800-rls4-sif',
    model: 'RLS Warm Staging - R4',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS Warm Staging - R4',
    partNumber: '800-RLS4-SIF',
    estimatedCost: '$1,005.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-800-wave-sif',
    model: 'Wavesever 1.X / Ai Sif - Per Shelf',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Wavesever 1.X / Ai Sif - Per Shelf',
    partNumber: '800-WAVE-SIF',
    estimatedCost: '$512.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-prmu-acg',
    model: 'PRM USA GRNFLD 6500 W/Build Addl 1 DGRS Or Up To 4 Serv Cards No L2/DS1/DS3 (Sam',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'PRM USA GRNFLD 6500 W/Build Addl 1 DGRS Or Up To 4 Serv Cards No L2/DS1/DS3 (Same Site)',
    partNumber: '8N0-PRMU-ACG',
    estimatedCost: '$1,064.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-prmu-r04a',
    model: 'Ciena Premium Incremental 6500-R4 Ac 1 Degree',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Ciena Premium Incremental 6500-R4 Ac 1 Degree',
    partNumber: '8N0-PRMU-R04A',
    estimatedCost: '$4,458.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-prmu-wsa',
    model: 'Incremental Waveserver Ac Per Site (Ws 1.X/Ai With 1 Sled)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Incremental Waveserver Ac Per Site (Ws 1.X/Ai With 1 Sled)',
    partNumber: '8N0-PRMU-WSA',
    estimatedCost: '$1,638.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-prmu-wsf',
    model: 'Initial Waveserver Ac (Deployed Only Waveserver Or Redeployment) Per Site (Ws 1.',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Initial Waveserver Ac (Deployed Only Waveserver Or Redeployment) Per Site (Ws 1.X/Ai With 1 Sled)',
    partNumber: '8N0-PRMU-WSF',
    estimatedCost: '$6,013.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-fc2',
    model: 'Fiber Characterization Per Span (Includes 2 Fibers)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Fiber Characterization Per Span (Includes 2 Fibers)',
    partNumber: '8N0-ULFT-FC2',
    estimatedCost: '$2,232.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-fc3',
    model: 'Fiber Characterization Per Additional Fiber',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Fiber Characterization Per Additional Fiber',
    partNumber: '8N0-ULFT-FC3',
    estimatedCost: '$323.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-lc10',
    model: 'Uplift Incremental Fiber Run - Ten (Same Site/No Mob)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Uplift Incremental Fiber Run - Ten (Same Site/No Mob)',
    partNumber: '8N0-ULFT-LC10',
    estimatedCost: '$1,039.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-lc10-uplift',
    model: 'Uplift Incremental Fiber Run - Ten (Same Site/No Mob)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Uplift Incremental Fiber Run - Ten (Same Site/No Mob)',
    partNumber: '8N0-ULFT-LC10 UPLIFT',
    estimatedCost: '$1,039.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-ss2',
    model: 'Uplift For On-Site Survey Incremental Site (Inter-Site Mob)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Uplift For On-Site Survey Incremental Site (Inter-Site Mob)',
    partNumber: '8N0-ULFT-SS2',
    estimatedCost: '$1,365.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-wsld',
    model: 'Waveserver Additional Sled',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Waveserver Additional Sled',
    partNumber: '8N0-ULFT-WSLD',
    estimatedCost: '$724.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8np-ulft-dcn1',
    model: 'Uplift For Internal Dcn Design Per Shelf',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Uplift For Internal Dcn Design Per Shelf',
    partNumber: '8NP-ULFT-DCN1',
    estimatedCost: '$375.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-k86-c049-900',
    model: 'Waveserver 5 Chassis W/Ac Power Modules,Ctrl,Fan Modules - W/Lic For API',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'Waveserver 5 Chassis W/Ac Power Modules,Ctrl,Fan Modules - W/Lic For API',
    partNumber: 'K86-C049-900',
    estimatedCost: '$5,200.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk509nze6',
    model: 'Small Optical Installation/Irm Kit',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Small Optical Installation/Irm Kit',
    partNumber: 'NTK509NZE6',
    estimatedCost: '$79.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk591vq',
    model: 'GE DWDM 1568.36Nm Sfp Module',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'GE DWDM 1568.36Nm Sfp Module',
    partNumber: 'NTK591VQ',
    estimatedCost: '$320.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk803fa',
    model: '6500-R4 8-SLOT SHELF ASSEMBLY',
    manufacturer: 'Ciena',
    category: 'other',
    description: '6500-R4 8-SLOT SHELF ASSEMBLY',
    partNumber: 'NTK803FA',
    estimatedCost: '$1,700.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk805mb',
    model: 'Access Panel Type 2 (6500-R4)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Access Panel Type 2 (6500-R4)',
    partNumber: 'NTK805MB',
    estimatedCost: '$930.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk805ra',
    model: 'PIM 100V-240V Ac (Power Input Module), Murata Part Number D1UCIEN1978-1900-48W',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'PIM 100V-240V Ac (Power Input Module), Murata Part Number D1UCIEN1978-1900-48W',
    partNumber: 'NTK805RA',
    estimatedCost: '$580.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk805raw',
    model: 'PIM 100V-240V Ac (Power Input Module), Murata Part Number D1Ucien1978-1900-48W',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'PIM 100V-240V Ac (Power Input Module), Murata Part Number D1Ucien1978-1900-48W',
    partNumber: 'NTK805RAW',
    estimatedCost: '$580.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk807fa',
    model: 'Shelf Fan Module',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Shelf Fan Module',
    partNumber: 'NTK807FA',
    estimatedCost: '$590.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809fd',
    model: 'Left-Hinged Shelf Front Cover Kit W/Extended Depth (6500-R4)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Left-Hinged Shelf Front Cover Kit W/Extended Depth (6500-R4)',
    partNumber: 'NTK809FD',
    estimatedCost: '$520.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809mq',
    model: 'Shelf Bracket Kit, 19In Rack, 465Mm C-C, Eia Hp, 127-202Mm/254-461Mm 2-Post/4-Po',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Shelf Bracket Kit, 19In Rack, 465Mm C-C, Eia Hp, 127-202Mm/254-461Mm 2-Post/4-Post Depth (6500-R4)',
    partNumber: 'NTK809MQ',
    estimatedCost: '$150.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809mw',
    model: 'Shelf Sliding Brkt Kit, Etsi/19/21/23In (515/465/516/567 Mm), 15.1-23.75 In Dept',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Shelf Sliding Brkt Kit, Etsi/19/21/23In (515/465/516/567 Mm), 15.1-23.75 In Depth (6500-R4/R2)',
    partNumber: 'NTK809MW',
    estimatedCost: '$280.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809sa',
    model: 'I/F Module Carrier (2X Im Slots)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'I/F Module Carrier (2X Im Slots)',
    partNumber: 'NTK809SA',
    estimatedCost: '$150.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809xa',
    model: 'Filler (For 2X Im Slots)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Filler (For 2X Im Slots)',
    partNumber: 'NTK809XA',
    estimatedCost: '$250.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809ya',
    model: 'Filler (For Im Slot In Carrier)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Filler (For Im Slot In Carrier)',
    partNumber: 'NTK809YA',
    estimatedCost: '$200.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk810fa',
    model: 'CTM (Control And Timing Module, Rls)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CTM (Control And Timing Module, Rls)',
    partNumber: 'NTK810FA',
    estimatedCost: '$2,300.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk834aa',
    model: 'Ccmd16 C-Band Module (16-Channel Colorless Mux/Demux, RLS)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'Ccmd16 C-Band Module (16-Channel Colorless Mux/Demux, RLS)',
    partNumber: 'NTK834AA',
    estimatedCost: '$6,455.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk834ae',
    model: 'Ccmd16 L-Band Module (16-Channel Colorless Mux/Demux, Rls)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'Ccmd16 L-Band Module (16-Channel Colorless Mux/Demux, Rls)',
    partNumber: 'NTK834AE',
    estimatedCost: '$8,240.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk835aa',
    model: 'TPS Module (Trunk Protection Switch, RLS)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'TPS Module (Trunk Protection Switch, RLS)',
    partNumber: 'NTK835AA',
    estimatedCost: '$8,142.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk850dc',
    model: 'DLE C&L-Band 2X SFPModule (Dual Line Equalizer, Rls)',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'DLE C&L-Band 2X SFPModule (Dual Line Equalizer, Rls)',
    partNumber: 'NTK850DC',
    estimatedCost: '$23,000.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk852bc',
    model: 'RLA 12X1 C&L-Band 1X SFP Module (Roadm With Line Amplifier, RLS)',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'RLA 12X1 C&L-Band 1X SFP Module (Roadm With Line Amplifier, RLS)',
    partNumber: 'NTK852BC',
    estimatedCost: '$29,950.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk852na',
    model: 'LRU 12X1 Module (L-Band Roadm Upgrade, Rls)',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'LRU 12X1 Module (L-Band Roadm Upgrade, Rls)',
    partNumber: 'NTK852NA',
    estimatedCost: '$21,465.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk955em',
    model: 'AC Power Cord - North America, Straight, Iec 60320 C15 (F) To Iec 60320 C14 (M),',
    manufacturer: 'Ciena',
    category: 'cable',
    description: 'AC Power Cord - North America, Straight, Iec 60320 C15 (F) To Iec 60320 C14 (M), 15A/250V, 1.8M',
    partNumber: 'NTK955EM',
    estimatedCost: '$28.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk955ga',
    model: 'AC Power Cord, SAF-D-Grid To C20, 12Awg, 250V, 2M',
    manufacturer: 'Ciena',
    category: 'cable',
    description: 'AC Power Cord, SAF-D-Grid To C20, 12Awg, 250V, 2M',
    partNumber: 'NTK955GA',
    estimatedCost: '$60.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-nttp06cd',
    model: 'Transceiver,Ge Lx (10K) / Fc100 Sm / Fc200 Sm,1310Nm,3.3V,-40/+85C,Sfp,20Pins,Lc',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'Transceiver,Ge Lx (10K) / Fc100 Sm / Fc200 Sm,1310Nm,3.3V,-40/+85C,Sfp,20Pins,Lc,Enhanced Msa',
    partNumber: 'NTTP06CD',
    estimatedCost: '$242.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntyy99em',
    model: 'Packs In Place Kit, 6500-R4',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Packs In Place Kit, 6500-R4',
    partNumber: 'NTYY99EM',
    estimatedCost: '$330.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntzf99yk',
    model: 'Bracket Kit, RLS R4 Shelf, Etsi/23In/19In (1 Ea Of Ntk809MN, NTK809MP, NTK809MQ)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Bracket Kit, RLS R4 Shelf, Etsi/23In/19In (1 Ea Of Ntk809MN, NTK809MP, NTK809MQ)',
    partNumber: 'NTZF99YK',
    estimatedCost: '$580.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-k86-c147-900',
    model: 'WAVESERVER AI 1XWL5E PREM BASE KIT (186-1611-900 W/LIC FOR 8X100G CAPACITY, REAC',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'WAVESERVER AI 1XWL5E PREM BASE KIT (186-1611-900 W/LIC FOR 8X100G CAPACITY, REACH 250KM, ITS, FPLUG)',
    partNumber: 'K86-C147-900',
    estimatedCost: '$19,500.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-k86-3010-901',
    model: 'WAVESERVER AI CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC FOR API',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'WAVESERVER AI CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC FOR API',
    partNumber: 'K86-3010-901',
    estimatedCost: '$3,200.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk591nc',
    model: 'TRCVR,1.25GB/S,20DB,CWDM,1511NM',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'TRCVR,1.25GB/S,20DB,CWDM,1511NM',
    partNumber: 'NTK591NC',
    estimatedCost: '$69.96',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-160-9600-900',
    model: '400G-FR4, SMF, 2KM QSFP-DD',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: '400G-FR4, SMF, 2KM QSFP-DD',
    partNumber: '160-9600-900',
    estimatedCost: '$550.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-1901-900',
    model: 'WAVESERVER AI 10-CH MUX/DEMUX (CMD10)',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'WAVESERVER AI 10-CH MUX/DEMUX (CMD10)',
    partNumber: '186-1901-900',
    estimatedCost: '$9,700.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s86-lic-aibase020500',
    model: 'WAVESERVER AI RELEASE 2.5.00 BASE SOFTWARE LICENSE (PER CHASSIS)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER AI RELEASE 2.5.00 BASE SOFTWARE LICENSE (PER CHASSIS)',
    partNumber: 'S86-LIC-AIBASE020500',
    estimatedCost: '$715.50',
    specs: 'License | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-ber1',
    model: 'UPLIFT FOR BASE 15-MIN BERT (INCLUDES TEST PLANNING AND INTERNAL TEST SET-UP TO',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT FOR BASE 15-MIN BERT (INCLUDES TEST PLANNING AND INTERNAL TEST SET-UP TO 10 CIRCUITS)',
    partNumber: '8N0-ULFT-BER1',
    estimatedCost: '$2,078.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-fc1',
    model: 'FIBER CHARACTERIZATION MOBILIZATION (PER PROJECT)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'FIBER CHARACTERIZATION MOBILIZATION (PER PROJECT)',
    partNumber: '8N0-ULFT-FC1',
    estimatedCost: '$7,493.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-ss1',
    model: 'UPLIFT FOR ON-SITE SURVEY INCLUDING INITIAL MOB',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT FOR ON-SITE SURVEY INCLUDING INITIAL MOB',
    partNumber: '8N0-ULFT-SS1',
    estimatedCost: '$4,478.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8np-ulft-cp02',
    model: 'CIRCUIT PROVISIONING LAYER 1 (OTN, EXCLUDING PACKET) PER 10 CIRCUITS - UPLIFT',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIRCUIT PROVISIONING LAYER 1 (OTN, EXCLUDING PACKET) PER 10 CIRCUITS - UPLIFT',
    partNumber: '8NP-ULFT-CP02',
    estimatedCost: '$263.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-wsai-4ar',
    model: 'WAVERSERVER AI 4 HOUR MANAGED SPARES 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVERSERVER AI 4 HOUR MANAGED SPARES 1 YEAR',
    partNumber: '80M-WSAI-4AR',
    estimatedCost: '$10,736.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-wsai-4ed',
    model: 'WAVERSERVER AI 4 HOUR ENGINEER DISPATCH 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVERSERVER AI 4 HOUR ENGINEER DISPATCH 1 YEAR',
    partNumber: '80M-WSAI-4ED',
    estimatedCost: '$8,820.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-wsai-ssp-com',
    model: 'WAVESERVER AI COMPREHENSIVE SUPPORT 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER AI COMPREHENSIVE SUPPORT 1 YEAR',
    partNumber: '80M-WSAI-SSP-COM',
    estimatedCost: '$7,487.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-1032-900',
    model: 'WAVESERVER AI SLOT FILLER',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'WAVESERVER AI SLOT FILLER',
    partNumber: '186-1032-900',
    estimatedCost: '$504.30',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk505uh',
    model: 'POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    partNumber: 'NTK505UH',
    estimatedCost: '$420.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk505yae5',
    model: 'INTERFACE FILLER PACK',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'INTERFACE FILLER PACK',
    partNumber: 'NTK505YAE5',
    estimatedCost: '$58.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk803pa',
    model: '6500-R6-300 7-SLOT SHELF ASSEMBLY',
    manufacturer: 'Ciena',
    category: 'server',
    description: '6500-R6-300 7-SLOT SHELF ASSEMBLY',
    partNumber: 'NTK803PA',
    estimatedCost: '$1,805.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk805pa',
    model: 'ACCESS PANEL (R2-300/R6-300)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'ACCESS PANEL (R2-300/R6-300)',
    partNumber: 'NTK805PA',
    estimatedCost: '$720.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk807pa',
    model: 'SHELF FAN MODULE (R6-300)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'SHELF FAN MODULE (R6-300)',
    partNumber: 'NTK807PA',
    estimatedCost: '$630.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809hm',
    model: 'SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300)',
    partNumber: 'NTK809HM',
    estimatedCost: '$370.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk809mu',
    model: 'SHELF SLIDING BRKT KIT, 19/23IN RACK, 465/567MM C-C, EIA HP, 23.5-36.0IN DEPTH (',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'SHELF SLIDING BRKT KIT, 19/23IN RACK, 465/567MM C-C, EIA HP, 23.5-36.0IN DEPTH (6500-R4/R2)',
    partNumber: 'NTK809MU',
    estimatedCost: '$280.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk810pa',
    model: 'CTM (CONTROL AND TIMING MODULE, R2-300/R6-300)',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'CTM (CONTROL AND TIMING MODULE, R2-300/R6-300)',
    partNumber: 'NTK810PA',
    estimatedCost: '$2,300.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntzf99yr',
    model: 'BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK50',
    manufacturer: 'Ciena',
    category: 'server',
    description: 'BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC)',
    partNumber: 'NTZF99YR',
    estimatedCost: '$1,200.00',
    specs: 'Storage Server / Chassis | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk830ac',
    model: 'SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS)',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS)',
    partNumber: 'NTK830AC',
    estimatedCost: '$14,000.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk880ac',
    model: 'SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS-300)',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS-300)',
    partNumber: 'NTK880AC',
    estimatedCost: '$14,000.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk890bc',
    model: 'DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300)',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300)',
    partNumber: 'NTK890BC',
    estimatedCost: '$20,000.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk890dc',
    model: 'DLE C&L-BAND 2X SFP MODULE (DUAL LINE EQUALIZER, RLS-300)',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'DLE C&L-BAND 2X SFP MODULE (DUAL LINE EQUALIZER, RLS-300)',
    partNumber: 'NTK890DC',
    estimatedCost: '$23,000.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s74-lic-ntk800ba',
    model: 'RLS OTDR LICENSE (PER SHELF)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS OTDR LICENSE (PER SHELF)',
    partNumber: 'S74-LIC-NTK800BA',
    estimatedCost: '$159.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s74-lic-ntk800bc',
    model: 'RLS SPAN CALIBRATION LICENSE (PER SHELF)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS SPAN CALIBRATION LICENSE (PER SHELF)',
    partNumber: 'S74-LIC-NTK800BC',
    estimatedCost: '$159.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s74-lic-ntk800bf',
    model: 'RLS PERFORMANCE MONITORING LICENSE (PER SHELF)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS PERFORMANCE MONITORING LICENSE (PER SHELF)',
    partNumber: 'S74-LIC-NTK800BF',
    estimatedCost: '$159.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s74-lic-ntk800bg',
    model: 'RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF)',
    partNumber: 'S74-LIC-NTK800BG',
    estimatedCost: '$159.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s74-lic-ntk800bq',
    model: 'RLS NBI LICENSE (PER SHELF)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS NBI LICENSE (PER SHELF)',
    partNumber: 'S74-LIC-NTK800BQ',
    estimatedCost: '$3,180.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s74-lic-rls040000',
    model: 'RLS REL 4.0 SOFTWARE LICENSE',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS REL 4.0 SOFTWARE LICENSE',
    partNumber: 'S74-LIC-RLS040000',
    estimatedCost: '$477.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntyy99ep',
    model: 'PACKS-IN-PLACE KIT (R6-300)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'PACKS-IN-PLACE KIT (R6-300)',
    partNumber: 'NTYY99EP',
    estimatedCost: '$335.50',
    specs: 'Equipment | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-186-3031-900',
    model: 'WAVESERVER 5 DOUBLE SLOT FILLER',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER 5 DOUBLE SLOT FILLER',
    partNumber: '186-3031-900',
    estimatedCost: '$174.90',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-170-0063-900',
    model: 'DB9F TO EIA-RJ45M STANDARD, 6 FT SERIAL CONSOLE CABLE',
    manufacturer: 'Ciena',
    category: 'cable',
    description: 'DB9F TO EIA-RJ45M STANDARD, 6 FT SERIAL CONSOLE CABLE',
    partNumber: '170-0063-900',
    estimatedCost: '$10.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s86-lic-wosbase030101',
    model: 'WAVESERVER OS RELEASE 3.1.01 BASE SOFTWARE LICENSE (PER CHASSIS)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER OS RELEASE 3.1.01 BASE SOFTWARE LICENSE (PER CHASSIS)',
    partNumber: 'S86-LIC-WOSBASE030101',
    estimatedCost: '$716.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-k86-3501-tc-320005000',
    model: 'WAVESERVER 2XWL6E C PREM KIT (186-3501-900 W/LIC FOR 32X100G CLIENT CAPACITY, RE',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER 2XWL6E C PREM KIT (186-3501-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS)',
    partNumber: 'K86-3501-TC-320005000',
    estimatedCost: '$48,000.00',
    specs: 'IT Infrastructure | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-k86-3511-tc-320005000',
    model: 'WAVESERVER 2XWL6E L PREM (186-3511-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER 2XWL6E L PREM (186-3511-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS)',
    partNumber: 'K86-3511-TC-320005000',
    estimatedCost: '$55,200.00',
    specs: 'IT Infrastructure | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-160-9604-900',
    model: '400GE/4X100GE, SMF, 1310NM, 2KM, MPO QSFP-DD',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: '400GE/4X100GE, SMF, 1310NM, 2KM, MPO QSFP-DD',
    partNumber: '160-9604-900',
    estimatedCost: '$999.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s16-lic-mcpbaet-com',
    model: 'NAVIGATOR BASE WITH ENH TRBL SW ANNUAL SUBSCRIPTION LICENSE, COMPREHENSIVE SUPPO',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NAVIGATOR BASE WITH ENH TRBL SW ANNUAL SUBSCRIPTION LICENSE, COMPREHENSIVE SUPPORT',
    partNumber: 'S16-LIC-MCPBAET-COM',
    estimatedCost: '$1.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-s16-rtu-mcpbaet-com',
    model: 'NAVIGATOR BASE ENH TRBL SW ANNUAL SUBSCRIPTION SCALE VIRTUAL RTU, COMPREHENSIVE',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NAVIGATOR BASE ENH TRBL SW ANNUAL SUBSCRIPTION SCALE VIRTUAL RTU, COMPREHENSIVE SUPPORT 1 Year',
    partNumber: 'S16-RTU-MCPBAET-COM',
    estimatedCost: '$520,200.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-800-rls8-sif',
    model: 'RLS WARM STAGING - R6/R8 300MM',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'RLS WARM STAGING - R6/R8 300MM',
    partNumber: '800-RLS8-SIF',
    estimatedCost: '$1,240.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-acg',
    model: 'CIENA GCNE PREMIER NA - GRNFLD 6500/RLS W/BUILD ADDL 1 DGRS OR UP TO 4 SERV CARD',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - GRNFLD 6500/RLS W/BUILD ADDL 1 DGRS OR UP TO 4 SERV CARDS (SAME SITE)',
    partNumber: '8N0-GPRM-ACG',
    estimatedCost: '$810.34',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-r04a',
    model: 'CIENA GCNE PREMIER NA - INCREMENTAL RLS R4 UP TO 1 DEGREE (SAME SITE)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - INCREMENTAL RLS R4 UP TO 1 DEGREE (SAME SITE)',
    partNumber: '8N0-GPRM-R04A',
    estimatedCost: '$4,354.21',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-r08a',
    model: 'CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE)',
    partNumber: '8N0-GPRM-R08A',
    estimatedCost: '$4,265.40',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-r08f',
    model: 'CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE',
    partNumber: '8N0-GPRM-R08F',
    estimatedCost: '$8,238.50',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-wsa',
    model: 'CIENA GCNE PREMIER NA - INCREMENTAL WAVESERVER AC PER SITE (WITH 1 SLED)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - INCREMENTAL WAVESERVER AC PER SITE (WITH 1 SLED)',
    partNumber: '8N0-GPRM-WSA',
    estimatedCost: '$1,468.01',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-wsf',
    model: 'CIENA GCNE PREMIER NA - INITIAL WAVESERVER AC PER SITE (WITH 1 SLED)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - INITIAL WAVESERVER AC PER SITE (WITH 1 SLED)',
    partNumber: '8N0-GPRM-WSF',
    estimatedCost: '$5,089.73',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-ber2',
    model: 'UPLIFT FOR INCREMENTAL 15-MIN BERT (INTERNAL TEST SET-UP TO 10 CIRCUITS)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT FOR INCREMENTAL 15-MIN BERT (INTERNAL TEST SET-UP TO 10 CIRCUITS)',
    partNumber: '8N0-ULFT-BER2',
    estimatedCost: '$783.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-lc20',
    model: 'UPLIFT INCREMENTAL FIBER RUN - TWENTY (SAME SITE/NO MOB)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT INCREMENTAL FIBER RUN - TWENTY (SAME SITE/NO MOB)',
    partNumber: '8N0-ULFT-LC20',
    estimatedCost: '$1,947.68',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-mp01',
    model: 'UPLIFT INCREMENTAL MPO CABLE RUN - ONE (SAME SITE/NO MOB)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT INCREMENTAL MPO CABLE RUN - ONE (SAME SITE/NO MOB)',
    partNumber: '8N0-ULFT-MP01',
    estimatedCost: '$628.88',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-mp05',
    model: 'UPLIFT INCREMENTAL MPO CABLE RUN - FIVE (SAME SITE/NO MOB)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT INCREMENTAL MPO CABLE RUN - FIVE (SAME SITE/NO MOB)',
    partNumber: '8N0-ULFT-MP05',
    estimatedCost: '$2,636.08',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-ulft-p1ab',
    model: 'UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT',
    partNumber: '8N0-ULFT-P1AB',
    estimatedCost: '$1,834.88',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80p-nms0-mcp-vh',
    model: 'NAVIGATOR NMS INSTALL WITH REMOTE DELIVERY - 3 VM HA VM CLUSTER',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NAVIGATOR NMS INSTALL WITH REMOTE DELIVERY - 3 VM HA VM CLUSTER',
    partNumber: '80P-NMS0-MCP-VH',
    estimatedCost: '$12,225.28',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80p-nms1-mcp',
    model: 'NAVIGATOR 1 DAY ONBOARDING WITH REMOTE DELIVERY',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NAVIGATOR 1 DAY ONBOARDING WITH REMOTE DELIVERY',
    partNumber: '80P-NMS1-MCP',
    estimatedCost: '$2,413.15',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8np-ulft-spd1',
    model: 'SOLUTION PRINCIPLES - DCN < 50 NE',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'SOLUTION PRINCIPLES - DCN < 50 NE',
    partNumber: '8NP-ULFT-SPD1',
    estimatedCost: '$4,187.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-6500r-4ar',
    model: 'GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR',
    partNumber: '80M-6500R-4AR',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-6500r-4ed',
    model: 'GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR',
    partNumber: '80M-6500R-4ED',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-6500r-ssp-com',
    model: 'GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR',
    partNumber: '80M-6500R-SSP-COM',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-wave5-4ar',
    model: 'WAVESERVER 5 4 HOUR MANAGED SPARES 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER 5 4 HOUR MANAGED SPARES 1 YEAR',
    partNumber: '80M-WAVE5-4AR',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-wave5-4ed',
    model: 'WAVESERVER 5 4 HOUR ENGINEER DISPATCH 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER 5 4 HOUR ENGINEER DISPATCH 1 YEAR',
    partNumber: '80M-WAVE5-4ED',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-80m-wave5-ssp-com',
    model: 'WAVESERVER 5 COMPREHENSIVE SUPPORT 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'WAVESERVER 5 COMPREHENSIVE SUPPORT 1 YEAR',
    partNumber: '80M-WAVE5-SSP-COM',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-8n0-gprm-aci',
    model: 'CIENA GCNE PREMIER NA - INSERV 6500/RLS W/BUILD ADDL 1 DGRS OR UP TO 4 SERV CARD',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'CIENA GCNE PREMIER NA - INSERV 6500/RLS W/BUILD ADDL 1 DGRS OR UP TO 4 SERV CARDS (SEPARATE TRIP)',
    partNumber: '8N0-GPRM-ACI',
    estimatedCost: '$5,382.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08819',
    model: 'S16-LIC-MCPBAET-COM - NAVIGATOR BASE WITH ENH TRBL SW ANNUAL SUBSCRIPTION LICENS',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'S16-LIC-MCPBAET-COM - NAVIGATOR BASE WITH ENH TRBL SW ANNUAL SUBSCRIPTION LICENSE, COMPREHENSIVE SUPPORT - x1 S16-RTU-MCPBAET-COM - NAVIGATOR BASE ENH TRBL SW ANNUAL SUBSCRIPTION SCALE VIRTUAL RTU, COMPREHENSIVE SUPPORT 1 Year - x1',
    partNumber: '=A2988',
    estimatedCost: '$520,201.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881a',
    model: 'NTK803FA - 6500-R4 8-SLOT SHELF ASSEMBLY - x8 NTK805MB - ACCESS PANEL TYPE 2 (6',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK803FA - 6500-R4 8-SLOT SHELF ASSEMBLY - x8 NTK805MB - ACCESS PANEL TYPE 2 (6500-R4) - x8 NTK805RA - PIM 100V-240V AC (POWER INPUT MODULE) - x16 NTK807FA SHELF FAN MODULE 16 NTK809MU SHELF SLIDING BRKT KIT, 19/23IN RACK, 465/567MM C-C, EIA HP, 23.5-36.0IN DEPTH (6500-R4/R2) - x8 NTK809MW SHELF SLIDING BRKT KIT, ETSI/19/21/23IN (515/465/516/567 MM), 15.1-23.75 IN DEPTH (6500-R4/R2) - x8 NTK809SA I/F MODULE CARRIER (2X IM SLOTS) - x16 NTK809YA FILLER (FOR IM SLOT IN CARRIER) - x4 NTK810FA CTM (CONTROL AND TIMING MODULE, RLS) - x16 NTTP06CD TRANSCEIVER,GE LX (10K) / FC100 SM / FC200 SM,1310NM,3.3V,-40/+85C,SFP,20PINS,LC,ENHANCED MSA - x8 NTZF99YK BRACKET KIT, RLS R4 SHELF, ETSI/23IN/19IN (1 EA OF NTK809MN, NTK809MP, NTK809MQ) - x8 NTK955EM AC POWER CORD - NORTH AMERICA, STRAIGHT, IEC 60320 C15 (F) TO IEC 60320 C14 (M), 15A/250V, 1.8M - x16 NTK591VQ GE DWDM 1568.36NM SFP MODULE - x8 NTK830AC SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS) x 4 NTK834AA CCMD16 C-BAND MODULE (16-CHANNEL COLORLESS MUX/DEMUX, RLS) - x8 NTK834AE CCMD16 L-BAND MODULE (16-CHANNEL COLORLESS MUX/DEMUX, RLS) - x8 NTK835AA TPS MODULE (TRUNK PROTECTION SWITCH, RLS) - x4 NTK850DC DLE C&L-BAND 2X SFP MODULE (DUAL LINE EQUALIZER, RLS) - x8 NTK852BC RLA 12X1 C&L-BAND 1X SFP MODULE (ROADM WITH LINE AMPLIFIER, RLS) - x4 NTK852NA LRU 12X1 MODULE (L-BAND ROADM UPGRADE, RLS) - x4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) - x8 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) - x8 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) - x8 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) - x8 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) - x8 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE - x8 NTK509NZE6 SMALL OPTICAL INSTALLATION/IRM KIT - x8 NTYY99EM PACKS IN PLACE KIT, 6500-R4 - x8',
    partNumber: '=A2989',
    estimatedCost: '$727,228.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881k',
    model: 'K86-C049-900 - WAVESERVER 5 CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'K86-C049-900 - WAVESERVER 5 CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC FOR API x22 186-1300-900 - WAVESERVER 19 IN. BRACKET KIT x22 186-1306-900 - WAVESERVER DATACENTER RACK KIT, 19 IN WIDE X 24-36 IN DEEP x22 186-1307-900 - WAVESERVER DATACENTER RACK KIT, 23 IN WIDE X 24-36 IN DEEP x22 186-3031-900 - WAVESERVER 5 DOUBLE SLOT FILLER x4 170-0062-900 - EIA-RJ45M STANDARD TO CISCO RJ45F SERIAL PORT ADAPTER,6 IN x22 170-0063-900 - DB9F TO EIA-RJ45M STANDARD, 6 FT SERIAL CONSOLE CABLE x22 NTK955GA - AC POWER CORD, SAF-D-GRID TO C20, 12AWG, 250V, 2M x44 S86-LIC-WOSBASE030101 - WAVESERVER OS RELEASE 3.1.01 BASE SOFTWARE LICENSE (PER CHASSIS) x22 WL6E Premium Kits K86-3501-TC-320005000 - WAVESERVER 2XWL6E C PREM KIT (186-3501-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS) x48 K86-3511-TC-320005000 - WAVESERVER 2XWL6E L PREM (186-3511-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS) x36 160-9600-900 - 400G-FR4, SMF, 2KM QSFP-DD x576 174-0094-900 - 1U BULK FIBER MANAGEMENT TRAY x10 186-1312-900 - WAVESERVER METRIC AND IMPERIAL INSTALLATION KIT x22 NTK509NZE6 - SMALL OPTICAL INSTALLATION/IRM KIT x10',
    partNumber: '=A2990',
    estimatedCost: '$4,756,499.60',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1m',
    model: '800-RLS4-SIF - RLS WARM STAGING - R4 - x8',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS4-SIF - RLS WARM STAGING - R4 - x8',
    partNumber: '=A2991',
    estimatedCost: '$8,040.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880c',
    model: '8N0-GPRM-ACG CIENA GCNE PREMIER NA - GRNFLD 6500/RLS W/BUILD ADDL 1 DGRS',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-ACG CIENA GCNE PREMIER NA - GRNFLD 6500/RLS W/BUILD ADDL 1 DGRS OR UP TO 4 SERV CARDS (SAME SITE) - x26 8N0-GPRM-R04A CIENA GCNE PREMIER NA - INCREMENTAL RLS R4 UP TO 1 DEGREE (SAME SITE) - x8 8N0-GPRM-WSA CIENA GCNE PREMIER NA - INCREMENTAL WAVESERVER AC PER SITE (WITH 1 SLED) - x21 8N0-GPRM-WSF CIENA GCNE PREMIER NA - INITIAL WAVESERVER AC PER SITE (WITH 1 SLED) - x1 8N0-ULFT-FC1 FIBER CHARACTERIZATION MOBILIZATION (PER PROJECT) - x1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER - x6 8N0-ULFT-LC50 UPLIFT INCREMENTAL FIBER RUN - FIFTY (SAME SITE/NO MOB) - x12 8N0-ULFT-SS1 UPLIFT FOR ON-SITE SURVEY INCLUDING INITIAL MOB - x1 8N0-ULFT-WSLD WAVESERVER ADDITIONAL SLED - x62',
    partNumber: '=A2992',
    estimatedCost: '$206,321.46',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1y',
    model: '800-WAVE-SIF - WAVESEVER 1.X / AI SIF - PER SHELF - x22',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-WAVE-SIF - WAVESEVER 1.X / AI SIF - PER SHELF - x22',
    partNumber: '=A2993',
    estimatedCost: '$11,264.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880p',
    model: '8NP-ULFT-DCN1 - UPLIFT FOR INTERNAL DCN DESIGN PER SHELF - x30',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 - UPLIFT FOR INTERNAL DCN DESIGN PER SHELF - x30',
    partNumber: '=A2994',
    estimatedCost: '$11,250.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880z',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - x1 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - x1 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1 80M-WAVE5-4AR - WAVESERVER 5 4 HOUR MANAGED SPARES 1 YEAR - x1 80M-WAVE5-4ED - WAVESERVER 5 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-WAVE5-SSP-COM - WAVESERVER 5 COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A2995',
    estimatedCost: '$519,523.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880o',
    model: '80P-NMS0-MCP-VH NAVIGATOR NMS INSTALL WITH REMOTE DELIVERY - 3 VM HA VM C',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80P-NMS0-MCP-VH NAVIGATOR NMS INSTALL WITH REMOTE DELIVERY - 3 VM HA VM CLUSTER 1 80P-NMS1-MCP NAVIGATOR 1 DAY ONBOARDING WITH REMOTE DELIVERY 1 8NP-ULFT-CP02 CIRCUIT PROVISIONING LAYER 1 (OTN, EXCLUDING PACKET) PER 10 CIRCUITS - UPLIFT 58 8NP-ULFT-SPD1 SOLUTION PRINCIPLES - DCN < 50 NE 1',
    partNumber: '=A2996',
    estimatedCost: '$34,079.43',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880b',
    model: '8N0-ULFT-BER1 UPLIFT FOR BASE 15-MIN BERT (INCLUDES TEST PLANNING AND INT',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-ULFT-BER1 UPLIFT FOR BASE 15-MIN BERT (INCLUDES TEST PLANNING AND INTERNAL TEST SET-UP TO 10 CIRCUITS) 1 8N0-ULFT-BER2 UPLIFT FOR INCREMENTAL 15-MIN BERT (INTERNAL TEST SET-UP TO 10 CIRCUITS) 57',
    partNumber: '=A2997',
    estimatedCost: '$46,709.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881j',
    model: 'NTK803FA 6500-R4 8-SLOT SHELF ASSEMBLY 8 NTK805MB A',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK803FA 6500-R4 8-SLOT SHELF ASSEMBLY 8 NTK805MB ACCESS PANEL TYPE 2 (6500-R4) 8 NTK805RA PIM 100V-240V AC (POWER INPUT MODULE) 16 NTK807FA SHELF FAN MODULE 16 NTK809MU SHELF SLIDING BRKT KIT, 19/23IN RACK, 465/567MM C-C, EIA HP, 23.5-36.0IN DEPTH (6500-R4/R2) 8 NTK809MW SHELF SLIDING BRKT KIT, ETSI/19/21/23IN (515/465/516/567 MM), 15.1-23.75 IN DEPTH (6500-R4/R2) 8 NTK809SA I/F MODULE CARRIER (2X IM SLOTS) 12 NTK809XA FILLER (FOR 2X IM SLOTS) 4 NTK809YA FILLER (FOR IM SLOT IN CARRIER) 4 NTK810FA CTM (CONTROL AND TIMING MODULE, RLS) 16 NTTP06CD TRANSCEIVER,GE LX (10K) / FC100 SM / FC200 SM,1310NM,3.3V,-40/+85C,SFP,20PINS,LC,ENHANCED MSA 8 NTZF99YK BRACKET KIT, RLS R4 SHELF, ETSI/23IN/19IN (1 EA OF NTK809MN, NTK809MP, NTK809MQ) 8 NTK955EM AC POWER CORD - NORTH AMERICA, STRAIGHT, IEC 60320 C15 (F) TO IEC 60320 C14 (M), 15A/250V, 1.8M 16 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK834AA CCMD16 C-BAND MODULE (16-CHANNEL COLORLESS MUX/DEMUX, RLS) 8 NTK834AE CCMD16 L-BAND MODULE (16-CHANNEL COLORLESS MUX/DEMUX, RLS) 8 NTK835AA TPS MODULE (TRUNK PROTECTION SWITCH, RLS) 4 NTK850DC DLE C&L-BAND 2X SFP MODULE (DUAL LINE EQUALIZER, RLS) 8 NTK852BC RLA 12X1 C&L-BAND 1X SFP MODULE (ROADM WITH LINE AMPLIFIER, RLS) 4 NTK852NA LRU 12X1 MODULE (L-BAND ROADM UPGRADE, RLS) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 8 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 8 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 8 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 8 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 8 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 8 NTK509NZE6 SMALL OPTICAL INSTALLATION/IRM KIT 8 NTYY99EM PACKS IN PLACE KIT, 6500-R4 8',
    partNumber: '=A2998',
    estimatedCost: '$671,628.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881l',
    model: 'K86-C049-900 - WAVESERVER 5 CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'K86-C049-900 - WAVESERVER 5 CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC FOR API - x22 186-1300-900 - WAVESERVER 19 IN. BRACKET KIT - x22 186-1306-900 - WAVESERVER DATACENTER RACK KIT, 19 IN WIDE X 24-36 IN DEEP - x22 186-1307-900 - WAVESERVER DATACENTER RACK KIT, 23 IN WIDE X 24-36 IN DEEP - x22 186-3031-900 - WAVESERVER 5 DOUBLE SLOT FILLER - x4 170-0062-900 - EIA-RJ45M STANDARD TO CISCO RJ45F SERIAL PORT ADAPTER,6 IN - x22 170-0063-900 - DB9F TO EIA-RJ45M STANDARD, 6 FT SERIAL CONSOLE CABLE - x22 NTK955GA - AC POWER CORD, SAF-D-GRID TO C20, 12AWG, 250V, 2M - x44 S86-LIC-WOSBASE030101 - WAVESERVER OS RELEASE 3.1.01 BASE SOFTWARE LICENSE (PER CHASSIS) - x22 K86-3501-TC-320005000 - WAVESERVER 2XWL6E C PREM KIT (186-3501-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS) - x48 K86-3511-TC-320005000 - WAVESERVER 2XWL6E L PREM (186-3511-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS) - x36 160-9600-900 - 400G-FR4, SMF, 2KM QSFP-DD - x576 174-0094-900 - 1U BULK FIBER MANAGEMENT TRAY - x10 186-1312-900 - WAVESERVER METRIC AND IMPERIAL INSTALLATION KIT - x22 NTK509NZE6 - SMALL OPTICAL INSTALLATION/IRM KIT - x10',
    partNumber: '=A2999',
    estimatedCost: '$4,756,499.60',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1w',
    model: '800-RLS4-SIF - RLS WARM STAGING - R4 - x8 - ATL03',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS4-SIF - RLS WARM STAGING - R4 - x8 - ATL03',
    partNumber: '=A3000',
    estimatedCost: '$8,040.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1n',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3001',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1u',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3002',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1t',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3003',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1o',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3004',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1v',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3005',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1p',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3006',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1s',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3007',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1r',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3008',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1q',
    model: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-RLS8-SIF - RLS WARM STAGING - R6/R8 300MM - x4',
    partNumber: '=A3009',
    estimatedCost: '$4,960.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1z',
    model: '800-WAVE-SIF - WAVESEVER 1.X / AI SIF - PER SHELF - x22',
    manufacturer: 'Ciena',
    category: 'other',
    description: '800-WAVE-SIF - WAVESEVER 1.X / AI SIF - PER SHELF - x22',
    partNumber: '=A3010',
    estimatedCost: '$11,264.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880y',
    model: '8NP-ULFT-DCN1 - UPLIFT FOR INTERNAL DCN DESIGN PER SHELF - x30',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 - UPLIFT FOR INTERNAL DCN DESIGN PER SHELF - x30',
    partNumber: '=A3011',
    estimatedCost: '$11,250.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08818',
    model: '80M-6500R-4AR GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR 1 80M-6500R-4ED GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR 1 80M-6500R-SSP-COM GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR 1 80M-WAVE5-4AR WAVESERVER 5 4 HOUR MANAGED SPARES 1 YEAR 1 80M-WAVE5-4ED WAVESERVER 5 4 HOUR ENGINEER DISPATCH 1 YEAR 1 80M-WAVE5-SSP-COM WAVESERVER 5 COMPREHENSIVE SUPPORT 1 YEAR 1',
    partNumber: '=A3012',
    estimatedCost: '$514,825.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880l',
    model: '8N0-GPRM-ACG CIENA GCNE PREMIER NA - GRNFLD 6500/RLS W/BUILD ADDL 1 DGRS',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-ACG CIENA GCNE PREMIER NA - GRNFLD 6500/RLS W/BUILD ADDL 1 DGRS OR UP TO 4 SERV CARDS (SAME SITE) 25 8N0-GPRM-R04A CIENA GCNE PREMIER NA - INCREMENTAL RLS R4 UP TO 1 DEGREE (SAME SITE) 8 8N0-GPRM-WSA CIENA GCNE PREMIER NA - INCREMENTAL WAVESERVER AC PER SITE (WITH 1 SLED) 21 8N0-GPRM-WSF CIENA GCNE PREMIER NA - INITIAL WAVESERVER AC PER SITE (WITH 1 SLED) 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC50 UPLIFT INCREMENTAL FIBER RUN - FIFTY (SAME SITE/NO MOB) 12 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1 8N0-ULFT-WSLD WAVESERVER ADDITIONAL SLED 62',
    partNumber: '=A3013',
    estimatedCost: '$197,137.12',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880d',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3014',
    estimatedCost: '$27,608.70',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880k',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3015',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880j',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3016',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880e',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3017',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx1x',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3018',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880f',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3019',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880i',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3020',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880h',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3021',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880g',
    model: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGRE',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8N0-GPRM-R08A CIENA GCNE PREMIER NA - INCREMENTAL RLS R6/R8-300MM 1 DEGREE (SAME SITE) 3 8N0-GPRM-R08F CIENA GCNE PREMIER NA - FIRST RLS R6/R8-300MM 1 DEGREE 1 8N0-ULFT-FC2 FIBER CHARACTERIZATION PER SPAN (INCLUDES 2 FIBERS) 1 8N0-ULFT-FC3 FIBER CHARACTERIZATION PER ADDITIONAL FIBER 6 8N0-ULFT-LC10 UPLIFT INCREMENTAL FIBER RUN - TEN (SAME SITE/NO MOB) 1 8N0-ULFT-P1AB UPLIFT FOR POWER RUN 1A + 1B (SAME SITE/NO MOB) INCLUDES IRM AND EFFORT 4 8N0-ULFT-SS2 UPLIFT FOR ON-SITE SURVEY INCREMENTAL SITE (INTER-SITE MOB) 1',
    partNumber: '=A3022',
    estimatedCost: '$34,948.22',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880q',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3023',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880x',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3024',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880w',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3025',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880r',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3026',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx20',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3027',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880s',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3028',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880v',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3029',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880u',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3030',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0880t',
    model: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    manufacturer: 'Ciena',
    category: 'other',
    description: '8NP-ULFT-DCN1 UPLIFT FOR INTERNAL DCN DESIGN PER SHELF 4',
    partNumber: '=A3031',
    estimatedCost: '$1,500.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08810',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3032',
    estimatedCost: '$29,425.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08817',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3033',
    estimatedCost: '$24,809.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08816',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3034',
    estimatedCost: '$21,195.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08811',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3035',
    estimatedCost: '$20,199.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx21',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3036',
    estimatedCost: '$20,199.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08812',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3037',
    estimatedCost: '$24,809.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08815',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3038',
    estimatedCost: '$24,809.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08814',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3039',
    estimatedCost: '$20,199.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i08813',
    model: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED',
    manufacturer: 'Ciena',
    category: 'other',
    description: '80M-6500R-4AR - GLOBAL 6500 RLS 4 HOUR MANAGED SPARES 1 YEAR - 1x 80M-6500R-4ED - GLOBAL 6500 RLS 4 HOUR ENGINEER DISPATCH 1 YEAR - x1 80M-6500R-SSP-COM - GLOBAL 6500 RLS COMPREHENSIVE SUPPORT 1 YEAR - x1',
    partNumber: '=A3040',
    estimatedCost: '$21,195.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881b',
    model: 'NTK505UN POWER INPUT CARD 100V-240V AC - x8 NTK803PA 6500-R6-300 7',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UN POWER INPUT CARD 100V-240V AC - x8 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY - x4 NTK805PA ACCESS PANEL (R2-300/R6-300) - x4 NTK807PA SHELF FAN MODULE (R6-300) - x4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) - x4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) - x4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC)- x4 NTK955EM AC POWER CORD - NORTH AMERICA, STRAIGHT, IEC 60320 C15 (F) TO IEC 60320 C14 (M), 15A/250V, 1.8M - x8 NTK591VQ GE DWDM 1568.36NM SFP MODULE - x8 NTK880AC SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS-300) - x8 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) - x4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) - x4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) - x4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) - x4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) - x4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) - x4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE - x4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) - x4',
    partNumber: '=A3041',
    estimatedCost: '$244,849.36',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881i',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) - x8 NTK505YA',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) - x8 NTK505YAE5 INTERFACE FILLER PACK - x8 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY - x4 NTK805PA ACCESS PANEL (R2-300/R6-300) - x4 NTK807PA SHELF FAN MODULE (R6-300) - x4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) - x4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) - x4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) -x4 NTK591VQ GE DWDM 1568.36NM SFP MODULE - x8 NTK880AC SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS-300) - x4 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) - x4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) - x4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) - x4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) - x4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) - x4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) - x4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE - x4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) - x4',
    partNumber: '=A3042',
    estimatedCost: '$188,998.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881h',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK505YAE5 INTERFACE FILLER PACK 16 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY 4 NTK805PA ACCESS PANEL (R2-300/R6-300) 4 NTK807PA SHELF FAN MODULE (R6-300) 4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) 4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) 4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) 4 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK890DC DLE C&L-BAND 2X SFP MODULE (DUAL LINE EQUALIZER, RLS-300) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) 4',
    partNumber: '=A3043',
    estimatedCost: '$145,462.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881c',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK505YAE5 INTERFACE FILLER PACK 16 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY 4 NTK805PA ACCESS PANEL (R2-300/R6-300) 4 NTK807PA SHELF FAN MODULE (R6-300) 4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) 4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) 4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) 4 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) 4',
    partNumber: '=A3044',
    estimatedCost: '$133,462.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3ixpx22',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK505YAE5 INTERFACE FILLER PACK 16 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY 4 NTK805PA ACCESS PANEL (R2-300/R6-300) 4 NTK807PA SHELF FAN MODULE (R6-300) 4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) 4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) 4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) 4 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) 4',
    partNumber: '=A3045',
    estimatedCost: '$133,462.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881d',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK505YAE5 INTERFACE FILLER PACK 8 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY 4 NTK805PA ACCESS PANEL (R2-300/R6-300) 4 NTK807PA SHELF FAN MODULE (R6-300) 4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) 4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) 4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) 4 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK880AC SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS-300) 4 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) 4',
    partNumber: '=A3046',
    estimatedCost: '$188,998.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881g',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK5',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK505YAE5 INTERFACE FILLER PACK 8 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY 4 NTK805PA ACCESS PANEL (R2-300/R6-300) 4 NTK807PA SHELF FAN MODULE (R6-300) 4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) 4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) 4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) 4 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK880AC SRA C&L-BAND MODULE (SINGLE LINE RAMAN AMPLIFIER, RLS-300) 4 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) 4',
    partNumber: '=A3047',
    estimatedCost: '$188,998.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881f',
    model: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A)',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) 8 NTK505YAE5 INTERFACE FILLER PACK 16 NTK803PA 6500-R6-300 7-SLOT SHELF ASSEMBLY 4 NTK805PA ACCESS PANEL (R2-300/R6-300) 4 NTK807PA SHELF FAN MODULE (R6-300) 4 NTK809HM SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) 4 NTK810PA CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) 4 NTZF99YR BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) 4 NTK591VQ GE DWDM 1568.36NM SFP MODULE 8 NTK890BC DLA C&L-BAND 2X SFP MODULE (DUAL LINE AMPLIFIER, RLS-300) 4 S74-LIC-NTK800BA RLS OTDR LICENSE (PER SHELF) 4 S74-LIC-NTK800BC RLS SPAN CALIBRATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BF RLS PERFORMANCE MONITORING LICENSE (PER SHELF) 4 S74-LIC-NTK800BG RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) 4 S74-LIC-NTK800BQ RLS NBI LICENSE (PER SHELF) 4 S74-LIC-RLS040000 RLS REL 4.0 SOFTWARE LICENSE 4 NTYY99EP PACKS-IN-PLACE KIT (R6-300) 4',
    partNumber: '=A3048',
    estimatedCost: '$133,462.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-a3i0881e',
    model: 'NTK505UH - POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) - x8 NTK505YAE5 -',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'NTK505UH - POWER INPUT CARD TYPE 2 (BREAKERLESS PIM, MAX 30A) - x8 NTK505YAE5 - INTERFACE FILLER PACK x16 NTK803PA - 6500-R6-300 7-SLOT SHELF ASSEMBLY x4 NTK805PA - ACCESS PANEL (R2-300/R6-300) x4 NTK807PA - SHELF FAN MODULE (R6-300) - x4 NTK809HM - SHELF FRONT DOOR W/EXTENDED DEPTH (R6-300) x4 NTK810PA - CTM (CONTROL AND TIMING MODULE, R2-300/R6-300) x4 NTZF99YR - BRACKET AND AIR BAFFLE KIT, R6-300, 19/21/23IN AND ETSI (1 EA OF NTK509QA, NTK509QB, NTK509QC) x4 Modules NTK591VQ - GE DWDM 1568.36NM SFP MODULE - x8 NTK890DC - DLE C&L-BAND 2X SFP MODULE (DUAL LINE EQUALIZER, RLS-300) - x4 Software, Licenses, Certificates, Customer Docs S74-LIC-NTK800BA - RLS OTDR LICENSE (PER SHELF) - x4 S74-LIC-NTK800BC - RLS SPAN CALIBRATION LICENSE (PER SHELF) - x4 S74-LIC-NTK800BF - RLS PERFORMANCE MONITORING LICENSE (PER SHELF) - x4 S74-LIC-NTK800BG - RLS NETWORK ALARM CORRELATION LICENSE (PER SHELF) - x4 S74-LIC-NTK800BQ - RLS NBI LICENSE (PER SHELF) - x4 S74-LIC-RLS040000 - RLS REL 4.0 SOFTWARE LICENSE - x4 Project Related Equipment NTYY99EP - PACKS-IN-PLACE KIT (R6-300) - x4',
    partNumber: '=A3049',
    estimatedCost: '$145,462.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-navigator-01',
    model: 'Coreweave - VA Regional DCI - Oct2025 - NAVIGATOR BASE ENH TRBL SW ANNUAL SUBSCR',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Coreweave - VA Regional DCI - Oct2025 - NAVIGATOR BASE ENH TRBL SW ANNUAL SUBSCRIPTION SCALE VIRTUAL RTU, COMPREHENSIVE SUPPORT 1 Year',
    partNumber: 'NAVIGATOR-01',
    estimatedCost: '$98,940.86',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-rls-01',
    model: 'Coreweave - VA Regional DCI - Oct2025 - RLS - 6500 Reconfigurable Line System',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'Coreweave - VA Regional DCI - Oct2025 - RLS - 6500 Reconfigurable Line System Core Cable (core) Modules Software, Licenses, Certificates, & Customer Docs Project Related Equipment',
    partNumber: 'RLS-01',
    estimatedCost: '$1,312,471.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-waveserver-5-01',
    model: 'Waveserver 5 - Coreweave - VA Regional DCI - Oct2025 - PTO Kits: WAVESERVER 5 CH',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'Waveserver 5 - Coreweave - VA Regional DCI - Oct2025 - PTO Kits: WAVESERVER 5 CHASSIS W/AC POWER MODULES,CTRL,FAN MODULES - W/LIC FOR API - 6x Core: WAVESERVER 19 IN. BRACKET KIT - 6x WAVESERVER DATACENTER RACK KIT, 19 IN WIDE X 24-36 IN DEEP - 6x WAVESERVER DATACENTER RACK KIT, 23 IN WIDE X 24-36 IN DEEP - 6x WAVESERVER 5 DOUBLE SLOT FILLER - 4x Cables (Core): EIA-RJ45M STANDARD TO CISCO RJ45F SERIAL PORT ADAPTER,6 IN - 6x DB9F TO EIA-RJ45M STANDARD, 6 FT SERIAL CONSOLE CABLE - 6x AC POWER CORD, SAF-D-GRID TO C20, 12AWG, 250V, 2M - 12x Software Licenses: WAVESERVER OS RELEASE 3.1.01 BASE SOFTWARE LICENSE (PER CHASSIS) - 6x WLGE Premium Kits: WAVESERVER 2XWL6E C PREM KIT (186-3501-900 W/LIC FOR 32X100G CLIENT CAPACITY, REACH TO 5000KM, ITS) - 20x QSFP-DD: 400G-FR4, SMF, 2KM QSFP-DD - 128x Projected Related Equipment: 1U BULK FIBER MANAGEMENT TRAY - 6x WAVESERVER METRIC AND IMPERIAL INSTALLATION KIT - 6x SMALL OPTICAL INSTALLATION/IRM KIT - 6x',
    partNumber: 'WAVESERVER 5-01',
    estimatedCost: '$2,145,167.20',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-deployment-services-pit-01',
    model: 'DEPLOYMENT SERVICES PIT - VA Regional DCI - Oct2025 - RLS WARM STAGING',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DEPLOYMENT SERVICES PIT - VA Regional DCI - Oct2025 - RLS WARM STAGING',
    partNumber: 'DEPLOYMENT SERVICES PIT-01',
    estimatedCost: '$20,440.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-deployment-services-poc-01',
    model: 'DEPLOYMENT SERVICES POC - Coreweave - VA Regional DCI - Oct2025 -',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DEPLOYMENT SERVICES POC - Coreweave - VA Regional DCI - Oct2025 -',
    partNumber: 'DEPLOYMENT SERVICES POC-01',
    estimatedCost: '$260,451.38',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-design-oper-svc-pit-01',
    model: 'DESIGN & OPER SVC PIT - Coreweave - VA Regional DCI - Oct2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DESIGN & OPER SVC PIT - Coreweave - VA Regional DCI - Oct2025',
    partNumber: 'DESIGN & OPER SVC PIT-01',
    estimatedCost: '$6,144.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-design-oper-svc-poc-01',
    model: 'DESIGN & OPER SVC POC - Coreweave - VA Regional DCI - Oct2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DESIGN & OPER SVC POC - Coreweave - VA Regional DCI - Oct2025',
    partNumber: 'DESIGN & OPER SVC POC-01',
    estimatedCost: '$18,856.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-maintain-services-01',
    model: 'MAINTAIN SERVICES - Coreweave - VA Regional DCI - Oct2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'MAINTAIN SERVICES - Coreweave - VA Regional DCI - Oct2025',
    partNumber: 'MAINTAIN SERVICES-01',
    estimatedCost: '$352,165.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-navigator-02',
    model: 'Coreweave - GA Regaional Protected TPS - Sep2025 - NAVIGATOR BASE WITH ENH TRBL',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'Coreweave - GA Regaional Protected TPS - Sep2025 - NAVIGATOR BASE WITH ENH TRBL SW ANNUAL SUBSCRIPTION LICENSE, COMPREHENSIVE SUPPORT NAVIGATOR BASE ENH TRBL SW ANNUAL SUBSCRIPTION SCALE VIRTUAL RTU, COMPREHENSIVE SUPPORT 1 Year',
    partNumber: 'NAVIGATOR - 02',
    estimatedCost: '$520,201.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-rls-02',
    model: 'Coreweave - GA Regional Protected TPS - Sep2025 - RLS - 6500 Reconfigurable Lin',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'Coreweave - GA Regional Protected TPS - Sep2025 - RLS - 6500 Reconfigurable Line System Core Cable (core) Modules Software, Licenses, Certificates, & Customer Docs Project Related Equipment',
    partNumber: 'RLS-02',
    estimatedCost: '$2,230,381.36',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-waveserver-5-02',
    model: 'Waveserver 5 CoreWeave-GA Sep 2025 TPS bundle: 22 chassis with AC power, control',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'Waveserver 5 CoreWeave-GA Sep 2025 TPS bundle: 22 chassis with AC power, controllers, fans; rack/brackets; console & cables; OS licenses; WL6E kits; 400G optics; fiber-management & install kits.',
    partNumber: 'WAVESERVER 5-02',
    estimatedCost: '$4,756,499.60',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-deployment-services-pit-02',
    model: 'DEPLOYMENT SERVICES PIT - Coreweave - GA Regaional Protected TPS - Sep2025 - RLS',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DEPLOYMENT SERVICES PIT - Coreweave - GA Regaional Protected TPS - Sep2025 - RLS WARM STAGING',
    partNumber: 'DEPLOYMENT SERVICES PIT-02',
    estimatedCost: '',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-deployment-services-poc-02',
    model: 'DEPLOYMENT SERVICES POC - Coreweave - GA Regaional Protected TPS - Sep2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DEPLOYMENT SERVICES POC - Coreweave - GA Regaional Protected TPS - Sep2025',
    partNumber: 'DEPLOYMENT SERVICES POC-02',
    estimatedCost: '',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-design-oper-svc-pit-02',
    model: 'DESIGN & OPER SVC PIT - Coreweave - GA Regaional Protected TPS - Sep2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DESIGN & OPER SVC PIT - Coreweave - GA Regaional Protected TPS - Sep2025',
    partNumber: 'DESIGN & OPER SVC PIT-02',
    estimatedCost: '',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-design-oper-svc-poc-02',
    model: 'DESIGN & OPER SVC POC - Coreweave - GA Regaional Protected TPS - Sep2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'DESIGN & OPER SVC POC - Coreweave - GA Regaional Protected TPS - Sep2025',
    partNumber: 'DESIGN & OPER SVC POC-02',
    estimatedCost: '',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-maintain-services-02',
    model: 'MAINTAIN SERVICES - Coreweave - GA Regaional Protected TPS - Sep2025',
    manufacturer: 'Ciena',
    category: 'other',
    description: 'MAINTAIN SERVICES - Coreweave - GA Regaional Protected TPS - Sep2025',
    partNumber: 'MAINTAIN SERVICES-02',
    estimatedCost: '',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-waveserver-ai',
    model: 'Waveserver AI bundle: chassis w/AC power & API + 8x100G license, slot filler, 19',
    manufacturer: 'Ciena',
    category: 'switch',
    description: 'Waveserver AI bundle: chassis w/AC power & API + 8x100G license, slot filler, 19in rack/bracket kits, PTO kit, NA power cords, QSFP-DD/SFP optics, 10-ch MUX/DEMUX, fiber mgmt & install kits.',
    partNumber: 'WAVESERVER AI',
    estimatedCost: '$35,533.76',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["ciena"],
  },
  {
    id: 'ciena-ntk591nj',
    model: 'TRCVR,1.25GB/S,36DB,CWDM,1511NM',
    manufacturer: 'Ciena',
    category: 'transceiver',
    description: 'TRCVR,1.25GB/S,36DB,CWDM,1511NM',
    partNumber: 'NTK591NJ',
    estimatedCost: '$419.76',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["ciena"],
  },
];

export default cienaCatalog;
