import type { CatalogItem } from './types';

const ciscoCatalog: CatalogItem[] = [
  {
    id: 'cisco-n3k-c3064-fan-b',
    model: 'Cisco Fan Module Port side intake Airflow',
    manufacturer: 'Cisco',
    category: 'server',
    description: 'Cisco Fan Module Port side intake Airflow',
    partNumber: 'N3K-C3064-FAN-B',
    estimatedCost: '$130.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-ds-sfp-fc8g-sw',
    model: '8 Gbps Fibre Channel SFP+ Switching Module',
    manufacturer: 'Cisco',
    category: 'transceiver',
    description: '8 Gbps Fibre Channel SFP+ Switching Module',
    partNumber: 'DS-SFP-FC8G-SW',
    estimatedCost: '$40.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fan-t2-m',
    model: 'Cisco Nexus 9000 Series Exit Fans',
    manufacturer: 'Cisco',
    category: 'server',
    description: 'Cisco Nexus 9000 Series Exit Fans',
    partNumber: 'FAN-T2-M',
    estimatedCost: '$244.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-n3k-c3164q-40ge',
    model: 'Cisco N3K-C3164Q-40GE Nexus 3100 Series 3164Q 64-Port 40G QSFP+ Switch',
    manufacturer: 'Cisco',
    category: 'switch',
    description: 'Cisco N3K-C3164Q-40GE Nexus 3100 Series 3164Q 64-Port 40G QSFP+ Switch',
    partNumber: 'N3K-C3164Q-40GE',
    estimatedCost: '$350.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4245-ngfw-k9',
    model: 'Cisco Secure Firewall 4245 NGFW Appliance, 1U, 2xNetMod Bays',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4245 NGFW Appliance, 1U, 2xNetMod Bays',
    partNumber: 'FPR4245-NGFW-K9',
    estimatedCost: '$73,987.53',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-snt-fpr424nw',
    model: 'SNTC-8X5XNBD Cisco Secure Firewall 4245 NGFW Appliance',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SNTC-8X5XNBD Cisco Secure Firewall 4245 NGFW Appliance',
    partNumber: 'CON-SNT-FPR424NW',
    estimatedCost: '$21,875.44',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4245-p',
    model: 'Cloud Management for FPR 4245',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cloud Management for FPR 4245',
    partNumber: 'FPR4245-P',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-l-fpr4245-p-3y',
    model: 'Cloud Management for FPR 4245 3YR Subscrip. Term: 36 months',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cloud Management for FPR 4245 3YR Subscrip. Term: 36 months',
    partNumber: 'L-FPR4245-P-3Y',
    estimatedCost: '$4,396.96',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4200-pwr-ac',
    model: 'Cisco Secure Firewall 4200 Series AC Power Supply',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4200 Series AC Power Supply',
    partNumber: 'FPR4200-PWR-AC',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-pwr-cab-ac-usa',
    model: 'Power Cord for AC V2 Power Module (USA)',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Power Cord for AC V2 Power Module (USA)',
    partNumber: 'PWR-CAB-AC-USA',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-sf-f4k-td7-4-k9',
    model: 'Cisco Secure Firewall TD 7.4 SW for 4200 series appliances',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall TD 7.4 SW for 4200 series appliances',
    partNumber: 'SF-F4K-TD7.4-K9',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4200-ssd1800',
    model: 'Cisco Secure Firewall 4200 Series 1.8TB SSD',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4200 Series 1.8TB SSD',
    partNumber: 'FPR4200-SSD1800',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4200-sld-rails',
    model: 'Cisco Secure Firewall 4200 Slide Rail Kit',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4200 Slide Rail Kit',
    partNumber: 'FPR4200-SLD-RAILS',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-cons-rj45-db9',
    model: 'Console Cable 6ft with RJ45 and DB9F',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Console Cable 6ft with RJ45 and DB9F',
    partNumber: 'CAB-CONS-RJ45-DB9',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4245-bse',
    model: 'Cisco Secure Firewall 4245 Base License',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4245 Base License',
    partNumber: 'FPR4245-BSE',
    estimatedCost: '$0.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4200-fan',
    model: 'Cisco Secure Firewall 4200 Series Fan',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4200 Series Fan',
    partNumber: 'FPR4200-FAN',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4200-nm-blank',
    model: 'Cisco Secure Firewall 4200 Network Module Blank Slot Cover',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4200 Network Module Blank Slot Cover',
    partNumber: 'FPR4200-NM-BLANK',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4k-exclude-subs',
    model: 'Cisco Firepower 4000 Series - Exclude Subscriptions',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Firepower 4000 Series - Exclude Subscriptions',
    partNumber: 'FPR4K-EXCLUDE-SUBS',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4k-xnm-2x400g',
    model: 'Cisco Secure Firewall 4200 2X400G QSFP+ Netmod',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco Secure Firewall 4200 2X400G QSFP+ Netmod',
    partNumber: 'FPR4K-XNM-2X400G=',
    estimatedCost: '$7,901.71',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-snc-fpr4kxng',
    model: 'SNTC-NCD Cisco Secure Firewall 4200 2X400G QSFP+ Term: 36 months',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SNTC-NCD Cisco Secure Firewall 4200 2X400G QSFP+ Term: 36 months',
    partNumber: 'CON-SNC-FPR4KXNG',
    estimatedCost: '$1,088.64',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-l-ac-apx-lic',
    model: 'Secure Client Premier Term License, Total Unique Users',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Secure Client Premier Term License, Total Unique Users',
    partNumber: 'L-AC-APX-LIC=',
    estimatedCost: '$0.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-l-ac-apx-3y-s2',
    model: 'Cisco AnyConnect Apex License, 3YR, 100-249 Users Term: 36 months',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco AnyConnect Apex License, 3YR, 100-249 Users Term: 36 months',
    partNumber: 'L-AC-APX-3Y-S2',
    estimatedCost: '$5.25',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cdo-sec-sub',
    model: 'Cloud Management for Firewall and Multicloud Defense Sub - Term: 36 months',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cloud Management for Firewall and Multicloud Defense Sub - Term: 36 months',
    partNumber: 'CDO-SEC-SUB',
    estimatedCost: '$0.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-svs-cdo-sup-b',
    model: 'Basic Online Support for Cloud-delivered Firewall Management - Term: 36 months',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Basic Online Support for Cloud-delivered Firewall Management - Term: 36 months',
    partNumber: 'SVS-CDO-SUP-B',
    estimatedCost: '$0.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cdo-base-lic',
    model: 'Cloud Management for Firewall and Multicloud defense Tenant - Term: 36 months -',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cloud Management for Firewall and Multicloud defense Tenant - Term: 36 months - $632.81 Per Instance/year',
    partNumber: 'CDO-BASE-LIC',
    estimatedCost: '$1,898.45',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-glc-te-i',
    model: 'Cisco GLC-TE Compatible 1000Base-T SFP 100m RJ45 CATx EXT TAA Transceiver Module',
    manufacturer: 'Cisco',
    category: 'transceiver',
    description: 'Cisco GLC-TE Compatible 1000Base-T SFP 100m RJ45 CATx EXT TAA Transceiver Module',
    partNumber: 'GLC-TE-I',
    estimatedCost: '$16.90',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-pwr-c49-300ac',
    model: 'Cisco PWR-C49-300AC Catalyst 4900 Series 300W AC Switch Power Supply',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco PWR-C49-300AC Catalyst 4900 Series 300W AC Switch Power Supply',
    partNumber: 'PWR-C49-300AC',
    estimatedCost: '$44.99',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-nxa-pac-500w-pe',
    model: 'Cisco NXA-PAC-500W-PE 500W AC Back-to-Front Air (Port Side Exhaust) Power Supply',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco NXA-PAC-500W-PE 500W AC Back-to-Front Air (Port Side Exhaust) Power Supply',
    partNumber: 'NXA-PAC-500W-PE',
    estimatedCost: '$275.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-nxa-pac-650w-pe',
    model: 'Cisco NXA-PAC-650W-PE 650W AC Back-to-Front Airflow (Port Side Exhaust) PSU',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco NXA-PAC-650W-PE 650W AC Back-to-Front Airflow (Port Side Exhaust) PSU',
    partNumber: 'NXA-PAC-650W-PE',
    estimatedCost: '$429.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-n2200-pac-400w',
    model: 'Cisco N2200-PAC-400W 400W AC N2K N3K Back-to-Front Airflow Switch Power Supply',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco N2200-PAC-400W 400W AC N2K N3K Back-to-Front Airflow Switch Power Supply',
    partNumber: 'N2200 PAC-400W',
    estimatedCost: '$27.99',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-glc-sx-mm',
    model: 'Cisco GLC-SX-MM SFP (mini-GBIC) transceiver module - LC',
    manufacturer: 'Cisco',
    category: 'transceiver',
    description: 'Cisco GLC-SX-MM SFP (mini-GBIC) transceiver module - LC',
    partNumber: 'GLC-SX-MM',
    estimatedCost: '$55.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-sfp-ge-t-lu',
    model: 'Cisco Compatible 1000BASE-T SFP Copper 100m RJ-45 Optical Transceiver Module',
    manufacturer: 'Cisco',
    category: 'transceiver',
    description: 'Cisco Compatible 1000BASE-T SFP Copper 100m RJ-45 Optical Transceiver Module',
    partNumber: 'SFP-GE-T-LU',
    estimatedCost: '$45.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-72-101029-01',
    model: 'Cisco Serial Cable for NIM-16A and NIM-24A',
    manufacturer: 'Cisco',
    category: 'cable',
    description: 'Cisco Serial Cable for NIM-16A and NIM-24A',
    partNumber: '72-101029-01',
    estimatedCost: '$107.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cvr-qsfp-sfp10g',
    model: 'Cisco QSA Module, QSFP TO SFP10G Adapter Module',
    manufacturer: 'Cisco',
    category: 'transceiver',
    description: 'Cisco QSA Module, QSFP TO SFP10G Adapter Module',
    partNumber: 'CVR-QSFP-SFP10G',
    estimatedCost: '$119.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-n3k-c3172tq-10gt',
    model: 'Cisco Nexus 48 Port Switch w/ Dual Power',
    manufacturer: 'Cisco',
    category: 'switch',
    description: 'Cisco Nexus 48 Port Switch w/ Dual Power',
    partNumber: 'N3K-C3172TQ-10GT',
    estimatedCost: '$710.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-ucs-mr-1x322rv-a',
    model: 'CISCO 32GB PC4-19200 Registered 2RX4 DDR4 Memory',
    manufacturer: 'Cisco',
    category: 'server',
    description: 'CISCO 32GB PC4-19200 Registered 2RX4 DDR4 Memory',
    partNumber: 'UCS-MR-1X322RV-A',
    estimatedCost: '$110.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-sf-fmc-vmw-300-k9',
    model: 'CISCO FIREPOWER MANAGEMENT CENTER, (VMWARE) FOR 300 DEVICES',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CISCO FIREPOWER MANAGEMENT CENTER, (VMWARE) FOR 300 DEVICES',
    partNumber: 'SF-FMC-VMW-300-K9',
    estimatedCost: '$14,443.56',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-sssnt-fpr4kxng',
    model: 'SOLN SUPP 8X5XNBD CISCO SECURE FIREWALL 4200 2X400G QSFP+ 3 YEAR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SOLN SUPP 8X5XNBD CISCO SECURE FIREWALL 4200 2X400G QSFP+ 3 YEAR',
    partNumber: 'CON-SSSNT-FPR4KXNG',
    estimatedCost: '$1,215.75',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-ecmus-sffmcvmw',
    model: 'SOLN SUPP SWSS CISCO FIREPOWER MANAGEMENT CENTER 3 YEAR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SOLN SUPP SWSS CISCO FIREPOWER MANAGEMENT CENTER 3 YEAR',
    partNumber: 'CON-ECMUS-SFFMCVMW',
    estimatedCost: '$10,207.31',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-sssnt-fpr424nw',
    model: 'SOLN SUPP 8X5XNBD CISCO SECURE FIREWALL 4245 NGFW APPLIANCE 3 YEAR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SOLN SUPP 8X5XNBD CISCO SECURE FIREWALL 4245 NGFW APPLIANCE 3 YEAR',
    partNumber: 'CON-SSSNT-FPR424NW',
    estimatedCost: '$29,884.85',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-fpr4245-ngfw-k9-bundle',
    model: 'CISCO SECURE FIREWALL 4245 NGFW Bundle - FPR4245-NGFW-K9 - 1x CON-SSSNT-FPR424NW',
    manufacturer: 'Cisco',
    category: 'switch',
    description: 'CISCO SECURE FIREWALL 4245 NGFW Bundle - FPR4245-NGFW-K9 - 1x CON-SSSNT-FPR424NW - 1x FPR4K-EXCLUDE-SUBS - 1x FPR4200-PWR-AC - 1x PWR-CAB-AC-USA - 2x SF-F42H-TD7.4-K9 - Threat Defense software v7.4 for 4200 series appliances - 1x FPR4200-SSD1800 - 2x FPR4200-SLD-RAILS - 1x CAB-CONS-RJ45-DB9 - 1x FPR4245-BSE - 1x FPR4200-PWR-AC - 1x FPR4200-FAN - 4x FPR4200-NM-BLANK - 2x FPR4K-XNM-2X400G= - 2x SF-FMC-VMW-300-K9 - CISCO FIREPOWER MANAGEMENT CENTER, (VMWARE) FOR 300 DEVICES - 1x',
    partNumber: 'FPR4245-NGFW-K9',
    estimatedCost: '$116,289.06',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-lic-cswan-l-a',
    model: 'CISCO SD-WAN ADVANTAGE LIC LARGE',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CISCO SD-WAN ADVANTAGE LIC LARGE',
    partNumber: 'LIC-CSWAN-L-A',
    estimatedCost: '$3,464.46',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-lic-cw-a',
    model: 'CISCO WIRELESS LICENSE - ADVANTAGE',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CISCO WIRELESS LICENSE - ADVANTAGE',
    partNumber: 'LIC-CW-A',
    estimatedCost: '$4,580.25',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c1100tgx-1n24p32a',
    model: 'Cisco 1100 Term Gateway w/ 32 Async,24-Port, 1 NIM (8G)',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco 1100 Term Gateway w/ 32 Async,24-Port, 1 NIM (8G)',
    partNumber: 'C1100TGX-1N24P32A',
    estimatedCost: '$1,888.69',
    specs: 'IT Infrastructure | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-l1ncd-c1100tgx',
    model: 'CX LEVEL 1 8X7NCDCisco 1100 Term Gate',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CX LEVEL 1 8X7NCDCisco 1100 Term Gate',
    partNumber: 'CON-L1NCD-C1100TGX',
    estimatedCost: '$1,059.23',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-sl-1100tg-ipb-k9',
    model: 'IP Base License for Cisco 1100 Series Terminal Gateway',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'IP Base License for Cisco 1100 Series Terminal Gateway',
    partNumber: 'SL-1100TG-IPB-K9',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-nim-24a',
    model: '24 Channel Async serial interface for ISR4000 series router',
    manufacturer: 'Cisco',
    category: 'other',
    description: '24 Channel Async serial interface for ISR4000 series router',
    partNumber: 'NIM-24A',
    estimatedCost: '$724.69',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c1100tg-bra',
    model: 'Async Bracket for Cisco 1100TG',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Async Bracket for Cisco 1100TG',
    partNumber: 'C1100TG-BRA',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-async-8',
    model: 'Async cable',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Async cable',
    partNumber: 'CAB-ASYNC-8',
    estimatedCost: '$30.19',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-pwr-1100tg-ac',
    model: 'AC Power Supply for Cisco 1100 Term Gateway',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'AC Power Supply for Cisco 1100 Term Gateway',
    partNumber: 'PWR-1100TG-AC',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-acs1100tg-rm19',
    model: 'Rack Mount Kit for Cisco 1100TG',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Rack Mount Kit for Cisco 1100TG',
    partNumber: 'ACS1100TG-RM19',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-network-pnp-lic',
    model: 'Network Plug-n-Play Connect for zero- touch device deployment',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Network Plug-n-Play Connect for zero- touch device deployment',
    partNumber: 'NETWORK-PNP-LIC',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c1100tg-16a',
    model: '16-port Async Module for Cisco 1100 Term Gateway',
    manufacturer: 'Cisco',
    category: 'other',
    description: '16-port Async Module for Cisco 1100 Term Gateway',
    partNumber: 'C1100TG-16A',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-nimasync-bra',
    model: 'Cable Bracket for NIM 16A-24A',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cable Bracket for NIM 16A-24A',
    partNumber: 'NIMASYNC-BRA',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-console-usb',
    model: 'Console Cable 6ft with USB Type A and mini-B',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Console Cable 6ft with USB Type A and mini-B',
    partNumber: 'CAB-CONSOLE-USB',
    estimatedCost: '$20.13',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-ac',
    model: 'AC Power Cord (North America), C13, NEMA 5-15P, 2.1m',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'AC Power Cord (North America), C13, NEMA 5-15P, 2.1m',
    partNumber: 'CAB-AC',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-sc1100tguk9-1715',
    model: 'UNIVERSAL',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'UNIVERSAL',
    partNumber: 'SC1100TGUK9-1715',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-aux-rj45',
    model: 'Auxiliary Cable 8ft with RJ45 and DB25M',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Auxiliary Cable 8ft with RJ45 and DB25M',
    partNumber: 'CAB-AUX-RJ45=',
    estimatedCost: '$6.03',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-console-rj45',
    model: 'Console Cable 6ft with RJ45 and DB9F',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Console Cable 6ft with RJ45 and DB9F',
    partNumber: 'CAB-CONSOLE-RJ45=',
    estimatedCost: '$24.16',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c1100tg-1n24p32a',
    model: 'Cisco 1100 Term Gateway w/ 32 Async,24-Port, 1 NIM',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Cisco 1100 Term Gateway w/ 32 Async,24-Port, 1 NIM',
    partNumber: 'C1100TG-1N24P32A',
    estimatedCost: '$1,514.17',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-l1ncd-c1100tgn',
    model: 'CX LEVEL 1 8X7NCDCisco 1100 Term Gate',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CX LEVEL 1 8X7NCDCisco 1100 Term Gate',
    partNumber: 'CON-L1NCD-C1100TGN',
    estimatedCost: '$848.82',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-nim-blank',
    model: 'Blank faceplate for NIM slot on Cisco ISR 4400',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'Blank faceplate for NIM slot on Cisco ISR 4400',
    partNumber: 'NIM-BLANK',
    estimatedCost: '$0.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c9500-48y4c-a',
    model: 'CATALYST 9500 48-PORT X 1/10/25G + 4-PORT 40/100G, ADVANTAGE',
    manufacturer: 'Cisco',
    category: 'switch',
    description: 'CATALYST 9500 48-PORT X 1/10/25G + 4-PORT 40/100G, ADVANTAGE',
    partNumber: 'C9500-48Y4C-A',
    estimatedCost: '$5,599.39',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-snt-c9504ya4',
    model: 'SNTC-8X5XNBD CATALYST 9500 48-PORT 25/100G ONLY, ADVA 5YR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SNTC-8X5XNBD CATALYST 9500 48-PORT 25/100G ONLY, ADVA 5YR',
    partNumber: 'CON-SNT-C9504YA4',
    estimatedCost: '$1,746.40',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c9500-dna-a-5y',
    model: 'DNA ADVANTAGE 5 YEAR LICENSE',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'DNA ADVANTAGE 5 YEAR LICENSE',
    partNumber: 'C9500-DNA-A-5Y',
    estimatedCost: '$3,578.82',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c8375-e-g2',
    model: 'CISCO C8300 SERIES SECURE ROUTER',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CISCO C8300 SERIES SECURE ROUTER',
    partNumber: 'C8375-E-G2',
    estimatedCost: '$4,186.51',
    specs: 'IT Infrastructure | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-l1nbd-c8375eg2',
    model: 'CX LEVEL 1 8X5XNBD CISCO SECURE WAN C83 5YR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CX LEVEL 1 8X5XNBD CISCO SECURE WAN C83 5YR',
    partNumber: 'CON-L1NBD-C8375EG2',
    estimatedCost: '$2,238.40',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-r-os-l-e',
    model: 'CISCO OS ESSENTIALS - LARGE (EMBEDDED, PERPETUAL)',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CISCO OS ESSENTIALS - LARGE (EMBEDDED, PERPETUAL)',
    partNumber: 'R-OS-L-E',
    estimatedCost: '$542.70',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cw9176i-rtg',
    model: 'CISCO WIRELESS 9176I(W7,3 RADIO,3 BAND 4X4,UWB),GLOBAL',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CISCO WIRELESS 9176I(W7,3 RADIO,3 BAND 4X4,UWB),GLOBAL',
    partNumber: 'CW9176I-RTG',
    estimatedCost: '$609.29',
    specs: 'IT Infrastructure | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-sfp-10g-lr-s',
    model: '10GBASE-LR SFP MODULE, ENTERPRISE-CLASS',
    manufacturer: 'Cisco',
    category: 'transceiver',
    description: '10GBASE-LR SFP MODULE, ENTERPRISE-CLASS',
    partNumber: 'SFP-10G-LR-S=',
    estimatedCost: '$152.54',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c9300x-48hx-a',
    model: 'CATALYST 9300 48-PORT MGIG UPOE+, NETWORK ADVANTAGE',
    manufacturer: 'Cisco',
    category: 'switch',
    description: 'CATALYST 9300 48-PORT MGIG UPOE+, NETWORK ADVANTAGE',
    partNumber: 'C9300X-48HX-A',
    estimatedCost: '$3,702.79',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-snt-c9300xy4',
    model: 'SNTC-8X5XNBD CATALYST 9300 48-PORT MGIG UPOE+, NETWORK 5 YR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SNTC-8X5XNBD CATALYST 9300 48-PORT MGIG UPOE+, NETWORK 5 YR',
    partNumber: 'CON-SNT-C9300XY4',
    estimatedCost: '$979.20',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c9300-dna-a-48-5y',
    model: 'C9300 DNA ADVANTAGE, 48-PORT, 5 YEAR TERM LICENSE',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'C9300 DNA ADVANTAGE, 48-PORT, 5 YEAR TERM LICENSE',
    partNumber: 'C9300-DNA-A-48-5Y',
    estimatedCost: '$1,114.28',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-stack-t1-3m',
    model: '3M TYPE 1 STACKING CABLE',
    manufacturer: 'Cisco',
    category: 'other',
    description: '3M TYPE 1 STACKING CABLE',
    partNumber: 'STACK-T1-3M=',
    estimatedCost: '$69.90',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-cab-spwr-150cm',
    model: 'CATALYST STACK POWER CABLE 150 CM SPARE',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'CATALYST STACK POWER CABLE 150 CM SPARE',
    partNumber: 'CAB-SPWR-150CM=',
    estimatedCost: '$41.51',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-pwr-c1-1100wac-p',
    model: '1100W AC 80+ PLATINUM CONFIG 1 POWER SUPPLY SPARE',
    manufacturer: 'Cisco',
    category: 'other',
    description: '1100W AC 80+ PLATINUM CONFIG 1 POWER SUPPLY SPARE',
    partNumber: 'PWR-C1-1100WAC-P=',
    estimatedCost: '$348.58',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-snt-c1100tgx',
    model: 'SNTC-8X5XNBD CISCO 1100 TERM GATEWAY W/ 32 ASYNC,24-P 5 YR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SNTC-8X5XNBD CISCO 1100 TERM GATEWAY W/ 32 ASYNC,24-P 5 YR',
    partNumber: 'CON-SNT-C1100TGX',
    estimatedCost: '$659.03',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c9300x-12y-a',
    model: 'CATALYST 9300X 12X25G FIBER PORTS, MODULAR UPLINK SWITCH',
    manufacturer: 'Cisco',
    category: 'switch',
    description: 'CATALYST 9300X 12X25G FIBER PORTS, MODULAR UPLINK SWITCH',
    partNumber: 'C9300X-12Y-A',
    estimatedCost: '$4,327.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-con-snt-c9300x21',
    model: 'SNTC-8X5XNBD CATALYST 9300X 12X25G FIBER PORTS, MODULE 5YR',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'SNTC-8X5XNBD CATALYST 9300X 12X25G FIBER PORTS, MODULE 5YR',
    partNumber: 'CON-SNT-C9300X21',
    estimatedCost: '$1,226.40',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-c9300-dna-l-a-5y',
    model: 'DNA ADVANTAGE 5 YEAR LICENSE',
    manufacturer: 'Cisco',
    category: 'other',
    description: 'DNA ADVANTAGE 5 YEAR LICENSE',
    partNumber: 'C9300-DNA-L-A-5Y',
    estimatedCost: '$594.40',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
  {
    id: 'cisco-trn-clc-001',
    model: '100 Training credit. Expires in 1 yr. Team Captain required',
    manufacturer: 'Cisco',
    category: 'other',
    description: '100 Training credit. Expires in 1 yr. Team Captain required',
    partNumber: 'TRN-CLC-0',
    estimatedCost: '$2,133.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["cisco"],
  },
];

export default ciscoCatalog;
