import type { CatalogItem } from './types';

const comtopCatalog: CatalogItem[] = [
  {
    id: 'comtop-10x6-28-6a807',
    model: '7ft (2.1m) Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '7ft (2.1m) Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-28-6A807',
    estimatedCost: '$7.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-28-6a110',
    model: '10ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '10ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-28-6A110',
    estimatedCost: '$5.59',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-28-6a825',
    model: '25ft (7.62m) Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '25ft (7.62m) Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-28-6A825',
    estimatedCost: '$13.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-6a102-utp',
    model: '2ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '2ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-6A102-UTP',
    estimatedCost: '$5.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-6a801-utp',
    model: '1ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '1ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-6A801-UTP',
    estimatedCost: '$4.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-6a805-utp',
    model: '5ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '5ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-6A805-UTP',
    estimatedCost: '$5.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-6a806-utp',
    model: '6ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '6ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-6A806-UTP',
    estimatedCost: '$7.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-6a810-utp',
    model: '10ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '10ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-6A810-UTP',
    estimatedCost: '$7.85',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-10x6-6a814-utp',
    model: '14ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    manufacturer: 'Comtop',
    category: 'cable',
    description: '14ft Cat6 Snagless Unshielded (UTP) Slim Ethernet Network Patch Cable',
    partNumber: '10X6-6A814-UTP',
    estimatedCost: '$10.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
  {
    id: 'comtop-16fp-10-scsc-01',
    model: 'OM3 SC/SC 10G Multi-Mode Fiber Cable 1M',
    manufacturer: 'Comtop',
    category: 'cable',
    description: 'OM3 SC/SC 10G Multi-Mode Fiber Cable 1M',
    partNumber: '16FP-10-SCSC-01',
    estimatedCost: '$5.68',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["comtop"],
  },
];

export default comtopCatalog;
