import type { CatalogItem } from './types';

const dataDirectCatalog: CatalogItem[] = [
  {
    id: 'datadirect-es200nvx2',
    model: '2U All NVMe Platform, Active/Active Dual Controller',
    manufacturer: 'DataDirect Networks',
    category: 'other',
    description: '2U All NVMe Platform, Active/Active Dual Controller',
    partNumber: 'ES200NVX2',
    estimatedCost: '',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-ai400x2-ndr200',
    model: 'AI400X2 All Flash Appliance with 24x NVMe slots, 8x NDR200 / 200GbE QSFP112 port',
    manufacturer: 'DataDirect Networks',
    category: 'server',
    description: 'AI400X2 All Flash Appliance with 24x NVMe slots, 8x NDR200 / 200GbE QSFP112 ports, 2x PSUs w/cables, rail kit; requires 4 VM EXAScaler support purchased separately',
    partNumber: 'AI400X2-NDR200',
    estimatedCost: '$86,715.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-ai400x2-ssd-3-500t',
    model: 'SSD bundle for AI400X2 Includes 24x NVMe SED Capable SSDs for 737TB RAW / 500TB',
    manufacturer: 'DataDirect Networks',
    category: 'server',
    description: 'SSD bundle for AI400X2 Includes 24x NVMe SED Capable SSDs for 737TB RAW / 500TB Useable Capacity',
    partNumber: 'AI400X2-SSD-3-500T',
    estimatedCost: '$191,517.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-s0g13072p24ep',
    model: '1 DWPD NVMe G4 4K SSD drive module for 400NVX2 system; SED ca',
    manufacturer: 'DataDirect Networks',
    category: 'server',
    description: '1 DWPD NVMe G4 4K SSD drive module for 400NVX2 system; SED ca',
    partNumber: 'S0G13072P24EP',
    estimatedCost: '$7,980.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-sup-pros',
    model: 'Support; storage systems, storage servers, disk drives and accessories; 7x24 rem',
    manufacturer: 'DataDirect Networks',
    category: 'other',
    description: 'Support; storage systems, storage servers, disk drives and accessories; 7x24 remote support; NBD parts and labor onsite; DDN replace CRU and FRU; SW support separate; annual',
    partNumber: 'SUP-PROS',
    estimatedCost: '$346,860.00',
    specs: 'Support | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-sup-ssd-pros-1',
    model: 'nsite Support; SSD Drives; coverage through normal wear life; use only with P',
    manufacturer: 'DataDirect Networks',
    category: 'other',
    description: 'nsite Support; SSD Drives; coverage through normal wear life; use only with PROS offerings; price is per SSD; annual',
    partNumber: 'SUP-SSD-PROS-1',
    estimatedCost: '$400.00',
    specs: 'Support | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-supsp-es1oss',
    model: 'upport Subscription; EXAScaler Software;per OSS or MDS, VM or physical server',
    manufacturer: 'DataDirect Networks',
    category: 'other',
    description: 'upport Subscription; EXAScaler Software;per OSS or MDS, VM or physical server; SLO based on underlying (BSPO, BSOS or PROS) hardware system support; 1 year',
    partNumber: 'SUPSP-ES1OSS',
    estimatedCost: '$3,600.00',
    specs: 'Support | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
  {
    id: 'datadirect-ins-ai400-4',
    model: 'n and configuration of factory-configured AI400 appliance including full soft',
    manufacturer: 'DataDirect Networks',
    category: 'other',
    description: 'n and configuration of factory-configured AI400 appliance including full software stack; for up to 4 clients',
    partNumber: 'INS-AI400-4',
    estimatedCost: '$12,995.00',
    specs: 'Support | Serialized | UOM: Eaches',
    vendorIds: ["dataDirect"],
  },
];

export default dataDirectCatalog;
