import type { CatalogItem } from './types';

const dellCatalog: CatalogItem[] = [
  {
    id: 'dell-xe9680-h100',
    model: 'PowerEdge XE9680',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'High-performance 6U AI rack server with 8x NVIDIA H100 GPUs',
    partNumber: 'XE9680-H100',
    estimatedCost: '$350,000.00',
    specs: '6U | 2× Xeon | 8× H100 SXM5 80GB | DDR5 up to 4TB | ~10–11.5 kW',
    vendorIds: ['dell'],
    links: {
      productPage: 'https://www.dell.com/en-us/shop/ipovw/poweredge-xe9680',
      datasheet: 'https://www.delltechnologies.com/asset/en-us/products/servers/technical-support/poweredge-xe9680-spec-sheet.pdf',
    },
  },
  {
    id: 'dell-xe9680-h200',
    model: 'PowerEdge XE9680 (H200)',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'High-performance 6U AI rack server with 8x NVIDIA HGX H200 GPUs and BlueField-3 SuperNIC support',
    partNumber: 'XE9680-H200',
    estimatedCost: '$400,000.00',
    specs: '6U | 2× Xeon | 8× H200 SXM5 | DDR5 | ~11.5–12.5 kW',
    vendorIds: ['dell'],
    links: {
      productPage: 'https://www.dell.com/en-us/shop/ipovw/poweredge-xe9680',
      datasheet: 'https://www.delltechnologies.com/asset/en-us/products/servers/technical-support/poweredge-xe9680-spec-sheet.pdf',
    },
  },
  {
    id: 'dell-xe9712',
    model: 'PowerEdge XE9712',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'NVIDIA GB200 NVL72 Compute Node (1U Sled) for AI at Scale with Liquid Cooling',
    partNumber: 'XE9712',
    estimatedCost: '$120,000.00',
    specs: '1U sled | Grace CPU + Blackwell GB200 | LPDDR5X | Liquid cooled',
    vendorIds: ['dell'],
    links: {
      productPage: 'https://www.dell.com/en-us/shop/ipovw/poweredge-xe9712',
      datasheet: 'https://www.delltechnologies.com/asset/en-us/products/servers/technical-support/poweredge-xe-ai-spec-sheet.pdf',
    },
  },
  {
    id: 'dell-cabinet-44u',
    model: 'Dell 44U Rack Cabinet',
    manufacturer: 'Dell Technologies',
    category: 'cabinet',
    description: '44U EIA/IEC rack cabinet',
    partNumber: '770-BBIN',
    estimatedCost: '$3,500.00',
    specs: '44U | EIA/IEC standard | Cable management + security',
    vendorIds: ['dell'],
    links: {
      productPage: 'https://www.dell.com/en-us/shop/netshelter-4-post-open-frame-rack-44u-12-24-threaded-holes/apd/a3707707/power-cooling-data-center-infrastructure',
    },
  },
  {
    id: 'dell-gpu-h100-01',
    model: 'PowerEdge XE9680 210-BFXH* 2x Intel 8462Y+ 32x 64GB DDR5 8 x SSDPF2KX076T1OS 1 x',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'PowerEdge XE9680 210-BFXH* 2x Intel 8462Y+ 32x 64GB DDR5 8 x SSDPF2KX076T1OS 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x Nvidia H100 BB',
    partNumber: 'PowerEdge XE9680 210-BFXH*',
    estimatedCost: '$282,017.76',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-h200-04',
    model: 'PowerEdge XE9680 210-BFXH* 2x Intel 8562Y+ 32x 64GB DDR5 8 x SSDPF2KX076T1OS 1 x',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'PowerEdge XE9680 210-BFXH* 2x Intel 8562Y+ 32x 64GB DDR5 8 x SSDPF2KX076T1OS 1 x 900-9D3B6-00CV-AA0 8 x MCX75310AAS-NEAT 1 x Nvidia H200 BB',
    partNumber: 'PowerEdge XE9680 210-BFXH*',
    estimatedCost: '$260,712.00',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb200-01',
    model: 'Dell Server 9712a Server Node Containing: 2x "Bianca" GB200 HPM (1 Grace CPU, 2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell Server 9712a Server Node Containing: 2x "Bianca" GB200 HPM (1 Grace CPU, 2 Blackwell GPU each) 2x ConnectX-7 internal mezz cards (2x CX7 per mezz for 1:1 IB to GPU ratio) 1x NVIDIA BlueField-3 B3220 1x PCIe Switch Assy 1x HMC module 8x E1.S Micron 7450 Read Intensive 3.84 TB Gen 4 NVMe Drives',
    partNumber: 'GB200 NVL72',
    estimatedCost: '',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-poweredge-c6320',
    model: 'Dell PowerEdge C6320 Intel Xeon processor E5-2600 v4 product family Support for',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell PowerEdge C6320 Intel Xeon processor E5-2600 v4 product family Support for 2400MT/s DDR4 DIMMs Flexible 2.5" or 3.5" high-capacity drive configurations iDRAC8 with Lifecycle Controller (Express or Enterprise)',
    partNumber: 'PowerEdge C6320',
    estimatedCost: '$2,046.64',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-poweredge-r640',
    model: 'Dell PowerEdge R640 Server 2x RAM',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell PowerEdge R640 Server 2x RAM',
    partNumber: 'PowerEdge R640',
    estimatedCost: '',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-poweredge-r6515',
    model: 'Dell EMC 4JJ53 PowerEdge R6515 Server',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell EMC 4JJ53 PowerEdge R6515 Server',
    partNumber: 'PowerEdge R6515',
    estimatedCost: '',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-poweredge-r740xd',
    model: 'Dell PowerEdge R740xd 2U Rack Server',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell PowerEdge R740xd 2U Rack Server',
    partNumber: 'PowerEdge R740xd',
    estimatedCost: '$891.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-vc496',
    model: 'Dell VC496 Mellanox ConnectX-5 VPI CX555A Single Port 100GB QSFP PCIe 3.0 x16 Ne',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Dell VC496 Mellanox ConnectX-5 VPI CX555A Single Port 100GB QSFP PCIe 3.0 x16 Network Adapter FH Ref',
    partNumber: 'VC496',
    estimatedCost: '$215.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-y1t43',
    model: 'Dell Y1T43 Mellanox CX653105A ConnectX-6 Single Port VPI HDR100 QSFP Adapter FH',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Dell Y1T43 Mellanox CX653105A ConnectX-6 Single Port VPI HDR100 QSFP Adapter FH',
    partNumber: 'Y1T43',
    estimatedCost: '$375.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb200-l11-01',
    model: 'GPU-GB200-L11-01 | Single Rack GB200 NVL72 featuring Dell Server 9712A and "Arch',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'GPU-GB200-L11-01 | Single Rack GB200 NVL72 featuring Dell Server 9712A and "Archer" rack Infrastructure Compute: 18x Dell Server 9712a Server Node Containing: -2x "Bianca" GB200 HPM (1 Grace CPU, 2 Blackwell GPU each) -2x ConnectX-7 internal mezz cards (2x CX7 per mezz for 1:1 IB to GPU ratio) -1x NVIDIA BlueField-3 B3220 -1x PCIe Switch Assy -1x HMC module -8x E1.S Micron 7450 Read Intensive 3.84 TB Gen 4 NVMe Drives NVLink Infrastructure 9x GB200-NVLINK-SW | 920-9K36W-00MV-GS0 - NVIDIA Quantum-3, NVLink Tray Solution, 1U, with 144 NVLink5 Internal Ports 4x Cable Cartridges (Backplane) Rack Infrastructure 1x Dell "Archer" enhanced ORv3 rack (DLC manifolds, bus bar, blanks, etc) 8x PS-1OU-01 | Delta - 33kW power shelves 1 x 60a input 1x CDU-4RU-02 | Vertiv In-Rack CDU XDU100 & manifold connection hose/hardware 1x CDU-IPSL-01 | Vertiv ADX - IPSL104-400 Redfish Appliance & ADX - IPPS power supply for redfish 3x MSN2201-CSMRC | NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU, Busbar​ powered 2x Vertiv UI30024 PDU & power whip FSC3U001',
    partNumber: 'GB200 NVL72',
    estimatedCost: '$3,592,000.00',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb200-l11-02',
    model: 'GPU-GB200-L11-02 | Single Rack GB200 NVL72 featuring Dell Server 9712A and "Arch',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'GPU-GB200-L11-02 | Single Rack GB200 NVL72 featuring Dell Server 9712A and "Archer" rack Infrastructure Compute: 18x Dell Server 9712a Server Node Containing: -2x "Bianca" GB200 HPM (1 Grace CPU, 2 Blackwell GPU each) -2x ConnectX-8 internal mezz cards -1x NVIDIA BlueField-3 B3220 -1x PCIe Switch Assy -1x HMC module -8x E.1 7.68TB SSD NVMe Drives NVLink Infrastructure 9x GB200-NVLINK-SW | 920-9K36W-00MV-GS0 - NVIDIA Quantum-3, NVLink Tray Solution, 1U, with 144 NVLink5 Internal Ports 4x Cable Cartridges (Backplane) Rack Infrastructure 1x Dell "Archer" enhanced ORv3 rack (DLC manifolds, bus bar, blanks, etc) 8x PS-1OU-01 | Delta - 33kW power shelves 1 x 60a input 1x CDU-4RU-02 | Vertiv In-Rack CDU XDU100 & manifold connection hose/hardware 2x MSN2201-CSMRC | NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU, Busbar​ powered 2x Vertiv UI30024 PDU & power whip FSC3U001 4x MMS1V70-CM TOR QSFP Tranceivers',
    partNumber: 'GB200 NVL72',
    estimatedCost: '$3,710,000.00',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-ssdpf2kx076t1os',
    model: '86DM1 7.68TB NVMe Read Intensive 2.5 inch U.2 PCIe 4.0, OPAL 2.0 SED Drive, D7-P',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: '86DM1 7.68TB NVMe Read Intensive 2.5 inch U.2 PCIe 4.0, OPAL 2.0 SED Drive, D7-P5520, Solidigm SSDPF2KX076T1OS',
    partNumber: 'SSDPF2KX076T1OS',
    estimatedCost: '$1,864.98',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-dvt88',
    model: 'Dell XE9680 2U Rack Rail Kit',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell XE9680 2U Rack Rail Kit',
    partNumber: 'DVT88',
    estimatedCost: '$79.99',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-03wf88',
    model: 'Dell 2U Rack Rail Kit V2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell 2U Rack Rail Kit V2',
    partNumber: '03WF88',
    estimatedCost: '$79.99',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb200-02',
    model: 'Dell Server 9712a Server Node Containing: 2x "Bianca" GB200 HPM (1 Grace CPU, 2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell Server 9712a Server Node Containing: 2x "Bianca" GB200 HPM (1 Grace CPU, 2 Blackwell GPU each) 2x ConnectX-8 internal mezz cards (2x CX8 per mezz for 1:1 IB to GPU ratio) 1x NVIDIA BlueField-3 B3220 1x PCIe Switch Assy 1x HMC module 8x E1.S 7.68TB Gen 4 NVMe Drives',
    partNumber: 'GB200 NVL72',
    estimatedCost: '',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-c6420',
    model: 'Dell EMC PowerEdge C6420 Server with Dell C6400 Chassis',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell EMC PowerEdge C6420 Server with Dell C6400 Chassis',
    partNumber: 'C6420',
    estimatedCost: '$2,810.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-1pdr6',
    model: 'Power Supply Unit Dell 1PDR6 2800 Watts Redundant Power Supply',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Power Supply Unit Dell 1PDR6 2800 Watts Redundant Power Supply',
    partNumber: '1PDR6',
    estimatedCost: '$368.29',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-86dm1',
    model: '7.68TB NVMe Read Intensive 2.5 inch U.2 PCIe 4.0, OPAL 2.0 SED Drive, D7-P5520,',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: '7.68TB NVMe Read Intensive 2.5 inch U.2 PCIe 4.0, OPAL 2.0 SED Drive, D7-P5520, Solidigm SSDPF2KX076T1OS',
    partNumber: '86DM1',
    estimatedCost: '$1,864.98',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-fx9wj',
    model: 'Power Supply Unit Dell 1PDR6 2800 Watts 86,ART,54VOUT,TI',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Power Supply Unit Dell 1PDR6 2800 Watts 86,ART,54VOUT,TI',
    partNumber: 'FX9WJ',
    estimatedCost: '$368.29',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-3r8ch',
    model: 'Assembly Fan Cage,80X105,XE9680,V2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Assembly Fan Cage,80X105,XE9680,V2',
    partNumber: '3R8CH',
    estimatedCost: '$142.77',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-9nt8p',
    model: 'Power Supply Unit Dell 1PDR6 2800 Watts 86,LIT,54VOUT,TI',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Power Supply Unit Dell 1PDR6 2800 Watts 86,LIT,54VOUT,TI',
    partNumber: '9NT8P',
    estimatedCost: '$368.29',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-x485v',
    model: 'CRD,NTWK,400,SP,NDR,OSFP,CX7,Z',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'CRD,NTWK,400,SP,NDR,OSFP,CX7,Z',
    partNumber: 'X485V',
    estimatedCost: '$2,010.01',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-2cxnx',
    model: 'CRD,NTWK,200,DP,QSFP112,BF3P,Z',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'CRD,NTWK,200,DP,QSFP112,BF3P,Z',
    partNumber: '2CXNX',
    estimatedCost: '$3,363.33',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-r630',
    model: 'Dell PowerEdge R630 NVMe 1U Server',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell PowerEdge R630 NVMe 1U Server',
    partNumber: 'R630',
    estimatedCost: '$529.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-345-bgsy',
    model: 'Dell 960GB SSD SATA Read Intensive 6Gbps 512e 2.5in with 3.5in Hybrid Carrier Ho',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell 960GB SSD SATA Read Intensive 6Gbps 512e 2.5in with 3.5in Hybrid Carrier Hot-plug',
    partNumber: '345-BGSY',
    estimatedCost: '$1,969.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-dps-1100ab-14',
    model: 'Dell DPS-1100AB-14 1100W DC Power Supply for T550/R750',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Dell DPS-1100AB-14 1100W DC Power Supply for T550/R750',
    partNumber: 'DPS-1100AB-14',
    estimatedCost: '$640.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb300-01-qs',
    model: 'Dell Server XE9712 Server Node Containing: 2x "Bianca" GB300 HPM (1 Grace CPU, 2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell Server XE9712 Server Node Containing: 2x "Bianca" GB300 HPM (1 Grace CPU, 2 Blackwell GPU each) 2x ConnectX-8 internal mezz cards 1x NVIDIA BlueField-3 B3220 1x iDRAC 1x HMC module GB300 version 8x E1.S 7.68 TB Gen 4 NVMe Drives (gen 5)',
    partNumber: 'GB300 NVL72',
    estimatedCost: '',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb300-l11-01-qs',
    model: 'Single Rack GB300 NVL72, featuring Dell Server XE9712 Compute: 18x Dell Server X',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Single Rack GB300 NVL72, featuring Dell Server XE9712 Compute: 18x Dell Server XE9712 Server Node Containing: - 1x " Cordillia" GB300 HPM (2 Grace CPU, 4 Blackwell GPU w/ SOCAMM) - 2x ConnectX-8 internal mezz cards - 1x NVIDIA BlueField-3 B3220 - 1x iDRAC - 1x HMC module GB300 version - 8x E.1 7.68TB SSD NVMe Drives (Gen 5) NVLink Infrastructure 9x NVIDIA N5500 Non-Scale Nvlink Switch 4x Cable Cartridges (Backplane) Rack Infrastructure 1x Dell IR9048 48RU 21in ORv3 Rack 9DLC Manifolds, bus bar, blanks, etc.) 8x 33kW power shelves 1 x 60a input (new Delta Powerbrake feature) 2x MSN2201-CSMRC | NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU, Busbar​ powered 4x TOR QSFP Tranceivers 2x rPDU 1x XDU CDU (requires rPDU above) - Vertiv',
    partNumber: 'GB300 NVL72',
    estimatedCost: '',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-r7625',
    model: 'Dell 2800W Power Supply 1PDR6 D2800E-S1 16th Gen Power Supply',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Dell 2800W Power Supply 1PDR6 D2800E-S1 16th Gen Power Supply',
    partNumber: 'R7625',
    estimatedCost: '$405.59',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-fsc3u001',
    model: 'Vertiv Geist PDU Facility Side Cable - 16/20A, 230/400V WYE',
    manufacturer: 'Dell Technologies',
    category: 'cable',
    description: 'Vertiv Geist PDU Facility Side Cable - 16/20A, 230/400V WYE',
    partNumber: 'FSC3U001',
    estimatedCost: '$354.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-mcx623106an-cdat',
    model: 'Mellanox ConnectX-6 Dx - Network adapter - PCIe 4.0 x16 - 100 Gigabit QSFP56 x',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Mellanox ConnectX-6 Dx - Network adapter - PCIe 4.0 x16 - 100 Gigabit QSFP56 x 2',
    partNumber: 'MCX623106AN-CDAT',
    estimatedCost: '$1,228.72',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-stor-cold-01',
    model: 'PowerEdge R7715 Storage Server 1x AMD EPYC 9655P 2.60GHz, 96C/192T, 384 Cache (4',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'PowerEdge R7715 Storage Server 1x AMD EPYC 9655P 2.60GHz, 96C/192T, 384 Cache (400W) DDR5-6400 24x 64GB RDIMM, 6400MT/s, Dual Rank 32x 61.44 TB Micron 6550 ION pTLC SSD E3.S 1x Nvidia BlueField-3 DP InfiniBand NDR 200GbE QSFP112 DPU PCIe',
    partNumber: 'PowerEdge R7715',
    estimatedCost: '$166,745.00',
    specs: 'Storage Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-d7-p5520',
    model: '15.36TB NVMe Read Intensive 2.5in PCIe 4.0 OPAL SED Drive, Solidigm D7-P5520 CUS',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: '15.36TB NVMe Read Intensive 2.5in PCIe 4.0 OPAL SED Drive, Solidigm D7-P5520 CUS, DSS RESTRICTED',
    partNumber: 'D7-P5520',
    estimatedCost: '$3,012.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb300-l11-01',
    model: 'Single Rack GB300 NVL72, featuring Dell Server XE9712 Compute: 18x Dell Server',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Single Rack GB300 NVL72, featuring Dell Server XE9712 Compute: 18x Dell Server XE9712 Server Node Containing: 2x " Cordillia" GB300 HPM (1 Grace CPU, 2 Blackwell GPU)12H Board 2x ConnectX-8 internal mezz cards 1x NVIDIA BlueField-3 B3220 1x HMC module GB300 version 8x E.1 7.68TB SSD NVMe Drives (Gen 5) NVLink Infrastructure: 9x NVIDIA N5600 Non-Scale Nvlink Switch 4x Cable Cartridges (Backplane) Rack Infrastructure: 1x Dell IR9048 48RU 21in ORv3 Rack (DLC manifolds, bus bar, blanks, etc.) 8x 33kW power shelves 1 x 60a input (new Delta Power Shelf) 2x MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU, Busbar powered 4x TOR QSFP Tranceivers',
    partNumber: 'GB300 NVL72',
    estimatedCost: '$4,577,600.00',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb300-01',
    model: 'Dell Server XE9712 Server Node Containing: 2x "Bianca" GB300 HPM (1 Grace CPU, 2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell Server XE9712 Server Node Containing: 2x "Bianca" GB300 HPM (1 Grace CPU, 2 Blackwell GPU each) 2x ConnectX-8 internal mezz cards 1x NVIDIA BlueField-3 B3220 1x iDRAC 1x HMC module GB300 version 8x E1.S 7.68 TB Gen 4 NVMe Drives (gen 5)',
    partNumber: 'GB300 NVL72',
    estimatedCost: '',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb300-l11-02',
    model: 'Single Rack GB300 NVL72, featuring Dell Server XE9712 Compute: 18x Dell Server',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Single Rack GB300 NVL72, featuring Dell Server XE9712 Compute: 18x Dell Server XE9712 Server Node Containing: 2x " Cordillia" GB300 HPM (1 Grace CPU, 2 Blackwell GPU)12H Board 2x ConnectX-8 internal mezz cards 1x NVIDIA BlueField-3 B3220 1x HMC module GB300 version 8x E.1 7.68TB SSD NVMe Drives (Gen 5) NVLink Infrastructure: 9x NVIDIA N5600 Non-Scale Nvlink Switch 4x Cable Cartridges (Backplane) Rack Infrastructure: 1x Dell 48RU 21in ORv3 Rack (DLC manifolds, bus bar, blanks, etc.) 8x 33kW power shelves 1 x 60a input (new Delta Power Shelf) 2x MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU, Busbar powered 4x TOR QSFP Tranceivers 1x XDU150 CDU',
    partNumber: 'GB300 NVL72',
    estimatedCost: '$4,615,000.00',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-dell-gb-rack-cdu-drip-tray',
    model: 'Dell GB Rack CDU Drip Tray',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Dell GB Rack CDU Drip Tray',
    partNumber: 'GB300 NVL72',
    estimatedCost: '$815.00',
    specs: 'Machinery and Equipment | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-dell-gb-rack-cdu-rack-rail',
    model: 'Dell GB Rack CDU Rack Rail',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Dell GB Rack CDU Rack Rail',
    partNumber: 'GB300 NVL72',
    estimatedCost: '$117.65',
    specs: 'Machinery and Equipment | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-mtfdkce7t6tfr-1bc15abyy',
    model: 'Micron 7450 Pro 7.68TB NVMe (SED / TCG Opal 2.0) E1.S Solid State Drive (SSD)',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Micron 7450 Pro 7.68TB NVMe (SED / TCG Opal 2.0) E1.S Solid State Drive (SSD)',
    partNumber: 'MTFDKCE7T6TFR-1BC15ABYY',
    estimatedCost: '$865.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-210-btcm',
    model: 'Dell Server 9712a Server Nodes',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'Dell Server 9712a Server Nodes',
    partNumber: '210-BTCM',
    estimatedCost: '$53,014.88',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-210-bsdq',
    model: '33kW power shelves 1 x 60a input',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: '33kW power shelves 1 x 60a input',
    partNumber: '210-BSDQ',
    estimatedCost: '$212,059.50',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-210-bsry',
    model: 'NvLink Non-Scalable switches 210-BSRY',
    manufacturer: 'Dell Technologies',
    category: 'switch',
    description: 'NvLink Non-Scalable switches 210-BSRY',
    partNumber: '210-BSRY',
    estimatedCost: '$106,029.74',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-629-bbgs',
    model: 'MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cum',
    manufacturer: 'Dell Technologies',
    category: 'switch',
    description: 'MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU,Busbar powered 629-BBGS',
    partNumber: '629-BBGS',
    estimatedCost: '$212,059.50',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-ovtvd',
    model: 'Delta Power Supply',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Delta Power Supply',
    partNumber: 'OVTVD',
    estimatedCost: '$21,205.95',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-oykc3',
    model: 'Delta PMC Power Supply',
    manufacturer: 'Dell Technologies',
    category: 'other',
    description: 'Delta PMC Power Supply',
    partNumber: 'OYKC3',
    estimatedCost: '$212,059.50',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["dell"],
  },
  {
    id: 'dell-gpu-gb300-l11-04',
    model: 'GB300 NVL72, featuring Dell Server XE9712 18x Dell Server XE9712 Server Nodes 2',
    manufacturer: 'Dell Technologies',
    category: 'server',
    description: 'GB300 NVL72, featuring Dell Server XE9712 18x Dell Server XE9712 Server Nodes 2x GB300 1 CPU:2 GPU 12H Board PC 2x ConnectX-8 internal mezz cards 1x NVIDIA BlueField-3 B3220 1x HMC module GB300 version 8x E.1 7.68TB SSD NVMe Drives (Gen 5) NVLINK INFRASTRUCTURE 9x NVIDIA N5600 Non-Scale Nvlink Switch 4x Cable Cartridges (Backplane) RACK INFRASTRUCTURE (IR9048 Rack) 1x Dell 48RU 21in ORv3 Rack (DLC manifolds, bus bar, blanks, etc.) 8x 33kW power shelves 1 x 60a input (new Delta Power Shelf) 2x MSN2201-CSMRC NVIDIA Spectrum based 1GbE/100GbE 1U Open Ethernet switch with Cumulus Linux, 48 RJ45 ports and 4 QSFP28 ports, x86 CPU, Busbar powered 1x XDU100B CDU, rails and drip tray 4x TOR QSFP Transceivers SUPPORT 3YR Prosupport One Datacenter CSP & AI Bundle NBD parts with Designated Support Engineer (DSE), Field Services Engineer (OSE/FSE) 3YR Nvidia Spectrum Support Contact 3YR Delta Support and Commissioning',
    partNumber: 'GPU-GB300-L11-04',
    estimatedCost: '$4,630,752.00',
    specs: 'GPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["dell"],
  },
];

export default dellCatalog;
