import type { CatalogItem } from './types';

const deltaElectronicsCatalog: CatalogItem[] = [
  {
    id: 'deltaelectronics-ps-1ou-01',
    model: '3kW power shelves 1 x 60a input',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: '3kW power shelves 1 x 60a input',
    partNumber: 'ECD68000060',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
  {
    id: 'deltaelectronics-dps-1900ab',
    model: 'Arista 1900W AC Power Supply PWR-00237-01',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: 'Arista 1900W AC Power Supply PWR-00237-01',
    partNumber: 'DPS-1900AB',
    estimatedCost: '$268.11',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
  {
    id: 'deltaelectronics-dps-3000ab-1a',
    model: 'Delta Electronics 3000W Switching Power Supply',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: 'Delta Electronics 3000W Switching Power Supply',
    partNumber: 'DPS-3000AB-1A',
    estimatedCost: '$360.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
  {
    id: 'deltaelectronics-dps-3000ab-10c',
    model: 'Delta Electronics 3000W Switching Power Supply',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: 'Delta Electronics 3000W Switching Power Supply',
    partNumber: 'DPS-3000AB-10C',
    estimatedCost: '$360.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
  {
    id: 'deltaelectronics-clshk-aeb01-s',
    model: 'Valvey Train Assembly - Supply',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: 'Valvey Train Assembly - Supply',
    partNumber: 'CLSHK-AEB01-S',
    estimatedCost: '$10,500.00',
    specs: 'CDU | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
  {
    id: 'deltaelectronics-clshk-aeb02-s',
    model: 'Valvey Train Assembly - Return',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: 'Valvey Train Assembly - Return',
    partNumber: 'CLSHK-AEB02-S',
    estimatedCost: '$11,000.00',
    specs: 'CDU | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
  {
    id: 'deltaelectronics-clscd305aeb01-0',
    model: 'SuperCDU-3000',
    manufacturer: 'Delta Electronics',
    category: 'other',
    description: 'SuperCDU-3000',
    partNumber: 'CLSCD305AEB01-0',
    estimatedCost: '$250,000.00',
    specs: 'CDU | UOM: Eaches',
    vendorIds: ["deltaElectronics"],
  },
];

export default deltaElectronicsCatalog;
