import type { CatalogItem } from './types';

const eziBlankCatalog: CatalogItem[] = [
  {
    id: 'eziblank-bkpnl01-b',
    model: 'EziBlank 19" 6RU Modular Blanking Panel (10-Pack)',
    manufacturer: 'EziBlank',
    category: 'other',
    description: 'EziBlank 19" 6RU Modular Blanking Panel (10-Pack)',
    partNumber: 'BKPNL01-B',
    estimatedCost: '$85.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["eziBlank"],
  },
  {
    id: 'eziblank-bkpnl01u-b',
    model: 'EziBlank 19" Universal 6RU Modular Blanking Panel (10-Pack)',
    manufacturer: 'EziBlank',
    category: 'other',
    description: 'EziBlank 19" Universal 6RU Modular Blanking Panel (10-Pack)',
    partNumber: 'BKPNL01U-BL',
    estimatedCost: '$95.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["eziBlank"],
  },
  {
    id: 'eziblank-ezbr19x1upnl-100',
    model: 'EziBlank Brush 19" 1RU - Pack of 100 Bulk packaging does not include rack studs',
    manufacturer: 'EziBlank',
    category: 'other',
    description: 'EziBlank Brush 19" 1RU - Pack of 100 Bulk packaging does not include rack studs',
    partNumber: 'EZBR19X1UPNL-100',
    estimatedCost: '$1,400.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["eziBlank"],
  },
  {
    id: 'eziblank-ezbr19x1upnl-200',
    model: 'EziBlank Brush 19" 1RU - Pack of 200 Bulk packaging does not include rack studs',
    manufacturer: 'EziBlank',
    category: 'other',
    description: 'EziBlank Brush 19" 1RU - Pack of 200 Bulk packaging does not include rack studs',
    partNumber: 'EZBR19X1UPNL-200',
    estimatedCost: '$2,600.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["eziBlank"],
  },
  {
    id: 'eziblank-ezbr19x1upnl-50',
    model: 'EziBlank Brush 19" 1RU - Pack of 50 Bulk packaging does not include rack studs',
    manufacturer: 'EziBlank',
    category: 'other',
    description: 'EziBlank Brush 19" 1RU - Pack of 50 Bulk packaging does not include rack studs',
    partNumber: 'EZBR19X1UPNL-50',
    estimatedCost: '$540.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["eziBlank"],
  },
  {
    id: 'eziblank-ezbr19x1upnl05',
    model: 'EziBlank Brush 19" 1RU - Pack of 5',
    manufacturer: 'EziBlank',
    category: 'other',
    description: 'EziBlank Brush 19" 1RU - Pack of 5',
    partNumber: 'EZBR19X1UPNL05',
    estimatedCost: '$84.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["eziBlank"],
  },
];

export default eziBlankCatalog;
