import type { CatalogItem } from './types';

const flexOptixCatalog: CatalogItem[] = [
  {
    id: 'flexoptix-q-161hg-2-c',
    model: '100G CWDM4 QSFP',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: '100G CWDM4 QSFP',
    partNumber: 'Q.161HG.2.C',
    estimatedCost: '$150.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
  {
    id: 'flexoptix-q-161hg-10',
    model: 'Flexoptix 100G LR4 Programmable QSFP28 Transceiver',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: 'Flexoptix 100G LR4 Programmable QSFP28 Transceiver',
    partNumber: 'Q.161HG.10',
    estimatedCost: '$100.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
  {
    id: 'flexoptix-q-851hg-02',
    model: 'Q.851HG.02',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: 'Q.851HG.02',
    partNumber: 'Q.851HG.02',
    estimatedCost: '$251.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
  {
    id: 'flexoptix-f-8540g-02',
    model: '100 m, 4x 850 nm, MTP/MPO-8/12, Multimode',
    manufacturer: 'FlexOptix',
    category: 'cable',
    description: '100 m, 4x 850 nm, MTP/MPO-8/12, Multimode',
    partNumber: 'F.8540G.02',
    estimatedCost: '$111.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
  {
    id: 'flexoptix-q-8540g-02',
    model: '40GB QSFP+ SR4 MPO Multimod 4x 850nm 100m QSFP+ Transceiver',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: '40GB QSFP+ SR4 MPO Multimod 4x 850nm 100m QSFP+ Transceiver',
    partNumber: 'Q.8540G.02',
    estimatedCost: '$78.89',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
  {
    id: 'flexoptix-p-1396-10',
    model: 'SMF 1310nm 0.6-11.3Gbit/s 10G LR Programmable SFP+ Transceiver',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: 'SMF 1310nm 0.6-11.3Gbit/s 10G LR Programmable SFP+ Transceiver',
    partNumber: 'P.1396.10',
    estimatedCost: '$45.04',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
  {
    id: 'flexoptix-q-1640g-10',
    model: '40G LR4 Programmable QSFP+ Transceiver',
    manufacturer: 'FlexOptix',
    category: 'transceiver',
    description: '40G LR4 Programmable QSFP+ Transceiver',
    partNumber: 'Q.1640G.10',
    estimatedCost: '$321.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["flexOptix"],
  },
];

export default flexOptixCatalog;
