import type { CatalogItem } from './types';

const fsComCatalog: CatalogItem[] = [
  {
    id: 'fscom-mfmc-12dp',
    model: '12 Slots 10/100M and 10/100/1000M Mini Media Converter Chassis, 1U Rack Mount, D',
    manufacturer: 'FS.com',
    category: 'other',
    description: '12 Slots 10/100M and 10/100/1000M Mini Media Converter Chassis, 1U Rack Mount, Dual Power AC 220V',
    partNumber: 'MFMC-12DP',
    estimatedCost: '$110.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp1g-lx-31',
    model: 'Customized SFP 1000BASE-LX/LH 1310nm 10km DOM Duplex LC SMF Optical Transceiver',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Customized SFP 1000BASE-LX/LH 1310nm 10km DOM Duplex LC SMF Optical Transceiver Module, Palo Alto Coded',
    partNumber: 'SFP1G-LX-31',
    estimatedCost: '$8.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-umc-ga1f1t',
    model: 'Mini Unmanaged 1x 10/100/1000Base-T RJ45 to 1x 1000Base-X SFP Slot Gigabit Ether',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'Mini Unmanaged 1x 10/100/1000Base-T RJ45 to 1x 1000Base-X SFP Slot Gigabit Ethernet Media Converter, American Plug Standard',
    partNumber: 'UMC-GA1F1T',
    estimatedCost: '$29.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-umc-ga1f2t',
    model: 'Mini Unmanaged 2x 10/100/1000Base-T RJ45 to 1x 1000Base-X SFP Slot Gigabit Ether',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'Mini Unmanaged 2x 10/100/1000Base-T RJ45 to 1x 1000Base-X SFP Slot Gigabit Ethernet Media Converter, American Plug Standard',
    partNumber: 'UMC-GA1F2T',
    estimatedCost: '$43.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10glr-31',
    model: '10GBASE-LR SFP+ 1310nm 10km DOM Duplex LC/UPC SMF Optical Transceiver Module for',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '10GBASE-LR SFP+ 1310nm 10km DOM Duplex LC/UPC SMF Optical Transceiver Module for FS Switches',
    partNumber: 'SFP-10GLR-31',
    estimatedCost: '$27.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc005',
    model: '100G DAC NODE TO SWITCH 0.5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 0.5 METER',
    partNumber: 'QSFP-100G-PC005',
    estimatedCost: '$32.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc01',
    model: '100G DAC NODE TO SWITCH 1 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 1 METER',
    partNumber: 'QSFP-100G-PC01',
    estimatedCost: '$32.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc015',
    model: '100G DAC NODE TO SWITCH 1.5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 1.5 METER',
    partNumber: 'QSFP-100G-PC015',
    estimatedCost: '$43.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc02',
    model: '100G DAC NODE TO SWITCH 2 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 2 METER',
    partNumber: 'QSFP-100G-PC02',
    estimatedCost: '$43.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc025',
    model: '100G DAC NODE TO SWITCH 2.5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 2.5 METER',
    partNumber: 'QSFP-100G-PC025',
    estimatedCost: '$54.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc03',
    model: '100G DAC NODE TO SWITCH 3 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 3 METER',
    partNumber: 'QSFP-100G-PC03',
    estimatedCost: '$54.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc05',
    model: '100G DAC NODE TO SWITCH 5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 5 METER',
    partNumber: 'QSFP-100G-PC05',
    estimatedCost: '$77.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc04',
    model: '100G DAC NODE TO SWITCH 4 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 4 METER',
    partNumber: 'QSFP-100G-PC04',
    estimatedCost: '$69.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-pc06',
    model: '100G DAC NODE TO SWITCH 6 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G DAC NODE TO SWITCH 6 METER',
    partNumber: 'QSFP-100G-PC06',
    estimatedCost: '$85.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc005',
    model: '40G > 4X10G DAC NODE TO SWITCH 0.5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 0.5 METER',
    partNumber: 'QSFP-40G-4SPC005',
    estimatedCost: '$40.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc01',
    model: '40G > 4X10G DAC NODE TO SWITCH 1 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 1 METER',
    partNumber: 'QSFP-40G-4SPC01',
    estimatedCost: '$43.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc015',
    model: '40G > 4X10G DAC NODE TO SWITCH 1.5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 1.5 METER',
    partNumber: 'QSFP-40G-4SPC015',
    estimatedCost: '$43.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc02',
    model: '40G > 4X10G DAC NODE TO SWITCH 2 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 2 METER',
    partNumber: 'QSFP-40G-4SPC02',
    estimatedCost: '$57.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc03',
    model: '40G > 4X10G DAC NODE TO SWITCH 3 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 3 METER',
    partNumber: 'QSFP-40G-4SPC03',
    estimatedCost: '$69.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc04',
    model: '40G > 4X10G DAC NODE TO SWITCH 4 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 4 METER',
    partNumber: 'QSFP-40G-4SPC04',
    estimatedCost: '$76.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc05',
    model: '40G > 4X10G DAC NODE TO SWITCH 5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 5 METER',
    partNumber: 'QSFP-40G-4SPC05',
    estimatedCost: '$83.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-4spc07',
    model: '40G > 4X10G DAC NODE TO SWITCH 7 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G > 4X10G DAC NODE TO SWITCH 7 METER',
    partNumber: 'QSFP-40G-4SPC07',
    estimatedCost: '$129.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-pc01',
    model: '40G DAC NODE TO SWITCH 1 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G DAC NODE TO SWITCH 1 METER',
    partNumber: 'QSFP-40G-PC01',
    estimatedCost: '$28.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-pc015',
    model: '40G DAC NODE TO SWITCH 1.5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G DAC NODE TO SWITCH 1.5 METER',
    partNumber: 'QSFP-40G-PC015',
    estimatedCost: '$30.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-pc02',
    model: '40G DAC NODE TO SWITCH 2 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G DAC NODE TO SWITCH 2 METER',
    partNumber: 'QSFP-40G-PC02',
    estimatedCost: '$33.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-pc03',
    model: '40G DAC NODE TO SWITCH 3 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G DAC NODE TO SWITCH 3 METER',
    partNumber: 'QSFP-40G-PC03',
    estimatedCost: '$35.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-pc05',
    model: '40G DAC NODE TO SWITCH 5 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '40G DAC NODE TO SWITCH 5 METER',
    partNumber: 'QSFP-40G-PC05',
    estimatedCost: '$51.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-2qpc03',
    model: '100G > 2X50G DAC NODE TO SWITCH 3 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G > 2X50G DAC NODE TO SWITCH 3 METER',
    partNumber: 'QSFP-100G-2QPC03',
    estimatedCost: '$109.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-2qpc04',
    model: '100G > 2X50G DAC NODE TO SWITCH 4 METER',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '100G > 2X50G DAC NODE TO SWITCH 4 METER',
    partNumber: 'QSFP-100G-2QPC04',
    estimatedCost: '$119.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-4sao10',
    model: '10m (33ft) Generic Compatible 100G QSFP28 to 4 x 25G SFP28 Active Optical Breako',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '10m (33ft) Generic Compatible 100G QSFP28 to 4 x 25G SFP28 Active Optical Breakout Cable',
    partNumber: 'QSFP-100G-4SAO10',
    estimatedCost: '$217.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40235',
    model: '2m (7ft) Fiber Patch Cable, SC UPC to SC UPC, Duplex, 2 Fibers, Single Mode (OS2',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2m (7ft) Fiber Patch Cable, SC UPC to SC UPC, Duplex, 2 Fibers, Single Mode (OS2), Riser (OFNR), 2.0mm, Tight-Buffered, Yellow',
    partNumber: '40235',
    estimatedCost: '$4.90',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40201',
    model: '7M LC/LC - SMF Fiber - Yellow',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '7M LC/LC - SMF Fiber - Yellow',
    partNumber: '40201',
    estimatedCost: '$6.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-88529',
    model: '25M LC/LC - SMF Fiber - Yellow',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '25M LC/LC - SMF Fiber - Yellow',
    partNumber: '88529',
    estimatedCost: '$13.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-88527',
    model: '.5M LC/LC - SMF Fiber - Yellow',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '.5M LC/LC - SMF Fiber - Yellow',
    partNumber: '88527',
    estimatedCost: '$4.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40491',
    model: 'OM3 50.125 MULTIMODE FIBER PATCH CABLE-2M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'OM3 50.125 MULTIMODE FIBER PATCH CABLE-2M',
    partNumber: '40491',
    estimatedCost: '$5.93',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40488',
    model: '9/125 SINGLE MODE FIBER PATCH CABLE-10M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '9/125 SINGLE MODE FIBER PATCH CABLE-10M',
    partNumber: '40488',
    estimatedCost: '$3.80',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-om5lcdx',
    model: 'OM4 50/125 Multimode Fiber patch cable - Make: FS',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'OM4 50/125 Multimode Fiber patch cable - Make: FS',
    partNumber: 'OM5LCDX',
    estimatedCost: '$30.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40193',
    model: 'LC/UPC-LC/UPC dia 3.0 duplex MM 50/125 OM3 3M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'LC/UPC-LC/UPC dia 3.0 duplex MM 50/125 OM3 3M',
    partNumber: '40193',
    estimatedCost: '$4.90',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc005',
    model: '.5 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '.5 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC005',
    estimatedCost: '$11.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc01',
    model: '1.0 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '1.0 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC01',
    estimatedCost: '$11.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc015',
    model: '1.5 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '1.5 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC015',
    estimatedCost: '$14.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc02',
    model: '2.0 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2.0 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC02',
    estimatedCost: '$14.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc025',
    model: '2.5 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2.5 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC025',
    estimatedCost: '$16.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc03',
    model: '3 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC03',
    estimatedCost: '$16.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc04',
    model: '4 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '4 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC04',
    estimatedCost: '$20.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-pc05',
    model: '5 meter 10G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '5 meter 10G Direct Attach Copper Cable',
    partNumber: 'SFP-10G-PC05',
    estimatedCost: '$20.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-pc005',
    model: '.5 meter 40G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '.5 meter 40G Direct Attach Copper Cable',
    partNumber: 'QSFP-PC005',
    estimatedCost: '$61.46',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-40g-pc06',
    model: '6 meter 40G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '6 meter 40G Direct Attach Copper Cable',
    partNumber: 'QSFP-40G-PC06',
    estimatedCost: '$95.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-pc07',
    model: '7 meter 40G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '7 meter 40G Direct Attach Copper Cable',
    partNumber: 'QSFP-PC07',
    estimatedCost: '$95.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-q56-pc005',
    model: '.5 meter 200G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '.5 meter 200G Direct Attach Copper Cable',
    partNumber: 'Q56-PC005',
    estimatedCost: '$80.31',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-q56-pc01',
    model: '1 meter 200G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '1 meter 200G Direct Attach Copper Cable',
    partNumber: 'Q56-PC01',
    estimatedCost: '$79.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-q56-pc02',
    model: '2 meter 200G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2 meter 200G Direct Attach Copper Cable',
    partNumber: 'Q56-PC02',
    estimatedCost: '$118.76',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-q56-pc03',
    model: '3 meter 200G Direct Attach Copper Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3 meter 200G Direct Attach Copper Cable',
    partNumber: 'Q56-PC03',
    estimatedCost: '$135.85',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-mcx455a-ecat',
    model: 'Mellanox MCX455A-ECAT ConnectX-4 EDR IB VPI Single-Port x16 PCIe 3.0 HCA',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'Mellanox MCX455A-ECAT ConnectX-4 EDR IB VPI Single-Port x16 PCIe 3.0 HCA',
    partNumber: 'MCX455A-ECAT',
    estimatedCost: '$410.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-axs13-192-10',
    model: 'AXS13-192-10 1310nm DFB 10Gigabit Transceiver',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'AXS13-192-10 1310nm DFB 10Gigabit Transceiver',
    partNumber: 'AXS13-192-10',
    estimatedCost: '$16.99',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-lr4-40g',
    model: '40GBASE-LR4 QSFP+ 1310nm 10km DOM Duplex LC/UPC SMF Optical Transceiver Module f',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '40GBASE-LR4 QSFP+ 1310nm 10km DOM Duplex LC/UPC SMF Optical Transceiver Module for FS Switches',
    partNumber: 'QSFP-LR4-40G',
    estimatedCost: '$309.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10gsr-85',
    model: '10g SFP+',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '10g SFP+',
    partNumber: 'SFP-10GSR-85',
    estimatedCost: '$26.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-10gsfp-lpm',
    model: '10g SFP+LPM',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '10g SFP+LPM',
    partNumber: '10GSFP-LPM',
    estimatedCost: '$16.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-sr',
    model: 'Cisco SFP-10G-SR-SFP+ Transceiver Module',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Cisco SFP-10G-SR-SFP+ Transceiver Module',
    partNumber: 'SFP-10G-SR',
    estimatedCost: '$20.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10ger-55',
    model: '10GBASE-ER SFP+ 1550nm 40km DOM Duplex LC/UPC SMF Optical Transceiver Module for',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '10GBASE-ER SFP+ 1550nm 40km DOM Duplex LC/UPC SMF Optical Transceiver Module for FS Switches',
    partNumber: 'SFP-10GER-55',
    estimatedCost: '$129.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-sr4-40g',
    model: '40g SR4 QSFP',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '40g SR4 QSFP',
    partNumber: 'QSFP-SR4-40G',
    estimatedCost: '$39.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-loop-40g',
    model: 'Cisco Compatible 40G QSFP+ Passive Loopback Testing Module',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Cisco Compatible 40G QSFP+ Passive Loopback Testing Module',
    partNumber: 'QSFP-LOOP-40G',
    estimatedCost: '$26.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-sfp10g-cvr',
    model: '40g CVR QSFP',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '40g CVR QSFP',
    partNumber: 'QSFP-SFP10G-CVR',
    estimatedCost: '$69.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-mam1q00a-qsa',
    model: 'NVIDIA/Mellanox MAM1Q00A-QSA Compatible QSFP+ 40G to SFP+ 10G Ethernet Adapter C',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'NVIDIA/Mellanox MAM1Q00A-QSA Compatible QSFP+ 40G to SFP+ 10G Ethernet Adapter Converter Module with DDMI',
    partNumber: 'MAM1Q00A-QSA',
    estimatedCost: '$76.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-loop-100g',
    model: '100G LB QSFP',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '100G LB QSFP',
    partNumber: 'SFP-LOOP-100G',
    estimatedCost: '$45.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-jnp-qsfp-4x10ge-lr',
    model: '4 x 10GBASE-LR QSFP+ 1310nm 10km DOM MPO-12/APC SMF Optical Transceiver Module',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '4 x 10GBASE-LR QSFP+ 1310nm 10km DOM MPO-12/APC SMF Optical Transceiver Module',
    partNumber: 'JNP-QSFP-4X10GE-LR',
    estimatedCost: '$359.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-gb-ge-t',
    model: '1000Base-T SFP RJ45 1GT RJ45',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '1000Base-T SFP RJ45 1GT RJ45',
    partNumber: 'SFP-GB-GE-T',
    estimatedCost: '$28.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-10g-t-100',
    model: '10G SFP+ Copper-T RJ45',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '10G SFP+ Copper-T RJ45',
    partNumber: 'SFP-10G-T-100',
    estimatedCost: '$139.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-4m-12fsm-pff-b',
    model: '4M MPO - MM Fiber - Pink',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '4M MPO - MM Fiber - Pink',
    partNumber: '4M-12FSM-PFF-B',
    estimatedCost: '$99.09',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-c6p-u24ft1u',
    model: '1U PATCH PANELS',
    manufacturer: 'FS.com',
    category: 'other',
    description: '1U PATCH PANELS',
    partNumber: 'C6P-U24FT1U',
    estimatedCost: '$65.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-dd-400g-dr4-m',
    model: 'PROFICIUM 400G OPTIC',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'PROFICIUM 400G OPTIC',
    partNumber: 'QSFP-DD-400G-DR4-M',
    estimatedCost: '$695.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-1m-8fsm-pf8',
    model: '1m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '1m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '68048',
    estimatedCost: '$57.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-2m-8fsm-pf8',
    model: '2m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '69021',
    estimatedCost: '$58.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-5m-8fsm-pf8',
    model: '5m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '5m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '6806',
    estimatedCost: '$63.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-6m-8fsm-pf8',
    model: '6m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '6m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '8FMTPLCSMF',
    estimatedCost: '$62.40',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-3m-8fsm-pf8',
    model: '3m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '68054',
    estimatedCost: '$59.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-25m-8fsm-pf8',
    model: '25m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '25m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '25M-8FSM-PF8',
    estimatedCost: '$81.66',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-38m-8fsm-pf8',
    model: '38m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '38m MTP Harness, MTP-8 APC to 4 LC UPC Duplex, 8 Fibers, Single Mode',
    partNumber: '68054',
    estimatedCost: '$89.24',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-base-1g-lr',
    model: 'Transceiver SFP 1000Base BX-U (Tx1490nm/Rx1310nm, SMF, 10km, LC, DOM)',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Transceiver SFP 1000Base BX-U (Tx1490nm/Rx1310nm, SMF, 10km, LC, DOM)',
    partNumber: 'SFP-BASE-1G-LR',
    estimatedCost: '$44.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-base-10g-lr',
    model: 'EX-SFP-10GE-LR-LU SFP+ 10GBase-LR 10 Gigabit Ethernet Optics, 1310nm for 10km tr',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'EX-SFP-10GE-LR-LU SFP+ 10GBase-LR 10 Gigabit Ethernet Optics, 1310nm for 10km transmission on SMF (Juniper/Arista/Mellanox Cumulus Compatible)',
    partNumber: 'SFP-BASE-10G-LR',
    estimatedCost: '$300.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-mcx623106ac-cdat',
    model: 'Mellanox MCX516A-CCAT ConnectX-5 EN Network Interface Card, 100GbE Dual-Port QSF',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'Mellanox MCX516A-CCAT ConnectX-5 EN Network Interface Card, 100GbE Dual-Port QSFP28, PCIe3.0 x 16',
    partNumber: 'MCX623106AC-CDAT',
    estimatedCost: '$669.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-88528',
    model: 'FS OS2 9/125 SINGLEMODE 1.5M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE 1.5M',
    partNumber: '88528',
    estimatedCost: '$4.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40191',
    model: 'FS OS2 9/125 SINGLEMODE 1M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE 1M',
    partNumber: '40191',
    estimatedCost: '$4.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-50147',
    model: 'FS OS2 9/125 SINGLEMODE 2.5M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE 2.5M',
    partNumber: '50147',
    estimatedCost: '$4.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40199',
    model: 'FS OS2 9/125 SINGLEMODE 4M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE 4M',
    partNumber: '40199',
    estimatedCost: '$5.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-402',
    model: 'FS OS2 9/125 SINGLEMODE 5M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE 5M',
    partNumber: '402',
    estimatedCost: '$5.70',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40202',
    model: 'FS OS2 9/125 SINGLEMODE 8M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE 8M',
    partNumber: '40202',
    estimatedCost: '$6.70',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40203',
    model: 'FS OS2 9/125 SINGLEMODE10M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE10M',
    partNumber: '40203',
    estimatedCost: '$6.90',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40204',
    model: 'FS OS2 9/125 SINGLEMODE15M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE15M',
    partNumber: '40204',
    estimatedCost: '$9.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40205',
    model: 'FS OS2 9/125 SINGLEMODE20M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE20M',
    partNumber: '40205',
    estimatedCost: '$11.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-74192',
    model: 'FS OS2 9/125 SINGLEMODE40M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLEMODE40M',
    partNumber: '74192',
    estimatedCost: '$13.67',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-68047',
    model: 'FS MTP(F)-MTP(M)/OM4/1M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/1M-Type B',
    partNumber: '68047',
    estimatedCost: '$43.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-69022',
    model: 'FS MTP(F)-MTP(M)/OM4/2M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/2M-Type B',
    partNumber: '69022',
    estimatedCost: '$49.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-68053',
    model: 'FS MTP(F)-MTP(M)/OM4/3M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/3M-Type B',
    partNumber: '68053',
    estimatedCost: '$59.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-74299',
    model: 'FS MTP(F)-MTP(M)/OM4/4M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/4M-Type B',
    partNumber: '74299',
    estimatedCost: '$66.56',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-68059',
    model: 'FS MTP(F)-MTP(M)/OM4/5M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/5M-Type B',
    partNumber: '68059',
    estimatedCost: '$72.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-74297',
    model: 'FS MTP(F)-MTP(M)/OM4/6M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/6M-Type B',
    partNumber: '74297',
    estimatedCost: '$77.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-74298',
    model: 'FS MTP(F)-MTP(M)/OM4/7M-Type B',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS MTP(F)-MTP(M)/OM4/7M-Type B',
    partNumber: '74298',
    estimatedCost: '$83.12',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-40206',
    model: 'FS OS2 9/125 SINGLE MODE 30M',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'FS OS2 9/125 SINGLE MODE 30M',
    partNumber: '40206',
    estimatedCost: '$14.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-9785',
    model: '100GBASE-FR QSFP28 Single 1310nm 2km DOM Duplex LC/UPC SMF Optical Transceiver M',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '100GBASE-FR QSFP28 Single 1310nm 2km DOM Duplex LC/UPC SMF Optical Transceiver Module',
    partNumber: '9785',
    estimatedCost: '$339.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-17807',
    model: '100G to SFP28 25G Adapter Converter Module with DDMI for FS Switches',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '100G to SFP28 25G Adapter Converter Module with DDMI for FS Switches',
    partNumber: '17807',
    estimatedCost: '$28.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp28-ir4-100g',
    model: '100G CWLR QSFP TRANSCEIVER',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '100G CWLR QSFP TRANSCEIVER',
    partNumber: 'QSFP28-IR4-100G',
    estimatedCost: '$189.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-75794',
    model: 'SFP 1310nm 2km DOM Duplex LC/UPC SMF/MMF Optical Transceiver Module',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'SFP 1310nm 2km DOM Duplex LC/UPC SMF/MMF Optical Transceiver Module',
    partNumber: '75794',
    estimatedCost: '$13.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-fhu-fpp48flcsmf',
    model: 'FHU 1U 19\'\' Fiber Adapter Panel, 48 Fibers OS2 Single Mode',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'FHU 1U 19\'\' Fiber Adapter Panel, 48 Fibers OS2 Single Mode',
    partNumber: 'FHU-FPP48FLCSMF',
    estimatedCost: '$62.00',
    specs: 'Equipment | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp-25g-sr-m',
    model: '25GBASE SR SFP28 MMF Optical Transceiver',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '25GBASE SR SFP28 MMF Optical Transceiver',
    partNumber: 'SFP-25G-SR-M',
    estimatedCost: '$62.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp28-blr4-100g',
    model: '100Gbps QSFP28 LR4 Transceiver, Single Mode, 10kmReach',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '100Gbps QSFP28 LR4 Transceiver, Single Mode, 10kmReach',
    partNumber: 'QSFP28-BLR4-100G',
    estimatedCost: '$439.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-fr4-400g',
    model: '400GBASE-FR4 QSFP-DD PAM4 1310nm 2km DOM Duplex LC/UPC SMF Optical Transceiver M',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: '400GBASE-FR4 QSFP-DD PAM4 1310nm 2km DOM Duplex LC/UPC SMF Optical Transceiver Module for FS Switches',
    partNumber: 'QDD-FR4-400G',
    estimatedCost: '$719.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-cmh-sfd1u',
    model: 'Horizontal Single Sided Manager, 1RU, Finger Duct with Cover, 3.43 in. Depth',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'Horizontal Single Sided Manager, 1RU, Finger Duct with Cover, 3.43 in. Depth',
    partNumber: 'CMH-SFD1U',
    estimatedCost: '$18.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-mfa1a00-c030',
    model: '30m (98ft) NVIDIA/Mellanox Compatible 100G QSFP28 Ethernet Active Optical Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '30m (98ft) NVIDIA/Mellanox Compatible 100G QSFP28 Ethernet Active Optical Cable',
    partNumber: 'MFA1A00-C030',
    estimatedCost: '$271.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-lr4-100g',
    model: 'Cisco QSFP-100G-LR4-S Compatible 100GBASE-LR4 QSFP28 1310nm 10km DOM Duplex LC/U',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Cisco QSFP-100G-LR4-S Compatible 100GBASE-LR4 QSFP28 1310nm 10km DOM Duplex LC/UPC SMF Optical Transceiver Module',
    partNumber: 'QSFP-LR4-100G',
    estimatedCost: '$499.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-ao15',
    model: '15m (49ft) Dell (DE) AOC-QSFP28-100G-15M Compatible 100G QSFP28 Active Optical C',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '15m (49ft) Dell (DE) AOC-QSFP28-100G-15M Compatible 100G QSFP28 Active Optical Cable',
    partNumber: 'QSFP-100G-AO15',
    estimatedCost: '$234.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-ao20',
    model: '20m (66ft) Dell (DE) AOC-QSFP28-100G-20M Compatible 100G QSFP28 Active Optical C',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '20m (66ft) Dell (DE) AOC-QSFP28-100G-20M Compatible 100G QSFP28 Active Optical Cable',
    partNumber: 'QSFP-100G-AO20',
    estimatedCost: '$246.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-ao30',
    model: '30m (98ft) Generic Compatible 100G QSFP28 Active Optical Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '30m (98ft) Generic Compatible 100G QSFP28 Active Optical Cable',
    partNumber: 'QSFP-100G-AO30',
    estimatedCost: '$271.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-200g-ao30',
    model: '30m (98ft) Generic Compatible 200G QSFP56 Active Optical Cable',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '30m (98ft) Generic Compatible 200G QSFP56 Active Optical Cable',
    partNumber: 'QSFP-200G-AO30',
    estimatedCost: '$271.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-200g-2q4xnpc02',
    model: '2m (7ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Passive Direct Attac',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2m (7ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Passive Direct Attach Copper Breakout Cable',
    partNumber: 'QDD-200G-2Q4xNPC02',
    estimatedCost: '$269.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-200g-2q4xnpc03',
    model: '3m (10ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Passive Direct Atta',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m (10ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Passive Direct Attach Copper Breakout Cable',
    partNumber: 'QDD-200G-2Q4xNPC03',
    estimatedCost: '$349.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-4spc03',
    model: '3m (10ft) Arista Networks CAB-Q-4S-100G-3M Compatible 100G QSFP28 to 4 x 25G SFP',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m (10ft) Arista Networks CAB-Q-4S-100G-3M Compatible 100G QSFP28 to 4 x 25G SFP28 Passive Direct Attach Copper Breakout Cable',
    partNumber: 'QSFP-100G-4SPC03',
    estimatedCost: '$136.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-ao05',
    model: '5m (16ft) Juniper Networks JNP-QSFP28-AOC-5M Compatible 100G QSFP28 Active Optic',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '5m (16ft) Juniper Networks JNP-QSFP28-AOC-5M Compatible 100G QSFP28 Active Optical Cable',
    partNumber: 'QSFP-100G-AO05',
    estimatedCost: '$209.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-200g-2q4xnao05',
    model: '5m (16ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Active Optical Brea',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '5m (16ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Active Optical Breakout Cable',
    partNumber: 'QDD-200G-2Q4xNAO05',
    estimatedCost: '$479.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-200g-2q4xnao07',
    model: '7m (23ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Active Optical Brea',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '7m (23ft) Generic Compatible 200G QSFP-DD to 2 x 100G QSFP28 Active Optical Breakout Cable',
    partNumber: 'QDD-200G-2Q4xNAO07',
    estimatedCost: '$489.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-100g-ao03',
    model: '3m (10ft) NVIDIA/Mellanox MFA1A00-C003 Compatible 100G QSFP28 Ethernet Active Op',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m (10ft) NVIDIA/Mellanox MFA1A00-C003 Compatible 100G QSFP28 Ethernet Active Optical Cable',
    partNumber: 'QSFP-100G-AO03',
    estimatedCost: '$204.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-41728',
    model: '3m (10ft) Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Multimode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m (10ft) Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Multimode (OM3), Riser (OFNR), 2.0mm, Tight-Buffered, Aqua',
    partNumber: '41728',
    estimatedCost: '$7.10',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-41737',
    model: '7m (23ft) Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Multimode',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '7m (23ft) Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Multimode (OM3), Riser (OFNR), 2.0mm, Tight-Buffered, Aqua',
    partNumber: '41737',
    estimatedCost: '$9.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-41735',
    model: '15m (49ft) Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Multimod',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '15m (49ft) Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Multimode (OM3), Riser (OFNR), 2.0mm, Tight-Buffered, Aqua',
    partNumber: '41735',
    estimatedCost: '$14.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-400g-2qac03',
    model: '3m (10ft) 400G QSFP-DD to 2 x 200G QSFP56 Active Direct Attach Copper Breakout C',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m (10ft) 400G QSFP-DD to 2 x 200G QSFP56 Active Direct Attach Copper Breakout Cable for FS Switches',
    partNumber: 'QDD-400G-2QAC03',
    estimatedCost: '$549.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-400g-2qac05',
    model: '5m (16ft) 400G QSFP-DD to 2 x 200G QSFP56 Active Direct Attach Copper Breakout C',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '5m (16ft) 400G QSFP-DD to 2 x 200G QSFP56 Active Direct Attach Copper Breakout Cable for FS Switches',
    partNumber: 'QDD-400G-2QAC05',
    estimatedCost: '$609.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp-200g-ac07',
    model: '7m (23ft) NVIDIA/Mellanox MCA1J00-H007E Compatible 200G QSFP56 InfiniBand HDR Ac',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '7m (23ft) NVIDIA/Mellanox MCA1J00-H007E Compatible 200G QSFP56 InfiniBand HDR Active Direct Attach Copper Twinax Cable for Quantum Switches and ConnectX-6 HCA',
    partNumber: 'QSFP-200G-AC07',
    estimatedCost: '$325.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-smlcsx',
    model: '0.5m (1.6ft) Fiber Patch Cable, 1 Fiber, LC UPC Simplex to LC UPC Simplex, Singl',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '0.5m (1.6ft) Fiber Patch Cable, 1 Fiber, LC UPC Simplex to LC UPC Simplex, Single Mode (OS2), Riser (OFNR), 2.0mm, Tight-Buffered, Yellow',
    partNumber: 'SMLCSX',
    estimatedCost: '$3.27',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-om3xxsx',
    model: 'Customized OM3 Multimode LC/SC/FC/ST/LSH/MU Simplex Fiber Patch Cabl',
    manufacturer: 'FS.com',
    category: 'cable',
    description: 'Customized OM3 Multimode LC/SC/FC/ST/LSH/MU Simplex Fiber Patch Cabl',
    partNumber: 'OM3XXSX',
    estimatedCost: '$3.15',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qsfp28-fr-100g',
    model: 'FS for Mellanox Compatible 100GBASE-FR QSFP28 Single Lambda 1310nm 2km DOM Duple',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'FS for Mellanox Compatible 100GBASE-FR QSFP28 Single Lambda 1310nm 2km DOM Duplex LC SMF Optical Transceiver Module',
    partNumber: 'QSFP28-FR-100G',
    estimatedCost: '$339.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-sfp1g-sx-31',
    model: 'Arista Networks SFP-1G-SX-2 Compatible 1000BASE-SX SFP 1310nm 2km DOM Duplex LC',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Arista Networks SFP-1G-SX-2 Compatible 1000BASE-SX SFP 1310nm 2km DOM Duplex LC MMF Transceiver Module',
    partNumber: 'SFP1G-SX-31',
    estimatedCost: '$130.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-pc14c15-15a',
    model: '6ft (1.8m) IEC60320 C14 to IEC60320 C15 14AWG 250V/15A Power Cord, Black',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '6ft (1.8m) IEC60320 C14 to IEC60320 C15 14AWG 250V/15A Power Cord, Black',
    partNumber: 'PC14C15-15A',
    estimatedCost: '$14.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-qdd-dr4-400g',
    model: 'Cisco QDD-400G-DR4-S Compatible 400GBASE-DR4 QSFP-DD PAM4 1310nm 500m DOM MPO-12',
    manufacturer: 'FS.com',
    category: 'transceiver',
    description: 'Cisco QDD-400G-DR4-S Compatible 400GBASE-DR4 QSFP-DD PAM4 1310nm 500m DOM MPO-12/APC SMF Optical Transceiver Module',
    partNumber: 'QDD-DR4-400G',
    estimatedCost: '$549.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-300382',
    model: '2m Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Single Mode (OS2',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '2m Fiber Patch Cable, 2 Fibers, LC UPC Duplex to LC UPC Duplex, Single Mode (OS2), Plenum (OFNP), 1.6mm, Tight-Buffered, Yellow',
    partNumber: '300382',
    estimatedCost: '$5.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-168012',
    model: '3m Flat Cat6 32AWG Snagless Unshielded (UTP) PVC Ethernet Network Patch Cable, W',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '3m Flat Cat6 32AWG Snagless Unshielded (UTP) PVC Ethernet Network Patch Cable, White',
    partNumber: '168012',
    estimatedCost: '$4.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-69127',
    model: '1.2 meter C14 to C13 16AWG 250V/13A Power Extension Cord, Black',
    manufacturer: 'FS.com',
    category: 'cable',
    description: '1.2 meter C14 to C13 16AWG 250V/13A Power Extension Cord, Black',
    partNumber: '69127',
    estimatedCost: '$5.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["fsCom"],
  },
  {
    id: 'fscom-383219',
    model: 'Mounting brackets for Mini Media Converter Chassis (40pcs/Pack)',
    manufacturer: 'FS.com',
    category: 'other',
    description: 'Mounting brackets for Mini Media Converter Chassis (40pcs/Pack)',
    partNumber: '383219',
    estimatedCost: '$0.00',
    specs: 'Consumables and Misc.',
    vendorIds: ["fsCom"],
  },
];

export default fsComCatalog;
