import type { CatalogItem } from './types';

const hpeCatalog: CatalogItem[] = [
  {
    id: 'hpe-cpu-hpe-01',
    model: 'DL360 Gen10 Plus 2 x Intel 6342 12 x 32GB DDR4 3200 3 x HPE PM1735 6.4T 3 x HPE',
    manufacturer: 'HPE',
    category: 'server',
    description: 'DL360 Gen10 Plus 2 x Intel 6342 12 x 32GB DDR4 3200 3 x HPE PM1735 6.4T 3 x HPE IB HDR100G 1P',
    partNumber: 'CPU-HPE-01',
    estimatedCost: '$9,100.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-cpu-hpe-03',
    model: 'DL360 Gen10 Plus 2 x Intel 6342 12 x 32GB DDR4 3200 3 x HPE PM1735 6.4T 1 x 900-',
    manufacturer: 'HPE',
    category: 'server',
    description: 'DL360 Gen10 Plus 2 x Intel 6342 12 x 32GB DDR4 3200 3 x HPE PM1735 6.4T 1 x 900-9D3B6-00CV-AA0',
    partNumber: 'CPU-HPE-03',
    estimatedCost: '$9,100.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-dl325',
    model: 'HPE ProLiant DL325 Gen10 AMD EPYC 7xx2 2933 Memory DIMMs with capacity upto 128',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE ProLiant DL325 Gen10 AMD EPYC 7xx2 2933 Memory DIMMs with capacity upto 128 GB 8 SFF with optional Optical Drive, 2 SFF SAS/SATA or 2 NVMe drive bay options',
    partNumber: 'DL325',
    estimatedCost: '$1,727.15',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-dl325-v2',
    model: 'HPE ProLiant DL325 Gen10 Plus v2 AMD EPYC 7443P 24-Core (2.85GHz 128MB) 32GB (1',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE ProLiant DL325 Gen10 Plus v2 AMD EPYC 7443P 24-Core (2.85GHz 128MB) 32GB (1 x 32GB) PC4-3200AA-R RDIMM 8 x Hot Plug 2.5in Small Form Factor Dynamic Smart Array P408i-a No Optical 800W Server',
    partNumber: 'DL325 V2',
    estimatedCost: '$3,434.11',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-dl360',
    model: 'HP DL360 G9 8 Bay Server 2x E5-2696v4 44c/88t 192GB DDR4 R-Memory (6x 32) 1x 1TB',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HP DL360 G9 8 Bay Server 2x E5-2696v4 44c/88t 192GB DDR4 R-Memory (6x 32) 1x 1TB SSD 2x 10G Ports 560sfp Intel card Rail Kit Included',
    partNumber: 'DL360',
    estimatedCost: '$1,073.74',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p21674-001',
    model: 'HPE 32-GB (1 x 32GB) Dual Rank x4 DDR4-3200',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE 32-GB (1 x 32GB) Dual Rank x4 DDR4-3200',
    partNumber: 'P21674-001',
    estimatedCost: '$195.95',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-869821-001',
    model: 'DL380 G10 Server GPU PCIe Riser Power Cable',
    manufacturer: 'HPE',
    category: 'cable',
    description: 'DL380 G10 Server GPU PCIe Riser Power Cable',
    partNumber: '869821-001',
    estimatedCost: '$46.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-869686-001',
    model: 'HP GPU Power Cable 6 Pin Male to 8 Pin PCI-E Riser male',
    manufacturer: 'HPE',
    category: 'cable',
    description: 'HP GPU Power Cable 6 Pin Male to 8 Pin PCI-E Riser male',
    partNumber: '869686-001',
    estimatedCost: '$64.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p21841-005',
    model: 'HP 12.8TB NVMe U.3',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HP 12.8TB NVMe U.3',
    partNumber: 'P21841-005',
    estimatedCost: '$1,456.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-d9n54a',
    model: 'HP 17.3kVA 208 V Three Phase 27 Outlet NA/JP Monitored Power Distribution Unit',
    manufacturer: 'HPE',
    category: 'pdu',
    description: 'HP 17.3kVA 208 V Three Phase 27 Outlet NA/JP Monitored Power Distribution Unit',
    partNumber: 'D9N54A',
    estimatedCost: '$358.70',
    specs: 'PDUs | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-865412-102',
    model: 'HPE 865412-102 800W Flex Slot Platinum Hot Plug Power Supply Kit',
    manufacturer: 'HPE',
    category: 'other',
    description: 'HPE 865412-102 800W Flex Slot Platinum Hot Plug Power Supply Kit',
    partNumber: '865412-102',
    estimatedCost: '$140.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p23665-h21',
    model: 'HPE InfiniBand HDR100/Ethernet 100Gb 1‑port QSFP56 PCIe4 x16 MCX653105A‑ECAT Ada',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE InfiniBand HDR100/Ethernet 100Gb 1‑port QSFP56 PCIe4 x16 MCX653105A‑ECAT Adapter',
    partNumber: 'P23665-H21',
    estimatedCost: '$470.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p26469-b21',
    model: 'HPE ProLiant DL36X Gen10 Plus CPU1 GPU Cable Kit',
    manufacturer: 'HPE',
    category: 'cable',
    description: 'HPE ProLiant DL36X Gen10 Plus CPU1 GPU Cable Kit',
    partNumber: 'P26469-B21',
    estimatedCost: '$54.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p26485-b21',
    model: 'HPE P26485-B21 DL300 Gen10 Plus 1U SFF Easy Install Rail Kit',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE P26485-B21 DL300 Gen10 Plus 1U SFF Easy Install Rail Kit',
    partNumber: 'P26485-B21',
    estimatedCost: '$210.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p40572-b21',
    model: 'HPE 6.4TB NVMe Gen4 High Performance Mixed Use SFF BC U.3 PM1735 SSD',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE 6.4TB NVMe Gen4 High Performance Mixed Use SFF BC U.3 PM1735 SSD',
    partNumber: 'P40572-B21',
    estimatedCost: '',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p13657-002',
    model: 'HPE MK000960GWXFH 960GB, Internal, 2.5 inch Solid State Drive - Gray',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE MK000960GWXFH 960GB, Internal, 2.5 inch Solid State Drive - Gray',
    partNumber: 'MK000960GWXFH',
    estimatedCost: '$354.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p11338-b21',
    model: 'HPE 548SFP+ PCIe 3.0 x8 10 Gigabit SFP+ x 2 Network Adapter',
    manufacturer: 'HPE',
    category: 'server',
    description: 'HPE 548SFP+ PCIe 3.0 x8 10 Gigabit SFP+ x 2 Network Adapter',
    partNumber: 'P11338-B21',
    estimatedCost: '$125.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-455888-001',
    model: 'HPE BladeSystem c-Class 10Gb SFP+ Long Range Transceiver',
    manufacturer: 'HPE',
    category: 'transceiver',
    description: 'HPE BladeSystem c-Class 10Gb SFP+ Long Range Transceiver',
    partNumber: '455888-001',
    estimatedCost: '$151.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-dps-2000ab-29d',
    model: 'HP 2000-Watts 48V Power Supply for AlphaServer GS1280',
    manufacturer: 'HPE',
    category: 'other',
    description: 'HP 2000-Watts 48V Power Supply for AlphaServer GS1280',
    partNumber: 'DPS-2000AB-29D',
    estimatedCost: '$154.85',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p20503-001',
    model: '32GB PC4-25600 DDR4-3200MT/s 2Rx4 ECC Memory',
    manufacturer: 'HPE',
    category: 'server',
    description: '32GB PC4-25600 DDR4-3200MT/s 2Rx4 ECC Memory',
    partNumber: 'P20503-001',
    estimatedCost: '$105.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-pc5-4800b',
    model: 'Micron 4800Mhz 64GB RAM DDR5 RDIMM 2Rx4 REG ECC Sever Memory',
    manufacturer: 'HPE',
    category: 'server',
    description: 'Micron 4800Mhz 64GB RAM DDR5 RDIMM 2Rx4 REG ECC Sever Memory',
    partNumber: 'PC5-4800B',
    estimatedCost: '$360.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-dps-3000ab-25',
    model: 'HPE Cray DPS-3000AB-25 - Power supply - 80 PLUS Titanium - 3000 Watt',
    manufacturer: 'HPE',
    category: 'other',
    description: 'HPE Cray DPS-3000AB-25 - Power supply - 80 PLUS Titanium - 3000 Watt',
    partNumber: 'DPS-3000AB-25',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-p48132-001',
    model: 'Hpe 960GB Sata-6Gbps MIXED USE 2.5Inch PM897 SSD-F/S',
    manufacturer: 'HPE',
    category: 'server',
    description: 'Hpe 960GB Sata-6Gbps MIXED USE 2.5Inch PM897 SSD-F/S',
    partNumber: 'P48132-001',
    estimatedCost: '$270.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-s4b20a-aba',
    model: 'CH - CX 8325H-18Y4C - 1U - WIRED - 100GBPS - 2 11,154.07 Y 22,308.14 GIGABIT E',
    manufacturer: 'HPE',
    category: 'switch',
    description: 'CH - CX 8325H-18Y4C - 1U - WIRED - 100GBPS - 2 11,154.07 Y 22,308.14 GIGABIT ETHERNET - 32GB RAM - 128GB SSD - 100-240 VAC, 50-60 HZ - SFP28',
    partNumber: 'S4B20A#ABA',
    estimatedCost: '$11,154.07',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-h06mje',
    model: 'RUBA NETWORKING FOUNDATIONAL CARE 3 YEAR NBD EXCH HW ONLY 8325H SW SVC',
    manufacturer: 'HPE',
    category: 'other',
    description: 'RUBA NETWORKING FOUNDATIONAL CARE 3 YEAR NBD EXCH HW ONLY 8325H SW SVC',
    partNumber: 'H06MJE',
    estimatedCost: '$953.37',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-r0z25a',
    model: 'DIRECT ATTACH CABLE - MALE LEFT GEND RIGHT GENDER - QSFP28 RIGHT CONNECTOR - QSF',
    manufacturer: 'HPE',
    category: 'cable',
    description: 'DIRECT ATTACH CABLE - MALE LEFT GEND RIGHT GENDER - QSFP28 RIGHT CONNECTOR - QSFP28 LEFT CONNECTOR - 1M LENGTH',
    partNumber: 'R0Z25A',
    estimatedCost: '$221.89',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-s2t43a',
    model: 'PE ARUBA NETWORKING 8325H 4-POST RACK MOUNT KIT - S2T43A',
    manufacturer: 'HPE',
    category: 'other',
    description: 'PE ARUBA NETWORKING 8325H 4-POST RACK MOUNT KIT - S2T43A',
    partNumber: 'S2T43A',
    estimatedCost: '$554.88',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-j9583b',
    model: 'ARUBA NETWORKING X414 1U UNIVERSAL 4POST RACK MOUNT KIT',
    manufacturer: 'HPE',
    category: 'other',
    description: 'ARUBA NETWORKING X414 1U UNIVERSAL 4POST RACK MOUNT KIT',
    partNumber: 'J9583B',
    estimatedCost: '$117.59',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-r6u89aae',
    model: 'A CENTRAL ON-PREMISES 8XXX SWITCH FOUNDATION 3 YEAR SUBSCRIPTION E-STU',
    manufacturer: 'HPE',
    category: 'other',
    description: 'A CENTRAL ON-PREMISES 8XXX SWITCH FOUNDATION 3 YEAR SUBSCRIPTION E-STU',
    partNumber: 'R6U89AAE',
    estimatedCost: '$1,567.28',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-jl661a',
    model: 'A CX 6300 SWITCH SERIES - QUAD CORE ARM CORTEX A72 1.8GHZ - 8 GB DDR4 32 GB EMMC',
    manufacturer: 'HPE',
    category: 'switch',
    description: 'A CX 6300 SWITCH SERIES - QUAD CORE ARM CORTEX A72 1.8GHZ - 8 GB DDR4 32 GB EMMC 8 MB SHARED PACKET BUFFER MEMORY',
    partNumber: 'JL661A',
    estimatedCost: '$5,343.38',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-hr4z0e',
    model: 'A 3 YEAR FOUNDATION CARE NEXT BUSINESS DAY EXCHANGE HARDWARE ONLY 6300M 48 POE',
    manufacturer: 'HPE',
    category: 'other',
    description: 'A 3 YEAR FOUNDATION CARE NEXT BUSINESS DAY EXCHANGE HARDWARE ONLY 6300M 48 POE SWITCH SERVICE - FOUNDATION CARE - HA',
    partNumber: 'HR4Z0E',
    estimatedCost: '$462.89',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-jl087a-aba',
    model: 'ARUBA NETWORKING X372 54VDC 1050W 110240VAC POWER SUPPLY, DIMENSIONS: 8.31 X 22.',
    manufacturer: 'HPE',
    category: 'other',
    description: 'ARUBA NETWORKING X372 54VDC 1050W 110240VAC POWER SUPPLY, DIMENSIONS: 8.31 X 22.56 X 4.01 CM (3.27 X 8.88 X 1.58 IN)',
    partNumber: 'JL087A#ABA',
    estimatedCost: '$606.72',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-jl669b',
    model: 'ARUBA NETWORKING X751 FRONT TO BACK FAN TRAY - FOR USE IN SELECT HPE ARUBA NETWO',
    manufacturer: 'HPE',
    category: 'other',
    description: 'ARUBA NETWORKING X751 FRONT TO BACK FAN TRAY - FOR USE IN SELECT HPE ARUBA NETWORKING PRODUCTS - WEIGHT: 208.7 GM (',
    partNumber: 'JL669B',
    estimatedCost: '$262.71',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-jl488a',
    model: 'HPE DIRECT ATTACH CABLE - MALE LEFT GENDER MALE RIGHT GENDER - SFP28 RIGHT CONNE',
    manufacturer: 'HPE',
    category: 'cable',
    description: 'HPE DIRECT ATTACH CABLE - MALE LEFT GENDER MALE RIGHT GENDER - SFP28 RIGHT CONNECTOR - SFP28 LEFT CONNECTOR - 3M LENGT',
    partNumber: 'JL488A',
    estimatedCost: '$168.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-r6u84aae',
    model: 'ARUBA CENTRAL ON-PREMISES 63XX OR 38XX SWITCH FOUNDATION 3 YEAR SUBSCRIPTION E-S',
    manufacturer: 'HPE',
    category: 'other',
    description: 'ARUBA CENTRAL ON-PREMISES 63XX OR 38XX SWITCH FOUNDATION 3 YEAR SUBSCRIPTION E-STU',
    partNumber: 'R6U84AAE',
    estimatedCost: '$556.13',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-juniper-ptx10008-bundle',
    model: '8xPTX10008-PREM5+8xJUNOS-EVO-64+8xJNP10K-RE2-E 128-R+192xCBL-PWRC21-C20-NA+32xPT',
    manufacturer: 'HPE',
    category: 'switch',
    description: '8xPTX10008-PREM5+8xJUNOS-EVO-64+8xJNP10K-RE2-E 128-R+192xCBL-PWRC21-C20-NA+32xPTX10K-LC1301-36 DD+256xQDD-2X400G',
    partNumber: 'Juniper PTX1008 Bundle',
    estimatedCost: '$2,857,669.20',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-qdd-2x400g-lr4-10',
    model: 'QSFP-DD800 2X400G LR4 TRANS KM STD TEMPERATURE',
    manufacturer: 'HPE',
    category: 'transceiver',
    description: 'QSFP-DD800 2X400G LR4 TRANS KM STD TEMPERATURE',
    partNumber: 'QDD-2X400G-LR4-10',
    estimatedCost: '$1,759.30',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-jnp10k-re2-e128-r',
    model: '128G TPM 2.0 with EVO / redundant',
    manufacturer: 'HPE',
    category: 'switch',
    description: '128G TPM 2.0 with EVO / redundant',
    partNumber: 'JNP10K-RE2-E128-R',
    estimatedCost: '$1,153.85',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-qdd-2x400g-fr4-p',
    model: 'PER QSFP-DD 2X400G FR4 TRANSCEIVER, 2 LC-DUP',
    manufacturer: 'HPE',
    category: 'transceiver',
    description: 'PER QSFP-DD 2X400G FR4 TRANSCEIVER, 2 LC-DUP',
    partNumber: 'QDD-2X400G-FR4-P',
    estimatedCost: '$810.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-qdd-2x400g-lr4-p',
    model: 'PER QSFP-DD 2X400G LR4 TRANSCEIVER, 2 LC-DUP',
    manufacturer: 'HPE',
    category: 'transceiver',
    description: 'PER QSFP-DD 2X400G LR4 TRANSCEIVER, 2 LC-DUP',
    partNumber: 'QDD-2X400G-LR4-P',
    estimatedCost: '$1,759.30',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-s-ptx800gmsec-p',
    model: 'SW PTX800G MACSEC 800G W/O CS PRPL',
    manufacturer: 'HPE',
    category: 'other',
    description: 'SW PTX800G MACSEC 800G W/O CS PRPL',
    partNumber: 'S-PTX800GMSEC-P',
    estimatedCost: '$146.59',
    specs: 'License | UOM: Eaches',
    vendorIds: ["hpe"],
  },
  {
    id: 'hpe-svc-cor-ptx800gmsc',
    model: 'JNPR CARE CORE SUPT S-PTX800GMSEC-P - 1 YEAR',
    manufacturer: 'HPE',
    category: 'other',
    description: 'JNPR CARE CORE SUPT S-PTX800GMSEC-P - 1 YEAR',
    partNumber: 'SVC-COR-PTX800GMSC',
    estimatedCost: '$17.01',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["hpe"],
  },
];

export default hpeCatalog;
