import type { CatalogItem } from './types';

const intelCatalog: CatalogItem[] = [
  {
    id: 'intel-x520-da2',
    model: 'Intel X520-DA2 Ethernet Converged Network Adapter X520-DA2',
    manufacturer: 'Intel',
    category: 'other',
    description: 'Intel X520-DA2 Ethernet Converged Network Adapter X520-DA2',
    partNumber: 'X520-DA2',
    estimatedCost: '$43.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-d5-p5316-15-36tb',
    model: 'INTEL SSD D5-P5316 SERIES 2.5 15.36 TB',
    manufacturer: 'Intel',
    category: 'server',
    description: 'INTEL SSD D5-P5316 SERIES 2.5 15.36 TB',
    partNumber: 'D5-P5316 15.36TB',
    estimatedCost: '$1,800.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-d5-p5316-30-72tb',
    model: 'INTEL SSD D5-P5316 SERIES 2.5 30.72 TB',
    manufacturer: 'Intel',
    category: 'server',
    description: 'INTEL SSD D5-P5316 SERIES 2.5 30.72 TB',
    partNumber: 'D5-P5316 30.72TB',
    estimatedCost: '$3,050.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-ssdpf2kx076t1os',
    model: 'Intel Hard Drive 15.36TB SSD PCIe 4.0 x4 NVMe U.2 15mm OPAL Encrypted - D7-P5520',
    manufacturer: 'Intel',
    category: 'server',
    description: 'Intel Hard Drive 15.36TB SSD PCIe 4.0 x4 NVMe U.2 15mm OPAL Encrypted - D7-P5520 Series',
    partNumber: 'SSDPF2KX076T1OS',
    estimatedCost: '$2,168.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-ftlx1471d3bcv-i3',
    model: 'Dual Rate 10GBase-LR 1310nm SFP+ Optical Transceiver F/s',
    manufacturer: 'Intel',
    category: 'transceiver',
    description: 'Dual Rate 10GBase-LR 1310nm SFP+ Optical Transceiver F/s',
    partNumber: 'FTLX1471D3BCV-I3',
    estimatedCost: '$102.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-ssdpe2kx010t807',
    model: 'Intel DC P4510 1 TB Solid State Drive - 2.5 Internal - PCI Express (PCI Express',
    manufacturer: 'Intel',
    category: 'server',
    description: 'Intel DC P4510 1 TB Solid State Drive - 2.5 Internal - PCI Express (PCI Express 3.1 x4)',
    partNumber: 'SSDPE2KX010T807',
    estimatedCost: '$189.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-ssdpe2kx020t801',
    model: 'Intel DC P4510 2TB Solid State Drive - 2.5 Internal - PCI Express (PCI Express 3',
    manufacturer: 'Intel',
    category: 'server',
    description: 'Intel DC P4510 2TB Solid State Drive - 2.5 Internal - PCI Express (PCI Express 3.1 x4)',
    partNumber: 'SSDPE2KX020T801',
    estimatedCost: '$235.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-nma1xxd256gps',
    model: 'Intel NMA1XXD256GPS 256GB DDR4-2666/PC4-21300 DCPMM 288-Pin CL19 ECC Registered',
    manufacturer: 'Intel',
    category: 'server',
    description: 'Intel NMA1XXD256GPS 256GB DDR4-2666/PC4-21300 DCPMM 288-Pin CL19 ECC Registered Memory Module',
    partNumber: 'NMA1XXD256GPS',
    estimatedCost: '$130.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-xl710qda2blk',
    model: 'Intel Ethernet Converged Network Adapter XL710-QDA2 - Network adapter - PCI Exp',
    manufacturer: 'Intel',
    category: 'other',
    description: 'Intel Ethernet Converged Network Adapter XL710-QDA2 - Network adapter - PCI Express 3.0 x8 low profile - 40 Gigabit QSFP+ x 2',
    partNumber: 'XL710QDA2BLK',
    estimatedCost: '$310.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-xl710',
    model: 'Intel Open QSFP+ Converged Adapter - PCIe 40 Gigabit Ethernet Server NIC - 40GbE',
    manufacturer: 'Intel',
    category: 'other',
    description: 'Intel Open QSFP+ Converged Adapter - PCIe 40 Gigabit Ethernet Server NIC - 40GbE Fiber Optic LAN Card',
    partNumber: 'XL710',
    estimatedCost: '$576.99',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-ssdpf2kx038tz',
    model: 'Intel SSD 3.84TB D7-P5510 U.2 Series DC NVME Solid State Drive',
    manufacturer: 'Intel',
    category: 'server',
    description: 'Intel SSD 3.84TB D7-P5510 U.2 Series DC NVME Solid State Drive',
    partNumber: 'SSDPF2KX038TZ',
    estimatedCost: '$698.61',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
  {
    id: 'intel-ssdpe2ke016t801',
    model: 'Intel DC P4610 1.6TB PCIe 3.1 x4 NVMe U.2 2.5" Enterprise SSD',
    manufacturer: 'Intel',
    category: 'server',
    description: 'Intel DC P4610 1.6TB PCIe 3.1 x4 NVMe U.2 2.5" Enterprise SSD',
    partNumber: 'SSDPE2KE016T801',
    estimatedCost: '$205.85',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["intel"],
  },
];

export default intelCatalog;
