import type { CatalogItem } from './types';

const juniperCatalog: CatalogItem[] = [
  {
    id: 'juniper-qfx10002-72q',
    model: 'QFX10002 SYST W/ 72PORT 40G PERP QSFP+ 24PORT 100G QSFP28/ 288PORT',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'QFX10002 SYST W/ 72PORT 40G PERP QSFP+ 24PORT 100G QSFP28/ 288PORT',
    partNumber: 'QFX10002-72Q',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx4100-ac',
    model: 'SRX4100 HW WITH TWO AC PSUHW ONLY MUST ORDER SRX4100-JSB SW',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'SRX4100 HW WITH TWO AC PSUHW ONLY MUST ORDER SRX4100-JSB SW',
    partNumber: 'SRX4100-AC',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx-5400',
    model: 'Juniper SRX5400 Firewall performance (max) 960 Gbps, IPS performance 172 Gbps, V',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'Juniper SRX5400 Firewall performance (max) 960 Gbps, IPS performance 172 Gbps, VPN performance 188 Gbps, Maximum concurrent sessions 91 million',
    partNumber: 'SRX-5400',
    estimatedCost: '$3,346.55',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx5k-re-13-20',
    model: 'Juniper SRX5K-RE-13-20, Routing Engine for SRX5400, SRX5600, and SRX5800 Service',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'Juniper SRX5K-RE-13-20, Routing Engine for SRX5400, SRX5600, and SRX5800 Services Gateways',
    partNumber: 'SRX5K-RE-13-20',
    estimatedCost: '$102.37',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx5k-re-1800x4',
    model: 'Juniper SRX5K-RE-1800X4, Routing Engine for SRX5400, SRX5600, and SRX5800 Servic',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'Juniper SRX5K-RE-1800X4, Routing Engine for SRX5400, SRX5600, and SRX5800 Services Gateways',
    partNumber: 'SRX5K-RE-1800X4',
    estimatedCost: '$12,106.60',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx5k-scb',
    model: 'Juniper SRX5K-SCB, SCB with slot for Routing Engine',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'Juniper SRX5K-SCB, SCB with slot for Routing Engine',
    partNumber: 'SRX5K-SCB',
    estimatedCost: '$2,000.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx5k-scb3',
    model: 'Juniper SRX5K-SCB3, SCB3 with slot for Routing Engine',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'Juniper SRX5K-SCB3, SCB3 with slot for Routing Engine',
    partNumber: 'SRX5K-SCB3',
    estimatedCost: '$3,250.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx5k-spc-4-15-320',
    model: 'Juniper SRX5K-SPC-4-15-320, SPC with four SPUs',
    manufacturer: 'Juniper',
    category: 'switch',
    description: 'Juniper SRX5K-SPC-4-15-320, SPC with four SPUs',
    partNumber: 'SRX5K-SPC-4-15-320',
    estimatedCost: '$1,038.95',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-mtp-4lc-s3m',
    model: '3M MPO/4XLC DUPLX FANOUT SMF',
    manufacturer: 'Juniper',
    category: 'cable',
    description: '3M MPO/4XLC DUPLX FANOUT SMF',
    partNumber: 'MTP-4LC-S3M',
    estimatedCost: '$529.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx4100',
    model: 'Juniper SRX4100-SYS-JB-DC Firewall',
    manufacturer: 'Juniper',
    category: 'other',
    description: 'Juniper SRX4100-SYS-JB-DC Firewall',
    partNumber: 'SRX4100-SYS-JB-DC',
    estimatedCost: '$56,000.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["juniper"],
  },
  {
    id: 'juniper-srx5k-mpc3-40g10g',
    model: 'Juniper Series 24 x SFP+ Ports 10GBase-X + 6 x QSFP+ Ports Gigabit Ethernet Conc',
    manufacturer: 'Juniper',
    category: 'other',
    description: 'Juniper Series 24 x SFP+ Ports 10GBase-X + 6 x QSFP+ Ports Gigabit Ethernet Concentrator Expansion Module',
    partNumber: 'SRX5K-MPC3-40G10G',
    estimatedCost: '$15,012.00',
    specs: 'IT Infrastructure | Serialized | UOM: Eaches',
    vendorIds: ["juniper"],
  },
];

export default juniperCatalog;
