import type { CatalogItem } from './types';

const mellanoxCatalog: CatalogItem[] = [
  {
    id: 'mellanox-mma4z00-ns',
    model: 'MMA4Z00-NS',
    manufacturer: 'NVIDIA (Mellanox)',
    category: 'transceiver',
    description: 'OSFP twin-port transceiver — 800Gb/s (2×400 SR4)',
    partNumber: 'MMA4Z00-NS',
    estimatedCost: '$2,500.00',
    specs: 'OSFP | 800G | MPO-12 | 50m OM4',
    vendorIds: ['mellanox', 'nvidia'],
    links: {
      productPage: 'https://docs.nvidia.com/networking/display/800gmma4z00ns',
      datasheet: 'https://docs.nvidia.com/networking/display/800gmma4z00ns/specifications',
    },
  },
  {
    id: 'mellanox-mma4z00-ns400',
    model: 'MMA4Z00-NS400',
    manufacturer: 'NVIDIA (Mellanox)',
    category: 'transceiver',
    description: 'OSFP transceiver — 400Gb/s SR4',
    partNumber: 'MMA4Z00-NS400',
    estimatedCost: '$1,900.00',
    specs: 'OSFP | 400G SR4 | MPO-12 | 50m OM4',
    vendorIds: ['mellanox', 'nvidia'],
    links: {
      productPage: 'https://docs.nvidia.com/networking/display/mma4z00ns400',
      datasheet: 'https://docs.nvidia.com/networking/display/mma4z00ns400/specifications',
    },
  },
  {
    id: 'mellanox-mms1v70-cm',
    model: 'MMS1V70-CM',
    manufacturer: 'NVIDIA (Mellanox)',
    category: 'transceiver',
    description: 'QSFP28 transceiver — 100GbE DR1',
    partNumber: 'MMS1V70-CM',
    estimatedCost: '$1,800.00',
    specs: 'QSFP28 | 100G DR1 | LC | 1310nm | 500m SMF',
    vendorIds: ['mellanox', 'nvidia'],
    links: {
      productPage: 'https://docs.nvidia.com/networking/display/MMS1V70CM10',
      datasheet: 'https://docs.nvidia.com/networking/display/mms1v70-cm-100gbe-qsfp28-dr1-transceiver-product-specifications.pdf',
    },
  },
  {
    id: 'mellanox-mms1v00-wm',
    model: 'MMS1V00-WM',
    manufacturer: 'NVIDIA (Mellanox)',
    category: 'transceiver',
    description: 'QSFP-DD transceiver — 400GbE DR4',
    partNumber: 'MMS1V00-WM',
    estimatedCost: '$2,200.00',
    specs: 'QSFP-DD | 400G DR4 | MPO-12 | 1310nm | 500m SMF',
    vendorIds: ['mellanox', 'nvidia'],
    links: {
      productPage: 'https://docs.nvidia.com/networking/display/MMS1V00WM10',
      datasheet: 'https://network.nvidia.com/pdf/prod_cables/PB_MMS1V00-WM_400GbE_QSFP-DD_DR4_Transceiver.pdf',
    },
  },
  {
    id: 'mellanox-mfp7e40-n007',
    model: '7M MPO FIBER',
    manufacturer: 'Mellanox',
    category: 'cable',
    description: '7M MPO FIBER',
    partNumber: 'MFP7E40-N007',
    estimatedCost: '$148.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["mellanox"],
  },
  {
    id: 'mellanox-mma1b00-c100d',
    model: 'NVIDIA/Mellanox MMA1B00-C100D Compatible 100GBASE-SR4 QSFP28 850nm 100m DOM MPO-',
    manufacturer: 'Mellanox',
    category: 'transceiver',
    description: 'NVIDIA/Mellanox MMA1B00-C100D Compatible 100GBASE-SR4 QSFP28 850nm 100m DOM MPO-12/UPC MMF Ethernet Optical Transceiver Module, Breakout to 4 x 25G-SR',
    partNumber: 'MMA1B00-C100D',
    estimatedCost: '$99.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["mellanox"],
  },
  {
    id: 'mellanox-mcx311a-xcat',
    model: 'Mellanox ConnectX-3 EN 10G Ethernet 10GbE SFP+ PCIe NIC LC Cable',
    manufacturer: 'Mellanox',
    category: 'cable',
    description: 'Mellanox ConnectX-3 EN 10G Ethernet 10GbE SFP+ PCIe NIC LC Cable',
    partNumber: 'MCX311A-XCAT',
    estimatedCost: '$15.29',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["mellanox"],
  },
  {
    id: 'mellanox-mfs1s00-h050e',
    model: 'Mellanox MFS1S00 QSFP56 Fiber Optic Network Cable IB HDR 50m',
    manufacturer: 'Mellanox',
    category: 'cable',
    description: 'Mellanox MFS1S00 QSFP56 Fiber Optic Network Cable IB HDR 50m',
    partNumber: 'MFS1S00-H050E',
    estimatedCost: '$1,729.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["mellanox"],
  },
];

export default mellanoxCatalog;
