import type { CatalogItem } from './types';

const micfoCatalog: CatalogItem[] = [
  {
    id: 'micfo-12mjsmpoa1s',
    model: 'Jumper 12FO MPO/APC-MPO/APC 1 mts SM',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 12FO MPO/APC-MPO/APC 1 mts SM',
    partNumber: '12MJSMPOA1S',
    estimatedCost: '$53.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-12mjsmpoa30s',
    model: 'Jumper 12FO MPO/APC-MPO/APC 30 mts SM',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 12FO MPO/APC-MPO/APC 30 mts SM',
    partNumber: '12MJSMPOA30S',
    estimatedCost: '$82.60',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-12mjsmpoa95snd',
    model: 'Jumper 12FO MPO/APC-MPO/APC 95 mts SM',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 12FO MPO/APC-MPO/APC 95 mts SM',
    partNumber: '12MJSMPOA95SND',
    estimatedCost: '$195.08',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-12mjsmpoa125snd',
    model: 'Jumper 12FO MPO/APC-MPO/APC 125 mts SM',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 12FO MPO/APC-MPO/APC 125 mts SM',
    partNumber: '12MJSMPOA125SND',
    estimatedCost: '$226.01',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc10s3',
    model: 'Jumper 2xLCPC - 2xLCPC 10mts 9/125 SM LSZH',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC - 2xLCPC 10mts 9/125 SM LSZH',
    partNumber: '2MJSLC10S3',
    estimatedCost: '$42.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc30s3',
    model: 'Jumper 2xLCPC - 2xLCPC 30mts 9/125 SM LSZH',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC - 2xLCPC 30mts 9/125 SM LSZH',
    partNumber: '2MJSLC30S3',
    estimatedCost: '$50.43',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc35s3',
    model: 'Jumper 2xLCPC - 2xLCPC 35mts 9/125 SM 3mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC - 2xLCPC 35mts 9/125 SM 3mm',
    partNumber: '2MJSLC35S3',
    estimatedCost: '$54.43',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc55s3',
    model: 'Jumper 2xLCPC - 2xLCPC 55mts 9/125 SM 3mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC - 2xLCPC 55mts 9/125 SM 3mm',
    partNumber: '2MJSLC55S3',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-12mjsmpoa15snd',
    model: 'Jumper 12FO MPO/APC-MPO/APC 15 mts SM',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 12FO MPO/APC-MPO/APC 15 mts SM',
    partNumber: '12MJSMPOA15SND',
    estimatedCost: '$112.53',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc125s3',
    model: 'Jumper 12FO MPO/APC-MPO/APC 125 mts SM',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 12FO MPO/APC-MPO/APC 125 mts SM',
    partNumber: '2MJSLC125S3',
    estimatedCost: '$226.01',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc40s3',
    model: 'Jumper 2xLCPC - 2xLCPC 40mts 9/125 SM 3mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC - 2xLCPC 40mts 9/125 SM 3mm',
    partNumber: '2MJSLC40S3',
    estimatedCost: '$54.43',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2mjslc60s3',
    model: 'Jumper 2xLCPC - 2xLCPC 60mts 9/125 SM 3mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC - 2xLCPC 60mts 9/125 SM 3mm',
    partNumber: '2MJSLC60S3',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2ejslc1s1',
    model: 'Jumper 2xLCPC-2xLCPC 1mts. 9/125 SM 1.6mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC-2xLCPC 1mts. 9/125 SM 1.6mm',
    partNumber: '2EJSLC1S1',
    estimatedCost: '$6.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2ejslc2s1',
    model: 'Jumper 2xLCPC-2xLCPC 2mts 9/125 SM 1,6mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC-2xLCPC 2mts 9/125 SM 1,6mm',
    partNumber: '2EJSLC2S1',
    estimatedCost: '$6.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-2ejslc3s1',
    model: 'Jumper 2xLCPC-2xLCPC 3mts 9/125 SM 1.6mm',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper 2xLCPC-2xLCPC 3mts 9/125 SM 1.6mm',
    partNumber: '2EJSLC3S1.',
    estimatedCost: '$7.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
  {
    id: 'micfo-12mjsmpoa95snf',
    model: 'Jumper MPO-MPO 95mts SM NEXO FTTH (B)',
    manufacturer: 'MICFO',
    category: 'cable',
    description: 'Jumper MPO-MPO 95mts SM NEXO FTTH (B)',
    partNumber: '12MJSMPO9',
    estimatedCost: '$167.10',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["micfo"],
  },
];

export default micfoCatalog;
