import type { CatalogItem } from './types';

const networksCentreCatalog: CatalogItem[] = [
  {
    id: 'networkscentre-sm-sp6a-s06m-02',
    model: 'SIEMON SKINNYPATCH CAT6A 28 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEA',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'SIEMON SKINNYPATCH CAT6A 28 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEAR BOOTS 6.0M',
    partNumber: 'SM-SP6A-S06M-02',
    estimatedCost: '$14.58',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sm-sp6a-s12m-02',
    model: 'SIEMON SKINNYPATCH CAT6A 28 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEA',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'SIEMON SKINNYPATCH CAT6A 28 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEAR BOOTS 12.0M',
    partNumber: 'SM-SP6A-S12M-02',
    estimatedCost: '$21.14',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sm-sp6a-s07m-02',
    model: 'SIEMON SKINNYPATCH CAT6A 28 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEA',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'SIEMON SKINNYPATCH CAT6A 28 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEAR BOOTS 7M',
    partNumber: 'SM-SP6A-S07M-02',
    estimatedCost: '$17.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sm-zm6a-s05m-02',
    model: 'SIEMON Z-MAX CAT6A 26 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEAR BOOT',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'SIEMON Z-MAX CAT6A 26 AWG STRANDED S-FTP PATCH CORD LSOH WHITE SHEATH CLEAR BOOTS 5.0M',
    partNumber: 'SM-SP6A-S07M-02',
    estimatedCost: '$15.56',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-mpo-kit-m85-s13',
    model: 'MPO Loss Test Kit (includes MPOOPM, MPO-OLS-M85 & MPO-OLS-S13)',
    manufacturer: 'Networks Centre',
    category: 'other',
    description: 'MPO Loss Test Kit (includes MPOOPM, MPO-OLS-M85 & MPO-OLS-S13)',
    partNumber: 'MPO-KIT-M85-S13',
    estimatedCost: '$16,849.26',
    specs: 'Machinery and Equipment | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-0-5-yw',
    model: '0.5M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '0.5M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    partNumber: '9-DX-LC-LC-0.5-YW',
    estimatedCost: '$4.80',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-1-yw',
    model: '1.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '1.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    partNumber: '9-DX-LC-LC-1-YW',
    estimatedCost: '$5.18',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-2-yw',
    model: '2.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '2.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    partNumber: '9-DX-LC-LC-2-YW',
    estimatedCost: '$5.54',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-3-yw',
    model: '3.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '3.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    partNumber: '9-DX-LC-LC-3-YW',
    estimatedCost: '$6.31',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-5-yw',
    model: '5.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '5.0M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH LEAD YELLOW',
    partNumber: '9-DX-LC-LC-5-YW',
    estimatedCost: '$6.92',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-9-yw',
    model: '9M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '9M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    partNumber: '9-DX-LC-LC-9-YW',
    estimatedCost: '$10.55',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-10-yw',
    model: '10M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '10M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    partNumber: '9-DX-LC-LC-10-YW',
    estimatedCost: '$11.13',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-11-yw',
    model: '11M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '11M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    partNumber: '9-DX-LC-LC-11-YW',
    estimatedCost: '$12.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-12-yw',
    model: '12M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '12M LC-LC SINGLEMODE DUPLEX PATCHCORD YELLOW',
    partNumber: '9-DX-LC-LC-12-YW',
    estimatedCost: '$14.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-15-yw',
    model: '15M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '15M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    partNumber: '9-DX-LC-LC-15-YW',
    estimatedCost: '$17.43',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-20-yw',
    model: '20M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '20M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    partNumber: '9-DX-LC-LC-20-YW',
    estimatedCost: '$20.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-25-yw',
    model: '25M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '25M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    partNumber: '9-DX-LC-LC-25-YW',
    estimatedCost: '$26.99',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-dx-lc-lc-30-yw',
    model: '30M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '30M LC-LC OS2 DUPLEX FIBRE OPTIC PATCH CORD YELLOW',
    partNumber: '9-DX-LC-LC-30-YW',
    estimatedCost: '$34.59',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-10',
    model: 'NEXCONEC 10M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 10M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-10',
    estimatedCost: '$98.50',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-12',
    model: 'NEXCONEC 12M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 12M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-12',
    estimatedCost: '$102.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-15',
    model: 'NEXCONEC 15M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 15M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-15',
    estimatedCost: '$106.40',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-20-nexcon',
    model: 'NEXCONEC 20M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 20M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-20 NEXCON',
    estimatedCost: '$112.66',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-25-nexcon',
    model: 'NEXCONEC 25M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 25M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-25 NEXCON',
    estimatedCost: '$119.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-30-nexcon',
    model: 'NEXCONEC 30M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 30M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-30 NEXCON',
    estimatedCost: '$127.26',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-mpo8-smf-40-nexcon',
    model: 'NEXCONEC 40M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC 40M, SINGLEMODE 8 FIBRE MPO APC FEMALE-FEMALE, POLARITY B',
    partNumber: 'NXC-MPO8-SMF-40 NEXCON',
    estimatedCost: '$143.90',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-om4-12-a-mmu-mma-1-re',
    model: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(M)/UPC-SUPER ELITE MTP(M)/APC 12F OM4 LSZH C',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(M)/UPC-SUPER ELITE MTP(M)/APC 12F OM4 LSZH CPR CCA 3MM POLARITY A REFERENCE GRADE, 1 METRE',
    partNumber: 'NXC-OM4-12-A-MMU-MMA-1-RE',
    estimatedCost: '$192.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-om4-12-a-mfa-mfa-1-re',
    model: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(F)/APC-SUPER ELITE MTP(F)/APC 12F OM4 LSZH C',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(F)/APC-SUPER ELITE MTP(F)/APC 12F OM4 LSZH CPR CCA 3MM POLARITY A REFERENCE GRADE, 1 METRE',
    partNumber: 'NXC-OM4-12-A-MFA-MFA-1-RE',
    estimatedCost: '$192.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-ad-mtp-sc-nexconec-mt',
    model: 'NEXCONEC MTP USCONEC',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MTP USCONEC',
    partNumber: 'NXC-AD-MTP-SC NEXCONEC MT',
    estimatedCost: '$17.61',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-om4-12-a-mmu-mma-1-ref',
    model: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(M)/UPC-SUPER ELITE MTP(M)/APC 12F OM4 LSZH C',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(M)/UPC-SUPER ELITE MTP(M)/APC 12F OM4 LSZH CPR CCA 3MM POLARITY A REFERENCE GRADE, 1 METRE',
    partNumber: 'NXC-OM4-12-A-MMU-MMA-1-REF',
    estimatedCost: '$219.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-om4-12-a-mfa-mfa-1-ref',
    model: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(F)/APC-SUPER ELITE MTP(F)/APC 12F OM4 LSZH C',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MINI FIBRE SUPER ELITE MTP(F)/APC-SUPER ELITE MTP(F)/APC 12F OM4 LSZH CPR CCA 3MM POLARITY A REFERENCE GRADE, 1 METRE',
    partNumber: 'NXC-OM4-12-A-MFA-MFA-1-REF',
    estimatedCost: '$219.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-ad-mtp-sc-nexconec',
    model: 'NEXCONEC MTP USCONEC ADAPTOR, KEY UP/KEY DOWN - MPO FOOTPRINT - NO FLANGE REQUIR',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MTP USCONEC ADAPTOR, KEY UP/KEY DOWN - MPO FOOTPRINT - NO FLANGE REQUIRED',
    partNumber: 'NXC-AD-MTP-SC NEXCONEC',
    estimatedCost: '$20.43',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nxc-ad-mtp-sc',
    model: 'NEXCONEC MTP USCONEC',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'NEXCONEC MTP USCONEC',
    partNumber: 'NXC-AD-MTP-SC',
    estimatedCost: '$17.77',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-pt-utp28x2m',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 2',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 2',
    partNumber: 'PT-UTP28X2M',
    estimatedCost: '$9.54',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-pt-utp28x1m',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 1M',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 1M',
    partNumber: 'PT-UTP28X1M',
    estimatedCost: '$8.87',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-pt-utp28x3m',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 3 METER',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 3 METER',
    partNumber: 'PT-UTP28X2M',
    estimatedCost: '$10.31',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nn6apl17',
    model: 'CAT 6A PATCH CORD 17M',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A PATCH CORD 17M',
    partNumber: 'NN6APL17',
    estimatedCost: '$37.78',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-nn6apl12',
    model: 'CAT 6A PATCH CORD 12M',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A PATCH CORD 12M',
    partNumber: 'NN6APL12',
    estimatedCost: '$29.23',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sgc6as2-0-wh',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 2 METER',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 2 METER',
    partNumber: 'SGC6AS2.0/WH',
    estimatedCost: '$865.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sgc6as1-5-wh',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 1.5 METER',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 1.5 METER',
    partNumber: 'SGC6AS1.5/WH',
    estimatedCost: '$1,047.15',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sgc6as3-wh',
    model: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 3 METER',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'CAT 6A 28AWG UTP PATCH CORD, CM/LSZH, OFF WHITE, 3 METER',
    partNumber: 'SGC6AS3/WH',
    estimatedCost: '$987.15',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sgc6as20-0-wh',
    model: 'Cat. 6a UFTP 20,0m LSZH',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'Cat. 6a UFTP 20,0m LSZH',
    partNumber: 'SGC6AS20.0/WH',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-gc6as20-0-wh',
    model: 'Cat. 6a SFTP 20,0m LSZH',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'Cat. 6a SFTP 20,0m LSZH',
    partNumber: 'GC6AS20.0/WH',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-gc6as15-0-wh',
    model: 'Cat. 6a SFTP 15,0m LSZH',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'Cat. 6a SFTP 15,0m LSZH',
    partNumber: 'GC6AS15.0/WH',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sgc6as15-0-wh',
    model: 'Cat. 6a UFTP 15,0m LSZH',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'Cat. 6a UFTP 15,0m LSZH',
    partNumber: 'SGC6AS15.0/WH',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-gc6au15-0-wh',
    model: 'GC6AU15.0/WH',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: '',
    partNumber: 'GC6AU15.0/WH',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-sgc6as10-0-wh',
    model: 'Cat. 6a UFTP 10,0m LSZH',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'Cat. 6a UFTP 10,0m LSZH',
    partNumber: 'SGC6AS10.0/WH',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-ft-lc-lc-140-yw-cca',
    model: 'SINGLEMODE LC-LC FLAT TWIN RUGGEDIZED PATCHCORD, EUROCLASS CCA, YELLOW, 140 METR',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'SINGLEMODE LC-LC FLAT TWIN RUGGEDIZED PATCHCORD, EUROCLASS CCA, YELLOW, 140 METRES',
    partNumber: '9-FT-LC-LC-140-YW-CCA',
    estimatedCost: '$164.12',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
  {
    id: 'networkscentre-9-ft-lc-lc-110-yw-cca',
    model: 'SINGLEMODE LC-LC FLAT TWIN RUGGEDIZED PATCHCORD, EUROCLASS CCA, YELLOW, 110 METR',
    manufacturer: 'Networks Centre',
    category: 'cable',
    description: 'SINGLEMODE LC-LC FLAT TWIN RUGGEDIZED PATCHCORD, EUROCLASS CCA, YELLOW, 110 METRES',
    partNumber: '9-FT-LC-LC-110-YW-CCA',
    estimatedCost: '$136.47',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["networksCentre"],
  },
];

export default networksCentreCatalog;
