import type { CatalogItem } from './types';

const nokiaCatalog: CatalogItem[] = [
  {
    id: 'nokia-3he00271aa',
    model: 'Nokia CBL - AC PWR CBL 110V USAAC Power Cable NEMA 5-15P to IEC 60320 C13 10A/11',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Nokia CBL - AC PWR CBL 110V USAAC Power Cable NEMA 5-15P to IEC 60320 C13 10A/110V 1.8 meter- United States / Canada / South America',
    partNumber: '3HE00271AA',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he15896aa',
    model: 'Nokia CBL - AC PWR CBL, 250V, 3M, C14-C13 AC Power Cable, IEC-60320-C14 to IEC-6',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Nokia CBL - AC PWR CBL, 250V, 3M, C14-C13 AC Power Cable, IEC-60320-C14 to IEC-60320-C13 AUTO-LOCK, 3.05m (10ft) Long',
    partNumber: '3HE15896AA',
    estimatedCost: '',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17415aa',
    model: 'Nokia VSR-a HN7 R22 AC VSR-a HN7 R22 AC Appliance is a configuration which inclu',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'Nokia VSR-a HN7 R22 AC VSR-a HN7 R22 AC Appliance is a configuration which includes one (1) HPE Server Node 7 AC server and one (1) Installation USB including a HostOS RHEL Subscription. This bundle does not include cables such as power, console or Cat6 nor does it include SFP+/QSFP hardware. The base VSR-a license and all application specific VSR licenses and QoS licenses (min. 1 Gbps basic QoS) are required to be purchased in addition to the base system',
    partNumber: '3HE17415AA',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he18712aa',
    model: 'Nokia SFP+ 10GE LR HPE INT BLc ROHS 6/6HPE Intel 1-port 10GBASE-LR Small Form-Fa',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'Nokia SFP+ 10GE LR HPE INT BLc ROHS 6/6HPE Intel 1-port 10GBASE-LR Small Form-Factor Pluggable+ (SFP+) Optics Module, Single Mode Fiber (SMF), 10km, 1310 nm, LC Connector, RoHS 6/6 compliant',
    partNumber: '3HE18712AA',
    estimatedCost: '',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc93809aabe',
    model: 'NokiaCFP2 400G DOC ZR 80KM 1550nm LC SMF',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'NokiaCFP2 400G DOC ZR 80KM 1550nm LC SMF',
    partNumber: '3KC93809AABE',
    estimatedCost: '$7,500.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1830-psi-4l-psi-m',
    model: 'Nokia 1830 PSI Kit (1) PSIMKIT PSI-M SHELF KIT (1XMEC2 5XFANM 0XBLANK) 3KC81770B',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'Nokia 1830 PSI Kit (1) PSIMKIT PSI-M SHELF KIT (1XMEC2 5XFANM 0XBLANK) 3KC81770BA (1) MEC2 MEC2 - PSI-M MEC2 REPLACEMENT KIT 3KC81972AA (1) PSI4LKIT PSI-L 4-SLOT SHELF KIT 3KC90291BA (1) CV1RU4P 1RU Cover Kit (19" 4 post) - PSC1-6, MSH4FSB, MLFSB, etc 8DG62423AB (2) MEC2L MEC2L - EQUIPT CONTROLLER HP - PSI-L 3KC81775AC (2) PSIMPFAC AC POWER SUPPLY PSI-M 1AF30787AAAA (2) PSILPFAC AC POWER SUPPLY PSI-L 3KC90395AA (1) OTDR - OTDR for fiber characterization 8DG62504AA (1) INSTPSC1-6 1RU Installation Kit 8DG62367AA (4) PSILACPWRCBL-US AC Power Cord. US, 2.3m 1AB463340001 (3) PSIMBNK PSI-M SLOT BLANK 3KC81780AA (1) TOOLKIT 1830 Tool Kit (incl SFPTL, LCTL, HSLADTL, HSLADDRV (1) IR9 IR9 - Integrated 9 degree ROADM 3KC70869AA (1) PSC1-6 PSC1-6 - Passive Splitter/Combiner 8DG62413AA (1) CA-INV2 CA-INVENTORY CABLE (NAR) (2.3M), SHIELDED CAT5E 8DG08359AA (3) DUJMSMN3 Duplex jumper (3.5m) - NAR (SM for internal connections) 1AB215120038 (2) SIMJLCAPC LC-LC APC SIMPLEX JUMPER-ANSI, 3.5M 8DG62768AA (3) SIMJSMN3 Simplex Jumper (3.5m) - NAR 1AB215120077 (1) JLCDEOSC Jumper, LC Duplex, 140mm, for External OSC (HH LD) 1AB155630001 (1) DD2M4 DD2M4 TERRESTRIAL UNRESTRICTED 3KC82113AA (1) SUL-1.2O OC3/STM1 APD ULHSFP (1510nm) 1AB373120002 (2) C2DCO4 C2DCO4-100-400G CFP2 DCO COHERENT MODULE 3KC93809AA (1) SWP KIT 1830PSS-8/16II/16/32/PSI-4L/PSI-8L/8x/12x/24x R23.6.0 3KC72164AAAA (license) (1) SWP 1830PSS R23.6.0 3KC82510AAAA (license) (1) TS-Gold, RES-AED, SSP (8.5%) (support)',
    partNumber: '1830 PSI-4L/PSI-M',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc90235ba01',
    model: '1830 PSI-L 4/8 SLT UNIV CHASSIS',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '1830 PSI-L 4/8 SLT UNIV CHASSIS',
    partNumber: '3KC90235BA01',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc82113aa02',
    model: '1830 PSI-M INTERFACE MOD PRNCD',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '1830 PSI-M INTERFACE MOD PRNCD',
    partNumber: '3KC82113AA02',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62413aa01',
    model: '1830 PSS PASV SPLTER/COMBR',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '1830 PSS PASV SPLTER/COMBR',
    partNumber: '8DG62413AA01',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17483ccrf01',
    model: 'Nokia SPI 7450/7750/7950 OS',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Nokia SPI 7450/7750/7950 OS',
    partNumber: '3HE17483CCRF01',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he20536aa',
    model: 'NokiaBNDL NSP Suite (SR-1x 4.8T 48p) BNDL NSP Suite (SR-1x 4.8T 48p) includes: (',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'NokiaBNDL NSP Suite (SR-1x 4.8T 48p) BNDL NSP Suite (SR-1x 4.8T 48p) includes: (2020) 3HE16254AA - NSP LICENSE POINT (2020) 3HE16255AA - NSP HIGH AVAILABILITY FP (1) 3HE16017AA - NSP IP CONTROL CLASS 2 NODE (2020) 3HE16003AA NSP NETWORK INFRASTRUCTURE MANAGEMENT FP (2020) 3HE16004AA NSP SERVICE ACTIVATION + CONFIG. FP (2020) 3HE16005AA NSP SERVICE ASSURANCE FP (2020) 3HE16007AA NSP NETWORK OPERATIONS ANALYTICS FP (2020) 3HE16010AA NSP INTENT BASED NETWORKING FRAMEWORK FP (2020) 3HE16011AA NSP WORKFLOW AUTOMATION ENGINE FP',
    partNumber: '3HE20536AA',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he20537aa',
    model: 'Nokia BNDL NSP Suite (SR-1se) BNDL NSP Suite (SR-1se) includes: (2660) 3HE16254A',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'Nokia BNDL NSP Suite (SR-1se) BNDL NSP Suite (SR-1se) includes: (2660) 3HE16254AA - NSP LICENSE POINT (2660) 3HE16255AA - NSP HIGH AVAILABILITY FP (1) 3HE16017AA - NSP IP CONTROL CLASS 2 NODE (2660) 3HE16003AA NSP NETWORK INFRASTRUCTURE MANAGEMENT FP (2660) 3HE16004AA NSP SERVICE ACTIVATION + CONFIG. FP (2660) 3HE16005AA NSP SERVICE ASSURANCE FP (2660) 3HE16007AA NSP NETWORK OPERATIONS ANALYTICS FP (2660) 3HE16010AA NSP INTENT BASED NETWORKING FRAMEWORK FP (2660) 3HE16011AA NSP WORKFLOW AUTOMATION ENGINE FP',
    partNumber: '3HE20537AA',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he20539aa',
    model: 'Nokia BND SR-1se 9.6T 36p 400G CR W/ MACSEC BND SR-1se 9.6T 36p 400G QSFP-DD AC',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'Nokia BND SR-1se 9.6T 36p 400G CR W/ MACSEC BND SR-1se 9.6T 36p 400G QSFP-DD AC CR W/ MACSEC includes: (1) 3HE17769AA - 7750 SR-1se 9.6T 36p 400G QSFP-DD CR AC (5) 3HE12376AA - FAN - 7750 SR-1s/1se Fan Module (2) 3HE11183AA - PSU - AC/HVDC 6kw Power Supply (4) 3HE11763AA - CBL - AC PWR CBL, 250V, 3M, USA (1) 3HE12507AA - ACC – 7750 SR-1s Rear Mounting Bundle (1) 3HE15808DA - SR - OS - 7450/7750/7950 R23.x LICENSE (1) 3HE13835AA - RTU - SROS EBGP HIGH (1) 3HE13836AA - RTU - SROS BGP FLOWSPEC (1) 3HE07473AA - RTU - SROS cFlowd (1) 3HE17118AA - RTU - SAP4k (1) 3HE13362AA - RTU - SROS Telemetry (1) 3HE13830AA - RTU - SROS EVPN (4) 3HE18946AA - RTU - 400GE MACSEC PORT Core Router (CR) scale feature set (1024 per complex = h/w queues, 1024 per complex = egress policers)',
    partNumber: '3HE20539AA',
    estimatedCost: '$153,608.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he20540aa',
    model: 'Nokia BNDL Edge SR-1x 4.8T 48p 400G CR BNDL Edge SR-1x 4.8T 48p 400G QSFP-DD AC',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'Nokia BNDL Edge SR-1x 4.8T 48p 400G CR BNDL Edge SR-1x 4.8T 48p 400G QSFP-DD AC CR W/ NSP includes: (1) 3HE17762AA - 7750 SR-1x 4.8T 48p 400G QSFP-DD CR (3) 3HE16484AA - FAN - 7750 SR-1x 2RU Fan Tray (F2B) (4) 3HE16724AA - PSU 2400W AC CRPS ETR (4) 3HE17621AA - CBL-AC PWR,250V,3.7M,C20/C19,AL (1) 3HE15808DA - SR - OS - 7450/7750/7950 R23.x LICENSE (1) 3HE13835AA - RTU - SROS EBGP HIGH (1) 3HE13836AA - RTU - SROS BGP FLOWSPEC (1) 3HE07473AA - RTU - SROS cFlowd (1) 3HE17118AA - RTU - SAP4k (1) 3HE13362AA - RTU - SROS Telemetry (1) 3HE13830AA - RTU - SROS EVPN Core Router (CR) scale feature set (1024 per complex = h/w queues, 1024 per complex = egress policers)',
    partNumber: '3HE20540AA',
    estimatedCost: '$74,920.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he20541aa',
    model: 'Nokia BNDL VSR-a vRR HN7 (BA) R23 AC BNDL BA VSR-a HN7 R23 AC W/NSP Appliance is',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'Nokia BNDL VSR-a vRR HN7 (BA) R23 AC BNDL BA VSR-a HN7 R23 AC W/NSP Appliance is a configuration which includes one (1) HPE Server Node 7 AC server including a HostOS RHEL Subscription. This bundle include: (1) 3HE17415BA - VSR-a HN7 R23 AC (1) 3HE13476EA - ASL R23 VSR-a Base (1) 3HE11119AA - ASL VSR 1Gbps BW w Standard QoS (1) 3HE11380AA - ASL VSR BGP Route Reflector (2) 3HE15896AA - CBL - AC PWR CBL, 250V, 3M, C14-C13 (2) 3HE18712AA - SFP+ 10GE LR HPE INT BLc ROHS 6/6',
    partNumber: '3HE20541AA',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he10551aa',
    model: 'Nokia compatible 100G QSFP28 SR4 Module',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'Nokia compatible 100G QSFP28 SR4 Module',
    partNumber: '3HE10551AA',
    estimatedCost: '',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-qsfp-dd-400g-dr4',
    model: 'NOKIA 400G OPTIC',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'NOKIA 400G OPTIC',
    partNumber: 'QSFP-DD-400G-DR4',
    estimatedCost: '$695.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-qdd-400g-4qpc03',
    model: 'NOKIA 4X100G OPTIC',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'NOKIA 4X100G OPTIC',
    partNumber: 'QDD-400G-4QPC03',
    estimatedCost: '$229.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-qsfp-dd-400g-fr4',
    model: 'Q56DD-400G-FR4 QSFP56-DD 400GBASE-DR4+_4xFR1 W/ SN CONN 3AL82188AA',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'Q56DD-400G-FR4 QSFP56-DD 400GBASE-DR4+_4xFR1 W/ SN CONN 3AL82188AA',
    partNumber: 'QSFP-DD-400G-FR4',
    estimatedCost: '$1,000.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17769aa',
    model: '7750 SR-1se 9.6T 36p 400G QSFP-DD CR AC',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: '7750 SR-1se 9.6T 36p 400G QSFP-DD CR AC',
    partNumber: '3HE17769AA',
    estimatedCost: '',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17762aa',
    model: '7750 SR-1x 4.8T 48p 400G QSFP-DD CR',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '7750 SR-1x 4.8T 48p 400G QSFP-DD CR',
    partNumber: '3HE17762AA',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17067aa',
    model: 'QSFP56-DD - 4x100G LR1, MPO12, 0/70C',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'QSFP56-DD - 4x100G LR1, MPO12, 0/70C',
    partNumber: '3HE17067AA',
    estimatedCost: '$1,350.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he10536ab',
    model: '7210 SAS-S 24T4SFP+ ACSYS - 7210 SAS-S 24TF4SFP+ system includes; (1) Fixed Fans',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '7210 SAS-S 24T4SFP+ ACSYS - 7210 SAS-S 24TF4SFP+ system includes; (1) Fixed Fans, (1) Fixed AC Power supply, (1) Hot swappable power supply slot, No Air Filters, Accepts (24) 10/100/1000 TX, (4) SFP+.',
    partNumber: '3HE10536AB',
    estimatedCost: '$1,518.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he10542aa',
    model: 'PS - 7210 SAS-S Power Supply AC PS - 7210 SAS-S Power Supply AC (Fits Fiber & Co',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PS - 7210 SAS-S Power Supply AC PS - 7210 SAS-S Power Supply AC (Fits Fiber & Copper 1/10G NON-PoE "S" units)',
    partNumber: '3HE10542AA',
    estimatedCost: '$105.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he10866ha',
    model: 'OS-7210 SAS-S/Sx 1/10 Base Lic S-A R23.XOS - 7210 SAS-Sx and 7210 SAS-S, 1GE/10G',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'OS-7210 SAS-S/Sx 1/10 Base Lic S-A R23.XOS - 7210 SAS-Sx and 7210 SAS-S, 1GE/10GE variant, Release 23.X Base OS License / Native and MPLS Ethernet L2 VPNs License, Standalone Mode',
    partNumber: '3HE10866HA',
    estimatedCost: '$300.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he12507aa',
    model: 'ACC – 7750 SR-1s Rear Mounting Kit7750 SR-1s Rear Mounting Hardware Kit',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'ACC – 7750 SR-1s Rear Mounting Kit7750 SR-1s Rear Mounting Hardware Kit',
    partNumber: '3HE12507AA',
    estimatedCost: '$180.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17622aa',
    model: 'CBL-AC PWR,250V,3.7M,USA,L6-20P/C19,ALAC Power Cable, LOCKING NEMA L6-20P to IEC',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'CBL-AC PWR,250V,3.7M,USA,L6-20P/C19,ALAC Power Cable, LOCKING NEMA L6-20P to IEC-60320-C19 AUTO-LOCK, 3.66m (12ft), supported on 7250 IXR-X3',
    partNumber: '3HE17622AA',
    estimatedCost: '$55.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he10534aa',
    model: '7750 SR SYS 7210 SAS 5 38T4SFP + AC',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '7750 SR SYS 7210 SAS 5 38T4SFP + AC',
    partNumber: '3HE10534AA',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc72164aaaa',
    model: 'SWP-1830PSS SWDM R23.6.0 KIT',
    manufacturer: 'Nokia',
    category: 'server',
    description: 'SWP-1830PSS SWDM R23.6.0 KIT',
    partNumber: '3KC72164AAAA',
    estimatedCost: '$135.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he11763aa',
    model: 'CBL - AC PWR CBL, 250V, 3M, USA',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'CBL - AC PWR CBL, 250V, 3M, USA',
    partNumber: '3HE11763AA',
    estimatedCost: '$40.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he05180aara01',
    model: 'Nokia Fan 7750 SR-7 Enhanced Fan Tray',
    manufacturer: 'Nokia',
    category: 'server',
    description: 'Nokia Fan 7750 SR-7 Enhanced Fan Tray',
    partNumber: '3HE05180AARA01',
    estimatedCost: '$389.99',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc81780aa',
    model: 'PSIMBNK PSI-M SLOT BLANK',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSIMBNK PSI-M SLOT BLANK',
    partNumber: '3KC81780AA',
    estimatedCost: '$80.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab215120038',
    model: 'DUJMSMN3 Duplex jumper (3.5m) - NAR (SM for internal connections)',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'DUJMSMN3 Duplex jumper (3.5m) - NAR (SM for internal connections)',
    partNumber: '1AB215120038',
    estimatedCost: '$42.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab373120002',
    model: 'SUL-1.2OOC3/STM1 APD ULHSFP (1510nm)',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'SUL-1.2OOC3/STM1 APD ULHSFP (1510nm)',
    partNumber: '1AB373120002',
    estimatedCost: '$360.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab463340001',
    model: 'PSILACPWRCBL-US Ac Power Cord. Us, 2.3M',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'PSILACPWRCBL-US Ac Power Cord. Us, 2.3M',
    partNumber: '1Ab463340001',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1af30787aaaa',
    model: 'PSILPFAC AC Power Supply PSi-M',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSILPFAC AC Power Supply PSi-M',
    partNumber: '1AF30787AAAA',
    estimatedCost: '$950.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc70869aa',
    model: 'IR9 IR9 - Integrated 9 degree ROADM',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'IR9 IR9 - Integrated 9 degree ROADM',
    partNumber: '3KC70869AA',
    estimatedCost: '$11,500.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc81770ba',
    model: 'PSI-M Shelf Kit (1XMEC2 5XFANM 0XBLANK)',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSI-M Shelf Kit (1XMEC2 5XFANM 0XBLANK)',
    partNumber: '3KC81770BA',
    estimatedCost: '$3,500.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc81775ac',
    model: 'Mec2L Mec2L - Equipt Controller Hp - Psi-L',
    manufacturer: 'Nokia',
    category: 'server',
    description: 'Mec2L Mec2L - Equipt Controller Hp - Psi-L',
    partNumber: '3KC81775AC',
    estimatedCost: '$800.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc81972aa',
    model: 'PSI-M Mec2 Replacement Kit 3KC81972AA',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSI-M Mec2 Replacement Kit 3KC81972AA',
    partNumber: '3KC81972AA',
    estimatedCost: '$800.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc82113aa',
    model: 'DD2M4 Terrestrial Unrestricted',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'DD2M4 Terrestrial Unrestricted',
    partNumber: '3KC82113AA',
    estimatedCost: '$6,000.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc90291ba',
    model: 'PSI4LKIT PSI-L 4-Slot Shelf Kit',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSI4LKIT PSI-L 4-Slot Shelf Kit',
    partNumber: '3KC90291BA',
    estimatedCost: '$3,200.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc90395aa',
    model: 'PSILPFAC AC Power Supply PSi-L',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSILPFAC AC Power Supply PSi-L',
    partNumber: '3KC90395AA',
    estimatedCost: '$252.20',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc93809aa',
    model: 'C2DCO4-100-400G CFP2 DCO Coherent Module',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'C2DCO4-100-400G CFP2 DCO Coherent Module',
    partNumber: '3KC93809AA',
    estimatedCost: '$4,500.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg08359aa',
    model: 'Ca-Inv2 Ca-Inventory Cable (NAR) (2.3M), Shielded CAT5E',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Ca-Inv2 Ca-Inventory Cable (NAR) (2.3M), Shielded CAT5E',
    partNumber: '8DG08359AA',
    estimatedCost: '$45.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62367aa',
    model: 'INSTPSC1-6 1Ru Installation Kit',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'INSTPSC1-6 1Ru Installation Kit',
    partNumber: '8DG62367AA',
    estimatedCost: '$24.30',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62504aa',
    model: 'OTDR for fiber characterization',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'OTDR for fiber characterization',
    partNumber: '8DG62504AA',
    estimatedCost: '$6,500.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62768aa',
    model: 'SIMJLCAPC LC-LC APC Simplex Jumper-Ansi, 3.5M',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'SIMJLCAPC LC-LC APC Simplex Jumper-Ansi, 3.5M',
    partNumber: '8DG62768AA',
    estimatedCost: '$27.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-c2dco4',
    model: 'C2DCO4-100-400G CFP2 DCO Coherent Module 3KC93809AA',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'C2DCO4-100-400G CFP2 DCO Coherent Module 3KC93809AA',
    partNumber: 'C2DCO4',
    estimatedCost: '$4,500.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-cv1ru4p',
    model: '1RU Cover Kit (19" 4 post) - PSC1-6, MSH4FSB, MLFSB, etc 8DG62423AB',
    manufacturer: 'Nokia',
    category: 'other',
    description: '1RU Cover Kit (19" 4 post) - PSC1-6, MSH4FSB, MLFSB, etc 8DG62423AB',
    partNumber: 'CV1RU4P',
    estimatedCost: '$45.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-dd2m4',
    model: 'DD2M4 Terrestrial Unrestricted',
    manufacturer: 'Nokia',
    category: 'server',
    description: 'DD2M4 Terrestrial Unrestricted',
    partNumber: 'DD2M4',
    estimatedCost: '$6,000.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-dujmsmn3',
    model: 'Duplex jumper (3.5m) - NAR (SM for internal connections) 1AB215120038',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Duplex jumper (3.5m) - NAR (SM for internal connections) 1AB215120038',
    partNumber: 'DUJMSMN3',
    estimatedCost: '$42.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-instpsc1-6',
    model: '1RU Installation Kit 8DG62367AA',
    manufacturer: 'Nokia',
    category: 'other',
    description: '1RU Installation Kit 8DG62367AA',
    partNumber: 'INSTPSC1-6',
    estimatedCost: '$24.30',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-jlcdeosc',
    model: 'Jumper, LC Duplex, 140mm, for External OSC (HH LD) 1AB155630001',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Jumper, LC Duplex, 140mm, for External OSC (HH LD) 1AB155630001',
    partNumber: 'JLCDEOSC',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-mec2l',
    model: 'Equipt Controller HP - PSI-L 3KC81775AC',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Equipt Controller HP - PSI-L 3KC81775AC',
    partNumber: 'MEC2L',
    estimatedCost: '$800.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-psilacpwrcbl-us',
    model: 'Ac Power Cord. Us, 2.3M 1AB463340001',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Ac Power Cord. Us, 2.3M 1AB463340001',
    partNumber: 'PSILACPWRCBL-US',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-psimkit',
    model: 'PSI-M Shelf Kit (1XMEC2 5XFANM 0XBLANK) 3KC81770BA',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'PSI-M Shelf Kit (1XMEC2 5XFANM 0XBLANK) 3KC81770BA',
    partNumber: 'PSIMKIT',
    estimatedCost: '$3,500.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-simjlcapc',
    model: 'LC-LC Apc Simplex Jumper-Ansi, 3.5M 8DG62768AA',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'LC-LC Apc Simplex Jumper-Ansi, 3.5M 8DG62768AA',
    partNumber: 'SIMJLCAPC',
    estimatedCost: '$27.30',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-simjsmn3',
    model: 'Simplex Jumper (3.5m) - NAR 1AB215120077',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'Simplex Jumper (3.5m) - NAR 1AB215120077',
    partNumber: 'SIMJSMN3',
    estimatedCost: '$25.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-sul-1-2o',
    model: 'OC3/STM1 APD ULHSFP (1510nm) 1AB373120002',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'OC3/STM1 APD ULHSFP (1510nm) 1AB373120002',
    partNumber: 'SUL-1.2O',
    estimatedCost: '$360.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab352700013',
    model: 'CA-AC PWR SUPPLY C13-C14',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'CA-AC PWR SUPPLY C13-C14',
    partNumber: '1AB352700013',
    estimatedCost: '$25.76',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab215120056',
    model: 'DUPLEX JUMPER 3.5M - ETSI SM FOR INTERNA',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'DUPLEX JUMPER 3.5M - ETSI SM FOR INTERNA',
    partNumber: '1AB215120056',
    estimatedCost: '$43.28',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62461aa',
    model: 'CA-INVENTORY, ETSI (.92M)',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'CA-INVENTORY, ETSI (.92M)',
    partNumber: '8DG62461AA',
    estimatedCost: '$46.37',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab215120078',
    model: 'SIMPLEX JUMPER 3.5M - ETSI',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'SIMPLEX JUMPER 3.5M - ETSI',
    partNumber: '1AB215120078',
    estimatedCost: '$25.76',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62769aa',
    model: 'JUMPER, LC-APC, 3.5M, ETSI, SM, SIMPLEX',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'JUMPER, LC-APC, 3.5M, ETSI, SM, SIMPLEX',
    partNumber: '8DG62769AA',
    estimatedCost: '$28.14',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc72086ab',
    model: 'CA-SN-2LC CA-SN-2LC CONNECTOR SM ANSI/ETSI 3.5M',
    manufacturer: 'Nokia',
    category: 'cable',
    description: 'CA-SN-2LC CA-SN-2LC CONNECTOR SM ANSI/ETSI 3.5M',
    partNumber: '8DG62769AA',
    estimatedCost: '$26.79',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg62423ab',
    model: 'CV1RU4P 1RU Cover Kit (19" 4 post) - PSC1-6, MSH4FSB, MLFSB, etc',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'CV1RU4P 1RU Cover Kit (19" 4 post) - PSC1-6, MSH4FSB, MLFSB, etc',
    partNumber: '8DG62423AB',
    estimatedCost: '$86.20',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17415ba',
    model: 'VSR-a HN7 R23 AC Appliance is a configuration which includes one (1) HPE Server',
    manufacturer: 'Nokia',
    category: 'server',
    description: 'VSR-a HN7 R23 AC Appliance is a configuration which includes one (1) HPE Server Node 7 AC server including a HostOS RHEL Subscription',
    partNumber: '3HE17415BA',
    estimatedCost: '$0.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17993aa',
    model: 'BNDL SR-1x 4.8T 48p 400G QSFP-DD AC CR RED PWR includes: BNDL SR-1x 4.8T 48p 400',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'BNDL SR-1x 4.8T 48p 400G QSFP-DD AC CR RED PWR includes: BNDL SR-1x 4.8T 48p 400G QSFP-DD AC CR RED PWR includes: (1) 3HE17762AA - 7750 SR-1x 4.8T 48p 400G QSFP-DD CR (3) 3HE16484AA - FAN - 7750 SR-1x 2RU Fan Tray (F2B) (4) 3HE16724AA - PSU 2400W AC CRPS ETR Core Router (CR) scale feature set (1024 per complex = h/w queues, 1024 per complex = egress policers) RTU Included: 3HE13835AA - RTU - SROS EBGP HIGH 3HE13836AA - RTU - SROS BGP FLOWSPEC 3HE07473AA - RTU - SROS cFlowd 3HE17118AA - RTU - SAP4k SROS SAP Right To Use License per system. Allows the use of up to 4k SAPs. 3HE13362AA - RTU - SROS Telemetry 3HE13830AA - RTU - SROS EVPN Service Right To Use License. A per system license. Allows the use EVPN for VXLAN and/or MPLS tunnels.',
    partNumber: '3HE17993AA',
    estimatedCost: '$72,700.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he20546fa',
    model: 'SR - OS - 7450/7750/7950 SD R25.x LIC Release 25.x Operating Software License wi',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'SR - OS - 7450/7750/7950 SD R25.x LIC Release 25.x Operating Software License with support for base features and scaling. One (1) Operating Software License is required for each node in the network. Includes two (2) 8GB SD cards with the Operating Software. SR-OS License for the following Platforms; 7750 SR-1x (FP5) 7750 SR-1se/2se (FP5) /7s/14s (CPM2-s) Additional functionality and scale are available via additional licenses.',
    partNumber: '3HE20546FA',
    estimatedCost: '$2,000.00',
    specs: 'Network Switches | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-301013231',
    model: 'Annual TS-Gold, RES-AED & SSP - Annual Technical Support- Gold (TS-Gold), Repair',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Annual TS-Gold, RES-AED & SSP - Annual Technical Support- Gold (TS-Gold), Repair Service with Advance-Exchange Next Business Day (RES-AED) and SRS (Software Subscription Service). 9.0% of HW+SW Total',
    partNumber: '301013231',
    estimatedCost: '',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he16254aa',
    model: 'NSP LICENSE POINT NSP License Points are mandatory for all deployments of the NS',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'NSP LICENSE POINT NSP License Points are mandatory for all deployments of the NSP Platform Base for any Operations and/or Programming suite deployments.',
    partNumber: '3HE16254AA',
    estimatedCost: '$5.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he16255aa',
    model: 'NSP HIGH AVAILABILITY FP The NSP High Availability feature package enables high',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'NSP HIGH AVAILABILITY FP The NSP High Availability feature package enables high availability and disaster recovery for all Operations and Programming suites feature packages.',
    partNumber: '3HE16255AA',
    estimatedCost: '$2.50',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he16017aa',
    model: 'NSP IP CONTROL CLASS 2 NODE (SR-1se) The NSP IP/Control Class 2 Nodes are those',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'NSP IP CONTROL CLASS 2 NODE (SR-1se) The NSP IP/Control Class 2 Nodes are those performing either of the following role/function in the network: Business P (core) or Mobile Aggregation and backhaul nodes. Order quantity 1 (ONE) per Class 2 node supporting all four NSP IP Control Feature Packages: - NSP CONTROL + VISUALIZATION STARTER FP - NSP PATH CONTROL + OPTIMIZATION FP - NSP ENHANCED OPTIMIZATION FP - NSP SIMULATION FP',
    partNumber: '3HE16017AA',
    estimatedCost: '$3,000.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he10534abrc01',
    model: '7210 SAS-S 48T4SFP+ AC',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '7210 SAS-S 48T4SFP+ AC',
    partNumber: '3HE10534ABRC01',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1p3he17415aara01',
    model: 'VSR-a HN7 R22 AC',
    manufacturer: 'Nokia',
    category: 'switch',
    description: 'VSR-a HN7 R22 AC',
    partNumber: '1P3HE17415AARA01',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1p3he10536abrc01',
    model: '7210 SAS-S 24T4SFP+ AC',
    manufacturer: 'Nokia',
    category: 'switch',
    description: '7210 SAS-S 24T4SFP+ AC',
    partNumber: '1P3HE10536ABRC01',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he09407na',
    model: 'ASL R25 VSIM Simulator - Application Software License (ASL) supporting the VSIM',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'ASL R25 VSIM Simulator - Application Software License (ASL) supporting the VSIM functionality. One (1) ASL is required for each VSIM system, independent of the number of virtual machines that form the system. The VSIM supports most functionality of all 7x50 router HW and is intended to be used to test new SROS functionality in a release and or to test deployment architectures in a lab setting. The VSIM is intended to be used as a lab tool only and should not be used in a production or customer facing role. The ASL allows a forwarding rate of 250 packets per second per interface. The VSIM product carries limited technical support and software defects should be replicated on a hardware based 7x50 node before a customer defect software defects should be replicated on a hardware based 7x50 node before a customer defect report can be opened. A unique software license key is required to operate each individual VSIM system. The VSIM license is sold for the specified SROS release and is not covered by',
    partNumber: '3HE09407NA',
    estimatedCost: '$0.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg59613aa',
    model: 'TOOLKIT 1830 Tool Kit (incl SFPTL, LCTL, HSLADTL, HSLADDRV) 8DG59613AA',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'TOOLKIT 1830 Tool Kit (incl SFPTL, LCTL, HSLADTL, HSLADDRV) 8DG59613AA',
    partNumber: '8DG59613AA',
    estimatedCost: '$0.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-8dg64137aa',
    model: 'RA2P-96 RA2P-96 - 2 PUMP RMN 96CH, No MID-STG ACCESS 8DG64137AA',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'RA2P-96 RA2P-96 - 2 PUMP RMN 96CH, No MID-STG ACCESS 8DG64137AA',
    partNumber: '8DG64137AA',
    estimatedCost: '$0.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-1ab373120001',
    model: 'SL-16.2O OC3/STM1 APD SFP (1510nm) with DDM 1AB373120001',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'SL-16.2O OC3/STM1 APD SFP (1510nm) with DDM 1AB373120001',
    partNumber: '1AB373120001',
    estimatedCost: '$0.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3kc82510aaaa',
    model: 'SWP 1830PSI-M R23.6.0 SWP 1830PSI-M R23.6.0 3KC82510AAAA',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'SWP 1830PSI-M R23.6.0 SWP 1830PSI-M R23.6.0 3KC82510AAAA',
    partNumber: '3KC82510AAAA',
    estimatedCost: '$0.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he17064aa',
    model: 'QSFP-LS (Line system) supports CS connectors, one for the line system and one fo',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'QSFP-LS (Line system) supports CS connectors, one for the line system and one for the client (ingress/egress up to x8 coherent pluggable modules)',
    partNumber: '3HE17064AA',
    estimatedCost: '$3,600.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he19475aa',
    model: 'Demux/Mux cable with dual CS and one end and eight LC duplex',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: 'Demux/Mux cable with dual CS and one end and eight LC duplex',
    partNumber: '3HE19475AA',
    estimatedCost: '$275.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he18358aa',
    model: '1-port 400G ZR+ QSFP-DD pluggable, SMF, 400G Coherent tunable DWDM 0dBm higher T',
    manufacturer: 'Nokia',
    category: 'transceiver',
    description: '1-port 400G ZR+ QSFP-DD pluggable, SMF, 400G Coherent tunable DWDM 0dBm higher Tx power, Open ZR+ Amplified,1528.77 to 1563.86nm, DWDM Grid (ITU 196.1 to 191.7 THz), with ToF (Tunable optical filter), 0/70C',
    partNumber: '3HE18358AA',
    estimatedCost: '$4,895.00',
    specs: 'Optic | Serialized | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he13890aara0101',
    model: 'Nokia 7750 SR-1s Blanking Plate',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Nokia 7750 SR-1s Blanking Plate',
    partNumber: '3HE13890AARA0101',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-year-1-2024-2025-maint-services-renewal-sa-no-265823',
    model: 'Year-1 2024-2025 Maint. services renewal SA No. 265823 for 7750 SR & VSR-a vRR,',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Year-1 2024-2025 Maint. services renewal SA No. 265823 for 7750 SR & VSR-a vRR, NSP, 1830 PSI-L & PSI-M products installed in USA - RTS Gold, RES Advance Exchange Day & SSP.Term: Oct 1, 2024-Dec 31, 2025',
    partNumber: 'Year-1 2024-2025 Maint. Services Renewal SA No. 265823',
    estimatedCost: '$1,459,194.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-year-2-2026-maint-services-renewal-sa-no-265823',
    model: 'Year-2 2026 Maint. services renewal SA No. 265823 for 7750 SR & VSR-a vRR, NSP,',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Year-2 2026 Maint. services renewal SA No. 265823 for 7750 SR & VSR-a vRR, NSP, 1830 PSI-L & PSI-M products installed in USA - RTS Gold, RES Advance Exchange Day & SSP.Term: Jan. 1, 2026-Dec 31, 2026',
    partNumber: 'Year-2 2026 Maint. Services Renewal SA No. 265823',
    estimatedCost: '$2,448,698.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-year-3-2027-maint-services-renewal-sa-no-265823',
    model: 'Year-3 2027 Maint. services renewal SA No. 265823 for 7750 SR & VSR-a vRR, NSP,',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'Year-3 2027 Maint. services renewal SA No. 265823 for 7750 SR & VSR-a vRR, NSP, 1830 PSI-L & PSI-M products installed in USA - RTS Gold, RES Advance Exchange Day & SSP.Term: Jan. 1, 2027-Dec 31, 2027',
    partNumber: 'Year-3 2027 Maint. Services Renewal SA No. 265823',
    estimatedCost: '$2,731,868.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he00691aa',
    model: 'IP Training Credits good towards any IPR training courses up to $100,000 accumul',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'IP Training Credits good towards any IPR training courses up to $100,000 accumulation.',
    partNumber: '3HE00691AA',
    estimatedCost: '$100,000.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nokia"],
  },
  {
    id: 'nokia-3he18899aa',
    model: 'UPG - SR-1x-48D 4.8T CR to 6.0T CR - Upgrade license from SR-1x-48D 4.8T Core Ro',
    manufacturer: 'Nokia',
    category: 'other',
    description: 'UPG - SR-1x-48D 4.8T CR to 6.0T CR - Upgrade license from SR-1x-48D 4.8T Core Router (CR) scale feature to 6.0T Core Router (CR) scale feature.',
    partNumber: '3HE18899AA',
    estimatedCost: '$13,650.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nokia"],
  },
];

export default nokiaCatalog;
