import type { CatalogItem } from './types';

const nVidiaCatalog: CatalogItem[] = [
  {
    id: 'nvidia-mqm9790-ns2f',
    model: 'MQM9790-NS2F',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'InfiniBand NDR switch — 64 ports (32× OSFP 800Gb/s)',
    partNumber: 'MQM9790-NS2F',
    estimatedCost: '$32,000.00',
    specs: '1U | 64 ports | 51.2 Tb/s | InfiniBand NDR | ~1300 W',
    vendorIds: ['nvidia'],
    links: {
      productPage: 'https://docs.nvidia.com/networking/display/QM97X0PUB',
      datasheet: 'https://docs.nvidia.com/networking/display/qm97xx-1u-ndr-400gbps-infiniband-switch-systems-user-manual.pdf',
    },
  },
  {
    id: 'nvidia-msn2201-cb2fc',
    model: 'MSN2201-CB2FC',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'Spectrum Ethernet switch — 48×1G RJ45 + 4× 100G QSFP28',
    partNumber: 'MSN2201-CB2FC',
    estimatedCost: '$4,200.00',
    specs: '1U | 48×1G + 4×100G | Spectrum | ~100 W',
    vendorIds: ['nvidia'],
    links: {
      productPage: 'https://marketplace.nvidia.com/en-us/enterprise/networking/sn2201/',
      datasheet: 'https://docs.nvidia.com/networking/display/sn2201-and-sn2201-m-1g-management-switch-systems-user-manual.pdf',
    },
  },
  {
    id: 'nvidia-msn3700-cs2fc',
    model: 'MSN3700-CS2FC',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'Spectrum-2 Ethernet switch — 32× 100G QSFP28',
    partNumber: 'MSN3700-CS2FC',
    estimatedCost: '$14,000.00',
    specs: '1U | 32×100G QSFP28 | Spectrum-2 | ~450 W',
    vendorIds: ['nvidia'],
    links: {
      productPage: 'https://marketplace.nvidia.com/en-us/enterprise/networking/sn3700/',
      datasheet: 'https://docs.nvidia.com/networking/display/sn3000um',
    },
  },
  {
    id: 'nvidia-msn4700-ws2fc',
    model: 'MSN4700-WS2FC',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'Spectrum-3 Ethernet switch — 32× 400G QSFP-DD',
    partNumber: 'MSN4700-WS2FC',
    estimatedCost: '$22,000.00',
    specs: '1U | 32×400G QSFP-DD | Spectrum-3 | ~550 W',
    vendorIds: ['nvidia'],
    links: {
      productPage: 'https://marketplace.nvidia.com/en-us/enterprise/networking/sn4700/',
      datasheet: 'https://docs.nvidia.com/networking/display/nvidia-spectrum-3-sn4000-1u-and-2u-switch-systems-hardware-user-manual.pdf',
    },
  },
  {
    id: 'nvidia-sn5600',
    model: 'SN5600',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'Spectrum-4 Ethernet switch — 64× 800G OSFP',
    partNumber: 'SN5600',
    estimatedCost: '$55,000.00',
    specs: '2U | 64×800G OSFP | Spectrum-4 | ~2800 W',
    vendorIds: ['nvidia'],
    links: {
      productPage: 'https://marketplace.nvidia.com/en-us/enterprise/networking/sn5000/',
      datasheet: 'https://docs.nvidia.com/networking/display/nvidia-spectrum-4-sn5000-2u-switch-systems-hardware-user-manual.pdf',
    },
  },
  {
    id: 'nvidia-900-24768-0002-000',
    model: 'NVIDIA 2xConnectX-7 Mezz Crypto Enabled',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA 2xConnectX-7 Mezz Crypto Enabled',
    partNumber: '900-24768-0002-000',
    estimatedCost: '$1,840.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-2g133-0010-000',
    model: 'NVIDIA L40 Graphic Card - 48 GB DDR6 ECC - Ada - Passive - Dual Slot',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: 'NVIDIA L40 Graphic Card - 48 GB DDR6 ECC - Ada - Passive - Dual Slot',
    partNumber: '900-2G133-0010-000',
    estimatedCost: '',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9d3b4-00cv-ea0',
    model: 'NVIDIA BlueField-3 B3220L E-Series FHHL DPU, 200GbE (default mode) / NDR 200 IB,',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA BlueField-3 B3220L E-Series FHHL DPU, 200GbE (default mode) / NDR 200 IB, Dual-port QSFP112, PCIe Gen5.0 x16, 8 Arm cores, 16GB on-board D DR, integrated BMC, Crypto Enabled, Tall Bracket',
    partNumber: '900-9D3B4-00CV-EA0',
    estimatedCost: '$2,149.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9d3b6-00cv-aa0',
    model: 'NVIDIA BlueField-3 B3220 P-Series FHHL DPU, 200GbE (default mode) / NDR2 00 IB,',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA BlueField-3 B3220 P-Series FHHL DPU, 200GbE (default mode) / NDR2 00 IB, Dual-port QSFP112, PCIe Gen5.0 x16 with x16 PCIe extension option , 16 Arm cores, 32GB on-board DDR, integrated BMC, Crypto Enabled, Tall Bracket',
    partNumber: '900-9D3B6-00CV-AA0',
    estimatedCost: '$2,343.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9d3d4-00en-ha0',
    model: 'Nvidia BlueField-3 B3140H E-series HHHL DPU, 400GbE(default mode)/NDR IB , Singl',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Nvidia BlueField-3 B3140H E-series HHHL DPU, 400GbE(default mode)/NDR IB , Single-port QSFP112, PCIe Gen5.0 x16, 8 Arm cores, 16GB on board DDR, integrated BMC, Crypto Enabled, Tall Bracket',
    partNumber: '900-9D3D400EN-HA0',
    estimatedCost: '$2,600.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9n42c-00fb-7c0',
    model: 'NVIDIA Spectrum-4 based 400GbE 2U Open Ethernet switch with Cumulus Linu x Authe',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Spectrum-4 based 400GbE 2U Open Ethernet switch with Cumulus Linu x Authentication, 64 QSFP56-DD ports and 2 SFP28 ports, 2 power supplies (AC), x86 CPU, Secure-boot, standard depth, Power-to-Connector airflow, Tool-less Rail Kit',
    partNumber: '920-9N42C-00FB-7C0',
    estimatedCost: '$24,400.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9n42c-00rb-7c0',
    model: 'NVIDIA Spectrum-4 based 400GbE 2U Open Ethernet switch with Cumulus Linux Authen',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Spectrum-4 based 400GbE 2U Open Ethernet switch with Cumulus Linux Authentication, 64 QSFP56-DD ports and 1 2xSFP28 port, 2 power supplies (AC), x86 CPU, Secure-boot, standard depth, C2P airflow, Tool-less Rail Kit',
    partNumber: '920-9N42C-00RB-7C0',
    estimatedCost: '$24,400.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9n42f-00ri-7c0',
    model: 'NVIDIA Spectrum-4 based 800GbE 2U Open Ethernet switch with Cumulus Linu x Authe',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Spectrum-4 based 800GbE 2U Open Ethernet switch with Cumulus Linu x Authentication, 64 OSFP ports and 1 SFP28 port, 2 power supplies (3KW, AC), x86 CPU, Secure-boot, standard depth, C2P airflow, Tool-less Rail Kit',
    partNumber: '920-9N42F-00RI-7C0',
    estimatedCost: '$34,000.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-aoc-623106ac-cdat',
    model: 'Mellanox MCX621202AC-ADAT ConnectX-6 Dx EN Adapter Card, 25GbE Dual-port SFP28,',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Mellanox MCX621202AC-ADAT ConnectX-6 Dx EN Adapter Card, 25GbE Dual-port SFP28, PCIe 4.0 x 8',
    partNumber: 'MCX621202AC-ADAT',
    estimatedCost: '$1,368.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mbf20-dkit',
    model: 'NVIDIA DPU Accessories Kit: 1x USB 2.0 Type-A to Mini USB Type B cable, 30-pin s',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA DPU Accessories Kit: 1x USB 2.0 Type-A to Mini USB Type B cable, 30-pin shrouded connector cable',
    partNumber: 'MBF20-DKIT',
    estimatedCost: '$81.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mbf2m345a-hecot',
    model: 'NVIDIA BlueField-2 E-Series DPU, 200GbE/HDR single-port QSFP56, PCIe Gen 4 x16,',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA BlueField-2 E-Series DPU, 200GbE/HDR single-port QSFP56, PCIe Gen 4 x16, Secure Boot Enabled, Crypto Enabled, 16GB on-board DDR, 1GbE OOB management, Tall Bracket, HHHL',
    partNumber: '900-9D250-0048-ST1',
    estimatedCost: '$1,380.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mbf2m516c-cecot',
    model: 'NVIDIA BlueField-2 E-Series DPU 100GbE Dual-Port QSFP56, integrated BMC, PCIe Ge',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA BlueField-2 E-Series DPU 100GbE Dual-Port QSFP56, integrated BMC, PCIe Gen4 x16, Secure Boot Enabled, Crypto Enabled, 16GB on-board DDR, 1GbE OOB management, Tall Bracket, FHHL',
    partNumber: 'MBF2M516C-CECOT',
    estimatedCost: '$1,323.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mca4j80-n003',
    model: 'NVIDIA MCA4J80-N003 AOC Cable IB Twin Port NDR up to 800Gb/s 3m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA MCA4J80-N003 AOC Cable IB Twin Port NDR up to 800Gb/s 3m',
    partNumber: 'MCA4J80-N003',
    estimatedCost: '$665.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mca7j75-n005',
    model: 'NVIDIA Active copper splitter cable, IB twin port NDR 800Gb/s to 4x200Gb/s, OSFP',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA Active copper splitter cable, IB twin port NDR 800Gb/s to 4x200Gb/s, OSFP to 4xQSFP112, 5m',
    partNumber: 'MCA7J75-N005',
    estimatedCost: '$1,146.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcp4y10-n002',
    model: 'NVIDIA MCP4Y10-N002 DAC Cable IB Twin Port NDR up to 800Gb/s 2m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA MCP4Y10-N002 DAC Cable IB Twin Port NDR up to 800Gb/s 2m',
    partNumber: 'MCP4Y10-N002',
    estimatedCost: '$329.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcp7y40-n003',
    model: 'NVIDIA passive copper splitter cable, IB twin port NDR 800Gb/s to 4x200Gb/s, OSF',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive copper splitter cable, IB twin port NDR 800Gb/s to 4x200Gb/s, OSFP to 4xQSFP112, 3m',
    partNumber: 'MCP7Y40-N003',
    estimatedCost: '$643.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx623436ac-cdab',
    model: 'ConnectX®-6 Dx EN adapter card, 100GbE, OCP3.0, With Host Management, Dual-port',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'ConnectX®-6 Dx EN adapter card, 100GbE, OCP3.0, With Host Management, Dual-port QSFP56, PCIe 4.0 x16, Crypto and Secure Boot, Thumbscrew (Pull Tab) Bracket',
    partNumber: 'MCX623436AC-CDAB',
    estimatedCost: '$762.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx631432ac-adab',
    model: 'NVIDIA MCX631432AC-ADAB ConnectX-6 Lx EN Adapter Card OCP3.0 25GbE Crypto Enable',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA MCX631432AC-ADAB ConnectX-6 Lx EN Adapter Card OCP3.0 25GbE Crypto Enabled',
    partNumber: 'MCX631432AC-ADAB',
    estimatedCost: '$235.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx75310aas-neat',
    model: 'NVIDIA ConnectX-7 NDR 400G InfiniBand Adapter Card MCX75310AAS-NEAT',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ConnectX-7 NDR 400G InfiniBand Adapter Card MCX75310AAS-NEAT',
    partNumber: 'MCX75310AAS-NEAT',
    estimatedCost: '$874.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx755106ac-heat',
    model: 'NVIDIA MCX755106AC-HEAT ConnectX-7 Adapter Card 200GbE/NDR200 Crypto Enabled',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA MCX755106AC-HEAT ConnectX-7 Adapter Card 200GbE/NDR200 Crypto Enabled',
    partNumber: 'MCX755106AC-HEAT',
    estimatedCost: '$1,006.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx755106as-heat',
    model: 'NVIDIA MCX755106AS-HEAT ConnectX-7 Adapter Card 200GbE/NDR200 Crypto Disabled',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA MCX755106AS-HEAT ConnectX-7 Adapter Card 200GbE/NDR200 Crypto Disabled',
    partNumber: 'MCX755106AS-HEAT',
    estimatedCost: '$874.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfa7u10-h005',
    model: 'NVIDIA AOC splitter, IB twin port HDR, 400Gb/s to 2x200Gb/s, OSFP to 2xQSFP56, 5',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA AOC splitter, IB twin port HDR, 400Gb/s to 2x200Gb/s, OSFP to 2xQSFP56, 5m',
    partNumber: 'MFA7U10-H005',
    estimatedCost: '$657.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n005',
    model: 'NVIDIA MFP7E10-N005 Passive Fiber Cable MMF MPO12 APC to MPO12 APC 5m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA MFP7E10-N005 Passive Fiber Cable MMF MPO12 APC to MPO12 APC 5m',
    partNumber: 'MFP7E10-N005',
    estimatedCost: '$34.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n007',
    model: 'NVIDIA MFP7E10-N007 Passive Fiber Cable MMF MPO12 APC to MPO12 APC 7m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA MFP7E10-N007 Passive Fiber Cable MMF MPO12 APC to MPO12 APC 7m',
    partNumber: 'MFP7E10-N007',
    estimatedCost: '$36.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n020',
    model: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 20m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 20m',
    partNumber: 'MFP7E10-N020',
    estimatedCost: '$51.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e20-n010',
    model: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 10M',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 10M',
    partNumber: 'MFP7E20-N010',
    estimatedCost: '$58.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e20-n020',
    model: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 20M',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 20M',
    partNumber: 'MFP7E20-N020',
    estimatedCost: '$116.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e20-n003-p',
    model: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 3M',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 3M',
    partNumber: 'MFP7E20-N003-P',
    estimatedCost: '$52.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e20-n005-p',
    model: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 5M',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA PASSIVE FIBER CABLE, MMF, MPO12 APC TO 2XMPO12 APC, 5M',
    partNumber: 'MFP7E20-N005-P',
    estimatedCost: '$55.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mma4z00-ns',
    model: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO12 APC, 850nm MM F, up t',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO12 APC, 850nm MM F, up to 50m, finned',
    partNumber: 'MMA4Z00-NS',
    estimatedCost: '$854.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mma4z00-ns-t',
    model: 'TWIN PORT TRANSCEIVER, 800GBPS,2X400GbE, OSFP, 2XMPO12 APC, 850NM MMF, U P TO 50',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'TWIN PORT TRANSCEIVER, 800GBPS,2X400GbE, OSFP, 2XMPO12 APC, 850NM MMF, U P TO 50M, FINNED',
    partNumber: '980-9I510-F4NS00',
    estimatedCost: '$712.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mma4z00-ns400',
    model: 'NVIDIA single port transceiver, 400Gbps,NDR, OSFP, MPO12 APC, 850nm MMF, up to 5',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA single port transceiver, 400Gbps,NDR, OSFP, MPO12 APC, 850nm MMF, up to 50m, flat top',
    partNumber: 'MMA4Z00-NS400',
    estimatedCost: '$576.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mma4z00-ns400-t',
    model: 'SINGLE PORT TRANSCEIVER, 400GBPS,400GbE, OSFP, MPO12 APC, 850NM MMF, UP TO 50M,',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'SINGLE PORT TRANSCEIVER, 400GBPS,400GbE, OSFP, MPO12 APC, 850NM MMF, UP TO 50M, FLAT TOP',
    partNumber: '980-9I51S-F4NS00',
    estimatedCost: '$480.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mma1t00-vs',
    model: 'Mellanox transceiver, 200GbE, up to 200Gb/s, QSFP56, MPO, 850nm, SR4, up to 100M',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'Mellanox transceiver, 200GbE, up to 200Gb/s, QSFP56, MPO, 850nm, SR4, up to 100M',
    partNumber: '980-9I20T-00V000',
    estimatedCost: '$410.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x00-ns-t',
    model: 'TWIN PORT TRANSCEIVER, 800GBPS,2X400GbE, OSFP, 2XMPO12 APC, 1310NM SMF, UP TO 10',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'TWIN PORT TRANSCEIVER, 800GBPS,2X400GbE, OSFP, 2XMPO12 APC, 1310NM SMF, UP TO 100M, FINNED',
    partNumber: '980-9I30H-F4NM00',
    estimatedCost: '$1,024.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms1v00-wm',
    model: 'NVIDIA 400G QSFP-DD, 1310nm, MPO, DR4, up to 500m',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA 400G QSFP-DD, 1310nm, MPO, DR4, up to 500m',
    partNumber: 'MMS1V00-WM',
    estimatedCost: '$695.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms1v70-cm',
    model: '100GbE QSFP28 DR1 Transceiver | 980-9I042-00C000',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: '100GbE QSFP28 DR1 Transceiver | 980-9I042-00C000',
    partNumber: '980-9I042-00C000',
    estimatedCost: '$260.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x00-ns',
    model: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO12 APC, 1310nm SMF, up t',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO12 APC, 1310nm SMF, up to 100m, finned',
    partNumber: 'MMS4X00-NS',
    estimatedCost: '$1,024.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-rtx-a4000',
    model: '-',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: '-',
    partNumber: 'RTX A4000',
    estimatedCost: '',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-rtx-a5000',
    model: '-',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: '-',
    partNumber: 'RTX A5000',
    estimatedCost: '',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-rtx-a6000',
    model: '-',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: '-',
    partNumber: 'RTX A6000',
    estimatedCost: '$4,990.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-2g500-0110-030',
    model: 'NVDIA Tesla V100 32GB HBM2 CUDA PCIe GPU Accelerator Card',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: 'NVDIA Tesla V100 32GB HBM2 CUDA PCIe GPU Accelerator Card',
    partNumber: '900-2G500-0110-030',
    estimatedCost: '$2,250.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-2g133-0000-000',
    model: 'NVIDIA A40 Ampere - 48 GB GDDR6 - Dual Slot - PCIe 4.0 Graphic Card',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: 'NVIDIA A40 Ampere - 48 GB GDDR6 - Dual Slot - PCIe 4.0 Graphic Card',
    partNumber: '900-2G133-0000-000',
    estimatedCost: '$5,016.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-a100-sxm4',
    model: 'Nvidia A100 Tensor Core GPU SXM4 80GB Graphics card',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: 'Nvidia A100 Tensor Core GPU SXM4 80GB Graphics card',
    partNumber: 'A100-SXM4',
    estimatedCost: '$17,900.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-797-yufetb-p3cmi36',
    model: 'NVIDIA UFM Ent Subscription SW with Business Critical for 1K+ InfiniBand Adapter',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA UFM Ent Subscription SW with Business Critical for 1K+ InfiniBand Adapters (HCAs) - 36.0 Months',
    partNumber: '797-YUFETB+P3CMI36',
    estimatedCost: '$94.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n050',
    model: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 50m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 50m',
    partNumber: 'MFP7E10-N050',
    estimatedCost: '$80.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n010',
    model: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 10m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 10m',
    partNumber: 'MFP7E10-N010',
    estimatedCost: '$41.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n015',
    model: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 15m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 15m',
    partNumber: 'MFP7E10-N015',
    estimatedCost: '$47.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n003',
    model: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 3m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 3m',
    partNumber: '980-9I73U-000003',
    estimatedCost: '$33.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mfp7e10-n01-5m',
    model: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 1.5m',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA passive fiber cable, MMF , MPO12 APC to MPO12 APC, 1.5m',
    partNumber: 'MFP7E10-N01.5M',
    estimatedCost: '$18.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mca7j60-n005',
    model: 'NVIDIA active copper Splitter cable, IB twin port NDR 800Gb/s to 2x400Gb/s,OSFP',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA active copper Splitter cable, IB twin port NDR 800Gb/s to 2x400Gb/s,OSFP to 2xOSFP, 5m',
    partNumber: 'MCA7J60-N005',
    estimatedCost: '$982.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-acc-kit000745',
    model: 'Mellanox / Nvidia ACC-KIT000745 MSN2700 PWR-Cable fixation kit / clip',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Mellanox / Nvidia ACC-KIT000745 MSN2700 PWR-Cable fixation kit / clip',
    partNumber: 'ACC-KIT000745',
    estimatedCost: '$12.37',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtef-kit-m-tl',
    model: 'SN2201 Tool-Less Rail Kit',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'SN2201 Tool-Less Rail Kit',
    partNumber: '930-9NRKT-00JS-000',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-s23n0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for SN2201 Series - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for SN2201 Series - 36.0 Months',
    partNumber: '781-S23N0Z+P3CMI36',
    estimatedCost: '$288.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-s37n0z-p2cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for SN3700_CL - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for SN3700_CL - 36.0 Months',
    partNumber: '781-S37N0Z+P2CMI36',
    estimatedCost: '$1,324.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-790-sn9n0z-p2cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for QM9790',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for QM9790',
    partNumber: '790-SN9N0Z+P2CMI36',
    estimatedCost: '$2,814.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-s47n0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for SN4700 Series - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for SN4700 Series - 36.0 Months',
    partNumber: '781-S47N0Z+P3CMI36',
    estimatedCost: '$2,814.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-788-ps4oem-p2cmi00',
    model: 'Consulting and verification services to OEM, Price per 1000 GPUs Base package [P',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Consulting and verification services to OEM, Price per 1000 GPUs Base package [Package O]',
    partNumber: '788-PS4OEM+P2CMI00',
    estimatedCost: '$101,250.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mpmf12om3az-10',
    model: 'MMFMPO 10 METERS',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'MMFMPO 10 METERS',
    partNumber: 'MPMF12OM3AZ-10',
    estimatedCost: '$40.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mma4z00-ns-flt',
    model: 'OSFP 2x400G SR8 Flat Top Module',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'OSFP 2x400G SR8 Flat Top Module',
    partNumber: 'MMA4Z00-NS-FLT',
    estimatedCost: '$1,399.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9i57y-000015',
    model: 'NVIDIA 980-9I57Y-000015 Passive Optical Cables',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA 980-9I57Y-000015 Passive Optical Cables',
    partNumber: '980-9I57Y-000015',
    estimatedCost: '$88.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9d208-0086-st3',
    model: 'BlueField-2 E-Series DPU',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'BlueField-2 E-Series DPU',
    partNumber: '900-9D208-0086-ST3',
    estimatedCost: '$2,204.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9i57y-0000015',
    model: 'NVIDIA 980-9I57Y-000015 compatible MPO-MPO Multi-mode OM4 Patch Cable 15 Meter',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA 980-9I57Y-000015 compatible MPO-MPO Multi-mode OM4 Patch Cable 15 Meter',
    partNumber: '980-9I57Y-0000015',
    estimatedCost: '$94.34',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mbf35-dkit',
    model: 'NVIDIA Debug and Management Cables Kit USB type A to 20p connector for UART',
    manufacturer: 'NVIDIA',
    category: 'cable',
    description: 'NVIDIA Debug and Management Cables Kit USB type A to 20p connector for UART',
    partNumber: '930-9DOTR-00YK-000',
    estimatedCost: '$93.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtm018771',
    model: 'FRU Tall bracket for 2-port QSFP56 adapter. Fits MCX623106A/CX622106A',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'FRU Tall bracket for 2-port QSFP56 adapter. Fits MCX623106A/CX622106A',
    partNumber: '930-9XBRK00MB-000',
    estimatedCost: '$8.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtfdkcc7t6tfr-1bc1zabyy',
    model: 'NVIDIA ConnectX-6 Dx 100Gigabit Ethernet Card, Dual-Port QSFP56, PCIe 4.0 x16, C',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ConnectX-6 Dx 100Gigabit Ethernet Card, Dual-Port QSFP56, PCIe 4.0 x16, Crypto Enabled, Optical Fiber Network Adapter',
    partNumber: 'MTFDKCC7T6TFR-1BC1ZABYY',
    estimatedCost: '$1,661.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtef-psf-ac-k',
    model: 'NVIDIA Mellanox Power-Supply Unit, 2000W AC, P2C Airflow, For QM97xx switches, P',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA Mellanox Power-Supply Unit, 2000W AC, P2C Airflow, For QM97xx switches, Power cord included',
    partNumber: 'MTEF-PSF-AC-K',
    estimatedCost: '$901.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx653105a-hdat-sp',
    model: 'ConnectX®-6 InfiniBand & Ethernet Adapter Card 200GbE/HDR, Single-Port QSFP56, P',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'ConnectX®-6 InfiniBand & Ethernet Adapter Card 200GbE/HDR, Single-Port QSFP56, PCIe 4.0 x 16, Tall&Short Bracket',
    partNumber: 'MCX653105A-HDAT-SP',
    estimatedCost: '$1,189.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx623432an-adab',
    model: 'NVIDIA MCX623432AN-ADAB ConnectX-6 Dx EN Adapter Card OCP3.0 25GbE Crypto Disabl',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA MCX623432AN-ADAB ConnectX-6 Dx EN Adapter Card OCP3.0 25GbE Crypto Disabled',
    partNumber: 'MCX623432AN-ADAB',
    estimatedCost: '$579.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mbf2h536c-cecot',
    model: 'Mellanox NVIDIA BlueField-2 Ethernet DPU - FHHL - 100 GbE - 2x Port - QSFP56',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Mellanox NVIDIA BlueField-2 Ethernet DPU - FHHL - 100 GbE - 2x Port - QSFP56',
    partNumber: 'MBF2H536C-CECOT',
    estimatedCost: '$2,324.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9b36f-00rx-8s0',
    model: 'NVIDIA Quantum-3 based XDR InfiniBand Switch, , Q3400-RA, 4U, 144 XDR Ports over',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Quantum-3 based XDR InfiniBand Switch, , Q3400-RA, 4U, 144 XDR Ports over 72 OSFP Cages, 8 Power Supplies (Power Cords Not Included), Standard Depth, Managed, C2P Airflow, Rail Kit',
    partNumber: '920-9B36F-00RX-8S0',
    estimatedCost: '$60,000.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-790-sx4n0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for Q3400-RA Air Cooled - 36.0 Mon',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for Q3400-RA Air Cooled - 36.0 Months',
    partNumber: '790-SX4N0Z+P3CMI36',
    estimatedCost: '$15,000.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9iah1-00xm00',
    model: 'NVIDIA twin port transceiver, 1600Gbps,OSFP, 2xMPO, 1310nm SMF, EML, up to 500m,',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 1600Gbps,OSFP, 2xMPO, 1310nm SMF, EML, up to 500m, IHS',
    partNumber: '980-9IAH1-00XM00',
    estimatedCost: '$1,400.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9iat0-00xm00',
    model: 'NVIDIA single port transceiver for ConnectX-8 Mezz Card, 800Gbps,OSFP, MPO, 1310',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA single port transceiver for ConnectX-8 Mezz Card, 800Gbps,OSFP, MPO, 1310nm SMF, EML, up to 500m, RHS',
    partNumber: '980-9IAT0-00XM00',
    estimatedCost: '$989.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mbf2h516c-cecot',
    model: 'BlueField-2 Ethernet DPU - FHHL - 100 GbE - 2x Port - QSFP56',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'BlueField-2 Ethernet DPU - FHHL - 100 GbE - 2x Port - QSFP56',
    partNumber: 'MBF2H516C-CECOT',
    estimatedCost: '$2,463.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx623105an-cdat',
    model: 'NVIDIA ConnectX-6 Dx EN Adapter Card - PCIe 4.0 x16 - 100 GbE - 1x Port - QSFP56',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ConnectX-6 Dx EN Adapter Card - PCIe 4.0 x16 - 100 GbE - 1x Port - QSFP56',
    partNumber: 'MCX623105AN-CDAT',
    estimatedCost: '$1,261.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx653105a-ecat',
    model: 'Mellanox ConnectX-6 VPI 100Gigabit Ethernet Card MCX653105A-ECAT-SP',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Mellanox ConnectX-6 VPI 100Gigabit Ethernet Card MCX653105A-ECAT-SP',
    partNumber: 'MCX653105A-ECAT',
    estimatedCost: '$791.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mcx75310aas-heat',
    model: 'NVIDIA ConnectX-7 NDR 200Gb Adapter OSFP CX75310AA Card',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ConnectX-7 NDR 200Gb Adapter OSFP CX75310AA Card',
    partNumber: 'MCX75310AAS-HEAT',
    estimatedCost: '$650.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bfan-00ix-000',
    model: 'NVIDIA fan module, 40 x 40 [mm], P2C airflow',
    manufacturer: 'NVIDIA',
    category: 'server',
    description: 'NVIDIA fan module, 40 x 40 [mm], P2C airflow',
    partNumber: '930-9BFAN-00IX-000',
    estimatedCost: '$292.00',
    specs: 'Server Component | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-msn3700-vs2fc',
    model: 'NVIDIA Spectrum-2 based 200GbE 1U Open Switch with Cumulus Linux, 32 QSFP56 port',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Spectrum-2 based 200GbE 1U Open Switch with Cumulus Linux, 32 QSFP56 ports, 2 Power Supplies (AC), Standard depth, x86 CPU, P2C airflow, Rail Kit',
    partNumber: '920-9N201-00FA-0C0',
    estimatedCost: '$13,529.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms1x00-ns400',
    model: 'NVIDIA single port transceiver, 400Gbps, NDR, QSFP112, MPO, 1310nm SMF, up to 10',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA single port transceiver, 400Gbps, NDR, QSFP112, MPO, 1310nm SMF, up to 100m, flat top',
    partNumber: 'MMS1X00-NS400',
    estimatedCost: '$680.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9n42f-00ri-3c1',
    model: 'Nvidia SN5610 Spectrum-4 based 800GbE 2U Open Ethernet switch with Cumulus Linux',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'Nvidia SN5610 Spectrum-4 based 800GbE 2U Open Ethernet switch with Cumulus Linux Authentication, 64 OSFP ports and 2 SFP28 ports, 4 AC PSUs, Secure-boot, standard depth, Connector-to-Power Airflow, Tool-less Rail Kit',
    partNumber: '920-9N42F-00RI-3C1',
    estimatedCost: '$21,250.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bpsu-00jg-000',
    model: 'Mellanox Power-Supply Unit, 1100W AC, C2P Airflow, For QM8700, QM8780, QM8790, S',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Mellanox Power-Supply Unit, 1100W AC, C2P Airflow, For QM8700, QM8780, QM8790, SN3700, SN3800, SN4600C, TQ8X00 switches, Power cord included',
    partNumber: '920-9N110-00R1-0C0',
    estimatedCost: '$627.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bfan-00j0-000',
    model: 'Mellanox Fan Module, 40 x 40 [mm], C2P Airflow, For QM8700, QM8780, QM8790, SN34',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Mellanox Fan Module, 40 x 40 [mm], C2P Airflow, For QM8700, QM8780, QM8790, SN3420, SN3510, SN3700C,SN3700, SN4700 switches',
    partNumber: '920-9N110-00R1-0C0',
    estimatedCost: '$279.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9n301-00rb-0c0-msn4700-ws2rc',
    model: 'NVIDIA Spectrum-3 based 400GbE 1U Open Ethernet switch with Cumulus Linux, 32 QS',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Spectrum-3 based 400GbE 1U Open Ethernet switch with Cumulus Linux, 32 QSFPDD ports, 2 power supplies (AC), x86 CPU, standard depth, C2P airflow, rail kit',
    partNumber: '920-9N301-00RB-0C0',
    estimatedCost: '$18,445.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x00-nm-t',
    model: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO, 1310nm SMF, up to 500m',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO, 1310nm SMF, up to 500m, finned',
    partNumber: '980-9I30G-F4NM00',
    estimatedCost: '$960.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x00-nm-flt',
    model: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO, 1310nm SMF, up to 500m',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO, 1310nm SMF, up to 500m, flat',
    partNumber: 'MMS4X00-NM-FLT',
    estimatedCost: '$960.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x50-nm',
    model: 'MMS4X50-NM 800Gbps Twin-port OSFP 2xFR4, 2x400Gb/s Single Mode, 2km',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'MMS4X50-NM 800Gbps Twin-port OSFP 2xFR4, 2x400Gb/s Single Mode, 2km',
    partNumber: 'MMS4X50-NM',
    estimatedCost: '$1,050.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x50-nm-backend',
    model: 'MMS4X50-NM 800Gbps Twin-port OSFP 2xFR4, 2x400Gb/s Single Mode, 2km',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'MMS4X50-NM 800Gbps Twin-port OSFP 2xFR4, 2x400Gb/s Single Mode, 2km',
    partNumber: 'MMS4X50-NM (Backend)',
    estimatedCost: '$1,050.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtef-psf-ac-m',
    model: 'Power supply unit - 250W AC - P2C airflow - for SN2201 switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Power supply unit - 250W AC - P2C airflow - for SN2201 switch',
    partNumber: 'MTEF-PSF-AC-M',
    estimatedCost: '$406.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-s3vn0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for SN3700_V Series - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for SN3700_V Series - 36.0 Months',
    partNumber: '781-S3VN0Z+P3CMI36',
    estimatedCost: '$1,324.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9npsu-00j2-000',
    model: 'NVIDIA POWER-SUPPLY UNIT, 1500W AC, P2C',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA POWER-SUPPLY UNIT, 1500W AC, P2C',
    partNumber: 'MT2411J00YR7',
    estimatedCost: '$1,424.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-797-yufetb-p3cmi36',
    model: 'NVIDIA UFM Ent Subscription SW with Business Critical for 1K+ InfiniBand Adapter',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA UFM Ent Subscription SW with Business Critical for 1K+ InfiniBand Adapters (HCAs) - 36.0 Months',
    partNumber: '797-YUFETB +P3CMI36',
    estimatedCost: '$94.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-s54n0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for SN5400 Series - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for SN5400 Series - 36.0 Months',
    partNumber: '781-S54N0Z+P3CMI36',
    estimatedCost: '$3,416.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-s56n0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for SN5600 Series - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for SN5600 Series - 36.0 Months',
    partNumber: '781-S56N0Z+P3CMI36',
    estimatedCost: '$4,760.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-793-cu9n0z',
    model: 'NVIDIA ENT BUSINESS CRITICAL SUPPORT SERVICES FOR MUA9602H APPLIANCE',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT BUSINESS CRITICAL SUPPORT SERVICES FOR MUA9602H APPLIANCE',
    partNumber: '793-CU9N0Z',
    estimatedCost: '$5,971.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms1v90-wr',
    model: 'Mellanox Select Transceiver, 400GbE, QSFP-DD, LC-LC, 1310nm, LR4',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'Mellanox Select Transceiver, 400GbE, QSFP-DD, LC-LC, 1310nm, LR4',
    partNumber: 'MMS1V90-WR',
    estimatedCost: '$1,803.00',
    specs: 'Transceiver | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-781-c56n0z-p3cmi36',
    model: 'NVIDIA ENT Business Critical Support Services for SN5600 Series - 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Critical Support Services for SN5600 Series - 36.0 Months',
    partNumber: '781-C56N0Z+P3CMI36',
    estimatedCost: '$2,231.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-790-sn9n0z-p3cmi36',
    model: 'NVIDIA ENT Business Standard Support Services for QM9790- 36.0 Months',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ENT Business Standard Support Services for QM9790- 36.0 Months',
    partNumber: '790-SN9N0Z+P3CMI36',
    estimatedCost: '$2,814.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9skit-00l0-00a',
    model: 'NVIDIA Mellanox Tool-Less Rail-Kit for 64x400G and 64x800G Switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA Mellanox Tool-Less Rail-Kit for 64x400G and 64x800G Switch',
    partNumber: '930-9SKIT-00L0-00A',
    estimatedCost: '$206.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mms4x00-nm',
    model: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO, 1310nm SMF, up to 500',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 800Gbps,2xNDR, OSFP, 2xMPO, 1310nm SMF, up to 500m, finned',
    partNumber: 'MMS4X00-NM',
    estimatedCost: '$499.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9x81e-00ex-st0',
    model: 'NVIDIA ConnectX-8 C8180 HHHL SuperNIC, 800Gbs XDR IB (default mode) / 2x400GbE,',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ConnectX-8 C8180 HHHL SuperNIC, 800Gbs XDR IB (default mode) / 2x400GbE, Single-cage OSFP, PCIe 6 x16 with x16 PCIe Socket Direct Extension option, Crypto Enabled, Secure Boot Enabled, Tall bracket',
    partNumber: '900-9X81E-00EX-ST0',
    estimatedCost: '$1,080.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bpwe-00na-000',
    model: 'Power cord black 250V 10A 1830MM C14 TO C15 EUR + CCC',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Power cord black 250V 10A 1830MM C14 TO C15 EUR + CCC',
    partNumber: '930-9BPWE-00NA-000',
    estimatedCost: '$25.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bpwa-00na-000',
    model: 'Power cord black 250V 15A 1830MM C14 TO C15 UL',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Power cord black 250V 15A 1830MM C14 TO C15 UL',
    partNumber: '930-9BPWA-00NA-000',
    estimatedCost: '$25.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9skit-00l0-00b',
    model: 'Tool-less rail kit for NVIDIA Quantum-3 4U switch (Q3400)',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Tool-less rail kit for NVIDIA Quantum-3 4U switch (Q3400)',
    partNumber: '930-9SKIT-00L0-00B',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9spsu-00ra-00a',
    model: 'NVIDIA Power-Supply Unit, 2000W AC, C2P Airflow, for Quantum-3 switches',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA Power-Supply Unit, 2000W AC, C2P Airflow, for Quantum-3 switches',
    partNumber: '930-9SPSU-00RA-00A',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9sfan-00rm-00b',
    model: 'NVIDIA fan unit, C2P Airflow, for XDR air cooled switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA fan unit, C2P Airflow, for XDR air cooled switch',
    partNumber: '930-9SFAN-00RM-00B',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9nrkt-00jn-000',
    model: 'Static rack installation kit for 1U/2U systems into 4 poles, 430-800mm depth rac',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Static rack installation kit for 1U/2U systems into 4 poles, 430-800mm depth racks',
    partNumber: 'MTEF-KIT-J',
    estimatedCost: '$109.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-93-9skit-00l0-00a',
    model: 'NVIDIA Mellanox Tool-Less Rail-Kit for 64x400G and 64x800G Switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA Mellanox Tool-Less Rail-Kit for 64x400G and 64x800G Switch',
    partNumber: '93-9SKIT-00L0-00A',
    estimatedCost: '$206.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtmk9100-t15',
    model: 'Auxiliary Kit for additional PCIe Gen5 x16 connection, PCIe Gen5 x16 passive aux',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Auxiliary Kit for additional PCIe Gen5 x16 connection, PCIe Gen5 x16 passive auxiliary card, two 150mm I-PEX cables',
    partNumber: '930-9BAUX-00N1-000',
    estimatedCost: '$173.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9d4b4-00cw-aa0',
    model: 'NVIDIA BlueField-4 B4240 800G Air Cooled DPU, Dual-port 400GbE (default) / NDR I',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA BlueField-4 B4240 800G Air Cooled DPU, Dual-port 400GbE (default) / NDR IB, QSFP112, PCIe Gen6 x16, 64 Arm cores, 128GB on-board LPDDR5x, integrated BMC, Crypto Enabled, Secure Boot Enabled, Tall Bracket',
    partNumber: '900-9D4B4-00CW-AA0',
    estimatedCost: '$3,600.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9b36m-00mx-8qs',
    model: 'NVIDIA Quantum-3 based XDR InfiniBand CPO Switch, Q3450-LD, 4U, 144 XDR Ports ov',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Quantum-3 based XDR InfiniBand CPO Switch, Q3450-LD, 4U, 144 XDR Ports over 144 MPOs Connectors, 48VDC,Managed, C2P Liquid-cooled, Rail Kit, QS',
    partNumber: '920-9B36M-00MX-8QS',
    estimatedCost: '$130,000.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9iau0-00xm00',
    model: 'NVIDIA twin port transceiver, 2xDR4, 1600Gbps, OSFP, 2xMPO(APC), 1310nm SMF, up',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 2xDR4, 1600Gbps, OSFP, 2xMPO(APC), 1310nm SMF, up to 500m, RHS, Gen2',
    partNumber: '980-9IAU0-00XM00',
    estimatedCost: '$1,332.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9iau0-00xm01',
    model: 'NVIDIA twin port transceiver, 2xDR4, 1600Gbps, OSFP, 2xMPO(APC), 1310nm SMF, up',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 2xDR4, 1600Gbps, OSFP, 2xMPO(APC), 1310nm SMF, up to 500m, IHS, Gen2',
    partNumber: '980-9IAU0-00XM01',
    estimatedCost: '$1,332.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9b36m-00mx-8es',
    model: 'NVIDIA Quantum-3 based XDR InfiniBand CPO Switch, Q3450-LD, 4U, 144 XDR Ports ov',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Quantum-3 based XDR InfiniBand CPO Switch, Q3450-LD, 4U, 144 XDR Ports over 144 MPOs Connectors, 48VDC,Managed, C2P Liquid-cooled, Rail Kit, ES',
    partNumber: '920-9B36M-00MX-8ES',
    estimatedCost: '$130,000.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-788-ps4oem-p3cmi00',
    model: 'Consulting and verification services to OEM, Price per 1000 GPUs Base package [P',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Consulting and verification services to OEM, Price per 1000 GPUs Base package [Package O]',
    partNumber: '788-PS4OEM+P3CMI00',
    estimatedCost: '$0.01',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-920-9n62f-00li-gc0',
    model: 'NVIDIA Spectrum-6 based 800GbE Ethernet switch with Cumulus Linux Authentication',
    manufacturer: 'NVIDIA',
    category: 'switch',
    description: 'NVIDIA Spectrum-6 based 800GbE Ethernet switch with Cumulus Linux Authentication, 64 OSFP, 1 QSFP112, 48VDC Busbar, 8-Cores CPU, Secure-boot, Liquid-Cooling, Rail-Kit.',
    partNumber: '920-9N62F-00LI-GC0',
    estimatedCost: '$37,200.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9x766-003nsq0',
    model: 'NVIDIA ConnectX-7 HHHL Adapter card, 400GbE / NDR IB (default mode), Single-po',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA ConnectX-7 HHHL Adapter card, 400GbE / NDR IB (default mode), Single-port OSFP, PCIe 5.0 x16, Crypto Disabled, Secure Boot Enabled, Tall Bracket',
    partNumber: '900-9X766-003NSQ0',
    estimatedCost: '$874.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-900-9d4b4-cwaa-es1',
    model: 'NVIDIA BlueField-4 B4240 800G Air Cooled DPU, Dual-port 400GbE (default) / NDR I',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA BlueField-4 B4240 800G Air Cooled DPU, Dual-port 400GbE (default) / NDR IB, QSFP112, PCIe Gen6 x16, 64 Arm cores, 128GB on-board LPDDR5x, integrated BMC, Crypto Enabled, Secure Boot Enabled, Tall Bracket',
    partNumber: '900-9D4B4-CWAA-ES1',
    estimatedCost: '$3,600.00',
    specs: 'NIC/DPU | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9sfan-00rm-00a',
    model: 'NVIDIA fan unit, C2P airflow, for 64×400G and 64×800G switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA fan unit, C2P airflow, for 64×400G and 64×800G switch',
    partNumber: '930-9SFAN-00RM-00A',
    estimatedCost: '$317.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9spsu-00ra-00b',
    model: 'NVIDIA power supply unit, 3KW AC, C2P airflow, for 64×800G switch, power cord in',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA power supply unit, 3KW AC, C2P airflow, for 64×800G switch, power cord included',
    partNumber: '930-9SPSU-00RA-00B',
    estimatedCost: '$1,598.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-mtef-fanf-k',
    model: 'NVIDIA fan module, P2C Airflow, For SN2201 switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA fan module, P2C Airflow, For SN2201 switch',
    partNumber: 'MTEF-FANF-K',
    estimatedCost: '$99.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9nrkt-00js-000',
    model: 'NVIDIA Tool-less rack installation kit, 4-post rack, For SN2201 switch',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA Tool-less rack installation kit, 4-post rack, For SN2201 switch',
    partNumber: '930-9NRKT-00JS-000',
    estimatedCost: '$199.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bfan-00in-000',
    model: '200G 1U systems FAN MODULE W/ P2C air flow',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: '200G 1U systems FAN MODULE W/ P2C air flow',
    partNumber: '930-9BFAN-00IN-000',
    estimatedCost: '$259.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9npsu-00j1-000',
    model: 'Power-Supply Unit, 550W AC, P2C Airflow, Power cord included',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Power-Supply Unit, 550W AC, P2C Airflow, Power cord included',
    partNumber: '930-9NPSU-00J1-000',
    estimatedCost: '$575.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bpsu-00jz-000',
    model: 'Power-Supply Unit, 1100W AC, P2C Airflow, Power cord included',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Power-Supply Unit, 1100W AC, P2C Airflow, Power cord included',
    partNumber: '930-9BPSU-00JZ-000',
    estimatedCost: '$627.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9bfan-00iw-000',
    model: '400G 1U systems FAN MODULE W/ P2C air flow',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: '400G 1U systems FAN MODULE W/ P2C air flow',
    partNumber: '930-9BFAN-00IW-000',
    estimatedCost: '$108.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-930-9brkt-00ys-000',
    model: 'NVIDIA 19" racks ,Tool-less rail-kit for QM97xx system, Rack size 600-800mm',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'NVIDIA 19" racks ,Tool-less rail-kit for QM97xx system, Rack size 600-800mm',
    partNumber: '930-9BRKT-00YS-000',
    estimatedCost: '$170.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-980-9iaj0-00xm00',
    model: 'NVIDIA twin port transceiver, 2xDR4, 1600Gbps, OSFP, 2xMPO(APC), 1310nm SMF, up',
    manufacturer: 'NVIDIA',
    category: 'transceiver',
    description: 'NVIDIA twin port transceiver, 2xDR4, 1600Gbps, OSFP, 2xMPO(APC), 1310nm SMF, up to 500m, RHS, TRO, Ethernet Only',
    partNumber: '980-9IAJ0-00XM00',
    estimatedCost: '$998.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
  {
    id: 'nvidia-788-ps4csp-p3cmi00',
    model: 'Consulting and verification service for CSPs - Package H',
    manufacturer: 'NVIDIA',
    category: 'other',
    description: 'Consulting and verification service for CSPs - Package H',
    partNumber: '788-PS4CSP+P3CMI00',
    estimatedCost: '$0.01',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["nVidia"],
  },
];

export default nVidiaCatalog;
