import type { CatalogItem } from './types';

const opengearCatalog: CatalogItem[] = [
  {
    id: 'og-om2216',
    model: 'OM2216',
    manufacturer: 'Opengear',
    category: 'console-server',
    description: 'OM2200 Operations Manager — standard 16-port console server deployed across multiple sites',
    partNumber: 'OM2216',
    estimatedCost: '$5,500.00',
    specs: '16 serial ports | Dual GbE | Cellular option | Lighthouse Enterprise',
    vendorIds: ['opengear'],
    links: {
      productPage: 'https://opengear.com/products/om2200-operations-manager/',
      datasheet: 'https://resources.opengear.com/om/datasheets/om2200/om2200-datasheet.pdf',
    },
  },
  {
    id: 'og-om2224-24e-ddc-l',
    model: 'OM2224-24E-DDC-L',
    manufacturer: 'Opengear',
    category: 'console-server',
    description: 'OM2200 Operations Manager — 24 serial + 24 Ethernet ports with DC power, used for dark-fiber / TPOP sites',
    partNumber: 'OM2224-24E-DDC-L',
    estimatedCost: '$8,200.00',
    specs: '24 serial + 24 Ethernet ports | DC power | Dual GbE | Lighthouse Enterprise',
    vendorIds: ['opengear'],
    links: {
      productPage: 'https://opengear.com/products/om2200-operations-manager/',
      datasheet: 'https://resources.opengear.com/om/datasheets/om2200/om2200-datasheet.pdf',
    },
  },
  {
    id: 'og-cm8148',
    model: 'CM8148 / CM8148-10G',
    manufacturer: 'Opengear',
    category: 'console-server',
    description: 'CM8100 Console Manager — 48-port console manager, CM8148-10G variant includes 10G uplinks',
    partNumber: 'CM8148',
    estimatedCost: '$12,000.00',
    specs: '48 serial ports | 1G or 10G uplink | Lighthouse Enterprise | 1U',
    vendorIds: ['opengear'],
    links: {
      productPage: 'https://opengear.com/products/cm8100-console-server/',
      datasheet: 'https://resources.opengear.com/cm/datasheets/cm8100/',
    },
  },
  {
    id: 'og-im7248',
    model: 'IM7248',
    manufacturer: 'Opengear',
    category: 'console-server',
    description: 'IM7200 Infrastructure Manager — 48-port unit used in legacy sites, seed-run and elevation templates',
    partNumber: 'IM7248',
    estimatedCost: '$7,500.00',
    specs: '48 serial ports | Dual GbE | Cellular option | 1U',
    vendorIds: ['opengear'],
    links: {
      productPage: 'https://opengear.com/products/im7200-infrastructure-manager',
      datasheet: 'https://opengear.com/wp-content/uploads/2018/03/IM7200_Infrastructure_Manager-Data_Sheet.pdf',
    },
  },
  {
    id: 'opengear-cm8148-10g-c14',
    model: 'CM8148-10G 48 SERIAL SELECTABLE PINOUT 2X 10GBE SF',
    manufacturer: 'Opengear',
    category: 'switch',
    description: 'CM8148-10G 48 SERIAL SELECTABLE PINOUT 2X 10GBE SF',
    partNumber: 'CM8148-10G-C14',
    estimatedCost: '$3,820.74',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-im7248-2-dac',
    model: 'OPENGEAR IM7248-2-DAC 48PORT RS-232 RJ45 100-24',
    manufacturer: 'Opengear',
    category: 'switch',
    description: 'OPENGEAR IM7248-2-DAC 48PORT RS-232 RJ45 100-24',
    partNumber: 'IM7248-2-DAC',
    estimatedCost: '',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-im7248-2-dac-lma',
    model: '48 SERIAL-2 GBE/SFP-16GB FLASH 4G ATT-V.92-DAC-US CORD',
    manufacturer: 'Opengear',
    category: 'other',
    description: '48 SERIAL-2 GBE/SFP-16GB FLASH 4G ATT-V.92-DAC-US CORD',
    partNumber: 'IM7248-2-DAC-LMA',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-im7248-2-dac-lmp',
    model: '48 SERIAL SW SELECTABLE DUAL AC 2 GBE ETHERNET OR FIBER SFP 16GB FL',
    manufacturer: 'Opengear',
    category: 'other',
    description: '48 SERIAL SW SELECTABLE DUAL AC 2 GBE ETHERNET OR FIBER SFP 16GB FL',
    partNumber: 'IM7248-2-DAC-LMP',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-im7248-2-dac-us',
    model: '48 SERIAL-2 GBE/SFP-16GB FLASH V.92-DAC-US CORD',
    manufacturer: 'Opengear',
    category: 'other',
    description: '48 SERIAL-2 GBE/SFP-16GB FLASH V.92-DAC-US CORD',
    partNumber: 'IM7248-2-DAC-US',
    estimatedCost: '',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-cm7148',
    model: 'Opengear CM7148-2-DAC-US 256MB Console Server',
    manufacturer: 'Opengear',
    category: 'switch',
    description: 'Opengear CM7148-2-DAC-US 256MB Console Server',
    partNumber: 'CM7148',
    estimatedCost: '$3,495.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-om2224-24e-ddc-l',
    model: 'OPENGEAR OM2224-24E-DDC-L 24 SERIAL,24 GBE,DUAL DC,GLOBALCEL LTE-A',
    manufacturer: 'Opengear',
    category: 'switch',
    description: 'OPENGEAR OM2224-24E-DDC-L 24 SERIAL,24 GBE,DUAL DC,GLOBALCEL LTE-A',
    partNumber: 'OM2224-24E-DDC-L',
    estimatedCost: '$0.00',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-cm8008-c',
    model: 'OG 8XRS232 X2 PINOUT PT 2X1GBE/SFP COMBO 450048 PWR',
    manufacturer: 'Opengear',
    category: 'switch',
    description: 'OG 8XRS232 X2 PINOUT PT 2X1GBE/SFP COMBO 450048 PWR',
    partNumber: 'CM8008-C',
    estimatedCost: '$1,768.05',
    specs: 'Network Switches | Serialized | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-450051',
    model: 'CM8000 EXTERNAL DC-DC POWER CONVERTER KIT - INCLUDES 450045',
    manufacturer: 'Opengear',
    category: 'other',
    description: 'CM8000 EXTERNAL DC-DC POWER CONVERTER KIT - INCLUDES 450045',
    partNumber: '450051',
    estimatedCost: '$0.00',
    specs: 'Equipment | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-og-fnts-cm8000-5yr',
    model: '5-YEAR FOUNDATION SUPPORT FOR CM8000 - 8X5 REGIONAL SUPPORT WITH ADVANCED REPLAC',
    manufacturer: 'Opengear',
    category: 'other',
    description: '5-YEAR FOUNDATION SUPPORT FOR CM8000 - 8X5 REGIONAL SUPPORT WITH ADVANCED REPLACEMENT',
    partNumber: 'OG-FNTS-CM8000-5YR',
    estimatedCost: '$0.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-opg-att-sm-1yr',
    model: 'OG CEL DATAPLAN-ATT-SMALL PLAN-1 YR LIC',
    manufacturer: 'Opengear',
    category: 'other',
    description: 'OG CEL DATAPLAN-ATT-SMALL PLAN-1 YR LIC',
    partNumber: 'OPG-ATT-SM-1YR',
    estimatedCost: '$0.00',
    specs: 'License | UOM: Eaches',
    vendorIds: ["opengear"],
  },
  {
    id: 'opengear-590074',
    model: 'DIGI SIM CARD KIT, FOR ACTIVATION, MUST BE SOLD WITH OPENGEAR CELLULAR DATA PLAN',
    manufacturer: 'Opengear',
    category: 'other',
    description: 'DIGI SIM CARD KIT, FOR ACTIVATION, MUST BE SOLD WITH OPENGEAR CELLULAR DATA PLAN',
    partNumber: '590074',
    estimatedCost: '$0.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["opengear"],
  },
];

export default opengearCatalog;
