import type { CatalogItem } from './types';

const pulseCatalog: CatalogItem[] = [
  {
    id: 'pulse-ap8867b',
    model: 'PDU',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: 'PDU',
    partNumber: 'AP8867B',
    estimatedCost: '$860.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-ap5363m',
    model: 'Smart PDU 415V - 3PH - 60A Metered 36 Outlets New C39 outlets (18x) - New OLED s',
    manufacturer: 'Pulse',
    category: 'pdu',
    description: 'Smart PDU 415V - 3PH - 60A Metered 36 Outlets New C39 outlets (18x) - New OLED screen',
    partNumber: 'AP5363M',
    estimatedCost: '$1,380.00',
    specs: 'PDUs | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-apc-apdu10452sm',
    model: 'PDU',
    manufacturer: 'Pulse',
    category: 'pdu',
    description: 'PDU',
    partNumber: 'APDU10452SM',
    estimatedCost: '$1,780.00',
    specs: 'PDUs | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar3157-1070mm',
    model: '48U Server Rack',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: '48U Server Rack',
    partNumber: 'AR3157',
    estimatedCost: '$1,200.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar3300-1200mm',
    model: '42U 600x1200mm Server Rack - New * AR3300 - Complete * All doors * All panels -',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: '42U 600x1200mm Server Rack - New * AR3300 - Complete * All doors * All panels - with side Cable entry * All roof tops - solid with added Cable entry * 1200MM x 600mm',
    partNumber: 'AR3300',
    estimatedCost: '$1,190.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar3350-1200mm',
    model: '42U Server Rack -Custom',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: '42U Server Rack -Custom',
    partNumber: 'AR3350',
    estimatedCost: '$1,220.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar3357-1200mm',
    model: '48U Server Rack',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: '48U Server Rack',
    partNumber: 'AR3357',
    estimatedCost: '$1,300.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar3357-roof',
    model: 'Custom- Roof top for APC AR3357 cabinet',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: 'Custom- Roof top for APC AR3357 cabinet',
    partNumber: 'AR3357 (Custom Roof)',
    estimatedCost: '$240.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar3357sp-1200mm',
    model: '48U Server Rack',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: '48U Server Rack',
    partNumber: 'AR3357SP',
    estimatedCost: '$1,300.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar7580a',
    model: 'Rack Accessory-Cablemgmt',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: 'Rack Accessory-Cablemgmt',
    partNumber: 'AR7580A',
    estimatedCost: '$185.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-p-ar7701',
    model: 'Rack Accessory-Siesmic Kit',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: 'Rack Accessory-Siesmic Kit',
    partNumber: 'Bracket',
    estimatedCost: '$105.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-apc-ar8136blk',
    model: 'Rack Accessory-10pk Kit',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: 'Rack Accessory-10pk Kit',
    partNumber: 'AR8136BLK',
    estimatedCost: '$45.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-apc-ar8621',
    model: 'Rack Accessory',
    manufacturer: 'Pulse',
    category: 'cabinet',
    description: 'Rack Accessory',
    partNumber: 'AR8621',
    estimatedCost: '$40.00',
    specs: 'Rack | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-apc-epdu1232sx3620',
    model: 'PDU',
    manufacturer: 'Pulse',
    category: 'pdu',
    description: 'PDU',
    partNumber: 'AP6361',
    estimatedCost: '$1,380.00',
    specs: 'PDUs | UOM: Eaches',
    vendorIds: ["pulse"],
  },
  {
    id: 'pulse-apc-epdu1232sx3620-10ft',
    model: 'PDU',
    manufacturer: 'Pulse',
    category: 'pdu',
    description: 'PDU',
    partNumber: 'APC EPDU1232SX3620-10FT',
    estimatedCost: '$1,865.83',
    specs: 'PDUs | UOM: Eaches',
    vendorIds: ["pulse"],
  },
];

export default pulseCatalog;
