import type { CatalogItem } from './types';

const shiInternationalCatalog: CatalogItem[] = [
  {
    id: 'shiinternational-udm-pro-max',
    model: 'Cloud Gateway with 10 Gbps Ubiquiti - Part#: UDM-PRO-MAX',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'Cloud Gateway with 10 Gbps Ubiquiti - Part#: UDM-PRO-MAX',
    partNumber: 'UDM-PRO-MAX',
    estimatedCost: '$585.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-usw-pro-aggregation',
    model: 'FULLY MANAGED LAYER 3 SWITCH Ubiquiti - Part#: USW-PRO-AGGREGATION',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'FULLY MANAGED LAYER 3 SWITCH Ubiquiti - Part#: USW-PRO-AGGREGATION',
    partNumber: 'USW-PRO-AGGREGATION',
    estimatedCost: '$849.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-svc-sd-ptx10k-p5',
    model: 'JNPR Care SD Supt PTX10008 Support Term: 12 Months',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'JNPR Care SD Supt PTX10008 Support Term: 12 Months',
    partNumber: 'JNPR Care SD Supt PTX10008 Support Term: 12 Months',
    estimatedCost: '$1,814.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-svc-sd-ptx-l1301',
    model: 'JNPR Care SD Supt PTX10K-LC1301-36DD Support Term: 12 Months',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'JNPR Care SD Supt PTX10K-LC1301-36DD Support Term: 12 Months',
    partNumber: 'JNPR Care SD Supt PTX10K-LC1301-36DD Support Term: 12 Months',
    estimatedCost: '$2,782.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-svc-cor-ptx288cp1p',
    model: 'JNPR Care Core Supt S-PTX-288C-P1-P Support Term: 12 Months',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'JNPR Care Core Supt S-PTX-288C-P1-P Support Term: 12 Months',
    partNumber: 'JNPR Care Core Supt S-PTX-288C-P1-P Support Term: 12 Months',
    estimatedCost: '$2,797.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-qdd-2x400g-fr4',
    model: 'QSFP-DD800 2x400G FR4 Transceiver',
    manufacturer: 'SHI International',
    category: 'transceiver',
    description: 'QSFP-DD800 2x400G FR4 Transceiver',
    partNumber: 'QSFP-DD800 2x400G FR4 Transceiver',
    estimatedCost: '$806.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-cbl-pwrc21-c20-na',
    model: 'POWER CORD, AC, NA, C21 to IECC20',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'POWER CORD, AC, NA, C21 to IECC20',
    partNumber: 'POWER CORD, AC, NA, C21 to IECC20',
    estimatedCost: '$43.00',
    specs: 'Consumables and Misc. | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-ra-ps-con-rmot',
    model: 'PRO SERV REMOTE CONSULT SERV/DA Y USE W/IN 6 MS OF PURCHASE PP Note: Rubrik Inst',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'PRO SERV REMOTE CONSULT SERV/DA Y USE W/IN 6 MS OF PURCHASE PP Note: Rubrik Installation Services & Enablemen',
    partNumber: 'RA-PS-CON-RMOT',
    estimatedCost: '$2,800.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-ra-ps-inst-rmot',
    model: 'PROFESSIONAL SERVICES REMOTE INSTALL CONFIG FOR UP TO 8 BRIKS Note: Rubrik Insta',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'PROFESSIONAL SERVICES REMOTE INSTALL CONFIG FOR UP TO 8 BRIKS Note: Rubrik Installation Services & Enablement',
    partNumber: 'RA-PS-INST-RMOT',
    estimatedCost: '$8,000.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-rs-bt-ee-pe-pp',
    model: 'ENTERPRISE EDITION /USABLE BETB SABLE BETB PREMIUM SUPPORT PREPAY Note: 60 TB of',
    manufacturer: 'SHI International',
    category: 'other',
    description: 'ENTERPRISE EDITION /USABLE BETB SABLE BETB PREMIUM SUPPORT PREPAY Note: 60 TB of Rubrik EE Software: 12 month support term',
    partNumber: 'RS-BT-EE-PE-PP',
    estimatedCost: '$1,814.00',
    specs: 'Support | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-rh-7404-01',
    model: 'R7404 APPLIANCE 4-NODE 48TB RAWHDD 30.7TB NVME SFP+ NIC Note: 2x Rubrik 7404 - 3',
    manufacturer: 'SHI International',
    category: 'server',
    description: 'R7404 APPLIANCE 4-NODE 48TB RAWHDD 30.7TB NVME SFP+ NIC Note: 2x Rubrik 7404 - 30 TB usable capacity/appliance',
    partNumber: 'RH-7404-01',
    estimatedCost: '$25,716.00',
    specs: 'CPU Server / Chassis | Serialized | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-rc-f3m-cbl-01',
    model: '3M FIBER OPTIC OM3 LC/LC CABLE PACK OF 4',
    manufacturer: 'SHI International',
    category: 'cable',
    description: '3M FIBER OPTIC OM3 LC/LC CABLE PACK OF 4',
    partNumber: 'RC-F3M-CBL-01',
    estimatedCost: '$482.00',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
  {
    id: 'shiinternational-rc-sfp-tsr-01',
    model: '10G/1G DUAL RATE SFP+ TRANSCEIV ER PACK OF 4',
    manufacturer: 'SHI International',
    category: 'transceiver',
    description: '10G/1G DUAL RATE SFP+ TRANSCEIV ER PACK OF 4',
    partNumber: 'RC-SFP-TSR-01',
    estimatedCost: '$3,326.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["shiInternational"],
  },
];

export default shiInternationalCatalog;
