import type { CatalogItem } from './types';

const siemonCatalog: CatalogItem[] = [
  {
    id: 'siemon-fj2-lculcul0-5p',
    model: 'OS2 Duplex, LC-LC, 0.5M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 0.5M cUL rated',
    partNumber: 'FJ2-LCULCUL0.5P',
    estimatedCost: '$7.77',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-01p',
    model: 'OS2 Duplex, LC-LC, 1M cUL cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 1M cUL cUL rated',
    partNumber: 'FJ2-LCULCUL-01P',
    estimatedCost: '$7.91',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-02p',
    model: 'OS2 Duplex, LC-LC, 2M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 2M cUL rated',
    partNumber: 'FJ2-LCULCUL-02P',
    estimatedCost: '$8.20',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-03p',
    model: 'OS2 Duplex, LC-LC, 3M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 3M cUL rated',
    partNumber: 'FJ2-LCULCUL-03P',
    estimatedCost: '$8.49',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-20p',
    model: 'OS2 Duplex, LC-LC, 20M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 20M cUL rated',
    partNumber: 'FJ2-LCULCUL-20P',
    estimatedCost: '$13.37',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-35p',
    model: 'OS2 Duplex, LC-LC, 35M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 35M cUL rated',
    partNumber: 'FJ2-LCULCUL-35P',
    estimatedCost: '$17.67',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-40p',
    model: 'OS2 Duplex, LC-LC, 40M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 40M cUL rated',
    partNumber: 'FJ2-LCULCUL-40P',
    estimatedCost: '$19.11',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-45p',
    model: 'OS2 Duplex, LC-LC, 45M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 45M cUL rated',
    partNumber: 'FJ2-LCULCUL-45P',
    estimatedCost: '$20.54',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
  {
    id: 'siemon-fj2-lculcul-50p',
    model: 'OS2 Duplex, LC-LC, 50M cUL rated',
    manufacturer: 'Siemon',
    category: 'cable',
    description: 'OS2 Duplex, LC-LC, 50M cUL rated',
    partNumber: 'FJ2-LCULCUL-50P',
    estimatedCost: '$21.98',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["siemon"],
  },
];

export default siemonCatalog;
