import type { CatalogItem } from './types';

const sycompCatalog: CatalogItem[] = [
  {
    id: 'sycomp-m402-efef-12cca-pc-010-b',
    model: 'MTP (female) – MTP (female) Singlemode G657.A1 (9/125) 12 fibre micro core (3.0m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'MTP (female) – MTP (female) Singlemode G657.A1 (9/125) 12 fibre micro core (3.0mm) single sheath cable - Polarity B; Total Length – 10m; MTP ELITE connectors',
    partNumber: 'M402-EFEF-12CCA-PC-010-B',
    estimatedCost: '$119.97',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-m402-efef-12cca-pc-020-b',
    model: 'MTP (female) – MTP (female) Singlemode G657.A1 (9/125) 12 fibre micro core (3.0m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'MTP (female) – MTP (female) Singlemode G657.A1 (9/125) 12 fibre micro core (3.0mm) single sheath cable - Polarity B; Total Length – 20m; MTP ELITE connectors',
    partNumber: 'M402-EFEF-12CCA-PC-020-B',
    estimatedCost: '$284.98',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-15m-12fm3-pff-apc-b-lz',
    model: 'OM3 12F MTP F-F LSZH APC Type B 15M',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM3 12F MTP F-F LSZH APC Type B 15M',
    partNumber: '50M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$528.11',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-12m-12fm3-pff-apc-b-lz',
    model: 'OM3 12F MTP F-F LSZH APC Type B 12M',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM3 12F MTP F-F LSZH APC Type B 12M',
    partNumber: '55M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$466.78',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-11m-12fm3-pff-apc-b-lz',
    model: 'OM3 12F MTP F-F LSZH APC Type B 11M',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM3 12F MTP F-F LSZH APC Type B 11M',
    partNumber: '60M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$446.34',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-10m-12fm3-pff-apc-b-lz',
    model: 'OM3 12F MTP F-F LSZH APC Type B 10M',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM3 12F MTP F-F LSZH APC Type B 10M',
    partNumber: '65M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$425.89',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-9m-12fm3-pff-apc-b-lz',
    model: 'OM3 12F MTP F-F LSZH APC Type B 9M',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM3 12F MTP F-F LSZH APC Type B 9M',
    partNumber: '70M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$390.17',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-20m-12fm3-pff-apc-b-lz',
    model: 'OM3 12F MTP F-F LSZH APC Type B 20M',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM3 12F MTP F-F LSZH APC Type B 20M',
    partNumber: '75M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$618.07',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-160m-12fm4-pff-apc-b-k8-lz',
    model: 'OM4 12F MTP F-F LSZH APC Type B 160M (Bundle of 8 in Blue Mesh)',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM4 12F MTP F-F LSZH APC Type B 160M (Bundle of 8 in Blue Mesh)',
    partNumber: '160M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$4,885.72',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-100m-12fm4-pff-apc-b-k8-lz',
    model: 'OM4 12F MTP F-F LSZH APC Type B 100M (Bundle of 8 in Blue Mesh)',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'OM4 12F MTP F-F LSZH APC Type B 100M (Bundle of 8 in Blue Mesh)',
    partNumber: '100M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$3,166.45',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-80m-12fm4-pff-apc-b-k8-lz',
    model: '80M-12FM4-PFF-APC-B-K8-LZ OM4 12F MTP F-F LSZH APC Type B 80M - Bundle of (8) in',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: '80M-12FM4-PFF-APC-B-K8-LZ OM4 12F MTP F-F LSZH APC Type B 80M - Bundle of (8) in Blue Mesh',
    partNumber: '100M-12FM4-PFF-APC-B-K8-LZ',
    estimatedCost: '$2,546.29',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-lclc-ga1-dup-1-8-ylw-10',
    model: 'SMF LC-TO-LC-SMF 10m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'SMF LC-TO-LC-SMF 10m',
    partNumber: 'LCLC-GA1-DUP-(1.8)-YLW-10',
    estimatedCost: '$33.06',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-apl1l1da12y8',
    model: 'SMF LC-TO-LC-SMF 8m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'SMF LC-TO-LC-SMF 8m',
    partNumber: 'APL1L1DA12Y8',
    estimatedCost: '$13.96',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-apl1l1da12y12',
    model: 'SMF LC-TO-LC-SMF 12m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'SMF LC-TO-LC-SMF 12m',
    partNumber: 'APL1L1DA12Y12',
    estimatedCost: '$11.95',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-apl1l1da12ylp25',
    model: 'SMF LC-TO-LC-SMF 25m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'SMF LC-TO-LC-SMF 25m',
    partNumber: 'APL1L1DA12YLP25',
    estimatedCost: '$26.46',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-apl1l1da12y15',
    model: 'SMF LC-TO-LC-SMF 15m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'SMF LC-TO-LC-SMF 15m',
    partNumber: 'APL1L1DA12Y15',
    estimatedCost: '$17.58',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
  {
    id: 'sycomp-apl1l1da12y20',
    model: 'SMF LC-TO-LC-SMF 20m',
    manufacturer: 'Sycomp',
    category: 'cable',
    description: 'SMF LC-TO-LC-SMF 20m',
    partNumber: 'APL1L1DA12Y20',
    estimatedCost: '$18.47',
    specs: 'Cabling | UOM: Eaches',
    vendorIds: ["sycomp"],
  },
];

export default sycompCatalog;
