import type { CatalogItem } from './types';

const ubiquitiCatalog: CatalogItem[] = [
  {
    id: 'ubiquiti-usw-enterprise-24-poe',
    model: 'Ubiquiti Switch Enterprise 24 PoE delivers 12 2.5 GbE',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'Ubiquiti Switch Enterprise 24 PoE delivers 12 2.5 GbE',
    partNumber: 'USW-Enterprise-24-PoE',
    estimatedCost: '$799.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-usw-pro-max-24-poe',
    model: 'Ubiquiti PRO Switch Enterprise 24 PoE delivers 12 2.5 GbE',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'Ubiquiti PRO Switch Enterprise 24 PoE delivers 12 2.5 GbE',
    partNumber: 'USW-Pro-Max-24-PoE',
    estimatedCost: '$799.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-usw-enterprise-48-poe',
    model: 'Ubiquiti Switch Enterprise 48 PoE delivers 12 2.5 GbE',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'Ubiquiti Switch Enterprise 48 PoE delivers 12 2.5 GbE',
    partNumber: 'USW-Enterprise-48-PoE',
    estimatedCost: '$1,599.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-usw-enterprise-24-poe-eu',
    model: 'Ubiquiti Switch Enterprise 24 PoE delivers 12 2.5 GbE',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'Ubiquiti Switch Enterprise 24 PoE delivers 12 2.5 GbE',
    partNumber: 'USW-Enterprise-24-PoE-EU',
    estimatedCost: '$1,745.71',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-ubiquiti-efg-eu',
    model: 'Ubiquiti EFG-EU Enterprise-grade 25 Gbps UniFi Cloud Gateway with 3 WAN ports',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'Ubiquiti EFG-EU Enterprise-grade 25 Gbps UniFi Cloud Gateway with 3 WAN ports',
    partNumber: 'Ubiquiti EFG-EU',
    estimatedCost: '$3,566.42',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-uacc-cm-rj45-mg',
    model: 'SFP+ to RJ45 Adapter',
    manufacturer: 'Ubiquiti',
    category: 'transceiver',
    description: 'SFP+ to RJ45 Adapter',
    partNumber: 'UACC-CM-RJ45-MG',
    estimatedCost: '$65.00',
    specs: 'Optic | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-uacc-om-mm-10g-d',
    model: '10G Multi-Mode Optical Module',
    manufacturer: 'Ubiquiti',
    category: 'transceiver',
    description: '10G Multi-Mode Optical Module',
    partNumber: 'UACC-OM-MM-10G-D',
    estimatedCost: '$20.00',
    specs: 'Transceiver | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-u6-enterprise',
    model: 'UniFi U6 Enterprise Access Point',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'UniFi U6 Enterprise Access Point',
    partNumber: 'U6-Enterprise',
    estimatedCost: '$279.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
  {
    id: 'ubiquiti-u7-pro-xgs-b-us',
    model: 'Access Point U7 Pro XGS (black)',
    manufacturer: 'Ubiquiti',
    category: 'other',
    description: 'Access Point U7 Pro XGS (black)',
    partNumber: 'U7-Pro-XGS-B-US',
    estimatedCost: '$59.00',
    specs: 'IT Infrastructure | UOM: Eaches',
    vendorIds: ["ubiquiti"],
  },
];

export default ubiquitiCatalog;
